<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Notify
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Notify';

$aLangContent = array(

    '_modzzz_notify_page_title_admin_notify' => 'Admin Notifications',
  '_modzzz_notify_page_title_administration' => 'Notifier Administration',
  '_modzzz_notify_page_title_my_notify' => 'Mes Notifications',
  '_modzzz_notify_page_title_my' => 'Actions de notification des membres',
  '_modzzz_notify_page_title_home' => 'Actions de notification de mes contacts',
  '_modzzz_notify_menu_view_notify' => 'Principal',
  '_modzzz_notify_menu_my' => 'Mes Notifications',
  '_modzzz_notify_menu_main' => 'Notifications de mes contacts/Favoris',
  '_modzzz_notify_menu_root' => 'Notifier',
  '_modzzz_notify_block_administration_owner' => 'Administration',
  '_modzzz_notify_menu_admin_settings' => 'Paramètres',
  '_modzzz_notify_menu_admin_initialize' => 'Initialize Members',
  '_modzzz_notify_menu_admin_manage_templates' => 'Templates',
  '_modzzz_notify_menu_admin_manage_actions' => 'Manage Actions',
  '_modzzz_notify_block_desc' => 'Description',
  '_modzzz_notify_block_submenu_manage_notify' => 'Gérer',
  '_modzzz_notify_block_submenu_main' => 'Principal',
  '_modzzz_notify_caption_description' => 'Description',
  '_modzzz_notify_caption_action' => 'Action',
  '_modzzz_notify_caption_group' => 'Groupe',
  '_modzzz_notify_name' => 'Nom',
  '_modzzz_notify_btn_search' => 'Rechercher',
  '_modzzz_notify_btn_submit' => 'Envoter',
  '_modzzz_notify_btn_save' => 'Sauvegarder',
  '_modzzz_notify_btn_delete' => 'Supprimer',
  '_modzzz_notify_btn_edit' => 'Modifier',
  '_modzzz_notify_btn_add' => 'Ajouter',
  '_modzzz_notify_reset_success' => 'Notification Settings successfully initialized',
  '_modzzz_notify_reset_message' => 'This action will reset the Notification Settings for all Members. Make sure this is what you really want to do',
  '_modzzz_notify_actions' => 'Actions',
  '_modzzz_notify_forum' => 'Forum',
  '_modzzz_notify' => 'Notifications',
  '_modzzz_notify_notify_single' => 'notification',
  '_modzzz_notify_notify_plural' => 'Notification',
  '_modzzz_notify_block_acountpage' => 'Notification Settings',
  '_modzzz_notify_activity' => 'Notification',
  '_modzzz_notify_friend' => 'Contact',
  '_modzzz_notify_files' => 'Files',
  '_modzzz_notify_polls' => 'Polls',
  '_modzzz_notify_blogs' => 'Blogs',
  '_modzzz_notify_jobs' => 'Offres d\'emploi',
  '_modzzz_notify_modzzz_classified' => 'Petites Annonces',
  '_modzzz_notify_business_listings' => 'Page Entreprise',
  '_modzzz_notify_modzzz_articles' => 'Articles',
  '_modzzz_notify_events' => 'Evénements',
  '_modzzz_notify_sites' => 'Sites',
  '_modzzz_notify_videos' => 'Vidéos',
  '_modzzz_notify_photos' => 'Photos',
  '_modzzz_notify_sounds' => 'Sounds',
  '_modzzz_notify_groups' => 'Groupes',
  '_modzzz_notify_store' => 'Store',
  '_modzzz_notify_ads' => 'Ads',
  '_modzzz_notify_avatar' => 'Photo de profil',
  '_modzzz_notify_profile' => 'Profil',
  '_modzzz_notify_mail' => 'Mail',
  '_modzzz_notify_wall' => 'Wall',
 '_modzzz_notify_admin_notify' => 'Admin Notifications',
  '__modzzz_notify_block_Advanced_Notification' => '<i class="sys-icon bell"></i> Paramètres de notification avancés ',
  
  '_modzzz_notify_admin_settings' => 'Admin Settings',
  '_modzzz_notify_favorites' => 'Favoris',
  '_modzzz_notify_all' => 'Tous',
  '_modzzz_notify_none' => 'Aucun',
  '_modzzz_notify_both' => 'Les deux',
  '_modzzz_notify_yes' => 'Oui',
  '_modzzz_notify_no' => 'Non',
  '_modzzz_notify_caption_notify_me' => 'Notifier moi',
  '_modzzz_notify_caption_existing_settings' => 'Me Notifier quand une action est executée par:',
  '_modzzz_notify_block_settings' => 'Paramètres',
  '_modzzz_notify_block_my_actions' => 'Paramètres de notification des membres',
  '_modzzz_notify_block_friend_actions' => 'Actions de Notification pour des contacts/Favoris',
  '_modzzz_notify_no_actions' => 'Il n\'ya aucune action',
  '_modzzz_notify_no_templates' => 'There are no Email Templates',
  '_modzzz_notify_forum_flagged_reply_desc' => 'New Post for a flagged forum Topic',
  '_modzzz_notify_forum_participant_desc' => 'New Post for a participating forum Topic',
  '_modzzz_notify_profile_status_message_desc' => 'Modification d\'un statut',
  '_modzzz_notify_profile_view_desc' => 'Consultation de mon profil',
  '_modzzz_notify_profile_commentPost_desc' => 'Commentaire sur mon Profil',
  '_modzzz_notify_profile_comment_delete_desc' => 'Supprimer le commentaire d\'un profil',
  '_modzzz_notify_profile_rate_desc' => 'Note sur mon un Profil',
  '_modzzz_notify_profile_comment_rate_desc' => 'Voter un commentaire sur un profil',
  '_modzzz_notify_avatar_add_desc' => 'Ajout photo de profil',
  '_modzzz_notify_avatar_delete_desc' => 'Suppression photo de profil',
  '_modzzz_notify_classifieds_add_desc' => 'Post an Ad',
  '_modzzz_notify_classifieds_delete_desc' => 'Delete an Ad',
  '_modzzz_notify_classifieds_commentPost_desc' => 'Comment on an Ad',
  '_modzzz_notify_classifieds_comment_delete_desc' => 'Delete an Ad Comment',
  '_modzzz_notify_classifieds_rate_desc' => 'Rate an Ad',
  '_modzzz_notify_classifieds_comment_rate_desc' => 'Vote on an Ad Comment',
  '_modzzz_notify_articles_commentPost_desc' => 'Comment on an Article Post',
  '_modzzz_notify_articles_comment_delete_desc' => 'Delete an Article Post Comment',
  '_modzzz_notify_articles_rate_desc' => 'Rate an Article Post',
  '_modzzz_notify_articles_comment_rate_desc' => 'Vote on an Article Post Comment',
  '_modzzz_notify_news_commentPost_desc' => 'Comment on a News Post',
  '_modzzz_notify_news_comment_delete_desc' => 'Delete a News Post Comment',
  '_modzzz_notify_news_rate_desc' => 'Rate a News Post',
  '_modzzz_notify_news_comment_rate_desc' => 'Vote on a News Post Comment',
  '_modzzz_notify_store_add_desc' => 'Add a Store Product',
  '_modzzz_notify_store_delete_desc' => 'Delete a Store Product',
  '_modzzz_notify_store_commentPost_desc' => 'Comment on a Store Product',
  '_modzzz_notify_store_comment_delete_desc' => 'Delete a Store Product Comment',
  '_modzzz_notify_store_rate_desc' => 'Rate a Store Product',
  '_modzzz_notify_store_comment_rate_desc' => 'Vote on a Store Product Comment',
  '_modzzz_notify_event_add_desc' => 'Publication d\'un événement',
  '_modzzz_notify_event_delete_desc' => 'Supprimer un événement',
  '_modzzz_notify_event_join_desc' => 'Participation à un événement',
  '_modzzz_notify_job_delete_desc' => 'Suppression d\'un Job',
  '_modzzz_notify_business_listings_delete_desc' => 'Suppression d\'une Entreprise',
  '_modzzz_notify_modzzz_articles_delete_desc' => 'Suppression d\'un article',
  '_modzzz_notify_modzzz_classified_delete_desc' => 'Suppression d\'une annonce',
  '_modzzz_notify_job_add_desc' => 'Publication d\'un job',
  '_modzzz_notify_business_listings_add_desc' => 'Inscription d\'une Entreprise',
  '_modzzz_notify_modzzz_articles_add_desc' => 'Post d\\un article',
  '_modzzz_notify_modzzz_classified_add_desc' => 'Publication d\'une annonce',
  '_modzzz_notify_job_join_desc' => 'Suivi d\'un job',
  '_modzzz_notify_business_listings_join_desc' => 'Suivi d\'une entreprise',
  '_modzzz_notify_modzzz_articles_join_desc' => 'Suivi d\'un article',
  '_modzzz_notify_modzzz_classified_join_desc' => 'Suivi d\'une annonce',
  '_modzzz_notify_job_commentPost_desc' => 'Commentaire sur un job',
  '_modzzz_notify_business_listings_commentPost_desc' => 'Commentaire sur une entreprise',
  '_modzzz_notify_modzzz_articles_commentPost_desc' => 'Commentaire sur un article',
  '_modzzz_notify_modzzz_classified_commentPost_desc' => 'Commentaire sur une annonce',
  '_modzzz_notify_job_comment_delete_desc' => 'Supprimer un commentaire  sur un job ',
  '_modzzz_notify_business_listings_comment_delete_desc' => 'Supprimer un commentaire sur une entreprise',
  '_modzzz_notify_modzzz_articles_comment_delete_desc' => 'Supprimer un commentaire sur un article',
  '_modzzz_notify_modzzz_classified_comment_delete_desc' => 'Supprimer un commentaire sur une annonce',
  '_modzzz_notify_job_rate_desc' => 'Note sur un job',
  '_modzzz_notify_business_listings_rate_desc' => 'Note sur une entreprise',
  '_modzzz_notify_modzzz_articles_rate_desc' => 'Note sur un article',
  '_modzzz_notify_modzzz_classified_rate_desc' => 'Note sur une petite annonce',
  '_modzzz_notify_job_comment_rate_desc' => 'Vote on a job Comment',
  '_modzzz_notify_business_listings_comment_rate_desc' => 'Vote on a company Comment',
  '_modzzz_notify_modzzz_articles_comment_rate_desc' => 'Vote on an Article Comment',
  '_modzzz_notify_modzzz_classified_comment_rate_desc' => 'Vote on an Ad Comment',
  '_modzzz_notify_event_commentPost_desc' => 'Commentaire sur un événement',
  '_modzzz_notify_event_comment_delete_desc' => 'Supprimer le commentaire d\'un événement',
  '_modzzz_notify_event_rate_desc' => 'Note sur un événement',
  '_modzzz_notify_event_comment_rate_desc' => 'Vote sur un commentaire d\'un événement',
  '_modzzz_notify_group_add_desc' => 'Création  d\'un groupe',
  '_modzzz_notify_group_delete_desc' => 'Supprimer un groupe',
  '_modzzz_notify_group_join_desc' => 'Adhésion à un groupe',
  '_modzzz_notify_group_commentPost_desc' => 'Commentaire sur un groupe',
  '_modzzz_notify_group_comment_delete_desc' => 'Supprimer le commentaire d\'un groupe',
  '_modzzz_notify_group_rate_desc' => 'Note sur un groupe',
  '_modzzz_notify_group_comment_rate_desc' => 'Voter un commentaire d\'un groupe',
  '_modzzz_notify_sound_add_desc' => 'Upload a Sound',
  '_modzzz_notify_sound_commentPost_desc' => 'Comment on a Sound',
  '_modzzz_notify_sound_rate_desc' => 'Rate a Sound',
  '_modzzz_notify_sound_comment_rate_desc' => 'Vote on a Sound Comment',
  '_modzzz_notify_photo_add_desc' => 'Télécharger une Photo',
  '_modzzz_notify_photo_commentPost_desc' => 'Commenter une Photo',
  '_modzzz_notify_photo_rate_desc' => 'Noter une  Photo',
  '_modzzz_notify_photo_comment_rate_desc' => 'Voter un commentaire d\'une photo',
  '_modzzz_notify_video_add_desc' => 'Téléchargement d\'une Vidéo ',
  '_modzzz_notify_video_commentPost_desc' => 'Commentaire sur ma vidéo',
  '_modzzz_notify_video_rate_desc' => 'Noter une vidéo',
  '_modzzz_notify_video_comment_rate_desc' => 'Voter un commentaire d\'une vidéo',
  '_modzzz_notify_site_add_desc' => 'Add a Site',
  '_modzzz_notify_site_commentPost_desc' => 'Comment on a Site',
  '_modzzz_notify_site_rate_desc' => 'Rate a Site',
  '_modzzz_notify_site_comment_rate_desc' => 'Vote on a Site Comment',
  '_modzzz_notify_blog_add_desc' => 'Add a Blog Post',
  '_modzzz_notify_blog_commentPost_desc' => 'Comment on a Blog Post',
  '_modzzz_notify_blog_comment_delete_desc' => 'Delete a Blog Post Comment',
  '_modzzz_notify_blog_rate_desc' => 'Rate a Blog Post',
  '_modzzz_notify_blog_comment_rate_desc' => 'Vote on a Blog Post Comment',
  '_modzzz_notify_poll_add_desc' => 'Create a Poll',
  '_modzzz_notify_poll_vote_desc' => 'Vote on a Poll',
  '_modzzz_notify_poll_commentPost_desc' => 'Comment on a Poll',
  '_modzzz_notify_poll_comment_delete_desc' => 'Delete a Poll Comment',
  '_modzzz_notify_poll_rate_desc' => 'Rate a Poll',
  '_modzzz_notify_poll_comment_rate_desc' => 'Vote on a Poll Comment',
  '_modzzz_notify_file_add_desc' => 'Upload a File',
  '_modzzz_notify_file_commentPost_desc' => 'Comment on a File',
  '_modzzz_notify_file_comment_delete_desc' => 'Delete a File Comment',
  '_modzzz_notify_file_rate_desc' => 'Rate a File',
  '_modzzz_notify_file_comment_rate_desc' => 'Vote on a File Comment',
  '_modzzz_notify_login_desc' => 'Se connecter sur le site',
  '_modzzz_notify_join_desc' => 'S\'enregister sur le site',
  '_modzzz_notify_mail_receive_desc' => 'Reception d\'un message',
  '_modzzz_notify_wall_title' => 'Mur',
  '_modzzz_notify_wall_desc' => 'Poster sur le mur',
  '_modzzz_notify_wall_comment_desc' => 'Commenter sur le mur',
  '_modzzz_notify_hotlisted_desc' => 'Ajouter aux favoris',
  '_modzzz_notify_blocklisted_desc' => 'Add to Blocklist',
  '_modzzz_notify_friend_delete_desc' => 'Supprimer dela liste d\'amis',
  '_modzzz_notify_hotlist_delete_desc' => 'Supprimer demes favoris',
  '_modzzz_notify_blocklist_delete_desc' => 'Remove from Blocklist',
  '_modzzz_notify_forum_post_desc' => 'Create a Forum Topic',
  '_modzzz_notify_forum_reply_desc' => 'Post a Forum Reply',
  '_modzzz_notify_profile_title' => 'profil',
  '_modzzz_notify_avatar_title' => 'Photo de profil',
  '_modzzz_notify_classifieds_title' => 'une nnonce',
  '_modzzz_notify_store_title' => 'Store',
  '_modzzz_notify_event_title' => 'un événement',
  '_modzzz_notify_job_title' => 'une offre d\'emploi',
  '_modzzz_notify_modzzz_classified_title' => 'une nnonce',
  '_modzzz_notify_business_listings_title' => 'une entreprise',
  '_modzzz_notify_modzzz_articles_title' => 'un article',
  '_modzzz_notify_group_title' => 'un groupe',
  '_modzzz_notify_sound_title' => 'Sound',
  '_modzzz_notify_photo_title' => 'une photo',
  '_modzzz_notify_video_title' => 'une vidéo',
  '_modzzz_notify_site_title' => 'Site',
  '_modzzz_notify_blog_title' => 'Blog Post',
  '_modzzz_notify_poll_title' => 'Poll',
  '_modzzz_notify_file_title' => 'Fichier',
  '_modzzz_notify_friend_title' => 'Contact',
  '_modzzz_notify_hotlist_title' => 'Hotlist',
  '_modzzz_notify_blocklist_title' => 'Blocklist',
  '_modzzz_notify_forum_topic_title' => 'Forum Topic',
  '_modzzz_notify_forum_post_title' => 'Forum Post',
  '_modzzz_notify_notifications_for_period' => 'Notifications pour {0}',
  '_modzzz_notify_do_not_notify_me' => 'Ne pas me notifier',
  '_modzzz_notify_notify_me_immediately' => 'Me Notifier immédiatement',
  '_modzzz_notify_notify_me_daily' => 'Me Notifier une fois quotidiennement',
  '_modzzz_notify_notify_me_weekly' => 'Me Notifier une fois par semaine',
  '_modzzz_notify_notify_me_monthly' => 'Me Notifier une fois par mois',
  '_modzzz_notify_save' => 'Save',
  '_modzzz_notify_articles_title' => 'un article', 
  
    '_modzzz_notify_investment' => 'Projet',
  '_modzzz_notify_investment_delete_desc' => 'Suppression d\'un projet',
  '_modzzz_notify_investment_add_desc' => 'Publication d\'un projet',
  '_modzzz_notify_investment_join_desc' => 'Suivi d\'un projet',
  '_modzzz_notify_investment_commentPost_desc' => 'Commentaire sur un projet',
  '_modzzz_notify_investment_comment_delete_desc' => 'Supprimer un commentaire  sur un projet ',
  '_modzzz_notify_investment_rate_desc' => 'Vote sur un projet',
  '_modzzz_notify_investment_comment_rate_desc' => 'Vote sur le commentaire d\'un projet ',
  '_modzzz_notify_investment_title' => 'un projet',
  
    '_modzzz_notify_formations' => 'Formation',
  '_modzzz_notify_formation_delete_desc' => 'Suppression d\'une formation',
  '_modzzz_notify_formation_add_desc' => 'Publication d\'une formation',
  '_modzzz_notify_formation_join_desc' => 'Suivi d\'une formation',
  '_modzzz_notify_formation_commentPost_desc' => 'Commentaire sur une formation',
  '_modzzz_notify_formation_comment_delete_desc' => 'Supprimer un commentaire  sur une formation ',
  '_modzzz_notify_formation_rate_desc' => 'Vote sur une formation',
  '_modzzz_notify_formation_comment_rate_desc' => 'Vote sur le commentaire d\'une formation ',
  '_modzzz_notify_formation_title' => 'une formation',


);