<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Investment
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Investment';

$aLangContent = array(

    '_modzzz_investment_packages_empty' => 'There are no Investments Packages', 
    '_modzzz_investment_package_description' => 'Description', 
    '_modzzz_investment_package_featured' => 'Featured', 
    '_modzzz_investment_form_caption_quantity' => 'Quantity', 
    '_modzzz_investment_form_caption_currency' => 'Currency', 
	'_modzzz_investment_miles' => 'miles', 
	'_modzzz_investment_kilometers' => 'Km', 
	'_modzzz_investment_map_search_explanation' => 'Enter the City and Country (eg. miramer or miramer,US)', 

    '_modzzz_investment_featured_status' => 'Featured Status', 
    '_modzzz_investment_featured_until' => 'Featured until', 
    '_modzzz_investment_not_featured' => 'Not Featured', 
 	'_modzzz_investment_extend_featured' => 'Extend Featured Status',  
 
    '_modzzz_investment_page_title_sale_pending' => 'Sale Pending', 
    '_modzzz_investment_page_title_sold' => 'Sold', 
    '_modzzz_investment_admin_cancel_sale' => 'Cancel Sale', 
    '_modzzz_investment_admin_mark_complete' => 'Sale Completed', 
    '_modzzz_investment_offered_by' => 'Offered made by', 
    '_modzzz_investment_action_title_buy' => 'Buy', 

    '_modzzz_investment_form_caption_investment_item' => 'Investment Item', 
    '_modzzz_investment_message_sent' => 'Message has been sent to the Seller. <a href="{0}">Go back to listing</a>', 
    '_modzzz_investment_message_not_sent' => 'Failed to send message, <a href="{0}">please try again</a>', 
     '_modzzz_investment_caption_make_buy_offer' => 'Buy', 

    '_modzzz_investment_form_buy_message' => 'If you are interested in purchasing this item, send details of your interest to the seller so they can make arrangements with you to complete the transaction.', 
    '_modzzz_investment_form_caption_message' => 'Message', 
    '_modzzz_investment_form_info_message' => 'Enter your message with details of your purchase request', 
 

    '_modzzz_investment_block_submenu_salepending_investment' => 'Sale Pending', 
    '_modzzz_investment_block_submenu_sold_investment' => 'Sold', 
 

    '_modzzz_investment_form_header_additional_info' => 'Additional Information', 
    '_modzzz_investment_block_additional' => 'Additional Details', 

    '_modzzz_investment_menu_packages' => 'Packages', 
    '_modzzz_investment_page_title_packages' => 'Investments Packages', 
    '_modzzz_investment_block_packages' => 'Investments Packages', 
 
    '_modzzz_investment_categ_type' => 'Category Type', 
    '_modzzz_investment_why' => 'Why?', 
    '_modzzz_investment_form_header_contact_details' => 'Contact Details', 

    '_modzzz_investment_category_rent' => 'Rent', 
    '_modzzz_investment_category_sale' => 'Sale', 
    '_modzzz_investment_category_other' => 'Other', 
    '_modzzz_investment_for' => 'for', 

    '_modzzz_investment_wanted' => 'Wanted',  
    '_modzzz_investment_rent' => 'For Rent', 
    '_modzzz_investment_sale' => 'For Sale', 
    '_modzzz_investment_free' => 'Free', 
    '_modzzz_investment_hiring' => 'Hiring', 
    '_modzzz_investment_seeking' => 'Seeking', 
    '_modzzz_investment_form_caption_type' => 'Type', 
    '_modzzz_investment_form_caption_type_of_investment' => 'Who you are', 
    '_modzzz_investment_form_err_type_of_investment' => 'Please select who you are',  
    '_modzzz_investment_form_caption_price' => 'Price', 
    '_modzzz_investment_form_err_price' => 'Please enter a valid Price',   
    '_modzzz_investment_form_caption_saleprice' => 'Sale Price', 
    '_modzzz_investment_form_err_saleprice' => 'Please enter a valid Sale Price',   

    '_modzzz_investment_form_caption_why_wanted' => 'Why do you need it?', 
    '_modzzz_investment_form_caption_why_rent' => 'Why are you renting it out?', 
    '_modzzz_investment_form_caption_why_rent_wanted' => 'Why do you need a place to live?', 
	'_modzzz_investment_form_caption_why_sell' => 'Why are you selling it?', 
    '_modzzz_investment_form_caption_why_free' => 'Why are you giving it away?', 
    '_modzzz_investment_form_caption_why_hiring' => 'Why do you need to fill this position?', 
    '_modzzz_investment_form_caption_why_seeking' => 'Why are you the right person for the job?',  

    '_modzzz_investment_custom_field1' => 'Custom Field 1', 
    '_modzzz_investment_custom_field2' => 'Custom Field 2', 
    '_modzzz_investment_custom_field3' => 'Custom Field 3', 
    '_modzzz_investment_custom_field4' => 'Custom Field 4', 
    '_modzzz_investment_custom_field5' => 'Custom Field 5', 
    '_modzzz_investment_custom_field6' => 'Custom Field 6', 
    '_modzzz_investment_custom_field7' => 'Custom Field 7', 
    '_modzzz_investment_custom_field8' => 'Custom Field 8', 
    '_modzzz_investment_custom_field9' => 'Custom Field 9', 
    '_modzzz_investment_custom_field10' => 'Custom Field 10', 

    '_modzzz_investment_parent_category_name' => 'Parent Category', 
    '_modzzz_investment_category_name' => 'Sub Category', 
 
    '_modzzz_investment_menu_view_forum' => 'Forum', 
    '_modzzz_investment_privacy_post_in_forum' => 'Post In Forum',
 
   	'_modzzz_investment_form_header_video_embed' => 'Video Embed',
   	'_modzzz_investment_caption_video_embed_code' => 'Embed Code',
   	'_modzzz_investment_block_video_embed' => 'External Video',
	'_modzzz_investment_form_info_video_embed_code' => 'Enter either the URL or Embed Code for Youtube Video. Enter the Embed Code for other video sharing site (eg &lt;embed&gt;....&lt;/embed&gt;)',
 

	'_modzzz_investment_caption_membership_view_filter' => 'Allow viewing by membership',
	'_modzzz_investment_err_membership_view_filter' => 'incorrect value', 
    '_modzzz_investment_info_membership_view_filter' => 'only these members will be able to view this investment',
    '_modzzz_investment_membership_filter_none' => 'Allow All',	

    '_mma_investment_files_add' => 'investment documents add',  
    '_mma_investment_photos_add' => 'investment photos add',  
    '_mma_investment_videos_add' => 'investment videos add',  
    '_mma_investment_sounds_add' => 'investment sounds add',  

    '_modzzz_investment_continue' => 'Continue',  
    '_modzzz_investment_on' => 'on',  
    '_modzzz_investment_yes' => 'yes',  
    '_modzzz_investment_no' => 'no',  
 
	'_modzzz_investment_package_videos' => 'Videos',  	
	'_modzzz_investment_package_photos' => 'Photos',  	
	'_modzzz_investment_package_sounds' => 'Sounds',  	
	'_modzzz_investment_package_files' => 'Documents', 

	'_modzzz_investment_block_investment_states' => 'Browse Local Investment Opportunities', 
 
    '_mma_investment_purchase_featured' => 'investment purchase featured', 
    '_mma_investment_make_claim' => 'investment make claim', 
    '_mma_investment_make_inquiry' => 'investment make inquiry',  
    '_mma_investment_buy_item' => 'investment buy item',  
   
    '_modzzz_investment_regions_for_country' => 'Browse Opportunities in {0}',  
	'_modzzz_investment_block_browse_state' => 'Browse States', 
	'_modzzz_investment_block_browse_state_investments' => 'Browse Listings by State', 
	'_modzzz_investment_block_account' => 'Investments in my Area',  
	'_modzzz_investment_block_browse_country' => 'Browse by Country', 
	'_modzzz_investment_page_title_local' => 'Browse Local Listings',  
	'_modzzz_investment_caption_browse_local' => 'Browse Local Listings in {0}', 
	'_modzzz_investment_menu_local' => 'Local', 
 	'_modzzz_investment_block_local' => 'More Local Listings',
	'_modzzz_investment_block_other' => 'Other Listings by this member',
 	'_modzzz_investment_caption_browse_other' => 'Other Listings by {0}',


	'_modzzz_investment_action_title_purchase_featured' => 'Get Featured',
	'_modzzz_investment_action_title_extend_featured' => 'Extend Featured',  
	'_modzzz_investment_purchase_featured' => 'Purchase Featured Status', 
	'_modzzz_investment_purchase_featured_status' => 'Purchase Featured Status', 
	'_modzzz_investment_quantity' => 'Quantity',   
	'_modzzz_investment_featured_purchase_success' => 'You successfully Purchased {0} Days of Featured Status', 
	'_modzzz_investment_featured_purchase_fail' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_investment_featured_purchase_failed' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_investment_transaction_completed_already' => 'This transaction was already completed',  
	'_modzzz_investment_featured_cost_per_day' => 'Cost per Day',  
	'_modzzz_investment_caption_num_featured_days' => 'Number of Featured Days',    
	'_modzzz_investment_caption_err_featured_days' => 'You must enter Number of Featured Days',    
	'_modzzz_investment_get_featured' => 'Get Featured',   
    '_modzzz_investment_block_category_investment' => 'Investments in this Category',
    '_modzzz_investment_block_subcategories' => 'Sub-Categories',  
    '_modzzz_investment_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button', 
	'_modzzz_investment_categ_name' => 'Category',
	'_modzzz_investment_categ_btn_edit' => 'Edit',
	'_modzzz_investment_categ_btn_delete' => 'Delete',
	'_modzzz_investment_categ_btn_add' => 'Add',
	'_modzzz_investment_categ_btn_save' => 'Save',
	'_modzzz_investment_categ_btn_subcategories' => 'Sub-Categories', 
 	'_modzzz_investment_categories' => 'Categories',
 	'_modzzz_investment_menu_admin_manage_categories' => 'Categories',
  	'_modzzz_investment_menu_admin_manage_subcategories' => 'Sub-Cats',
  	'_modzzz_investment_subcategories' => 'Sub-Categories',
  	'_modzzz_investment_categories' => 'Categories',
    '_modzzz_investment_parent_categories' => 'Parent',
    '_modzzz_investment_all_categories' => 'All Categories',
    '_modzzz_investment_block_categories' => 'Categories',
    '_modzzz_investment_block_investment_subcategories' => 'Sub-Categories',
    '_modzzz_investment_block_answer_categories' => 'Investment Categories',
    '_modzzz_investment_menu_categories' => 'Categories',
    '_modzzz_investment_page_title_browse_by_category' => 'Browse Investments By Category: ',
    '_modzzz_investment_form_caption_category' => 'Category',
    '_modzzz_investment_form_err_category' => 'Category is invalid', 
	'_modzzz_investment_page_title_category' => 'Category', 
    '_modzzz_investment_page_title_categories' => 'Investments Categories',
    '_modzzz_investment_page_title_subcategories' => 'Investments Sub-Categories', 
    '_modzzz_investment_investments_in_category' => '<b>Investments</b> in <b>%s</b>',  
    '_modzzz_investment_block_investment' => 'Investments', 
	'_modzzz_investment_packages' => 'Packages',
	'_modzzz_investment_package_name' => 'Package Name',
	'_modzzz_investment_package_price' => 'Package Price',
	'_modzzz_investment_package_days' => 'Package Days',
	'_modzzz_investment_form_caption_package' => 'Available Packages',
	'_modzzz_investment_form_err_package' => 'Please select a Investments Package',  
	'_modzzz_investment_purchaser' => 'Purchaser', 
	'_modzzz_investment_invoice_no' => 'Invoice #', 
	'_modzzz_investment_package' => 'Package', 
	'_modzzz_investment_invoice_date' => 'Invoice Date', 
	'_modzzz_investment_invoice_due_date' => 'Due Date', 
	'_modzzz_investment_status' => 'Status',
	'_modzzz_investment_pending' => 'Pending',
	'_modzzz_investment_paid' => 'Paid',
	'_modzzz_investment_active' => 'Active',
	'_modzzz_investment_inactive' => 'Inactive',
	'_modzzz_investment_approved' => 'Approved',
	'_modzzz_investment_expired' => 'Expired', 
	'_modzzz_investment_block_submenu_pending_invoices' => 'Pending Invoices',
	'_modzzz_investment_block_submenu_orders' => 'Orders',
	'_modzzz_investment_page_title_orders' => 'Orders', 
	'_modzzz_investment_page_title_invoices' => 'Invoices', 
	'_modzzz_investment_menu_manage_invoices' => 'Invoices', 
	'_modzzz_investment_menu_manage_packages' => 'Packages',
	'_modzzz_investment_menu_manage_orders' => 'Orders',
	'_modzzz_investment_payment_method' => 'Payment Method',
	'_modzzz_investment_total' => 'Total',
	'_modzzz_investment_invoice_id' => 'Invoice ID',
	'_modzzz_investment_next_due_date' => 'Next Due Date',
	'_modzzz_investment_order_no' => 'Order #',
	 '_modzzz_investment_product_status' => 'Product Status',
	'_modzzz_investment_order_date' => 'Order Date',
	'_modzzz_investment_purchase_failed' => 'Sorry, there was a problem with the Payment.  View your Pending Orders <a href="{0}">here</a>.',
	'_modzzz_investment_transaction_completed_already' => 'The Transaction exists already. Click <a href="{0}">here</a> to view the Investment.',
	'_modzzz_investment_purchase_success' => 'Thank you. The Payment was successful. Click <a href="{0}">here</a> to view the Investment.',  
	'_modzzz_investment_trans_save_failed' => 'The Payment was successful but there was a Problem saving the transaction. Please contact the administrator with your Paypal transaction details so they can manually process your Order.',
	'_modzzz_investment_post_purchase_header' => 'Investment Purchase',  
 

	'_modzzz_investment_caption_state' => 'State',  
	'_modzzz_investment_block_browse_state' => 'Browse States', 
	'_modzzz_investment_block_browse_state_events' => 'Browse Investments by State',
	'_modzzz_investment_block_browse_country' => 'Browse by Country', 
	'_modzzz_investment_page_title_local' => 'Browse Local Investments',  
	'_modzzz_investment_caption_browse_local' => 'Browse Local Investments in {0}', 
	'_modzzz_investment_menu_local' => 'Local',
 	'_modzzz_investment_caption_search' => 'Search Investments',
 

    '_modzzz_investment_no_investments' => 'There are no Investments',
    '_sbs_txt_title_modzzz_investment' => 'Investment',
    '_modzzz_investment' => 'Investment',
    '_modzzz_investment_fans' => 'fans',
    '_modzzz_investment_add' => 'add',
    '_modzzz_investment_wall_added_new' => 'added new',
    '_modzzz_investment_wall_object' => 'investment',
    '_modzzz_investment_for_investment' => 'for %s',
    '_modzzz_investment_investment_single' => 'investment',
    '_modzzz_investment_investment_plural' => 'investments',
    '_modzzz_investment_user_unknown' => 'Someone',
    '_modzzz_investment_disabled' => 'disabled',
    '_modzzz_investment_enabled' => 'enabled',
    '_modzzz_investment_cannot_delete_default_parent' => 'Cannot Delete Default Parent Category',
	  
    '_modzzz_investment_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new investment <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_investment_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed investment <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_investment_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated investment <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_investment_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented investment <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_investment_sbs_change' => 'information was updated',
    '_modzzz_investment_sbs_comment' => 'new comment arrived',
    '_modzzz_investment_sbs_rate' => 'rating was updated',
 
    '_modzzz_investment_tab_featured' => 'Featured',
    '_modzzz_investment_tab_recent' => 'Recent',
    '_modzzz_investment_tab_top' => 'Top',
    '_modzzz_investment_tab_popular' => 'Popular',

    '_modzzz_investment_block_submenu_main' => 'Main',
    '_modzzz_investment_block_submenu_add_investment' => 'Add',
    '_modzzz_investment_block_submenu_manage_investment' => 'Manage',
    '_modzzz_investment_block_submenu_pending_investment' => 'Pending Approval',

    '_modzzz_investment_block_actions' => 'Actions',
    '_modzzz_investment_block_rate' => 'Rate',    
    '_modzzz_investment_block_info' => 'Info',
    '_modzzz_investment_block_desc' => 'Description',
    '_modzzz_investment_block_photo' => 'Photos',
    '_modzzz_investment_block_video' => 'Videos',
    '_modzzz_investment_block_sound' => 'Sounds',
    '_modzzz_investment_block_files' => 'Documents',
    '_modzzz_investment_block_file' => 'Documents',
    '_modzzz_investment_block_comments' => 'Comments',
    '_modzzz_investment_block_latest_featured_investment' => 'Latest Featured Investments',
    '_modzzz_investment_block_latest_featured_investors' => 'Latest Featured Investors',
    '_modzzz_investment_block_latest_featured_entrepreneurs' => 'Latest Featured Entrepreneurs',
    '_modzzz_investment_block_latest_featured_professionals' => 'Latest Featured Professionals',
    '_modzzz_investment_block_recent_professionals' => 'Recent Professionals',

    '_modzzz_investment_block_recent_investors' => 'Recent Investors',
    '_modzzz_investment_block_recent_entrepreneurs' => 'Recent Entrepreneurs',
    '_modzzz_investment_block_recent' => 'Recent Investments',
    '_modzzz_investment_block_popular' => 'Popular Investments',
    '_modzzz_investment_block_top' => 'Top Rated Investments',
    '_modzzz_investment_block_search' => 'Search Investments',
    '_modzzz_investment_block_investment_categories' => 'Categories',
    '_modzzz_investment_block_search' => 'Search for Investment Opportunities',
    '_modzzz_investment_block_nearby_opportunities' => 'Nearby Investment Opportunities',
    '_modzzz_investment_block_recent_investors' => 'Recent Investors',
    '_modzzz_investment_block_recent_entrepreneurs' => 'Recent Entrepreneurs',

    '_modzzz_investment_block_administration_owner' => 'Administration',
    '_modzzz_investment_block_users_investment' => "User Investments",
    '_modzzz_investment_block_my_investment' => 'My Investment',
    '_modzzz_investment_block_my_investments' => 'My Investments',
    '_modzzz_investment_block_area_investments' => 'Investments in my Area',

    '_modzzz_investment_block_homepage' => 'Investments',

    '_modzzz_investment_caption_add' => 'Add Investment',
    '_modzzz_investment_caption_share_investment' => 'Share Investment',
    '_modzzz_investment_caption_admin_actions' => 'Links',
    '_modzzz_investment_caption_pending_approval' => 'Pending Approval Investments', 
    
	'_modzzz_investment_menu_manage_parents' => 'Parent Cats',
    '_modzzz_investment_menu_manage_categories' => 'Cats',
    '_modzzz_investment_categ_btn_save' => 'Save',
    '_modzzz_investment_categ_btn_edit' => 'Edit',
    '_modzzz_investment_categ_btn_delete' => 'Delete',
    '_modzzz_investment_categ_name' => 'Name',
    '_modzzz_investment_categ_icon' => 'Icon',
    '_modzzz_investment_categ_present_icon' => 'Present Icon',
    '_modzzz_investment_categ_btn_add' => 'Add',

    '_modzzz_investment_menu_root' => 'Investments',
    '_modzzz_investment_menu_main' => 'Home',
    '_modzzz_investment_menu_recent' => 'Recent',
    '_modzzz_investment_menu_top_rated' => 'Top Rated',
    '_modzzz_investment_menu_popular' => 'Popular',
    '_modzzz_investment_menu_featured' => 'Featured',
    '_modzzz_investment_menu_tags' => 'Tags',
    '_modzzz_investment_menu_categories' => 'Categories',
    '_modzzz_investment_menu_calendar' => 'Calendar',
    '_modzzz_investment_menu_search' => 'Search',
    '_modzzz_investment_menu_view_investment' => 'Main',
    '_modzzz_investment_menu_view_comments' => 'Comments',
    '_modzzz_investment_menu_view_photos' => 'Photos',
    '_modzzz_investment_menu_view_videos' => 'Videos',
    '_modzzz_investment_menu_view_sounds' => 'Sounds',
    '_modzzz_investment_menu_view_files' => 'Documents',
    '_modzzz_investment_menu_my_investment_profile' => 'Investments',

    '_modzzz_investment_menu_admin_pending_approval' => 'Pending',
    '_modzzz_investment_menu_admin_entries' => 'Admin Investments',
    '_modzzz_investment_menu_admin_add_entry' => 'Add',
    '_modzzz_investment_menu_admin_settings' => 'Settings',
    
    '_modzzz_investment_page_title_home' => 'Investment Home',
    '_modzzz_investment_page_title_calendar' => 'Investment Calendar',
    '_modzzz_investment_page_title_comments' => 'Comments',
    '_modzzz_investment_page_title_photos' => 'Photos',
    '_modzzz_investment_page_title_videos' => 'Videos',
    '_modzzz_investment_page_title_sounds' => 'Sounds',
    '_modzzz_investment_page_title_files' => 'Documents',
    '_modzzz_investment_page_title_my_investment' => 'My Investments',
    '_modzzz_investment_page_title_search' => 'Search',
    '_modzzz_investment_page_title_add' => 'Add Investment', 
    '_modzzz_investment_page_title_edit' => 'Edit Investment',
    '_modzzz_investment_page_title_administration' => 'Investments Administration',
    '_modzzz_investment_admin_block_administration' => 'Admin.',
    '_modzzz_investment_page_title_browse' => 'Browse Investments',
    '_modzzz_investment_page_title_pending_approval' => 'Pending Approval Investments',
    '_modzzz_investment_page_title_search_results' => 'Investment Search Results',
    '_modzzz_investment_page_title_browse_by_author' => "\'s investments",
    '_modzzz_investment_page_title_admin_investment' => 'Admin Investments',
    '_modzzz_investment_page_title_browse_by_category' => 'Browse Investments By Category: ',
    '_modzzz_investment_page_title_browse_by_tag' => 'Browse Investments By Tag: ',
    '_modzzz_investment_page_title_browse_recent' => 'Recent Investments',
    '_modzzz_investment_page_title_browse_recent_investors' => 'Recent Investors',
    '_modzzz_investment_page_title_browse_recent_entrepreneurs' => 'Recent Entrepreneurs',
    '_modzzz_investment_page_title_browse_recent_professionals' => 'Recent Professionals',

    '_modzzz_investment_page_title_browse_top_rated' => 'Top Rated Investments',
    '_modzzz_investment_page_title_browse_popular' => 'Popular Investments',
    '_modzzz_investment_page_title_browse_featured' => 'Featured Investments',
    '_modzzz_investment_page_title_browse_featured_investors' => 'Featured Investors',
    '_modzzz_investment_page_title_browse_featured_entrepreneurs' => 'Featured Entrepreneurs',
    '_modzzz_investment_page_title_browse_featured_professionals' => 'Featured Professionals',
 
    '_modzzz_investment_page_title_browse_by_day' => 'Browse Investments By Day: ',
    '_modzzz_investment_page_title_tags' => 'Investments Tags',
    '_modzzz_investment_page_title_categories' => 'Investments Categories',
    '_modzzz_investment_page_title_upload_photos' => 'Add Photos',
    '_modzzz_investment_page_title_upload_videos' => 'Add Videos',
    '_modzzz_investment_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_investment_page_title_upload_files' => 'Documents',

    '_modzzz_investment_msg_pending_approval' => 'this investment is pending approval, please wait until it will be activated',
    '_modzzz_investment_msg_investment_was_deleted' => 'Investment was deleted',
    '_modzzz_investment_msg_removed_from_featured' => 'Investment was removed from featured',
    '_modzzz_investment_msg_added_to_featured' => 'Investment was added to featured',
    '_modzzz_investment_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_investment_msg_you_have_pending_approval_investment' => 'You have <a href="%s">%d pending approval investments</a>',
    '_modzzz_investment_msg_you_have_no_investment' => 'You do not have any investments. <a href="%s">Click here</a> to add one.',
    '_modzzz_investment_msg_you_have_some_investment' => 'You have <a href="%s">%d investment(s)</a>. <a href="%s">Click here</a> to add more.',

    '_modzzz_investment_admin_delete' => 'Delete',
    '_modzzz_investment_admin_activate' => 'Activate',
    '_modzzz_investment_admin_add_new_investment' => 'Add New Investment',
    '_modzzz_investment_admin_investment' => 'Admin Investment',
    '_modzzz_investment_admin_settings' => 'Admin Settings',

    '_modzzz_investment_form_header_info' => 'Investment Info',
    '_modzzz_investment_form_header_images' => 'Photos',
    '_modzzz_investment_form_header_videos' => 'Videos',
    '_modzzz_investment_form_header_sounds' => 'Sounds',
    '_modzzz_investment_form_header_files' => 'Documents',
    '_modzzz_investment_form_header_privacy' => 'Privacy Settings',
    '_modzzz_investment_form_caption_title' => 'Title',
    '_modzzz_investment_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_investment_form_caption_desc' => 'Description',
    '_modzzz_investment_form_err_desc' => 'Please enter at least 20 characters',
    '_modzzz_investment_form_err_tags' => 'Please enter tags',
    '_modzzz_investment_form_caption_author_id' => 'Author',
    '_modzzz_investment_form_info_author' => 'Author profile ID number',
    '_modzzz_investment_form_caption_keyword' => 'Keyword',
    '_modzzz_investment_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_modzzz_investment_form_caption_category' => 'Category',
    '_modzzz_investment_form_err_category' => 'Category is invalid',    
    '_modzzz_investment_form_caption_images_choice' => 'Choose',
    '_modzzz_investment_form_info_images_choice' => 'You can choose several images from your "Investment" category',
    '_modzzz_investment_form_caption_images_upload' => 'Upload',    
    '_modzzz_investment_form_info_images_upload' => 'Image will be placed in the "Investment" category automatically',
    '_modzzz_investment_form_caption_videos_choice' => 'Choose',
    '_modzzz_investment_form_info_videos_choice' => 'You can choose several videos from your "Investment" category',
    '_modzzz_investment_form_caption_videos_upload' => 'Upload',
    '_modzzz_investment_form_info_videos_upload' => 'Video will be placed in the "Investment" category automatically',
    '_modzzz_investment_form_caption_sounds_choice' => 'Choose',
    '_modzzz_investment_form_info_sounds_choice' => 'You can choose several sounds from your "Investment" category',
    '_modzzz_investment_form_caption_sounds_upload' => 'Upload',
    '_modzzz_investment_form_info_sounds_upload' => 'Sound will be placed in the "Investment" category automatically',
    '_modzzz_investment_form_caption_files_choice' => 'Choose',
    '_modzzz_investment_form_info_files_choice' => 'Unclick checkbox to remove file from this investment',
    '_modzzz_investment_form_caption_files_upload' => 'Upload',
    '_modzzz_investment_form_info_files_upload' => 'Document will be placed in the "Investment" category and set as private automatically',
    '_modzzz_investment_form_caption_file_title' => 'Title:',
    '_modzzz_investment_form_caption_file_price' => 'Price:',
    '_modzzz_investment_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_investment_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_investment_form_info_thumb_choice' => 'You can choose any image from your "Investment" category as investment thumbnail',
    '_modzzz_investment_form_caption_country' => 'Country',
    '_modzzz_investment_form_err_country' => 'Country is a required field',
    '_modzzz_investment_form_caption_city' => 'City',
    '_modzzz_investment_form_err_city' => 'Please enter from 2 to 50 characters',
    '_modzzz_investment_form_caption_zip' => 'Zip/Postal Code',
    '_modzzz_investment_form_err_zip' => 'Zip/Postal code is required',
    '_modzzz_investment_form_err_email' => 'Invalid Email entered',

    '_modzzz_investment_action_title_edit' => 'Edit',
    '_modzzz_investment_action_title_delete' => 'Delete',
    '_modzzz_investment_action_title_share' => 'Share',
    '_modzzz_investment_action_add_to_featured' => 'Feature',    
    '_modzzz_investment_action_remove_from_featured' => 'Unfeature',
    '_modzzz_investment_action_add_investment' => 'Add Listing',
    '_modzzz_investment_action_my_investment' => 'My Listings',
    '_modzzz_investment_action_upload_photos' => 'Add Photos',
    '_modzzz_investment_action_upload_videos' => 'Add Videos',
    '_modzzz_investment_action_upload_sounds' => 'Add Sounds',
    '_modzzz_investment_action_upload_files' => 'Add Documents',
    '_modzzz_investment_action_investment_home' => 'Home',

    '_modzzz_investment_action_title_claim' => 'Claim Investment',
    '_modzzz_investment_action_title_inquire' => 'Inquire About', 
    '_modzzz_investment_action_title_spread' => 'Spread This', 
    '_modzzz_investment_action_title_promote' => 'Promote', 
    '_modzzz_investment_invitation_sent' => '%d Invitations have been sent',
	'_modzzz_investment_no_users_msg' => 'There are no users in your contacts',
	'_modzzz_investment_caption_invite' => 'Send Invitation To Friends - ',

    '_modzzz_investment_inquiry_subject' => 'Subject', 
    '_modzzz_investment_inquiry_subject_info' => 'Enter the Subject of your inquiry', 
    '_modzzz_investment_inquiry_text' => 'Message', 
    '_modzzz_investment_inquiry_text_info' => 'Enter your inquiry here. It will be forwarded to the Investment Owner',  
	'_modzzz_investment_caption_make_inquiry' => 'Make Inquiry - ',
    '_modzzz_investment_inquiry_sent' => 'your inquiry has been sent',
    '_modzzz_investment_inquiry_not_sent' => 'your inquiry has not been sent',
   
    '_modzzz_investment_claim_subject' => 'Subject', 
    '_modzzz_investment_claim_subject_info' => 'Enter the Subject of your claim', 
    '_modzzz_investment_claim_text' => 'Message', 
    '_modzzz_investment_claim_text_info' => 'Enter your proof of claim here. It will be forwarded to the Administrators',  
	'_modzzz_investment_caption_make_claim' => 'Make Claim - ',
    '_modzzz_investment_claim_sent' => 'your claim request has been sent',
    '_modzzz_investment_claim_not_sent' => 'your claim request has not been sent',
	 
	'_modzzz_investment_user_unknown' => 'Unknown', 
    '_modzzz_investment_price' => 'Price',

	'_modzzz_investment_contact' => 'Contact Details', 
	'_modzzz_investment_block_contact' => 'Contact Details', 
	'_modzzz_investment_location' => 'Location',
	'_modzzz_investment_block_location' => 'Location',
	'_modzzz_investment_block_map_view' => 'Map View', 
	'_modzzz_investment_map' => 'Google Map', 
	'_modzzz_investment_form_caption_sellerfax' => 'Fax',
	'_modzzz_investment_form_caption_sellertelephone' => 'Telephone',
	'_modzzz_investment_form_caption_selleremail' => 'Email',
	'_modzzz_investment_form_caption_sellerwebsite' => 'Website',
	'_modzzz_investment_form_caption_sellername' => 'Name',
	'_modzzz_investment_form_caption_address1' => 'Address 1',
	'_modzzz_investment_form_caption_address2' => 'Address 2', 
	'_modzzz_investment_form_err_investmentoption' => 'Please select an Option', 
	'_modzzz_investment_form_err_investmenttype' => 'Please select a Type',
    '_modzzz_investment_form_err_city' => 'Please enter from 3 to 150 characters',
  
    '_modzzz_investment_privacy_view_investment' => 'View Investment',
    '_modzzz_investment_privacy_comment' => 'Comment',
    '_modzzz_investment_privacy_rate' => 'Rate',
    '_modzzz_investment_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_investment_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_investment_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_investment_privacy_upload_files' => 'Upload Documents',
    '_modzzz_investment_privacy_edit_investment' => 'Edit Investment',
    '_modzzz_investment_privacy_admins_only' => 'Admins Only',
    '_modzzz_investment_anonymous_note' => 'your name will not appear as the poster', 
    '_mma_investment_view_investment' => 'investment view investment', 
    '_mma_investment_browse' => 'investment browse', 
    '_mma_investment_search' => 'investment search', 
    '_mma_investment_add_investment' => 'investment add investment', 
    '_mma_investment_comments_delete_and_edit' => 'investment comments delete and edit', 
    '_mma_investment_edit_any_investment' => 'investment edit any investment', 
    '_mma_investment_delete_any_investment' => 'investment delete any investment', 
    '_mma_investment_mark_as_featured' => 'investment mark as featured', 
    '_mma_investment_approve_investment' => 'investment approve investment',   
 
	'_modzzz_investment_action_title_premium' => 'Get Premium',  
    '_modzzz_investment_page_title_premium' => 'Get Premium Listing',   
	'_mma_investment_purchase' => 'investment purchase package', 

	'_modzzz_investment_action_title_extend' => 'Extend',  
	'_modzzz_investment_page_title_extend' => 'Extend Investment listing',   
	'_mma_investment_extend' => 'investment extend', 

	'_modzzz_investment_action_title_relist' => 'Re-list',  
	'_modzzz_investment_page_title_relist' => 'Re-list Investment listing',  
	'_mma_investment_relist' => 'investment relist', 

    '_modzzz_investment_form_caption_current_no_package' => 'No Package currently',   
	'_modzzz_investment_form_caption_current_package' => 'Current Package',  
	'_modzzz_investment_form_caption_package_price' => 'Package Price',  
	'_modzzz_investment_form_caption_package_days' => 'Length of Listing',   
	'_modzzz_investment_expires_never' => 'unlimited (never expires)', 
	'_modzzz_investment_days' => 'days', 
	'_modzzz_investment_form_caption_current_item' => 'Investment', 
	'_modzzz_investment_extend' => 'Extend' ,
	 
    '_modzzz_investment_form_header_location' => 'Business Location',  
    '_modzzz_investment_form_header_contact' => 'Business Contact Details',  
    '_modzzz_investment_block_share' => 'Share', 
    '_modzzz_investment_block_facebook_comments' => 'Facebook Comments', 
 
    '_modzzz_investment_enter_your_investment' => 'Enter your Listing',
    '_modzzz_investment_block_investment_create' => 'Seeking Funding or Opportunity?', 
    '_modzzz_investment_block_latest_comments' => 'Latest Comments',
    '_modzzz_investment_block_forum' => 'Latest Forum Posts',
    '_modzzz_investment_posted_by' => 'Posted by',
    '_modzzz_investment_posted_in' => 'In', 
 
	'_modzzz_investment_allow_num_listings' => 'Number of Listings allowed', 	
	'_modzzz_investment_allow_videos' => 'Allow Videos', 	
	'_modzzz_investment_allow_photos' => 'Allow Photos', 	
	'_modzzz_investment_allow_sounds' => 'Allow Sounds', 	
	'_modzzz_investment_allow_files' => 'Allow Documents', 	
 	'_modzzz_investment_featured' => 'Featured Listing',  
 	
	'_modzzz_investment_package_desc' => 'Package Description',  
    '_modzzz_investment_block_submenu_expired_investment' => 'Expired',
    '_modzzz_investment_page_title_expired' => 'Expired Listings', 
 	'_modzzz_investment_expires' => 'Expires', 	 
 	'_modzzz_investment_never' => 'Never',  
 	'_modzzz_investment_featured_listing' => 'Featured Listing (never expires)',  
 
	'_modzzz_investment_block_browse_categories_drilldown' => 'Categories Drilldown', 
	'_modzzz_investment_category_drilldown_for_item' => 'Categories Drilldown for <b>{0}</b>', 
 
 	'_modzzz_investment_paypal_item_desc' => 'Payment for Investment listing - {0}',  
 	'_modzzz_investment_paypal_featured_item_desc' => 'Purchase Featured Status - {0}',  
 	'_modzzz_investment_menu_admin_promo_details' => 'Promo Details',  

 	'_modzzz_investment_form_modify_promotion_details' => 'Modify Promo Details',  
 	'_modzzz_investment_form_caption_details' => 'Promo Text',  
 	'_modzzz_investment_form_err_details' => 'You must enter Promo Text',  
 
 	'_modzzz_investment_investor' => 'Investor',  
 	'_modzzz_investment_entrepreneur' => 'Entrepreneur',  
 	'_modzzz_investment_professional' => 'Professional',  

 	'_modzzz_investment_form_caption_investment_type' => 'Who you are',  
  	'_modzzz_investment_form_header_location' => 'Location',  

 	'_modzzz_investment_why_invest' => 'Why Invest?',  
 	'_modzzz_investment_why_seek_invest' => 'Why Seeking Funds?',  
 	'_modzzz_investment_why_seek_professional' => 'Why Seeking Professional Service?',  

 	'_modzzz_investment_form_caption_min_investment' => 'Minimum Investment',  
  	'_modzzz_investment_form_caption_max_investment' => 'Maximum Investment',  

  	'_modzzz_investment_minimum' => 'Minimum',  
  	'_modzzz_investment_maximum' => 'Maximum',  
  	'_modzzz_investment_capital' => 'Capital',  
  	'_modzzz_investment_block_capital' => 'Capital',  
  	'_modzzz_investment_form_err_max_investment' => 'You must enter Maximum Investment',  
  	'_modzzz_investment_form_err_min_investment' => 'You must enter Minimum Investment',  
  	'_modzzz_investment_all' => 'All',  
 
	/*added 7.1 */
    '_modzzz_investment_wall_added_new_comment' => 'commented on a',
    '_modzzz_investment_wall_added_new_items' => 'added {0} new investment(s)',
	'_modzzz_investment_single' => 'Investment',
    '_modzzz_investment_posted_in_topic' => 'Posted in Forum',
    '_modzzz_investment_posted_in_investment' => 'Posted in Investment Listing',
  
	'_modzzz_investment_admin_cancel' => 'Cancel',
	'_modzzz_investment_block_calendar' => 'Calendar',
    '_modzzz_investment_adm_stats' => 'Pending Investments',
 	'_modzzz_investment_remove' => 'Remove', 
  	'_modzzz_investment_block_inquiries' => 'Inquiries', 
  	'_sys_module_investment' => 'Investments', 
	
	
	'_mma_investment_mark_as_favorite' => 'investment mark as favorite',
	 '_modzzz_investment_menu_favorite' => 'Favorite Project',
    '_modzzz_investment_msg_removed_from_favorite' => 'Project was removed from favorite',
    '_modzzz_investment_msg_added_to_favorite' => 'Project was added to favorite',
    '_modzzz_investment_page_title_browse_favorite' => '<i class="sys-icon star"></i> Favorites Projects',
    '_modzzz_investment_action_add_to_favorite' => 'Favorite',    
    '_modzzz_investment_action_remove_from_favorite' => 'Not Favorite',

);