<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Investment
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Investment';

$aLangContent = array(

    '_modzzz_investment_packages_empty' => 'There are no Investments Packages', 
    '_modzzz_investment_package_description' => 'Description', 
    '_modzzz_investment_package_featured' => 'Featured', 
    '_modzzz_investment_form_caption_quantity' => 'Quantity', 
    '_modzzz_investment_form_caption_currency' => 'Currency', 
	'_modzzz_investment_miles' => 'miles', 
	'_modzzz_investment_kilometers' => 'Km', 
	'_modzzz_investment_map_search_explanation' => 'Enter the City and Country (eg. Kishasa or Kinshasa,RD Congo)', 

    '_modzzz_investment_featured_status' => 'Featured Status', 
    '_modzzz_investment_featured_until' => 'Featured until', 
    '_modzzz_investment_not_featured' => 'Not Featured', 
 	'_modzzz_investment_extend_featured' => 'Extend Featured Status',  
 
    '_modzzz_investment_page_title_sale_pending' => 'Sale Pending', 
    '_modzzz_investment_page_title_sold' => 'Sold', 
    '_modzzz_investment_admin_cancel_sale' => 'Cancel Sale', 
    '_modzzz_investment_admin_mark_complete' => 'Sale Completed', 
    '_modzzz_investment_offered_by' => 'Offre faite par', 
    '_modzzz_investment_action_title_buy' => 'Acheter', 

    '_modzzz_investment_form_caption_investment_item' => 'Investment Item', 
    '_modzzz_investment_message_sent' => 'Message has been sent to the Seller. <a href="{0}">Go back to listing</a>', 
    '_modzzz_investment_message_not_sent' => 'Failed to send message, <a href="{0}">please try again</a>', 
     '_modzzz_investment_caption_make_buy_offer' => 'Buy', 

    '_modzzz_investment_form_buy_message' => 'If you are interested in purchasing this item, send details of your interest to the seller so they can make arrangements with you to complete the transaction.', 
    '_modzzz_investment_form_caption_message' => 'Message', 
    '_modzzz_investment_form_info_message' => 'Enter your message with details of your purchase request', 
 

    '_modzzz_investment_block_submenu_salepending_investment' => 'Sale Pending', 
    '_modzzz_investment_block_submenu_sold_investment' => 'Sold', 
 

    '_modzzz_investment_form_header_additional_info' => 'Information additionnelle', 
    '_modzzz_investment_block_additional' => 'Détails supplémentaires', 

    '_modzzz_investment_menu_packages' => 'Packages', 
    '_modzzz_investment_page_title_packages' => 'Investments Packages', 
    '_modzzz_investment_block_packages' => 'Investments Packages', 
 
    '_modzzz_investment_categ_type' => 'Type de catégorie', 
    '_modzzz_investment_why' => 'Why?', 
    '_modzzz_investment_form_header_contact_details' => 'Détails du contact', 

    '_modzzz_investment_category_rent' => 'Rent', 
    '_modzzz_investment_category_sale' => 'Sale', 
    '_modzzz_investment_category_other' => 'Other', 
    '_modzzz_investment_for' => 'for', 

    '_modzzz_investment_wanted' => 'Wanted',  
    '_modzzz_investment_rent' => 'For Rent', 
    '_modzzz_investment_sale' => 'For Sale', 
    '_modzzz_investment_free' => 'Free', 
    '_modzzz_investment_hiring' => 'Hiring', 
    '_modzzz_investment_seeking' => 'Seeking', 
    '_modzzz_investment_form_caption_type' => 'Type', 
    '_modzzz_investment_form_caption_type_of_investment' => 'Qui êtes-vous?', 
    '_modzzz_investment_form_err_type_of_investment' => 'Veuillez sélectionner qui vous êtes',  
    '_modzzz_investment_form_caption_price' => 'Price', 
    '_modzzz_investment_form_err_price' => 'Please enter a valid Price',   
    '_modzzz_investment_form_caption_saleprice' => 'Sale Price', 
    '_modzzz_investment_form_err_saleprice' => 'Please enter a valid Sale Price',   

    '_modzzz_investment_form_caption_why_wanted' => 'Why do you need it?', 
    '_modzzz_investment_form_caption_why_rent' => 'Why are you renting it out?', 
    '_modzzz_investment_form_caption_why_rent_wanted' => 'Why do you need a place to live?', 
	'_modzzz_investment_form_caption_why_sell' => 'Why are you selling it?', 
    '_modzzz_investment_form_caption_why_free' => 'Why are you giving it away?', 
    '_modzzz_investment_form_caption_why_hiring' => 'Why do you need to fill this position?', 
    '_modzzz_investment_form_caption_why_seeking' => 'Why are you the right person for the job?',  

    '_modzzz_investment_custom_field1' => 'Custom Field 1', 
    '_modzzz_investment_custom_field2' => 'Custom Field 2', 
    '_modzzz_investment_custom_field3' => 'Custom Field 3', 
    '_modzzz_investment_custom_field4' => 'Custom Field 4', 
    '_modzzz_investment_custom_field5' => 'Custom Field 5', 
    '_modzzz_investment_custom_field6' => 'Custom Field 6', 
    '_modzzz_investment_custom_field7' => 'Custom Field 7', 
    '_modzzz_investment_custom_field8' => 'Custom Field 8', 
    '_modzzz_investment_custom_field9' => 'Custom Field 9', 
    '_modzzz_investment_custom_field10' => 'Custom Field 10', 

    '_modzzz_investment_parent_category_name' => 'Catégorie', 
    '_modzzz_investment_category_name' => 'Sous Catégorie', 
 
    '_modzzz_investment_menu_view_forum' => 'Forum', 
    '_modzzz_investment_privacy_post_in_forum' => 'Post In Forum',
 
   	'_modzzz_investment_form_header_video_embed' => 'Vidéo Youtube',
   	'_modzzz_investment_caption_video_embed_code' => 'Lien de la vidéo Youtube',
   	'_modzzz_investment_block_video_embed' => 'Vidéo Youtube',
	'_modzzz_investment_form_info_video_embed_code' => 'Entrez l\'URL ou le code incorporé pour la vidéo Youtube.',
 

	'_modzzz_investment_caption_membership_view_filter' => 'Autoriser l\'affichage par adhésion',
	'_modzzz_investment_err_membership_view_filter' => 'Valeur incorrecte', 
    '_modzzz_investment_info_membership_view_filter' => 'Seuls ces membres pourront voir ce projet',
    '_modzzz_investment_membership_filter_none' => 'Autoriser tout le monde',	

    '_mma_investment_files_add' => 'investment documents add',  
    '_mma_investment_photos_add' => 'investment photos add',  
    '_mma_investment_videos_add' => 'investment videos add',  
    '_mma_investment_sounds_add' => 'investment sounds add',  

    '_modzzz_investment_continue' => 'Continuer',  
    '_modzzz_investment_on' => 'sur',  
    '_modzzz_investment_yes' => 'Oui',  
    '_modzzz_investment_no' => 'No',  
 
	'_modzzz_investment_package_videos' => 'Vidéos',  	
	'_modzzz_investment_package_photos' => 'Photos',  	
	'_modzzz_investment_package_sounds' => 'Sounds',  	
	'_modzzz_investment_package_files' => 'Documents', 

	'_modzzz_investment_block_investment_states' => 'Parcourir les opportunités d\'investissement locales', 
 
    '_mma_investment_purchase_featured' => 'investment purchase featured', 
    '_mma_investment_make_claim' => 'investment make claim', 
    '_mma_investment_make_inquiry' => 'investment make inquiry',  
    '_mma_investment_buy_item' => 'investment buy item',  
   
    '_modzzz_investment_regions_for_country' => 'Parcourir des opportunités dans {0}',  
	'_modzzz_investment_block_browse_state' => 'Parcourir des opportunités régionales', 
	'_modzzz_investment_block_browse_state_investments' => 'Parcourir des opportunités régionales', 
	'_modzzz_investment_block_account' => 'Opportunités près de chez moi',  
	'_modzzz_investment_block_browse_country' => 'Paercourir des opportunités par pays', 
	'_modzzz_investment_page_title_local' => 'Opportunités près de chez moi',  
	'_modzzz_investment_caption_browse_local' => 'Parcourir des Opportunités dans {0}', 
	'_modzzz_investment_menu_local' => 'Local', 
 	'_modzzz_investment_block_local' => 'Plus d\'opportunit"s locale',
	'_modzzz_investment_block_other' => 'Autres opportunités postées par ce membre',
 	'_modzzz_investment_caption_browse_other' => 'Autres opportunités par {0}',


	'_modzzz_investment_action_title_purchase_featured' => 'Get Featured',
	'_modzzz_investment_action_title_extend_featured' => 'Extend Featured',  
	'_modzzz_investment_purchase_featured' => 'Purchase Featured Status', 
	'_modzzz_investment_purchase_featured_status' => 'Purchase Featured Status', 
	'_modzzz_investment_quantity' => 'Quantity',   
	'_modzzz_investment_featured_purchase_success' => 'You successfully Purchased {0} Days of Featured Status', 
	'_modzzz_investment_featured_purchase_fail' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_investment_featured_purchase_failed' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_investment_transaction_completed_already' => 'This transaction was already completed',  
	'_modzzz_investment_featured_cost_per_day' => 'Cost per Day',  
	'_modzzz_investment_caption_num_featured_days' => 'Number of Featured Days',    
	'_modzzz_investment_caption_err_featured_days' => 'You must enter Number of Featured Days',    
	'_modzzz_investment_get_featured' => 'Get Featured',   
    '_modzzz_investment_block_category_investment' => 'Projets / Investissements dans cette catégorie',
    '_modzzz_investment_block_subcategories' => 'Sous-Catégorie',  
    '_modzzz_investment_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button', 
	'_modzzz_investment_categ_name' => 'Category',
	'_modzzz_investment_categ_btn_edit' => 'Edit',
	'_modzzz_investment_categ_btn_delete' => 'Delete',
	'_modzzz_investment_categ_btn_add' => 'Add',
	'_modzzz_investment_categ_btn_save' => 'Save',
	'_modzzz_investment_categ_btn_subcategories' => 'Sous-Catégories', 
 	'_modzzz_investment_categories' => 'Categories',
 	'_modzzz_investment_menu_admin_manage_categories' => 'Catégories',
  	'_modzzz_investment_menu_admin_manage_subcategories' => 'Sub-Cats',
  	'_modzzz_investment_subcategories' => 'Sous-Catégories',
  	'_modzzz_investment_categories' => 'Catégories',
    '_modzzz_investment_parent_categories' => 'Parent',
    '_modzzz_investment_all_categories' => 'All Categories',
    '_modzzz_investment_block_categories' => 'Categories',
    '_modzzz_investment_block_investment_subcategories' => 'Sub-Categories',
    '_modzzz_investment_block_answer_categories' => 'Investment Categories',
    '_modzzz_investment_menu_categories' => 'Catégories',
    '_modzzz_investment_page_title_browse_by_category' => 'Parcourir des projects/Investissement par catégorie: ',
    '_modzzz_investment_form_caption_category' => 'Catégory',
    '_modzzz_investment_form_err_category' => 'Category is invalid', 
	'_modzzz_investment_page_title_category' => 'Catégorie', 
    '_modzzz_investment_page_title_categories' => 'Investments Categories',
    '_modzzz_investment_page_title_subcategories' => 'Investments Sub-Categories', 
    '_modzzz_investment_investments_in_category' => '<b>Projets/Investissements</b> dans <b>%s</b>',  
    '_modzzz_investment_block_investment' => 'Investessements', 
	'_modzzz_investment_packages' => 'Packages',
	'_modzzz_investment_package_name' => 'Package Name',
	'_modzzz_investment_package_price' => 'Package Price',
	'_modzzz_investment_package_days' => 'Package Days',
	'_modzzz_investment_form_caption_package' => 'Available Packages',
	'_modzzz_investment_form_err_package' => 'Please select a Investments Package',  
	'_modzzz_investment_purchaser' => 'Purchaser', 
	'_modzzz_investment_invoice_no' => 'Invoice #', 
	'_modzzz_investment_package' => 'Package', 
	'_modzzz_investment_invoice_date' => 'Invoice Date', 
	'_modzzz_investment_invoice_due_date' => 'Due Date', 
	'_modzzz_investment_status' => 'Status',
	'_modzzz_investment_pending' => 'Pending',
	'_modzzz_investment_paid' => 'Paid',
	'_modzzz_investment_active' => 'Active',
	'_modzzz_investment_inactive' => 'Inactive',
	'_modzzz_investment_approved' => 'Approved',
	'_modzzz_investment_expired' => 'Expired', 
	'_modzzz_investment_block_submenu_pending_invoices' => 'Pending Invoices',
	'_modzzz_investment_block_submenu_orders' => 'Orders',
	'_modzzz_investment_page_title_orders' => 'Orders', 
	'_modzzz_investment_page_title_invoices' => 'Invoices', 
	'_modzzz_investment_menu_manage_invoices' => 'Invoices', 
	'_modzzz_investment_menu_manage_packages' => 'Packages',
	'_modzzz_investment_menu_manage_orders' => 'Orders',
	'_modzzz_investment_payment_method' => 'Payment Method',
	'_modzzz_investment_total' => 'Total',
	'_modzzz_investment_invoice_id' => 'Invoice ID',
	'_modzzz_investment_next_due_date' => 'Next Due Date',
	'_modzzz_investment_order_no' => 'Order #',
	 '_modzzz_investment_product_status' => 'Product Status',
	'_modzzz_investment_order_date' => 'Order Date',
	'_modzzz_investment_purchase_failed' => 'Sorry, there was a problem with the Payment.  View your Pending Orders <a href="{0}">here</a>.',
	'_modzzz_investment_transaction_completed_already' => 'The Transaction exists already. Click <a href="{0}">here</a> to view the Investment.',
	'_modzzz_investment_purchase_success' => 'Thank you. The Payment was successful. Click <a href="{0}">here</a> to view the Investment.',  
	'_modzzz_investment_trans_save_failed' => 'The Payment was successful but there was a Problem saving the transaction. Please contact the administrator with your Paypal transaction details so they can manually process your Order.',
	'_modzzz_investment_post_purchase_header' => 'Investment Purchase',  
 

	'_modzzz_investment_caption_state' => 'State',  
	'_modzzz_investment_block_browse_state' => 'Browse States', 
	'_modzzz_investment_block_browse_state_events' => 'Browse Investments by State',
	'_modzzz_investment_block_browse_country' => 'Browse by Country', 
	'_modzzz_investment_page_title_local' => 'Browse Local Investments',  
	'_modzzz_investment_caption_browse_local' => 'Browse Local Investments in {0}', 
	'_modzzz_investment_menu_local' => 'Local',
 	'_modzzz_investment_caption_search' => 'Rechercher des projets / Investissement',
 

    '_modzzz_investment_no_investments' => 'Aucun projet / investissement',
    '_sbs_txt_title_modzzz_investment' => 'Projet /Investissement',
    '_modzzz_investment' => 'Projet /Investissement',
    '_modzzz_investment_fans' => 'fans',
    '_modzzz_investment_add' => 'ajouter',
    '_modzzz_investment_wall_added_new' => 'a ajouté un',
    '_modzzz_investment_wall_object' => 'Projet /Investissement',
    '_modzzz_investment_for_investment' => 'pour %s',
    '_modzzz_investment_investment_single' => 'Projet /Investissement',
    '_modzzz_investment_investment_plural' => 'Projets /Investissements',
    '_modzzz_investment_user_unknown' => 'Someone',
    '_modzzz_investment_disabled' => 'disabled',
    '_modzzz_investment_enabled' => 'enabled',
    '_modzzz_investment_cannot_delete_default_parent' => 'Cannot Delete Default Parent Category',
	  
    '_modzzz_investment_spy_post' => '<a href="{profile_link}">{profile_nick}</a> a ajouté un nouveau projet / investissement <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_investment_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> a modifié un projet / investissement <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_investment_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> a noté un projet / investissement <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_investment_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> a commenté sur un projet / investissement <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_investment_sbs_change' => 'information was updated',
    '_modzzz_investment_sbs_comment' => 'new comment arrived',
    '_modzzz_investment_sbs_rate' => 'rating was updated',
 
    '_modzzz_investment_tab_featured' => 'En Vedette',
    '_modzzz_investment_tab_recent' => 'Recent',
    '_modzzz_investment_tab_top' => 'Top',
    '_modzzz_investment_tab_popular' => 'Populaire',

    '_modzzz_investment_block_submenu_main' => 'Projets | Investissement',
    '_modzzz_investment_block_submenu_add_investment' => 'Ajouter',
    '_modzzz_investment_block_submenu_manage_investment' => 'Gérer',
    '_modzzz_investment_block_submenu_pending_investment' => 'En attente de validation',

    '_modzzz_investment_block_actions' => 'Actions',
    '_modzzz_investment_block_rate' => 'Noter',    
    '_modzzz_investment_block_info' => 'Info',
    '_modzzz_investment_block_desc' => 'Description',
    '_modzzz_investment_block_photo' => 'Photos',
    '_modzzz_investment_block_video' => 'Vidéos',
    '_modzzz_investment_block_sound' => 'Sounds',
    '_modzzz_investment_block_files' => 'Documents',
    '_modzzz_investment_block_file' => 'Documents',
    '_modzzz_investment_block_comments' => 'Commentaires',
    '_modzzz_investment_block_latest_featured_investment' => 'Projets / Investissement à l\'honneur',
    '_modzzz_investment_block_latest_featured_investors' => 'Investisseurs à l\'honneur',
    '_modzzz_investment_block_latest_featured_entrepreneurs' => 'Entrepreneurs  à l\'honneur',
    '_modzzz_investment_block_latest_featured_professionals' => 'Professionnels  à l\'honneur',
    '_modzzz_investment_block_recent_professionals' => 'Professionnels ',

    '_modzzz_investment_block_recent_investors' => 'Investisseurs',
    '_modzzz_investment_block_recent_entrepreneurs' => 'Entrepreneurs',
    '_modzzz_investment_block_recent' => 'Projets/Investissements récents',
    '_modzzz_investment_block_popular' => 'Projets/Investissements populaires',
    '_modzzz_investment_block_top' => 'Projets/Investissements les plus notés',
    '_modzzz_investment_block_search' => 'Rechercher des Projets/Investissements',
    '_modzzz_investment_block_investment_categories' => 'Catégories',
    '_modzzz_investment_block_search' => 'Rechercher d\'opportunités d\'investissement',
    '_modzzz_investment_block_nearby_opportunities' => 'Opportunités d\'investissement à proximité',
    '_modzzz_investment_block_recent_investors' => 'Investisseurs récents',
    '_modzzz_investment_block_recent_entrepreneurs' => 'Entrepreneurs récents',

    '_modzzz_investment_block_administration_owner' => 'Administration',
    '_modzzz_investment_block_users_investment' => "Mes projets",
    '_modzzz_investment_block_my_investment' => 'Mes projets',
    '_modzzz_investment_block_my_investments' => 'Mes projets',
    '_modzzz_investment_block_area_investments' => 'Projets / Investissements dans ma région',

    '_modzzz_investment_block_homepage' => 'Projets / Investissements',

    '_modzzz_investment_caption_add' => 'Ajouter un projet',
    '_modzzz_investment_caption_share_investment' => 'partager ce projet',
    '_modzzz_investment_caption_admin_actions' => 'Liens',
    '_modzzz_investment_caption_pending_approval' => 'Projet en attente de validation', 
    
	'_modzzz_investment_menu_manage_parents' => 'Parent Cats',
    '_modzzz_investment_menu_manage_categories' => 'Cats',
    '_modzzz_investment_categ_btn_save' => 'Save',
    '_modzzz_investment_categ_btn_edit' => 'Edit',
    '_modzzz_investment_categ_btn_delete' => 'Delete',
    '_modzzz_investment_categ_name' => 'Name',
    '_modzzz_investment_categ_icon' => 'Icon',
    '_modzzz_investment_categ_present_icon' => 'Present Icon',
    '_modzzz_investment_categ_btn_add' => 'Add',

    '_modzzz_investment_menu_root' => 'Projets | Investissements',
    '_modzzz_investment_menu_main' => 'Accueil',
    '_modzzz_investment_menu_recent' => 'Récent',
    '_modzzz_investment_menu_top_rated' => 'Le plus noté',
    '_modzzz_investment_menu_popular' => 'Populaire',
    '_modzzz_investment_menu_featured' => 'En vedette',
    '_modzzz_investment_menu_tags' => 'Tags',
    '_modzzz_investment_menu_categories' => 'Catégories',
    '_modzzz_investment_menu_calendar' => 'Calendrier',
    '_modzzz_investment_menu_search' => 'Rechercher',
    '_modzzz_investment_menu_view_investment' => 'Projet | investissement',
    '_modzzz_investment_menu_view_comments' => 'Commentaires',
    '_modzzz_investment_menu_view_photos' => 'Photos',
    '_modzzz_investment_menu_view_videos' => 'Vidéos',
    '_modzzz_investment_menu_view_sounds' => 'Sounds',
    '_modzzz_investment_menu_view_files' => 'Documents',
    '_modzzz_investment_menu_my_investment_profile' => 'Projets | investissements',

    '_modzzz_investment_menu_admin_pending_approval' => 'Pending',
    '_modzzz_investment_menu_admin_entries' => 'Admin Investments',
    '_modzzz_investment_menu_admin_add_entry' => 'Add',
    '_modzzz_investment_menu_admin_settings' => 'Settings',
    
    '_modzzz_investment_page_title_home' => 'Accueil | Projets | Investissements',
    '_modzzz_investment_page_title_calendar' => 'Investment Calendar',
    '_modzzz_investment_page_title_comments' => 'Commentaires',
    '_modzzz_investment_page_title_photos' => 'Photos',
    '_modzzz_investment_page_title_videos' => 'Vidéos',
    '_modzzz_investment_page_title_sounds' => 'Sounds',
    '_modzzz_investment_page_title_files' => 'Documents',
    '_modzzz_investment_page_title_my_investment' => 'Mes projets',
    '_modzzz_investment_page_title_search' => 'Rechercher',
    '_modzzz_investment_page_title_add' => 'Ajouter un projet', 
    '_modzzz_investment_page_title_edit' => 'Modifier un projet',
    '_modzzz_investment_page_title_administration' => 'Administration',
    '_modzzz_investment_admin_block_administration' => 'Admin.',
    '_modzzz_investment_page_title_browse' => 'Parcourirs des opportunités / projets ',
    '_modzzz_investment_page_title_pending_approval' => 'Projets en attente d\'approbation',
    '_modzzz_investment_page_title_search_results' => 'Résultats de recherche des projets',
    '_modzzz_investment_page_title_browse_by_author' => "\'s investments",
    '_modzzz_investment_page_title_admin_investment' => 'Admin Investments',
    '_modzzz_investment_page_title_browse_by_category' => 'Parcourir des projets par catégorie: ',
    '_modzzz_investment_page_title_browse_by_tag' => 'Parcourir des projets par mots clés: ',
    '_modzzz_investment_page_title_browse_recent' => 'Projets récents',
    '_modzzz_investment_page_title_browse_recent_investors' => 'Investisseurs récents',
    '_modzzz_investment_page_title_browse_recent_entrepreneurs' => 'Entrepreneurs récents',
    '_modzzz_investment_page_title_browse_recent_professionals' => 'Professionnels récents',

    '_modzzz_investment_page_title_browse_top_rated' => 'Projets les plus notés',
    '_modzzz_investment_page_title_browse_popular' => 'Porjets les plus populaire',
    '_modzzz_investment_page_title_browse_featured' => 'Projets à l\'honneur',
    '_modzzz_investment_page_title_browse_featured_investors' => 'Investisseurs à l\'honneur',
    '_modzzz_investment_page_title_browse_featured_entrepreneurs' => 'Entrepreneurs à l\'honneur',
    '_modzzz_investment_page_title_browse_featured_professionals' => 'Professionnels à l\'honneur',
 
    '_modzzz_investment_page_title_browse_by_day' => 'Parcourir des projets par date: ',
    '_modzzz_investment_page_title_tags' => 'Mots clés',
    '_modzzz_investment_page_title_categories' => 'Investments Categories',
    '_modzzz_investment_page_title_upload_photos' => 'Ajouter des Photos',
    '_modzzz_investment_page_title_upload_videos' => 'Add Videos',
    '_modzzz_investment_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_investment_page_title_upload_files' => 'Ajouter des Documents',

    '_modzzz_investment_msg_pending_approval' => 'cete annonce  est en attente d\'approbation, veuillez attendre qu\'elle soit activée',
    '_modzzz_investment_msg_investment_was_deleted' => 'Annonce supprimée',
    '_modzzz_investment_msg_removed_from_featured' => 'Investment was removed from featured',
    '_modzzz_investment_msg_added_to_featured' => 'Investment was added to featured',
    '_modzzz_investment_msg_photo_is_pending_approval' => 'Photo en attente d\'approbation',
    '_modzzz_investment_msg_you_have_pending_approval_investment' => 'You have <a href="%s">%d pending approval investments</a>',
    '_modzzz_investment_msg_you_have_no_investment' => 'You do not have any investments. <a href="%s">Click here</a> to add one.',
    '_modzzz_investment_msg_you_have_some_investment' => 'You have <a href="%s">%d investment(s)</a>. <a href="%s">Click here</a> to add more.',

    '_modzzz_investment_admin_delete' => 'Delete',
    '_modzzz_investment_admin_activate' => 'Activate',
    '_modzzz_investment_admin_add_new_investment' => 'Add New Investment',
    '_modzzz_investment_admin_investment' => 'Admin Investment',
    '_modzzz_investment_admin_settings' => 'Admin Settings',

    '_modzzz_investment_form_header_info' => 'Information concernant votre projet / investissement',
    '_modzzz_investment_form_header_images' => 'Photos',
    '_modzzz_investment_form_header_videos' => 'Vidéos',
    '_modzzz_investment_form_header_sounds' => 'Sounds',
    '_modzzz_investment_form_header_files' => 'Documents',
    '_modzzz_investment_form_header_privacy' => 'Paramètres de confidentialité',
    '_modzzz_investment_form_caption_title' => 'Titre de votre projet',
    '_modzzz_investment_form_err_title' => 'Veuillez entrer de 3 à 100 caractères',
    '_modzzz_investment_form_caption_desc' => 'Description',
    '_modzzz_investment_form_err_desc' => 'Veuillez entrer au mons 20 caractères',
    '_modzzz_investment_form_err_tags' => 'Please enter tags',
    '_modzzz_investment_form_caption_author_id' => 'Author',
    '_modzzz_investment_form_info_author' => 'Author profile ID number',
    '_modzzz_investment_form_caption_keyword' => 'Mot clé',
    '_modzzz_investment_form_err_keyword' => 'Veuillez entrer de 3 à 100 caractères',
    '_modzzz_investment_form_caption_category' => 'Catégorie',
    '_modzzz_investment_form_err_category' => 'Séléctionner une catégorie',    
    '_modzzz_investment_form_caption_images_choice' => 'Choisir',
    '_modzzz_investment_form_info_images_choice' => 'You can choose several images from your "Investment" category',
    '_modzzz_investment_form_caption_images_upload' => 'Télécharger une photo',    
    '_modzzz_investment_form_info_images_upload' => 'Image will be placed in the "Investment" category automatically',
    '_modzzz_investment_form_caption_videos_choice' => 'Choose',
    '_modzzz_investment_form_info_videos_choice' => 'You can choose several videos from your "Investment" category',
    '_modzzz_investment_form_caption_videos_upload' => 'Upload',
    '_modzzz_investment_form_info_videos_upload' => 'Video will be placed in the "Investment" category automatically',
    '_modzzz_investment_form_caption_sounds_choice' => 'Choose',
    '_modzzz_investment_form_info_sounds_choice' => 'You can choose several sounds from your "Investment" category',
    '_modzzz_investment_form_caption_sounds_upload' => 'Upload',
    '_modzzz_investment_form_info_sounds_upload' => 'Sound will be placed in the "Investment" category automatically',
    '_modzzz_investment_form_caption_files_choice' => 'Choisir',
    '_modzzz_investment_form_info_files_choice' => 'Décochez la case pour supprimer le document de cette annonnce',
    '_modzzz_investment_form_caption_files_upload' => 'Télécharger un document',
    '_modzzz_investment_form_info_files_upload' => 'Document will be placed in the "Investment" category and set as private automatically',
    '_modzzz_investment_form_caption_file_title' => 'Titre:',
    '_modzzz_investment_form_caption_file_price' => 'Price:',
    '_modzzz_investment_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_investment_form_caption_thumb_choice' => 'Choisir une vignette',
    '_modzzz_investment_form_info_thumb_choice' => 'You can choose any image from your "Investment" category as investment thumbnail',
    '_modzzz_investment_form_caption_country' => 'Pays',
    '_modzzz_investment_form_err_country' => 'Veuillez sélectionner un pays',
    '_modzzz_investment_form_caption_city' => 'Ville',
    '_modzzz_investment_form_err_city' => 'Veuillez entrer 2 à 50 caractères',
    '_modzzz_investment_form_caption_zip' => 'Code Postal /Zip',
    '_modzzz_investment_form_err_zip' => 'Le code postal est obligatoire',
    '_modzzz_investment_form_err_email' => 'Vous avez saisi un email incorrect',

    '_modzzz_investment_action_title_edit' => 'Modifier',
    '_modzzz_investment_action_title_delete' => 'Supprimer',
    '_modzzz_investment_action_title_share' => 'Partager',
    '_modzzz_investment_action_add_to_featured' => 'Feature',    
    '_modzzz_investment_action_remove_from_featured' => 'Unfeature',
    '_modzzz_investment_action_add_investment' => 'Soumettre un projet',
    '_modzzz_investment_action_my_investment' => 'Mes Projets',
    '_modzzz_investment_action_upload_photos' => 'Ajouter des photos',
    '_modzzz_investment_action_upload_videos' => 'Ajouter des vidéos',
    '_modzzz_investment_action_upload_sounds' => 'Add Sounds',
    '_modzzz_investment_action_upload_files' => 'Ajouter des documents',
    '_modzzz_investment_action_investment_home' => 'Accueil',

    '_modzzz_investment_action_title_claim' => 'Claim Investment',
    '_modzzz_investment_action_title_inquire' => 'Se renseigner', 
    '_modzzz_investment_action_title_spread' => 'Spread This', 
    '_modzzz_investment_action_title_promote' => 'Inviter', 
    '_modzzz_investment_invitation_sent' => '%d invitations ont été envoyées',
	'_modzzz_investment_no_users_msg' => 'Il n\'y a aucun membre dans vos contacts',
	'_modzzz_investment_caption_invite' => 'Envoyer une invitation à mes contacts - ',

    '_modzzz_investment_inquiry_subject' => 'Sujet de votre demande', 
    '_modzzz_investment_inquiry_subject_info' => 'Entrez le sujet de votre demande', 
    '_modzzz_investment_inquiry_text' => 'Message', 
    '_modzzz_investment_inquiry_text_info' => 'Entrez votre demande ici. Elle sera transmise au propriétaire de cette annonce',  
	'_modzzz_investment_caption_make_inquiry' => 'Se renseigner - ',
    '_modzzz_investment_inquiry_sent' => 'Votre demande a pas été envoyée',
    '_modzzz_investment_inquiry_not_sent' => 'Votre demande n\'a pas été envoyée',
   
    '_modzzz_investment_claim_subject' => 'Subject', 
    '_modzzz_investment_claim_subject_info' => 'Enter the Subject of your claim', 
    '_modzzz_investment_claim_text' => 'Message', 
    '_modzzz_investment_claim_text_info' => 'Enter your proof of claim here. It will be forwarded to the Administrators',  
	'_modzzz_investment_caption_make_claim' => 'Make Claim - ',
    '_modzzz_investment_claim_sent' => 'your claim request has been sent',
    '_modzzz_investment_claim_not_sent' => 'your claim request has not been sent',
	 
	'_modzzz_investment_user_unknown' => 'Unknown', 
    '_modzzz_investment_price' => 'Price',

	'_modzzz_investment_contact' => 'Coordonnées', 
	'_modzzz_investment_block_contact' => 'Coordonnées', 
	'_modzzz_investment_location' => 'Lieu',
	'_modzzz_investment_block_location' => 'Lieu',
	'_modzzz_investment_block_map_view' => 'Map View', 
	'_modzzz_investment_map' => 'Google Map', 
	'_modzzz_investment_form_caption_sellerfax' => 'Fax',
	'_modzzz_investment_form_caption_sellertelephone' => 'Téléphone',
	'_modzzz_investment_form_caption_selleremail' => 'Email',
	'_modzzz_investment_form_caption_sellerwebsite' => 'Website',
	'_modzzz_investment_form_caption_sellername' => 'Nom',
	'_modzzz_investment_form_caption_address1' => 'Adresse 1',
	'_modzzz_investment_form_caption_address2' => 'Adresse 2', 
	'_modzzz_investment_form_err_investmentoption' => 'Veuillez sélectionner une option', 
	'_modzzz_investment_form_err_investmenttype' => 'Veuillez sélectionner un type',
    '_modzzz_investment_form_err_city' => 'Veuillez entrer de 3 à 150 caractères',
  
    '_modzzz_investment_privacy_view_investment' => 'Qui peut voir cette annonce',
    '_modzzz_investment_privacy_comment' => 'Qui peut commenter cette annonce',
    '_modzzz_investment_privacy_rate' => 'Qui peut noter cette annonce',
    '_modzzz_investment_privacy_upload_photos' => 'Qui peut télécharger des photos',
    '_modzzz_investment_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_investment_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_investment_privacy_upload_files' => 'Qui peut télécharger des documments',
    '_modzzz_investment_privacy_edit_investment' => 'Qui peut modifier cette annonce',
    '_modzzz_investment_privacy_admins_only' => 'Moi uniquement',
    '_modzzz_investment_anonymous_note' => 'your name will not appear as the poster', 
    '_mma_investment_view_investment' => 'investment view investment', 
    '_mma_investment_browse' => 'investment browse', 
    '_mma_investment_search' => 'investment search', 
    '_mma_investment_add_investment' => 'investment add investment', 
    '_mma_investment_comments_delete_and_edit' => 'investment comments delete and edit', 
    '_mma_investment_edit_any_investment' => 'investment edit any investment', 
    '_mma_investment_delete_any_investment' => 'investment delete any investment', 
    '_mma_investment_mark_as_featured' => 'investment mark as featured', 
    '_mma_investment_approve_investment' => 'investment approve investment',   
 
	'_modzzz_investment_action_title_premium' => 'Get Premium',  
    '_modzzz_investment_page_title_premium' => 'Get Premium Listing',   
	'_mma_investment_purchase' => 'investment purchase package', 

	'_modzzz_investment_action_title_extend' => 'Extend',  
	'_modzzz_investment_page_title_extend' => 'Extend Investment listing',   
	'_mma_investment_extend' => 'investment extend', 

	'_modzzz_investment_action_title_relist' => 'Re-soumettre',  
	'_modzzz_investment_page_title_relist' => 'Re-soumettre votre projet',  
	'_mma_investment_relist' => 'investment relist', 

    '_modzzz_investment_form_caption_current_no_package' => 'No Package currently',   
	'_modzzz_investment_form_caption_current_package' => 'Current Package',  
	'_modzzz_investment_form_caption_package_price' => 'Package Price',  
	'_modzzz_investment_form_caption_package_days' => 'Length of Listing',   
	'_modzzz_investment_expires_never' => 'unlimited (never expires)', 
	'_modzzz_investment_days' => 'days', 
	'_modzzz_investment_form_caption_current_item' => 'Investment', 
	'_modzzz_investment_extend' => 'Extend' ,
	 
    '_modzzz_investment_form_header_location' => 'Lieu',  
    '_modzzz_investment_form_header_contact' => 'Coordonnées professionnelles',  
    '_modzzz_investment_block_share' => 'Partager', 
    '_modzzz_investment_block_facebook_comments' => 'Commentaires Facebook ', 
 
    '_modzzz_investment_enter_your_investment' => 'Soumettre votre projet',
    '_modzzz_investment_block_investment_create' => 'Vous cherchez un financement ou une opportunité?', 
    '_modzzz_investment_block_latest_comments' => 'Derniers commentaires',
    '_modzzz_investment_block_forum' => 'Latest Forum Posts',
    '_modzzz_investment_posted_by' => 'Posté par',
    '_modzzz_investment_posted_in' => 'Dans', 
 
	'_modzzz_investment_allow_num_listings' => 'Number of Listings allowed', 	
	'_modzzz_investment_allow_videos' => 'Allow Videos', 	
	'_modzzz_investment_allow_photos' => 'Allow Photos', 	
	'_modzzz_investment_allow_sounds' => 'Allow Sounds', 	
	'_modzzz_investment_allow_files' => 'Allow Documents', 	
 	'_modzzz_investment_featured' => 'Featured Listing',  
 	
	'_modzzz_investment_package_desc' => 'Package Description',  
    '_modzzz_investment_block_submenu_expired_investment' => 'Expired',
    '_modzzz_investment_page_title_expired' => 'Expired Listings', 
 	'_modzzz_investment_expires' => 'Expires', 	 
 	'_modzzz_investment_never' => 'Never',  
 	'_modzzz_investment_featured_listing' => 'Featured Listing (never expires)',  
 
	'_modzzz_investment_block_browse_categories_drilldown' => 'Categories Drilldown', 
	'_modzzz_investment_category_drilldown_for_item' => 'Categories Drilldown for <b>{0}</b>', 
 
 	'_modzzz_investment_paypal_item_desc' => 'Payment for Investment listing - {0}',  
 	'_modzzz_investment_paypal_featured_item_desc' => 'Purchase Featured Status - {0}',  
 	'_modzzz_investment_menu_admin_promo_details' => 'Promo Details',  

 	'_modzzz_investment_form_modify_promotion_details' => 'Modify Promo Details',  
 	'_modzzz_investment_form_caption_details' => 'Promo Text',  
 	'_modzzz_investment_form_err_details' => 'You must enter Promo Text',  
 
 	'_modzzz_investment_investor' => 'Investisseur',  
 	'_modzzz_investment_entrepreneur' => 'Entrepreneur',  
 	'_modzzz_investment_professional' => 'Professionnel',  

 	'_modzzz_investment_form_caption_investment_type' => 'Qui êtes-vous?',  
  	'_modzzz_investment_form_header_location' => 'Lieu',  

 	'_modzzz_investment_why_invest' => 'Pourquoi voulez-vous investir',  
 	'_modzzz_investment_why_seek_invest' => 'Pourquoi recherchez-vous des fonds?',  
 	'_modzzz_investment_why_seek_professional' => 'Pourquoi recherchez-vous un service professionnel?',  

 	'_modzzz_investment_form_caption_min_investment' => 'Investissement Minimum ',  
  	'_modzzz_investment_form_caption_max_investment' => 'Investissement Maximum ',  

  	'_modzzz_investment_minimum' => 'Minimum',  
  	'_modzzz_investment_maximum' => 'Maximum',  
  	'_modzzz_investment_capital' => 'Capital',  
  	'_modzzz_investment_block_capital' => 'Capital',  
  	'_modzzz_investment_form_err_max_investment' => 'Vous devez entrer le montant d\'investissement maximum',  
  	'_modzzz_investment_form_err_min_investment' => 'Vous devez entrer le montant d\'investissement minimum',  
  	'_modzzz_investment_all' => 'Tout',  
 
	/*added 7.1 */
    '_modzzz_investment_wall_added_new_comment' => 'a commenté sur un',
    '_modzzz_investment_wall_added_new_items' => 'a ajouté {0} Projet(s) / Investissement(s) ',
	'_modzzz_investment_single' => 'Projet | Investissement',
    '_modzzz_investment_posted_in_topic' => 'Posted in Forum',
    '_modzzz_investment_posted_in_investment' => 'Posted in Investment Listing',
  
	'_modzzz_investment_admin_cancel' => 'Annuler',
	'_modzzz_investment_block_calendar' => 'Calendrier',
    '_modzzz_investment_adm_stats' => 'Pending Investments',
 	'_modzzz_investment_remove' => 'Supprimer', 
  	'_modzzz_investment_block_inquiries' => 'Se renseigner', 
  	'_sys_module_investment' => 'Investments', 
	
	 '_mma_investment_mark_as_favorite' => 'investment mark as favorite', 
	  '_modzzz_investment_menu_favorite' => 'Projets sauvegardés',
    '_modzzz_investment_msg_removed_from_favorite' => 'Projet supprimé de mes favoris',
    '_modzzz_investment_msg_added_to_favorite' => 'Projet sauvegardé',
    '_modzzz_investment_page_title_browse_favorite' => '<i class="sys-icon star"></i> Projets sauvegardés ',
    '_modzzz_investment_action_add_to_favorite' => 'Sauvegarder',    
    '_modzzz_investment_action_remove_from_favorite' => 'Not Favorite',


);