<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Article
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Articles';

$aLangContent = array(

    '_modzzz_articles_caption_browse_related' => 'Browse Related Articles',	  
    '_modzzz_articles_membership_filter_none' => 'Allow All',	 
    '_modzzz_articles_info_membership_filter' => 'only these members will be able to view this article',
     '_modzzz_articles_membership_filter_none' => 'Allow All',	
	'_modzzz_articles_caption_membership_filter' => 'Allow viewing by membership',
	'_modzzz_articles_err_membership_filter' => 'incorrect value',
    '_modzzz_articles_info_membership_filter' => 'only these members will be able to view this article',
    '_modzzz_articles_form_caption_publish_date' => 'Publish Date',
    '_modzzz_articles_form_caption_publish_now' => 'Publish Now',
    '_modzzz_articles_form_info_publish_now' => 'Yes - Article will be immediately Published.<br>No - Article will be published on Publish Date entered below',
 
    '_modzzz_articles_form_info_snippet' => 'Snippet length cannot be greater than {0}',
    '_modzzz_articles_form_caption_snippet' => 'Snippet',

    '_modzzz_articles_menu_admin_pending_publish' => 'Pending Publish',
    '_modzzz_articles_admin_publish' => 'Publish',
 
    '_modzzz_articles_calendar' => 'Calendar',
    '_modzzz_articles_enter_your_article_topic' => 'Enter your Topic',
    '_modzzz_articles_continue' => 'Continue',
    '_modzzz_articles_block_search' => 'Search Articles',
    '_modzzz_articles_block_article_create' => 'Post Article',
    '_modzzz_articles_block_calendar' => 'Calendar',
    '_modzzz_articles_block_archive' => 'Archive',
    '_modzzz_articles_block_comments' => 'Latest Comments',
    '_modzzz_articles_block_related' => 'Related Articles', 
    '_modzzz_articles_posted_by' => 'Posted by',
    '_modzzz_articles_posted_in' => 'In', 

    '_modzzz_articles_week_sun' => 'Sun',
    '_modzzz_articles_week_mon' => 'Mon',
    '_modzzz_articles_week_tue' => 'Tue',
    '_modzzz_articles_week_wed' => 'Wed',
    '_modzzz_articles_week_thu' => 'Thur', 
    '_modzzz_articles_week_fri' => 'Fri',
    '_modzzz_articles_week_sat' => 'Sat',

    '_sbs_txt_title_modzzz_articles' => 'Articles',
    '_modzzz_articles' => 'Articles',
    '_modzzz_articles_fans' => 'fans',
    '_modzzz_articles_add' => 'add',
    '_modzzz_articles_wall_added_new' => 'added new',
    '_modzzz_articles_wall_object' => 'article',
    '_modzzz_articles_for_article' => 'for %s',
    '_modzzz_articles_article_single' => 'article',
    '_modzzz_articles_article_plural' => 'articles',
    '_modzzz_articles_user_unknown' => 'Unknown',
    '_modzzz_articles_disabled' => 'disabled',
    '_modzzz_articles_enabled' => 'enabled',

    '_modzzz_articles_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new article <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_articles_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed article <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_articles_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated article <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_articles_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented article <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_articles_sbs_change' => 'information was updated',
    '_modzzz_articles_sbs_comment' => 'new comment arrived',
    '_modzzz_articles_sbs_rate' => 'rating was updated',
 
    '_modzzz_articles_tab_featured' => 'Featured',
    '_modzzz_articles_tab_recent' => 'Recent',
    '_modzzz_articles_tab_top' => 'Top',
    '_modzzz_articles_tab_popular' => 'Popular',

    '_modzzz_articles_block_submenu_main' => 'Main',
    '_modzzz_articles_block_submenu_add_article' => 'Add',
    '_modzzz_articles_block_submenu_manage_articles' => 'Manage',
    '_modzzz_articles_block_submenu_pending_articles' => 'Pending Approval',

    '_modzzz_articles_block_actions' => 'Actions',
    '_modzzz_articles_block_rate' => 'Rate',    
    '_modzzz_articles_block_info' => 'Info',
    '_modzzz_articles_block_desc' => 'Description',
    '_modzzz_articles_block_photo' => 'Photos',
    '_modzzz_articles_block_video' => 'Videos',
    '_modzzz_articles_block_sound' => 'Sounds',
    '_modzzz_articles_block_files' => 'Files',
    '_modzzz_articles_block_file' => 'Files',
    '_modzzz_articles_block_comments' => 'Comments',
    '_modzzz_articles_block_latest_featured_article' => 'Latest Featured Article',
    '_modzzz_articles_block_recent' => 'Recent Articles',
    '_modzzz_articles_block_popular' => 'Popular Articles',
    '_modzzz_articles_block_top' => 'Top Rated Articles',
    '_modzzz_articles_block_search' => 'Search Articles',
 
    '_modzzz_articles_block_administration_owner' => 'Administration',
    '_modzzz_articles_block_users_articles' => 'User\'s Articles',
    '_modzzz_articles_block_my_articles' => 'My Articles',
    '_modzzz_articles_block_homepage' => 'Public Articles',

    '_modzzz_articles_caption_add' => 'Add Article',
    '_modzzz_articles_caption_share_article' => 'Share Article',
    '_modzzz_articles_caption_admin_actions' => 'Links',
    '_modzzz_articles_caption_pending_approval' => 'Pending Approval Articles', 

    '_modzzz_articles_menu_root' => 'Articles',
    '_modzzz_articles_menu_main' => 'Articles Home',
    '_modzzz_articles_menu_recent' => 'Recent',
    '_modzzz_articles_menu_top_rated' => 'Top Rated',
    '_modzzz_articles_menu_popular' => 'Popular',
    '_modzzz_articles_menu_featured' => 'Featured',
    '_modzzz_articles_menu_tags' => 'Tags',
    '_modzzz_articles_menu_calendar' => 'Calendar',
    '_modzzz_articles_menu_search' => 'Search',
    '_modzzz_articles_menu_view_article' => 'Main',
    '_modzzz_articles_menu_view_comments' => 'Comments',
    '_modzzz_articles_menu_view_photos' => 'Photos',
    '_modzzz_articles_menu_view_videos' => 'Videos',
    '_modzzz_articles_menu_view_sounds' => 'Sounds',
    '_modzzz_articles_menu_view_files' => 'Files',
    '_modzzz_articles_menu_my_articles_profile' => 'Articles',

    '_modzzz_articles_menu_admin_pending_approval' => 'Pending Approval',
    '_modzzz_articles_menu_admin_entries' => 'Admin Articles',
    '_modzzz_articles_menu_admin_add_entry' => 'Add Article',
    '_modzzz_articles_menu_admin_settings' => 'Settings',
    
    '_modzzz_articles_page_title_home' => 'Articles Home',
    '_modzzz_articles_page_title_calendar' => 'Articles Calendar ',
    '_modzzz_articles_page_title_comments' => 'Comments',
    '_modzzz_articles_page_title_photos' => 'Photos',
    '_modzzz_articles_page_title_videos' => 'Videos',
    '_modzzz_articles_page_title_sounds' => 'Sounds',
    '_modzzz_articles_page_title_files' => 'Files',
    '_modzzz_articles_page_title_my_articles' => 'My Articles',
    '_modzzz_articles_page_title_search' => 'Articles Search',
    '_modzzz_articles_page_title_add' => 'Add Article', 
    '_modzzz_articles_page_title_edit' => 'Edit Article',
    '_modzzz_articles_page_title_administration' => 'Articles Administration',
    '_modzzz_articles_page_title_browse' => 'Browse Articles',
    '_modzzz_articles_page_title_pending_approval' => 'Pending Approval Articles',
    '_modzzz_articles_page_title_search_results' => 'Articles Search Results',
    '_modzzz_articles_page_title_browse_by_author' => '\'s articles',
    '_modzzz_articles_page_title_admin_articles' => 'Admin Articles',
    '_modzzz_articles_page_title_browse_by_tag' => 'Browse Articles By Tag: ',
    '_modzzz_articles_page_title_browse_recent' => 'Recent Articles',
    '_modzzz_articles_page_title_browse_top_rated' => 'Top Rated Articles',
    '_modzzz_articles_page_title_browse_popular' => 'Popular Articles',
    '_modzzz_articles_page_title_browse_featured' => 'Featured Articles',
    '_modzzz_articles_page_title_browse_by_day' => 'Browse Articles By Day: ',
    '_modzzz_articles_page_title_browse_by_period' => 'Browse Articles By Period: ',
    '_modzzz_articles_page_title_tags' => 'Articles Tags',
    '_modzzz_articles_page_title_upload_photos' => 'Add Photos',
    '_modzzz_articles_page_title_upload_videos' => 'Add Videos',
    '_modzzz_articles_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_articles_page_title_upload_files' => 'Add Files',

    '_modzzz_articles_msg_pending_approval' => 'this article is pending approval, please wait until it will be activated',
    '_modzzz_articles_msg_article_was_deleted' => 'Article was deleted',
    '_modzzz_articles_msg_removed_from_featured' => 'Article was removed from featured',
    '_modzzz_articles_msg_added_to_featured' => 'Article was added to featured',
    '_modzzz_articles_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_articles_msg_you_have_pending_approval_articles' => 'You have <a href="%s">%d pending approval articles</a>',
    '_modzzz_articles_msg_you_have_no_articles' => 'You don\'t have any articles. <a href="%s">Click here</a> to add one.',
    '_modzzz_articles_msg_you_have_some_articles' => 'You have <a href="%s">%d article(s)</a>. <a href="%s">Click here</a> to add more.',

    '_modzzz_articles_admin_delete' => 'Delete',
    '_modzzz_articles_admin_activate' => 'Activate',
    '_modzzz_articles_admin_add_new_article' => 'Add New Article',
    '_modzzz_articles_admin_articles' => 'Admin Articles',
    '_modzzz_articles_admin_settings' => 'Admin Settings',

    '_modzzz_articles_form_header_info' => 'Article\'s Info',
    '_modzzz_articles_form_header_images' => 'Article\'s Photos',
    '_modzzz_articles_form_header_videos' => 'Article\'s Videos',
    '_modzzz_articles_form_header_sounds' => 'Article\'s Sounds',
    '_modzzz_articles_form_header_files' => 'Article\'s Files',
    '_modzzz_articles_form_header_privacy' => 'Privacy Settings',
    '_modzzz_articles_form_caption_title' => 'Title',
    '_modzzz_articles_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_articles_form_caption_desc' => 'Description',
    '_modzzz_articles_form_err_desc' => 'Please enter at least 20 characters',
    '_modzzz_articles_form_err_tags' => 'Please enter tags',
    '_modzzz_articles_form_caption_author_id' => 'Author',
    '_modzzz_articles_form_info_author' => 'Author profile ID number',
    '_modzzz_articles_form_caption_keyword' => 'Keyword',
    '_modzzz_articles_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_modzzz_articles_form_caption_images_choice' => 'Choose',
    '_modzzz_articles_form_info_images_choice' => 'You can choose several images from your "Articles" category',
    '_modzzz_articles_form_caption_images_upload' => 'Upload',    
    '_modzzz_articles_form_info_images_upload' => 'Image will be placed in the "Articles" category automatically',
    '_modzzz_articles_form_caption_videos_choice' => 'Choose',
    '_modzzz_articles_form_info_videos_choice' => 'You can choose several videos from your "Articles" category',
    '_modzzz_articles_form_caption_videos_upload' => 'Upload',
    '_modzzz_articles_form_info_videos_upload' => 'Video will be placed in the "Articles" category automatically',
    '_modzzz_articles_form_caption_sounds_choice' => 'Choose',
    '_modzzz_articles_form_info_sounds_choice' => 'You can choose several sounds from your "Articles" category',
    '_modzzz_articles_form_caption_sounds_upload' => 'Upload',
    '_modzzz_articles_form_info_sounds_upload' => 'Sound will be placed in the "Articles" category automatically',
    '_modzzz_articles_form_caption_files_choice' => 'Choose',
    '_modzzz_articles_form_info_files_choice' => 'Unclick checkbox to remove file from this article',
    '_modzzz_articles_form_caption_files_upload' => 'Upload',
    '_modzzz_articles_form_info_files_upload' => 'File will be placed in the "Articles" category and set as private automatically',
    '_modzzz_articles_form_caption_file_title' => 'Title:',
    '_modzzz_articles_form_caption_file_price' => 'Price:',
    '_modzzz_articles_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_articles_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_articles_form_info_thumb_choice' => 'You can choose any image from your "Articles" category as article thumbnail',
    '_modzzz_articles_form_caption_country' => 'Country',
    '_modzzz_articles_form_err_country' => 'Country is a required field',
    '_modzzz_articles_form_caption_city' => 'City',
    '_modzzz_articles_form_err_city' => 'Please enter from 2 to 50 characters',
    '_modzzz_articles_form_caption_zip' => 'Zip/Postal Code',
    '_modzzz_articles_form_err_zip' => 'Zip/Postal code is required',
    '_modzzz_articles_form_caption_anonymous' => 'Anonymous',
    '_modzzz_articles_someone' => 'someone',

    '_modzzz_articles_action_title_edit' => 'Edit',
    '_modzzz_articles_action_title_delete' => 'Delete',
    '_modzzz_articles_action_title_share' => 'Share',
    '_modzzz_articles_action_add_to_featured' => 'Make Featured',    
    '_modzzz_articles_action_remove_from_featured' => 'Unfeature',
    '_modzzz_articles_action_add_article' => 'Add Article',
    '_modzzz_articles_action_my_articles' => 'My Articles',
    '_modzzz_articles_action_upload_photos' => 'Add Photos',
    '_modzzz_articles_action_upload_videos' => 'Add Videos',
    '_modzzz_articles_action_upload_sounds' => 'Add Sounds',
    '_modzzz_articles_action_upload_files' => 'Add Files',
    '_modzzz_articles_action_articles_home' => 'Home',

    '_modzzz_articles_privacy_view_article' => 'View Article',
    '_modzzz_articles_privacy_comment' => 'Comment',
    '_modzzz_articles_privacy_rate' => 'Rate',
    '_modzzz_articles_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_articles_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_articles_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_articles_privacy_upload_files' => 'Upload Files',
    '_modzzz_articles_privacy_edit_article' => 'Edit Article',
    '_modzzz_articles_privacy_admins_only' => 'Admins Only',
    '_modzzz_articles_anonymous_note' => 'your name will not appear as the poster', 
    '_mma_articles_view_article' => 'articles view article', 
    '_mma_articles_autoapprove_article' => 'articles autoapprove article',  
    '_mma_articles_browse' => 'articles browse', 
    '_mma_articles_search' => 'articles search', 
    '_mma_articles_add_article' => 'articles add article', 
    '_mma_articles_comments_delete_and_edit' => 'articles comments delete and edit', 
    '_mma_articles_edit_any_article' => 'articles edit any article', 
    '_mma_articles_delete_any_article' => 'articles delete any article', 
    '_mma_articles_mark_as_featured' => 'articles mark as featured', 
    '_mma_articles_approve_articles' => 'articles approve articles', 
 
  	'_modzzz_articles_block_submenu_draft_articles' => 'Pending Publishing',  
    '_modzzz_articles_page_title_browse_letter' => 'Browse Articles begining with the letter {0}',
 
	'_modzzz_articles_letter_a' => 'A',
	'_modzzz_articles_letter_b' => 'B',
	'_modzzz_articles_letter_c' => 'C',
	'_modzzz_articles_letter_d' => 'D',
	'_modzzz_articles_letter_e' => 'E',
	'_modzzz_articles_letter_f' => 'F',
	'_modzzz_articles_letter_g' => 'G',
	'_modzzz_articles_letter_h' => 'H',
	'_modzzz_articles_letter_i' => 'I',
	'_modzzz_articles_letter_j' => 'J',
	'_modzzz_articles_letter_k' => 'K',
	'_modzzz_articles_letter_l' => 'L',
	'_modzzz_articles_letter_m' => 'M',
	'_modzzz_articles_letter_n' => 'N',
	'_modzzz_articles_letter_o' => 'O',
	'_modzzz_articles_letter_p' => 'P',
	'_modzzz_articles_letter_q' => 'Q',
	'_modzzz_articles_letter_r' => 'R',
	'_modzzz_articles_letter_s' => 'S',
	'_modzzz_articles_letter_t' => 'T',
	'_modzzz_articles_letter_u' => 'U',
	'_modzzz_articles_letter_v' => 'V',
	'_modzzz_articles_letter_w' => 'W',
	'_modzzz_articles_letter_x' => 'X',
	'_modzzz_articles_letter_y' => 'Y',
	'_modzzz_articles_letter_z' => 'Z', 
 
	/*added 7.1 */
    '_modzzz_articles_wall_added_new_comment' => 'commented on a',
    '_modzzz_articles_wall_added_new_items' => 'added {0} new article(s)',
	'_modzzz_articles_single' => 'Article',
    '_modzzz_articles_posted_in_topic' => 'Posted in Forum',
    '_modzzz_articles_posted_in_article' => 'Posted for Article',
	'_modzzz_articles_browse_alphabetically' => 'Browse Alphabetically',
	'_modzzz_articles_go' => 'Go',
    '_modzzz_articles_adm_stats' => 'Pending Articles', 
	'_sys_module_articles' => 'Articles', 
	'_modzzz_articles_tags' => 'Tags',

    '_mma_articles_mark_as_favorite' => 'articles mark as favorite', 
    '_modzzz_articles_menu_favorite' => 'Favorites',
    '_modzzz_articles_msg_removed_from_favorite' => 'Article was removed from favorite',
    '_modzzz_articles_msg_added_to_favorite' => 'Article was added to favorite',
    '_modzzz_articles_page_title_browse_favorite' => 'Favorite Articles',
    '_modzzz_articles_action_add_to_favorite' => 'Favorite',    
    '_modzzz_articles_action_remove_from_favorite' => 'Not Favorite',
 
	'_modzzz_articles_tab_all' => 'All Time',
	'_modzzz_articles_tab_today' => 'Today',
	'_modzzz_articles_tab_week' => 'Week',
	'_modzzz_articles_tab_month' => 'Month',
	'_modzzz_articles_views' => 'Views',
	'_modzzz_articles_subscribers' => 'Subscribers',
 
    '_modzzz_articles_parent_categories' => 'Parent', 
    '_modzzz_articles_block_category_articles' => 'Articles in this Category',
    '_modzzz_articles_block_subcategories' => 'Sub-Categories',  
    '_modzzz_articles_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button', 
	'_modzzz_articles_categ_name' => 'Category',
	'_modzzz_articles_categ_btn_edit' => 'Edit',
	'_modzzz_articles_categ_btn_delete' => 'Delete',
	'_modzzz_articles_categ_btn_add' => 'Add',
	'_modzzz_articles_categ_btn_save' => 'Save',
	'_modzzz_articles_categ_btn_subcategories' => 'Sub-Categories', 
 	'_modzzz_articles_categories' => 'Categories',
 	'_modzzz_articles_menu_admin_manage_categories' => 'Categories',
  	'_modzzz_articles_menu_admin_manage_subcategories' => 'Sub-Cats',
  	'_modzzz_articles_subcategories' => 'Sub-Categories',
    '_modzzz_articles_all_categories' => 'All Categories',
    '_modzzz_articles_block_categories' => 'Categories',
    '_modzzz_articles_block_answer_categories' => 'Articles Categories',
    '_modzzz_articles_menu_categories' => 'Categories',
    '_modzzz_articles_page_title_browse_by_category' => 'Browse Articles By Category: ',
    '_modzzz_articles_form_caption_category' => 'Category',
    '_modzzz_articles_form_err_category' => 'Category is invalid', 
	'_modzzz_articles_page_title_category' => 'Category', 
    '_modzzz_articles_page_title_categories' => 'Articles Categories',
    '_modzzz_articles_page_title_subcategories' => 'Articles Sub-Categories', 
    '_modzzz_articles_articles_in_category' => '<b>Articles</b> in <b>%s</b>',    
	'_modzzz_articles_menu_manage_parents' => 'Parent Cats',
    '_modzzz_articles_menu_manage_categories' => 'Cats', 
    '_modzzz_articles_categ_name' => 'Name',
	'_modzzz_articles_form_caption_categories' => 'Categories',
	'_modzzz_articles_form_caption_subcategories' => 'Sub-Categories', 
    '_modzzz_articles_block_articles' => 'Articles',
    '_modzzz_articles_block_article_categories' => 'Categories',
 
    '_modzzz_articles_all_items_posted' => '<a href="{0}">All Articles</a> by {1}',
 
    '_modzzz_articles_form_header_location' => 'Location (optional)',
    '_modzzz_articles_form_caption_country' => 'Country',
    '_modzzz_articles_form_caption_state' => 'State',
    '_modzzz_articles_form_caption_city' => 'City',
    '_modzzz_articles_form_caption_address' => 'Address',
    '_modzzz_articles_form_caption_zip' => 'Zip/Postal Code',
	'_modzzz_articles_caption_browse_by_country' => 'Browse by Country',
  
	'_modzzz_articles_form_caption_youtube_link' => 'Video URL', 
	'_modzzz_articles_form_caption_youtube_caption' => 'Video Title',  
	'_modzzz_articles_form_header_youtube' => 'Youtube Videos',
	'_modzzz_articles_form_caption_youtube_attach' => 'Video',
	'_modzzz_articles_form_info_youtube_attach' => 'you can add multiple Youtube Videos',
	'_modzzz_articles_form_caption_youtube_choice' => 'Existing Videos',  
	'_modzzz_articles_form_info_youtube_choice' => 'Uncheck Videos that you want to remove',  
    '_modzzz_articles_page_title_embed_video' => 'Embed Video',
    '_modzzz_articles_action_embed_video' => 'Embed Video',
    '_mma_articles_allow_embed' => 'articles allow video embed',  
    '_modzzz_articles_block_video_embed' => 'External Video',
	'_modzzz_articles_form_header_video_embed' => 'Video Embed',
   	'_modzzz_articles_form_caption_video_embed_code' => 'Embed Code',
   	'_modzzz_articles_form_info_video_embed_code' => 'Enter either the URL or Embed Code for Youtube Video. Enter the Embed Code for other video sharing site (eg &lt;embed&gt;....&lt;/embed&gt;)',

 
    '_modzzz_articles_anonymous' => 'A guest',

    '_wall_reposted_modzzz_articles_add' => 'reposted an article',
    '_wall_reposted_title_modzzz_articles_add' => '{0} reposted an article',
    '_wall_reposted_modzzz_articles_comment_add' => 'reposted an article comment',
    '_wall_reposted_title_modzzz_articles_comment_add' => '{0} reposted an article comment',

    '_modzzz_articles_wall_added_new_title' => '{0} added new {1}',
    '_modzzz_articles_wall_added_new_title_items' => '{0} added {1} new articles',
    '_modzzz_articles_wall_added_new_title_comment' => '{0} commented on a {1}',
 
    '_modzzz_articles_form_header_background' => 'Background', 
    '_modzzz_articles_present_background' => 'Present Background', 
    '_modzzz_articles_form_caption_background' => 'Background', 
    '_modzzz_articles_form_caption_website' => 'Website Link', 
    '_modzzz_articles_block_website' => 'Website Link', 
    '_modzzz_articles_visit_website' => 'Visit Website', 
    '_modzzz_articles_remove' => 'Remove', 

 

);