<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Classified
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Classified';

$aLangContent = array(

    '_modzzz_classified_packages_empty' => 'There are no Classifieds Packages', 
    '_modzzz_classified_package_description' => 'Description', 
    '_modzzz_classified_package_featured' => 'Featured', 
    '_modzzz_classified_form_caption_quantity' => 'Quantity', 
    '_modzzz_classified_form_caption_currency' => 'Currency', 
  
    '_modzzz_classified_featured_status' => 'Featured Status', 
    '_modzzz_classified_featured_until' => 'Featured until', 
    '_modzzz_classified_not_featured' => 'Not Featured', 
 	'_modzzz_classified_extend_featured' => 'Extend Featured Status',  
 
    '_modzzz_classified_page_title_sale_pending' => 'Sale Pending', 
    '_modzzz_classified_page_title_sold' => 'Sold', 
    '_modzzz_classified_admin_cancel_sale' => 'Cancel Sale', 
    '_modzzz_classified_admin_mark_complete' => 'Sale Completed', 
    '_modzzz_classified_offered_by' => 'Offered made by', 

    '_modzzz_classified_form_caption_classified_item' => 'Classified Item', 
    '_modzzz_classified_message_sent' => 'Message has been sent to the Seller. <a href="{0}">Go back to listing</a>', 
    '_modzzz_classified_message_not_sent' => 'Failed to send message, <a href="{0}">please try again</a>', 

    '_modzzz_classified_form_buy_message' => 'If you are interested in purchasing this item, send details of your interest to the seller so they can make arrangements with you to complete the transaction.', 
 

    '_modzzz_classified_block_submenu_salepending_classified' => 'Sale Pending', 
    '_modzzz_classified_block_submenu_sold_classified' => 'Sold', 
 

    '_modzzz_classified_form_header_additional_info' => 'Additional Information', 
    '_modzzz_classified_block_additional' => 'Additional Details', 

    '_modzzz_classified_menu_packages' => 'Packages', 
    '_modzzz_classified_page_title_packages' => 'Classifieds Packages', 
    '_modzzz_classified_block_packages' => 'Classifieds Packages', 
 
    '_modzzz_classified_categ_type' => 'Category Type', 
    '_modzzz_classified_why' => 'Why?', 
    '_modzzz_classified_form_header_location' => 'Location', 
    '_modzzz_classified_form_header_contact_details' => 'Contact Details', 
	'_modzzz_classified_form_header_price_details' => 'Pricing Details (If item is being sold, rented etc.)', 

    '_modzzz_classified_category_rent' => 'Rent', 
    '_modzzz_classified_category_sale' => 'Sale', 
    '_modzzz_classified_category_other' => 'Other', 
    '_modzzz_classified_for' => 'for', 

    '_modzzz_classified_type_wanted' => 'Wanted',  
    '_modzzz_classified_type_rent' => 'For Rent', 
    '_modzzz_classified_type_sale' => 'For Sale', 
    '_modzzz_classified_type_free' => 'Free', 
    '_modzzz_classified_type_hiring' => 'Hiring', 
    '_modzzz_classified_type_seeking' => 'Seeking', 
    '_modzzz_classified_form_caption_type_of_classified' => 'Type of Classified', 
    '_modzzz_classified_form_err_type_of_classified' => 'Please select Type of Classified',  
    '_modzzz_classified_form_caption_price' => 'Price', 
    '_modzzz_classified_form_err_price' => 'Please enter a valid Price',   
    '_modzzz_classified_form_caption_saleprice' => 'Sale Price', 
    '_modzzz_classified_form_err_saleprice' => 'Please enter a valid Sale Price',   

    '_modzzz_classified_form_caption_why' => 'Why?', 
    '_modzzz_classified_form_caption_why_wanted' => 'Why do you need it?', 
    '_modzzz_classified_form_caption_why_rent' => 'Why are you renting it out?', 
    '_modzzz_classified_form_caption_why_rent_wanted' => 'Why do you need a place to live?', 
	'_modzzz_classified_form_caption_why_sell' => 'Why are you selling it?', 
    '_modzzz_classified_form_caption_why_free' => 'Why are you giving it away?', 
    '_modzzz_classified_form_caption_why_hiring' => 'Why do you need to fill this position?', 
    '_modzzz_classified_form_caption_why_seeking' => 'Why are you seeking this?',  

    '_modzzz_classified_custom_field1' => 'Custom Field 1', 
    '_modzzz_classified_custom_field2' => 'Custom Field 2', 
    '_modzzz_classified_custom_field3' => 'Custom Field 3', 
    '_modzzz_classified_custom_field4' => 'Custom Field 4', 
    '_modzzz_classified_custom_field5' => 'Custom Field 5', 
    '_modzzz_classified_custom_field6' => 'Custom Field 6', 
    '_modzzz_classified_custom_field7' => 'Custom Field 7', 
    '_modzzz_classified_custom_field8' => 'Custom Field 8', 
    '_modzzz_classified_custom_field9' => 'Custom Field 9', 
    '_modzzz_classified_custom_field10' => 'Custom Field 10', 

    '_modzzz_classified_parent_category_name' => 'Parent Category', 
    '_modzzz_classified_category_name' => 'Sub-Category', 
 
    '_modzzz_classified_menu_view_forum' => 'Forum', 
    '_modzzz_classified_privacy_post_in_forum' => 'Post In Forum',
 
 
	'_modzzz_classified_caption_membership_view_filter' => 'Allow viewing by membership',
	'_modzzz_classified_err_membership_view_filter' => 'incorrect value', 
    '_modzzz_classified_info_membership_view_filter' => 'only these members will be able to view this classified',
    '_modzzz_classified_membership_filter_none' => 'Allow All',	

    '_mma_classified_files_add' => 'classified files add',  
    '_mma_classified_photos_add' => 'classified photos add',  
    '_mma_classified_videos_add' => 'classified videos add',  
    '_mma_classified_sounds_add' => 'classified sounds add',  

    '_modzzz_classified_continue' => 'Continue',  
    '_modzzz_classified_on' => 'on',  
    '_modzzz_classified_yes' => 'yes',  
    '_modzzz_classified_no' => 'no',  
 
	'_modzzz_classified_package_videos' => 'Videos',  	
	'_modzzz_classified_package_photos' => 'Photos',  	
	'_modzzz_classified_package_sounds' => 'Sounds',  	
	'_modzzz_classified_package_files' => 'Files', 

	'_modzzz_classified_block_classified_states' => 'States', 
 
    '_mma_classified_purchase_featured' => 'classified purchase featured', 
    '_mma_classified_make_claim' => 'classified make claim', 
    '_mma_classified_make_inquiry' => 'classified make inquiry',  
    '_mma_classified_buy_item' => 'classified buy item',  
   
    '_modzzz_classified_regions_for_country' => 'States/Regions for',  
	'_modzzz_classified_block_browse_state' => 'Browse States', 
	'_modzzz_classified_block_browse_state_classifieds' => 'Browse Classifieds by State', 
	'_modzzz_classified_block_account' => 'Classifieds in my Area',  
	'_modzzz_classified_block_browse_country' => 'Browse Classifieds by Country', 
	'_modzzz_classified_page_title_local' => 'Browse Local Classifieds',  
	'_modzzz_classified_caption_browse_local' => 'Browse Local Classifieds in {0}', 
	'_modzzz_classified_menu_local' => 'Local', 
 	'_modzzz_classified_block_local' => 'More Local Classifieds',
	'_modzzz_classified_block_other' => 'Other Classifieds by this member',
 	'_modzzz_classified_caption_browse_other' => 'Other Classifieds by {0}', 
	'_modzzz_classified_caption_state' => 'State',  
 	'_modzzz_classified_caption_search' => 'Search Classifieds',
 


	'_modzzz_classified_action_title_purchase_featured' => 'Get Featured',
	'_modzzz_classified_action_title_extend_featured' => 'Extend Featured',  
	'_modzzz_classified_purchase_featured' => 'Purchase Featured Status', 
	'_modzzz_classified_purchase_featured_status' => 'Purchase Featured Status', 
	'_modzzz_classified_quantity' => 'Quantity',   
	'_modzzz_classified_featured_purchase_success' => 'You successfully Purchased {0} Days of Featured Status', 
	'_modzzz_classified_featured_purchase_fail' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_classified_featured_purchase_failed' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_classified_transaction_completed_already' => 'This transaction was already completed',  
	'_modzzz_classified_featured_cost_per_day' => 'Cost per Day',  
	'_modzzz_classified_caption_num_featured_days' => 'Number of Featured Days',    
	'_modzzz_classified_caption_err_featured_days' => 'You must enter Number of Featured Days',    
	'_modzzz_classified_get_featured' => 'Get Featured',   
    '_modzzz_classified_block_category_classified' => 'Classifieds in this Category',
    '_modzzz_classified_block_subcategories' => 'Sub-Categories',  
    '_modzzz_classified_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button', 
	'_modzzz_classified_categ_name' => 'Category',
	'_modzzz_classified_categ_btn_edit' => 'Edit',
	'_modzzz_classified_categ_btn_delete' => 'Delete',
	'_modzzz_classified_categ_btn_add' => 'Add',
	'_modzzz_classified_categ_btn_save' => 'Save',
	'_modzzz_classified_categ_btn_subcategories' => 'Sub-Categories', 
 	'_modzzz_classified_categories' => 'Categories',
 	'_modzzz_classified_menu_admin_manage_categories' => 'Categories',
  	'_modzzz_classified_menu_admin_manage_subcategories' => 'Sub-Cats',
  	'_modzzz_classified_subcategories' => 'Sub-Categories',
  	'_modzzz_classified_categories' => 'Categories',
    '_modzzz_classified_parent_categories' => 'Main Categories',
    '_modzzz_classified_all_categories' => 'All Categories',
    '_modzzz_classified_block_categories' => 'Categories',
    '_modzzz_classified_block_categories' => 'Categories',
    '_modzzz_classified_block_classified_subcategories' => 'Sub-Categories',
    '_modzzz_classified_block_answer_categories' => 'Classified Categories',
    '_modzzz_classified_menu_categories' => 'Categories',
    '_modzzz_classified_page_title_browse_by_category' => 'Browse Classifieds By Category: ',
    '_modzzz_classified_form_caption_category' => 'Category',
    '_modzzz_classified_form_err_category' => 'Category is invalid', 
	'_modzzz_classified_page_title_category' => 'Category', 
    '_modzzz_classified_page_title_categories' => 'Classifieds Categories',
    '_modzzz_classified_page_title_subcategories' => 'Classifieds Sub-Categories', 
    '_modzzz_classified_classifieds_in_category' => '<b>Classifieds</b> in <b>%s</b>',  
    '_modzzz_classified_block_classified' => 'Classifieds', 
	'_modzzz_classified_packages' => 'Packages',
	'_modzzz_classified_package_name' => 'Package Name',
	'_modzzz_classified_package_price' => 'Package Price',
	'_modzzz_classified_package_days' => 'Package Days',
	'_modzzz_classified_form_caption_package' => 'Available Packages',
	'_modzzz_classified_form_err_package' => 'Please select a Classifieds Package',  
	'_modzzz_classified_purchaser' => 'Purchaser', 
	'_modzzz_classified_invoice_no' => 'Invoice #', 
	'_modzzz_classified_package' => 'Package', 
	'_modzzz_classified_invoice_date' => 'Invoice Date', 
	'_modzzz_classified_invoice_due_date' => 'Due Date', 
	'_modzzz_classified_status' => 'Status',
	'_modzzz_classified_pending' => 'Pending',
	'_modzzz_classified_paid' => 'Paid',
	'_modzzz_classified_active' => 'Active',
	'_modzzz_classified_inactive' => 'Inactive',
	'_modzzz_classified_approved' => 'Approved',
	'_modzzz_classified_expired' => 'Expired', 
	'_modzzz_classified_block_submenu_pending_invoices' => 'Pending Invoices',
	'_modzzz_classified_block_submenu_orders' => 'Orders',
	'_modzzz_classified_page_title_orders' => 'Orders', 
	'_modzzz_classified_page_title_invoices' => 'Invoices', 
	'_modzzz_classified_menu_manage_invoices' => 'Invoices', 
	'_modzzz_classified_menu_manage_packages' => 'Packages',
	'_modzzz_classified_menu_manage_orders' => 'Orders',
	'_modzzz_classified_payment_method' => 'Payment Method',
	'_modzzz_classified_total' => 'Total',
	'_modzzz_classified_invoice_id' => 'Invoice ID',
	'_modzzz_classified_next_due_date' => 'Next Due Date',
	'_modzzz_classified_order_no' => 'Order #',
	 '_modzzz_classified_product_status' => 'Product Status',
	'_modzzz_classified_order_date' => 'Order Date',
	'_modzzz_classified_purchase_failed' => 'Sorry, there was a problem with the Payment.  View your Pending Orders <a href="{0}">here</a>.',
	'_modzzz_classified_transaction_completed_already' => 'The Transaction exists already. Click <a href="{0}">here</a> to view the Classified.',
	'_modzzz_classified_purchase_success' => 'Thank you. The Payment was successful. Click <a href="{0}">here</a> to view the Classified.',  
	'_modzzz_classified_trans_save_failed' => 'The Payment was successful but there was a Problem saving the transaction. Please contact the administrator with your Paypal transaction details so they can manually process your Order.',
	'_modzzz_classified_post_purchase_header' => 'Classified Purchase',  
  

    '_modzzz_classified_no_classifieds' => 'There are no Classifieds',
    '_sbs_txt_title_modzzz_classified' => 'Classified',
    '_modzzz_classified' => 'Classified',
    '_modzzz_classified_fans' => 'fans',
    '_modzzz_classified_add' => 'add',
    '_modzzz_classified_wall_added_new' => 'added new',
    '_modzzz_classified_wall_object' => 'classified',
    '_modzzz_classified_for_classified' => 'for %s',
    '_modzzz_classified_classified_single' => 'classified',
    '_modzzz_classified_classified_plural' => 'classifieds',
    '_modzzz_classified_user_unknown' => 'Someone',
    '_modzzz_classified_disabled' => 'disabled',
    '_modzzz_classified_enabled' => 'enabled',
    '_modzzz_classified_cannot_delete_default_parent' => 'Cannot Delete Default Parent Category',
	  
    '_modzzz_classified_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new classified <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_classified_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed classified <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_classified_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated classified <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_classified_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented classified <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_classified_sbs_change' => 'information was updated',
    '_modzzz_classified_sbs_comment' => 'new comment arrived',
    '_modzzz_classified_sbs_rate' => 'rating was updated',
 
    '_modzzz_classified_tab_featured' => 'Featured',
    '_modzzz_classified_tab_recent' => 'Recent',
    '_modzzz_classified_tab_top' => 'Top',
    '_modzzz_classified_tab_popular' => 'Popular',

    '_modzzz_classified_block_submenu_main' => 'Main',
    '_modzzz_classified_block_submenu_add_classified' => 'Add',
    '_modzzz_classified_block_submenu_manage_classified' => 'Manage',
    '_modzzz_classified_block_submenu_pending_classified' => 'Pending Approval',

    '_modzzz_classified_block_actions' => 'Actions',
    '_modzzz_classified_block_rate' => 'Rate',    
    '_modzzz_classified_block_info' => 'Info',
    '_modzzz_classified_block_desc' => 'Description',
    '_modzzz_classified_block_photo' => 'Photos',
    '_modzzz_classified_block_video' => 'Videos',
    '_modzzz_classified_block_sound' => 'Sounds',
    '_modzzz_classified_block_files' => 'Files',
    '_modzzz_classified_block_file' => 'Files',
    '_modzzz_classified_block_comments' => 'Comments',
    '_modzzz_classified_block_latest_featured_classified' => 'Latest Featured Classifieds',
    '_modzzz_classified_block_recent' => 'Recent Classifieds',
    '_modzzz_classified_block_popular' => 'Popular Classifieds',
    '_modzzz_classified_block_top' => 'Top Rated Classifieds',
    '_modzzz_classified_block_search' => 'Search Classifieds',
    '_modzzz_classified_block_classified_categories' => 'Categories',
    '_modzzz_classified_block_search' => 'Quick Search',

    '_modzzz_classified_block_administration_owner' => 'Administration',
    '_modzzz_classified_block_users_classified' => "User Classifieds",
    '_modzzz_classified_block_my_classified' => 'My Classified',
    '_modzzz_classified_block_my_classifieds' => 'My Classifieds',
    '_modzzz_classified_block_area_classifieds' => 'Classifieds in my Area',

    '_modzzz_classified_block_homepage' => 'Classifieds',

    '_modzzz_classified_caption_add' => 'Add Classified',
    '_modzzz_classified_caption_share_classified' => 'Share Classified',
    '_modzzz_classified_caption_admin_actions' => 'Links',
    '_modzzz_classified_caption_pending_approval' => 'Pending Approval Classifieds', 
    
	'_modzzz_classified_menu_manage_parents' => 'Parent Cats',
    '_modzzz_classified_menu_manage_categories' => 'Cats',
    '_modzzz_classified_categ_btn_save' => 'Save',
    '_modzzz_classified_categ_btn_edit' => 'Edit',
    '_modzzz_classified_categ_btn_delete' => 'Delete',
    '_modzzz_classified_categ_name' => 'Name',
    '_modzzz_classified_categ_icon' => 'Icon',
    '_modzzz_classified_categ_present_icon' => 'Present Icon',
    '_modzzz_classified_categ_btn_add' => 'Add',

    '_modzzz_classified_menu_root' => 'Classifieds',
    '_modzzz_classified_menu_main' => 'Classifieds Home',
    '_modzzz_classified_menu_recent' => 'Recent',
    '_modzzz_classified_menu_top_rated' => 'Top Rated',
    '_modzzz_classified_menu_popular' => 'Popular',
    '_modzzz_classified_menu_featured' => 'Featured',
    '_modzzz_classified_menu_tags' => 'Tags',
    '_modzzz_classified_menu_categories' => 'Categories',
    '_modzzz_classified_menu_calendar' => 'Calendar',
    '_modzzz_classified_menu_search' => 'Search',
    '_modzzz_classified_menu_view_classified' => 'Main',
    '_modzzz_classified_menu_view_comments' => 'Comments',
    '_modzzz_classified_menu_view_photos' => 'Photos',
    '_modzzz_classified_menu_view_videos' => 'Videos',
    '_modzzz_classified_menu_view_sounds' => 'Sounds',
    '_modzzz_classified_menu_view_files' => 'Files',
    '_modzzz_classified_menu_my_classified_profile' => 'Classifieds',

    '_modzzz_classified_menu_admin_pending_approval' => 'Pending',
    '_modzzz_classified_menu_admin_entries' => 'Admin Classifieds',
    '_modzzz_classified_menu_admin_add_entry' => 'Add',
    '_modzzz_classified_menu_admin_settings' => 'Settings',
    
    '_modzzz_classified_page_title_home' => 'Classified Home',
    '_modzzz_classified_page_title_calendar' => 'Classified Calendar',
    '_modzzz_classified_page_title_comments' => 'Comments',
    '_modzzz_classified_page_title_photos' => 'Photos',
    '_modzzz_classified_page_title_videos' => 'Videos',
    '_modzzz_classified_page_title_sounds' => 'Sounds',
    '_modzzz_classified_page_title_files' => 'Files',
    '_modzzz_classified_page_title_my_classified' => 'My Classifieds',
    '_modzzz_classified_page_title_search' => 'Search',
    '_modzzz_classified_page_title_add' => 'Add Classified', 
    '_modzzz_classified_page_title_edit' => 'Edit Classified',
    '_modzzz_classified_page_title_administration' => 'Classifieds Administration',
    '_modzzz_classified_admin_block_administration' => 'Admin.',
    '_modzzz_classified_page_title_browse' => 'Browse Classifieds',
    '_modzzz_classified_page_title_pending_approval' => 'Pending Approval Classifieds',
    '_modzzz_classified_page_title_search_results' => 'Classified Search Results',
    '_modzzz_classified_page_title_browse_by_author' => "\'s classifieds",
    '_modzzz_classified_page_title_admin_classified' => 'Admin Classifieds',
    '_modzzz_classified_page_title_browse_by_category' => 'Browse Classifieds By Category: ',
    '_modzzz_classified_page_title_browse_by_tag' => 'Browse Classifieds By Tag: ',
    '_modzzz_classified_page_title_browse_recent' => 'Recent Classifieds',
    '_modzzz_classified_page_title_browse_top_rated' => 'Top Rated Classifieds',
    '_modzzz_classified_page_title_browse_popular' => 'Popular Classifieds',
    '_modzzz_classified_page_title_browse_featured' => 'Featured Classifieds',
    '_modzzz_classified_page_title_browse_by_day' => 'Browse Classifieds By Day: ',
    '_modzzz_classified_page_title_tags' => 'Classifieds Tags',
    '_modzzz_classified_page_title_categories' => 'Classifieds Categories',
    '_modzzz_classified_page_title_upload_photos' => 'Add Photos',
    '_modzzz_classified_page_title_upload_videos' => 'Add Videos',
    '_modzzz_classified_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_classified_page_title_upload_files' => 'Add Files',

    '_modzzz_classified_msg_pending_approval' => 'this classified is pending approval, please wait until it will be activated',
    '_modzzz_classified_msg_classified_was_deleted' => 'Classified was deleted',
    '_modzzz_classified_msg_removed_from_featured' => 'Classified was removed from featured',
    '_modzzz_classified_msg_added_to_featured' => 'Classified was added to featured',
    '_modzzz_classified_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_classified_msg_you_have_pending_approval_classified' => 'You have <a href="%s">%d pending approval classifieds</a>',
    '_modzzz_classified_msg_you_have_no_classified' => 'You do not have any classifieds. <a href="%s">Click here</a> to add one.',
    '_modzzz_classified_msg_you_have_some_classified' => 'You have <a href="%s">%d classified(s)</a>. <a href="%s">Click here</a> to add more.',

    '_modzzz_classified_admin_delete' => 'Delete',
    '_modzzz_classified_admin_activate' => 'Activate',
    '_modzzz_classified_admin_add_new_classified' => 'Add New Classified',
    '_modzzz_classified_admin_classified' => 'Admin Classified',
    '_modzzz_classified_admin_settings' => 'Admin Settings',

    '_modzzz_classified_form_header_info' => 'Classified Info',
    '_modzzz_classified_form_header_images' => 'Classified Photos',
    '_modzzz_classified_form_header_videos' => 'Classified Videos',
    '_modzzz_classified_form_header_sounds' => 'Classified Sounds',
    '_modzzz_classified_form_header_files' => 'Classified Files',
    '_modzzz_classified_form_header_privacy' => 'Privacy Settings',
    '_modzzz_classified_form_caption_title' => 'Title',
    '_modzzz_classified_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_classified_form_caption_desc' => 'Description',
    '_modzzz_classified_form_err_desc' => 'Please enter at least 20 characters',
    '_modzzz_classified_form_err_tags' => 'Please enter tags',
    '_modzzz_classified_form_caption_author_id' => 'Author',
    '_modzzz_classified_form_info_author' => 'Author profile ID number',
    '_modzzz_classified_form_caption_keyword' => 'Keyword',
    '_modzzz_classified_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_modzzz_classified_form_caption_category' => 'Category',
    '_modzzz_classified_form_err_category' => 'Category is invalid',    
    '_modzzz_classified_form_caption_images_choice' => 'Choose',
    '_modzzz_classified_form_info_images_choice' => 'You can choose several images from your "Classified" category',
    '_modzzz_classified_form_caption_images_upload' => 'Upload',    
    '_modzzz_classified_form_info_images_upload' => 'Image will be placed in the "Classified" category automatically',
    '_modzzz_classified_form_caption_videos_choice' => 'Choose',
    '_modzzz_classified_form_info_videos_choice' => 'You can choose several videos from your "Classified" category',
    '_modzzz_classified_form_caption_videos_upload' => 'Upload',
    '_modzzz_classified_form_info_videos_upload' => 'Video will be placed in the "Classified" category automatically',
    '_modzzz_classified_form_caption_sounds_choice' => 'Choose',
    '_modzzz_classified_form_info_sounds_choice' => 'You can choose several sounds from your "Classified" category',
    '_modzzz_classified_form_caption_sounds_upload' => 'Upload',
    '_modzzz_classified_form_info_sounds_upload' => 'Sound will be placed in the "Classified" category automatically',
    '_modzzz_classified_form_caption_files_choice' => 'Choose',
    '_modzzz_classified_form_info_files_choice' => 'Unclick checkbox to remove file from this classified',
    '_modzzz_classified_form_caption_files_upload' => 'Upload',
    '_modzzz_classified_form_info_files_upload' => 'File will be placed in the "Classified" category and set as private automatically',
    '_modzzz_classified_form_caption_file_title' => 'Title:',
    '_modzzz_classified_form_caption_file_price' => 'Price:',
    '_modzzz_classified_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_classified_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_classified_form_info_thumb_choice' => 'You can choose any image from your "Classified" category as classified thumbnail',
    '_modzzz_classified_form_caption_country' => 'Country',
    '_modzzz_classified_form_err_country' => 'You must select a Country',
    '_modzzz_classified_form_caption_city' => 'City',
    '_modzzz_classified_form_err_city' => 'Please enter from 2 to 50 characters',
    '_modzzz_classified_form_caption_zip' => 'Zip/Postal Code',
    '_modzzz_classified_form_err_zip' => 'Zip/Postal code is required',
    '_modzzz_classified_form_err_email' => 'Invalid Email entered',

    '_modzzz_classified_action_title_edit' => 'Edit',
    '_modzzz_classified_action_title_delete' => 'Delete',
    '_modzzz_classified_action_title_share' => 'Share',
    '_modzzz_classified_action_add_to_featured' => 'Feature',    
    '_modzzz_classified_action_remove_from_featured' => 'Unfeature',
    '_modzzz_classified_action_add_classified' => 'Add Classified',
    '_modzzz_classified_action_my_classified' => 'My Classified',
    '_modzzz_classified_action_upload_photos' => 'Add Photos',
    '_modzzz_classified_action_upload_videos' => 'Add Videos',
    '_modzzz_classified_action_upload_sounds' => 'Add Sounds',
    '_modzzz_classified_action_upload_files' => 'Add Files',
    '_modzzz_classified_action_classified_home' => 'Home',

    '_modzzz_classified_action_title_claim' => 'Claim Classified',
    '_modzzz_classified_action_title_inquire' => 'Inquire About', 
    '_modzzz_classified_action_title_spread' => 'Spread This', 
    '_modzzz_classified_action_title_promote' => 'Promote', 
	'_modzzz_classified_no_users_msg' => 'There are no users in your contacts',

    '_modzzz_classified_inquiry_subject' => 'Subject', 
    '_modzzz_classified_inquiry_subject_info' => 'Enter the Subject of your inquiry', 
    '_modzzz_classified_inquiry_text' => 'Message', 
    '_modzzz_classified_inquiry_text_info' => 'Enter your inquiry here. It will be forwarded to the Classified Owner',  

   
    '_modzzz_classified_claim_subject' => 'Subject', 
    '_modzzz_classified_claim_subject_info' => 'Enter the Subject of your claim', 
    '_modzzz_classified_claim_text' => 'Message', 
    '_modzzz_classified_claim_text_info' => 'Enter your proof of claim here. It will be forwarded to the Administrators',  
	'_modzzz_classified_caption_make_claim' => 'Make Claim - ',
    '_modzzz_classified_claim_sent' => 'your claim request has been sent',
    '_modzzz_classified_claim_not_sent' => 'your claim request has not been sent',
	 
	'_modzzz_classified_user_unknown' => 'Unknown', 
    '_modzzz_classified_price' => 'Price',

	'_modzzz_classified_contact' => 'Seller Contact', 
	'_modzzz_classified_location' => 'Location',
	'_modzzz_classified_map' => 'Google Map', 
	'_modzzz_classified_form_caption_sellerfax' => 'Seller Fax',
	'_modzzz_classified_form_caption_sellertelephone' => 'Seller Telephone',
	'_modzzz_classified_form_caption_selleremail' => 'Seller Email',
	'_modzzz_classified_form_caption_sellerwebsite' => 'Seller Website',
	'_modzzz_classified_form_caption_sellername' => 'Seller Name',
	'_modzzz_classified_form_caption_address1' => 'Address 1',
	'_modzzz_classified_form_caption_address2' => 'Address 2', 
	'_modzzz_classified_form_err_classifiedoption' => 'Please select an Option', 
	'_modzzz_classified_form_err_classifiedtype' => 'Please select a Type',
    '_modzzz_classified_form_err_city' => 'Please enter from 3 to 150 characters',
  
    '_modzzz_classified_privacy_view_classified' => 'View Classified',
    '_modzzz_classified_privacy_comment' => 'Comment',
    '_modzzz_classified_privacy_rate' => 'Rate',
    '_modzzz_classified_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_classified_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_classified_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_classified_privacy_upload_files' => 'Upload Files',
    '_modzzz_classified_privacy_edit_classified' => 'Edit Classified',
    '_modzzz_classified_privacy_admins_only' => 'Admins Only',
    '_modzzz_classified_anonymous_note' => 'your name will not appear as the poster', 
    '_mma_classified_view_classified' => 'classified view classified', 
    '_mma_classified_browse' => 'classified browse', 
    '_mma_classified_search' => 'classified search', 
    '_mma_classified_add_classified' => 'classified add classified', 
    '_mma_classified_comments_delete_and_edit' => 'classified comments delete and edit', 
    '_mma_classified_edit_any_classified' => 'classified edit any classified', 
    '_mma_classified_delete_any_classified' => 'classified delete any classified', 
    '_mma_classified_mark_as_featured' => 'classified mark as featured', 
    '_mma_classified_approve_classified' => 'classified approve classified',   
 
	'_modzzz_classified_action_title_premium' => 'Get Premium',  
    '_modzzz_classified_page_title_premium' => 'Get Premium Listing',   
	'_mma_classified_purchase' => 'classified purchase package', 

	'_modzzz_classified_action_title_extend' => 'Extend',  
	'_modzzz_classified_page_title_extend' => 'Extend Classified listing',   
	'_mma_classified_extend' => 'classified extend', 

	'_modzzz_classified_action_title_relist' => 'Re-list',  
	'_modzzz_classified_page_title_relist' => 'Re-list Classified listing',  
	'_mma_classified_relist' => 'classified relist', 

    '_modzzz_classified_form_caption_current_no_package' => 'No Package currently',   
	'_modzzz_classified_form_caption_current_package' => 'Current Package',  
	'_modzzz_classified_form_caption_package_price' => 'Package Price',  
	'_modzzz_classified_form_caption_package_days' => 'Length of Listing',   
	'_modzzz_classified_expires_never' => 'unlimited (never expires)', 
	'_modzzz_classified_days' => 'days', 
	'_modzzz_classified_form_caption_current_item' => 'Classified', 
	'_modzzz_classified_extend' => 'Extend' ,
	 
    '_modzzz_classified_form_header_location' => 'Location',  
    '_modzzz_classified_form_header_contact' => 'Contact Details',  
    '_modzzz_classified_block_share' => 'Share', 
    
    '_modzzz_classified_enter_your_classified' => 'Enter your Listing',
    '_modzzz_classified_block_classified_create' => 'Post your Listing', 
    '_modzzz_classified_block_latest_comments' => 'Latest Comments',
    '_modzzz_classified_block_forum' => 'Latest Forum Posts',
    '_modzzz_classified_posted_by' => 'Posted by',
    '_modzzz_classified_posted_in' => 'In', 
 
	'_modzzz_classified_allow_num_listings' => 'Number of Listings allowed', 	
	'_modzzz_classified_allow_videos' => 'Allow Videos', 	
	'_modzzz_classified_allow_photos' => 'Allow Photos', 	
	'_modzzz_classified_allow_sounds' => 'Allow Sounds', 	
	'_modzzz_classified_allow_files' => 'Allow Files', 	
 	'_modzzz_classified_featured' => 'Featured Listing',  
 	
	'_modzzz_classified_package_desc' => 'Package Description',  
    '_modzzz_classified_block_submenu_expired_classified' => 'Expired',
    '_modzzz_classified_page_title_expired' => 'Expired Listings', 
 	'_modzzz_classified_expires' => 'Expires', 	 
 	'_modzzz_classified_never' => 'Never',  
 	'_modzzz_classified_featured_listing' => 'Featured Listing (never expires)',  
 
	'_modzzz_classified_block_browse_categories_drilldown' => 'Categories Drilldown', 
	'_modzzz_classified_category_drilldown_for_item' => 'Categories - {0}', 
 
 	'_modzzz_classified_paypal_item_desc' => 'Payment for Classified listing - {0}',  
 	'_modzzz_classified_paypal_featured_item_desc' => 'Purchase Featured Status - {0}',  
 	'_modzzz_classified_menu_admin_promo_details' => 'Promo Details',  

 	'_modzzz_classified_form_modify_promotion_details' => 'Modify Promo Details',  
 	'_modzzz_classified_form_caption_details' => 'Promo Text',  
 	'_modzzz_classified_form_err_details' => 'You must enter Promo Text',  
 
	/*added 7.1 */
    '_modzzz_classified_wall_added_new_comment' => 'commented on a',
    '_modzzz_classified_wall_added_new_items' => 'added {0} new classified item(s)',
	'_modzzz_classified_single' => 'Classified',
    '_modzzz_classified_posted_in_topic' => 'Posted in Forum',
    '_modzzz_classified_posted_in_classified' => 'Posted in Classified',
  
	'_modzzz_classified_admin_cancel' => 'Cancel',
	'_modzzz_classified_block_calendar' => 'Calendar',
    '_modzzz_classified_adm_stats' => 'Pending Classifieds',
 	'_sys_module_classified' => 'Classifieds', 
 	
	'_modzzz_classified_menu_expired_entries' => 'Expired', 
	'_modzzz_classified_page_title_expired_listings' => 'Expired Classifieds', 

 	'_modzzz_classified_form_caption_user_name' => 'Your Name', 
 	'_modzzz_classified_form_err_user_name' => 'Please enter your name', 
 
	'_modzzz_classified_form_caption_payment_type' => 'Payment Type', 

 	'_modzzz_classified_payment_per_week' => 'per week', 
 	'_modzzz_classified_payment_per_month' => 'per month', 
 	'_modzzz_classified_payment_per_year' => 'per year', 
 	'_modzzz_classified_payment_per_day' => 'per day', 
 	'_modzzz_classified_payment_per_session' => 'per session', 
 	'_modzzz_classified_payment_per_term' => 'per term',
 	'_modzzz_classified_featured_classified' => 'Featured Classified',
	
    '_modzzz_classified_browse_classified_in_country' => 'Listings in {0}',
	
 	'_modzzz_classified_form_caption_allow_view_contact' => 'Allowed to view Contact',  
 	'_modzzz_classified_all' => 'All', 
	
	/*[begin] - patch 2.1.6*/
 	'_modzzz_classified_block_map' => 'Map View', 
 	'_modzzz_classified_block_location' => 'Location', 
	/*[end] - patch 2.1.6*/

    '_modzzz_classified_form_err_inquiry' => 'You must enter inquiry info',
    '_modzzz_classified_inbox_inquiry_subject' => 'Message about your Classified Listing',
    '_modzzz_classified_inbox_inquiry_body' => 'Inquiry regarding your Classified Listing <a href="{0}">{1}</a>',

    '_modzzz_classified_action_title_buy' => 'Make Offer', 
    '_modzzz_classified_form_caption_offer_message' => 'Offer Details', 
    '_modzzz_classified_form_info_offer_message' => 'Enter your message with details of your purchase request',  
    '_modzzz_classified_form_err_buy_message' => 'You must enter a message',
    '_modzzz_classified_inbox_buy_subject' => 'Someone wants to buy your Classified Item',
    '_modzzz_classified_inbox_buy_body' => 'Offer for your Classified Listing <a href="{0}">{1}</a>',
    '_modzzz_classified_message_sent_header' => 'Message Sent', 
	'_modzzz_classified_caption_invite' => 'Send Invitation To Friends',
	'_modzzz_classified_caption_make_inquiry' => 'Make Inquiry',
    '_modzzz_classified_caption_make_buy_offer' => 'Make Offer', 
    '_modzzz_classified_invitation_sent' => '%d Invitations have been sent. <a href="{0}">Go back to listing</a>',
    '_modzzz_classified_inquiry_sent' => 'Your inquiry has been sent. <a href="{0}">Go back to listing</a>',
    '_modzzz_classified_inquiry_not_sent' => 'Your inquiry has not been sent. <a href="{0}">Go back to listing</a>',
    '_mma_classified_view_contacts' => 'classified allow view contact details',

	'_modzzz_classified_form_caption_name' => 'Your Name',
	'_modzzz_classified_form_err_name' => 'You must enter a name',
	'_modzzz_classified_form_caption_email' => 'Your Email',
	'_modzzz_classified_form_err_email' => 'You must enter an email',
  
    '_modzzz_classified_upgrade_membership' => 'Upgrade Membership to view',  
    '_modzzz_classified_upgrade_membership_url' => '<a href="{0}">Upgrade Membership</a> to view',  
 
   	'_modzzz_classified_block_video_embed' => 'Youtube Videos',
	'_modzzz_classified_form_caption_youtube_link' => 'Video URL', 
	'_modzzz_classified_form_caption_youtube_caption' => 'Video Title',  
	'_modzzz_classified_form_header_youtube' => 'Youtube Videos',
	'_modzzz_classified_form_caption_youtube_attach' => 'Video',
	'_modzzz_classified_form_info_youtube_attach' => 'you can add multiple Youtube Videos',
	'_modzzz_classified_form_caption_youtube_choice' => 'Existing Videos',  
	'_modzzz_classified_form_info_youtube_choice' => 'Uncheck Videos that you want to remove', 
    '_modzzz_classified_page_title_embed_video' => 'Embed Video',
    '_modzzz_classified_action_embed_video' => 'Embed Video',

    '_mma_classified_allow_embed' => 'classified allow embed',  
	'_modzzz_classified_form_caption_subcategories' => 'Sub-Categories',
    '_modzzz_classified_visitor' => 'Visitor',


);
