<?php
/***************************************************************************
* 
*     copyright            : (C) 2009 AQB Soft
*     website              : http://www.aqbsoft.com
*      
* IMPORTANT: This is a commercial product made by AQB Soft. It cannot be modified for other than personal usage.
* The "personal usage" means the product can be installed and set up for ONE domain name ONLY. 
* To be able to use this product for another domain names you have to order another copy of this product (license).
* 
* This product cannot be redistributed for free or a fee without written permission from AQB Soft.
* 
* This notice may not be removed from the source code.
* 
***************************************************************************/


$aLangContent = array(
	 '_aqb_aff_admin' => 'Forced Matrix System',
	 '_aqb_aff_admin_settings' => 'Settings',
	 '_aqb_aff_administration' => 'Forced Matrix System administration',
	 '_aqb_aff_nothing_found' => 'Sorry, nothing found',
	 '_aqb_aff_admin_membership_settings' => 'Membership Settings',
	 '_aqb_aff_admin_price_for_one_referral' => 'Price for one referral (<b>in your current currency</b>)',
	 '_aqb_aff_admin_points_for_one_referral' => 'Points for one referral (<b>in points</b>)',
	 '_aqb_aff_admin_reward_price_info' => 'You need to put any positive value here',
	 '_aqb_aff_admin_reward_points_info' => 'You need to put any positive <b>Integer</b> value here',
	 '_aqb_aff_points_upgraded_membership' => 'Number of points for each invited member who upgrades membership level',
	 '_aqb_aff_percent_upgraded_membership' => 'Percentage of a sum which was spent by referred member for membership upgrade',
	 '_aqb_aff_admin_percent_upgraded_info' => 'You need to put any <b>Integer</b> value here <b>%</b>',
	 '_aqb_aff_admin_affiliates_banners' => 'Affiliate/Banners',
	 '_aqb_aff_add_new_banner' => 'Upload new banner',
	 '_aqb_aff_upload' => 'Upload',
	 '_aqb_aff_uploaded_baners' => 'Existing banners',
	 '_aqb_aff_banner_name' => 'Banner name',
	 '_aqb_banner_image_size' => 'size',
	 '_aqb_aff_replace_new_banner' => 'Replace current image',
	 '_aqb_aff_admin_link' => 'Banner points to this page',
	 '_aqb_aff_impression_price' => 'Price per one impression',
	 '_aqb_aff_impression_points_price' => 'Points per one impression',
	 '_aqb_aff_click_price' => 'Price per one click',
	 '_aqb_aff_click_price_points' => 'Points per one click',
	 '_aqb_aff_join_price' => 'Price per one joined person',
	 '_aqb_aff_join_price_points' => 'Points per one joined person',
	 '_aqb_aff_admin_banner_id' => 'ID',
	 '_aqb_aff_admin_banner_name' => 'Name',
	 '_aqb_aff_admin_banner_size' => 'Size',
	 '_aqb_aff_admin_banner_link' => 'Link',
	 '_aqb_aff_admin_banner_date' => 'Date',
	 '_aqb_aff_admin_banner_active' => 'Active',
	 '_aqb_aff_admin_actions' => 'Actions',
	 '_aqb_aff_txt_history_clean' => 'remove all member\'s history',
	 '_aqb_aff_txt_commission_remove' => 'remove transaction',
     '_aqb_aff_admin_yes' => 'yes',
	 '_aqb_aff_admin_no' => 'no',
	 '_aqb_aff_admin_edit' => 'edit', 
	 '_aqb_aff_admin_view' => 'preview',
	 '_aqb_aff_banner_delete' => 'delete',
	 '_aqb_aff_banner_approve' => 'approve/disapprove',
	 '_aqb_aff_edit_banner' => 'Edit Banners',
	 '_aqb_aff_edit_parameters' => 'Parameters',
	 '_aqb_aff_save_button' => 'Save',
	 '_aqb_aff_edit_commission' => 'Commission (<b>in currency</b>)',
	 '_aqb_aff_edit_points' => 'Commission (<b>in points</b>)',
	 '_aqb_aff_banner_not_found' => 'Sorry, banner not found!',
	 '_aqb_aff_upload_error' => 'File upload error',
	 '_aqb_aff_changes_applied' => 'Changes were successfully applied!',
	 '_aqb_aff_changes_error' => 'Changes were not applied!',
	 '_aqb_aff_banner_preview' => 'Preview',
	 '_aqb_aff_code' => 'Banner\'s affiliate code',
	 '_aqb_aff_my_referrals' => 'My Referrals',
	 '_aqb_aff_link_message_title' => 'It is your referral link. You my use it for sending invitations to your friends. You will get referral\'s commission for each invited person on our site.',
	 '_aqb_aff_my_ref_in_matrix_title' => 'Members In matrix',
	 '_aqb_aff_my_ref_title' => 'Directly invited',
	 '_aqb_aff_my_invited_members_by_aff' => 'Members invited by affiliate banners',
	 '_aqb_aff_admin_melevel_seetings' => 'Settings for "{0}" level',
	 '_aqb_aff_successfully_saved' => 'Successfully Saved',
	 '_aqb_aff_my_cash_balance' => 'Unpaid commission',
	 '_aqb_aff_my_points_balance' => 'Untransferred points',
	 '_aqb_aff_referrals_upgraded' => 'Members who upgraded membership level',
	 '_aqb_aff_ref_title' => 'Affiliate\Referrals',
	 '_aqb_aff_my_referrals' => 'Referrals', 
	 '_aqb_aff_my_affilate' => 'Affilates', 
	 '_aqb_aff_my_history' => 'History',
	 '_aqb_aff_my_invitation' => 'Send invitation',
	 '_aqb_aff_my_referrals_info' => 'Information',
	 '_aqb_aff_my_referrals_my_ref' => 'My invited members by both(referral link and affiliate banners)',
	 '_aqb_aff_have_to_login' => 'You have to login first!',
	 '_aqb_aff_current_membership_level' => 'My current membership level',
	 '_aqb_aff_price_for_one_referral' => 'Price for one invited member',
	 '_aqb_aff_points_for_one_referral' => 'Points for one invited member',
	 '_aqb_aff_action_aqb_aff_send' => 'Invitation was sent',
	 '_aqb_aff_empty_result' => 'Empty',
	 '_aqb_aff_my_history_block' => 'My History',
	 '_aqb_aff_member_history_block' => '{0}\'s History',
	 '_aqb_aff_my_payment_info' => 'Price Information',
	 '_aqb_aff_my_commissions_info' => 'Commission Information',
	 '_aqb_aff_referrals_mem_level_upgrade_percentage' => 'Percentage of my invited members\' upgrades',
	 '_aqb_aff_referrals_mem_level_upgrade_points' => 'Points for invited members\' upgrades',
	 '_aqb_aff_referrals_banner_action_info' => 'Price for all banners\' activities such as <b>impressions</b> and <b>clicks</b> depends on banner\'s characteristics. You may find more details on <a href="{0}">Affiliates page</a>',
	 '_aqb_aff_execution_date' => 'last update',
	 '_aqb_aff_action_title'  => 'action',
	 '_aqb_aff_method'  => 'method',
	 '_aqb_aff_actions_number'  => 'number',
	 '_aqb_aff_sum_price'  => 'earned(currency)',
	 '_aqb_aff_sum_points' => 'earned(points)',
	 '_aqb_aff_action_name_impression' => 'impression',
	 '_aqb_aff_action_name_click' => 'click',
	 '_aqb_aff_action_name_join' => '{0} member joined',
	 '_aqb_aff_get_comission' => 'Get my Commissions',
	 '_aqb_aff_get_comission_message' => 'Email about commissions request will be sent to site administration. You need to wait a little!',
	 '_aqb_aff_assign_points' => 'Affiliate\Referrals commission',
	 '_aqb_aff_points_were_added' => '{0} points were successfully added to your points balance!',
	 '_aqb_aff_points_were_not_added' => 'Points were not added!!!', 
	 '_aqb_aff_my_pending_balance' => 'Pending Commission',
	 '_aqb_aff_my_pending_points_balance' => 'Pending Points Commission',
	 '_aqb_aff_my_paid_cash_commission' => 'Paid Commission',
	 '_aqb_aff_my_paid_points_commission' => 'Transferred points',
	 '_aqb_aff_get_commission_admin_email' => 'Member {0} wants to get commission {1}',
	 '_aqb_aff_commission_request_email_subject' => 'Commission Request',
	 '_aqb_aff_commission_to_pending_send_email' => 'Email about commission request has been successfully sent to site administration!',	 
	 '_aqb_aff_commission_not_to_pending_send_email' => 'Email about commission request has not been sent! Please contact site\'s administration about it!',	 
	 '_aqb_aff_commission_can_not_be_paid' => 'Sorry, commission can not be paid! Please contact site\'s administration about it!',
	 '_aqb_aff_commission_can_not_be_paid_empty' => 'You have no commission yet!',	 
	 '_aqb_aff_referral_link' => 'Your referral link',
	 '_aqb_aff_my_affiliate_info' => 'Affiliate banner\'s statistics',
	 '_aqb_aff_affiliate_page' => 'Affiliates',
	 '_aqb_aff_my_affiliate_banners' => 'Available Banners',
	 '_aqb_aff_affiliate_banners_shows' => 'Number of unique banners impressions',
	 '_aqb_aff_affiliate_banners_clicks' => 'Number of unique banners clicks',
	 '_aqb_aff_affiliate_banners_name' => 'Name',
	 '_aqb_aff_affiliate_banners_size' => 'Size',
	 '_aqb_aff_affiliate_banner_price_per_impression' => 'per impression', 
	 '_aqb_aff_affiliate_banner_price_per_click' => 'per click',
	 '_aqb_aff_affiliate_banner_price_per_join' => 'per member\'s join',
	 '_aqb_aff_affiliate_banner_price_per_upgrade' => 'percentage of member\'s upgrade',

	 '_aqb_aff_affiliate_banner_points_per_impression' => 'per impression', 
	 '_aqb_aff_affiliate_banner_points_per_click' => 'per click',
	 '_aqb_aff_affiliate_banner_points_per_join' => 'per member\'s join',
	 '_aqb_aff_affiliate_banner_points_per_upgrade' => 'for member\'s upgrade',
	 '_aqb_aff_affiliate_banners_code' => 'Banner code',
	 '_aqb_aff_commission_title' => 'Commission',
	 '_aqb_aff_points_title' => 'Points',
	 '_aqb_aff_button_show_banner_code' => 'Show/Hide banner\'s code',
	 '_aqb_aff_send_invintation' => 'Send Invitation',
	 '_aqb_aff_get_banner_link' => 'You may also use affiliate banners for invitations and earn commission {0}',
	 '_aqb_aff_read_more' => 'read more',
	 '_aqb_aff_emails' => 'Emails',
	 '_aqb_aff_info' => 'Here you may put emails separated by comma(,) or blanks (maximum {0} emails per 24 hours)',
	 '_aqb_aff_messages_info' => 'Message for your friends, maximum {0} symbols',
     '_aqb_aff_messages' => 'Message',
	 '_aqb_aff_error_symbols_length' => 'Sorry, you can send message which contains more then {0} symbols',
	 '_aqb_aff_error_symbols_empty_emails' => 'Emails field can not be empty',
	 '_aqb_aff_send_button' => 'Send',
	 '_aqb_aff_max_email_error' => 'Sorry, you can send invitations to no more then {0} person(s) now, because you have already sent {1} emails. Maximum allowed {2} emails per 24 hours.',
	 '_aqb_aff_invitation_message' => 'We are glad to invite you to {0}!',
	 '_aqb_aff_successfully_sent' => '{0} email(s) was(were) successfully sent!',
	 '_aqb_aff_not_sent' => 'Sorry, nothing has been sent!',
	 '_aqb_aff_admin_commissions' => 'Commissions',
     '_aqb_aff_admin_membersinfo' => 'Members',
	 '_aqb_aff_admin_txt_username' => 'Username',
	 '_aqb_aff_admin_txt_registration' => 'Registered', 
	 '_aqb_aff_admin_txt_last_login' => 'Last Visit',
	 '_aqb_aff_admin_txt_join' => 'Invited',
	 '_aqb_aff_admin_txt_impressions' => 'Imp.', 
	 '_aqb_aff_admin_txt_clicks' => 'Clicks',
	 '_aqb_aff_admin_txt_upgrades' => 'Upg.',
	 '_aqb_aff_admin_txt_actions' => 'Actions',
	 '_aqb_aff_admin_txt_view' => 'View',
	 '_aqb_aff_admin_confirm_del_transactions' => 'If you delete this transaction, all actions for which it was sent will be also deleted(you may just make it unpaid). Are you sure you want to delete it?',
	 '_aqb_aff_admin_confirm_clean' => 'Are you sure you want to delete all info about referred members, banners and commissions of this member?',
	 '_aqb_aff_can_not_clean_history' => 'Sorry, history can not be cleaned!',
	 '_aqb_aff_successfully_clean_history' => '{0}\'s history was successfully cleaned!',
	 '_aqb_aff_block_delete' => 'Delete',
	 '_aqb_aff_show_all_members' => 'Show all members',
	 '_aqb_aff_confirm_clean' => 'Are you sure you want to remove all members history?',
	 '_aqb_aff_clean_all_members' => 'Clean all members\' history',
	 '_aqb_aff_filter' => 'Filter',
	 '_aqb_aff_filter_info' => 'Filtration will be done by the next member\'s fields:<br/>NickName, Email, DescriptionMe, Tags, DateLastLogin',
	 '_aqb_aff_search' => 'Search',
	 '_aqb_aff_was_not_clean' => 'Sorry, history can not be cleaned!',
     '_aqb_aff_all_history_cleaned' => 'Cleaned!',
	 '_aqb_aff_admin_txt_price' => 'Sum',
	 '_aqb_aff_admin_commission_sum_points' => 'Points',
	 '_aqb_aff_admin_txt_points_title' => 'Points',
	 '_aqb_aff_admin_txt_transaction_date_start' => 'Requst date',
	 '_aqb_aff_admin_txt_transaction_date_end' => 'Paid',
	 '_aqb_aff_admin_txt_status' => 'Status',
	 '_aqb_aff_admin_txt_upgrades_trans' => 'Upg.',
	 '_aqb_aff_admin_txt_impressions_trans' => 'Imp.',
	 '_aqb_aff_transactions_delete' => 'Delete',
	 '_aqb_aff_transactions_approve' => 'Commission was paid!',
	 '_aqb_aff_changes_trans_status' => 'Are you sure you want to change transaction(s) status? Staus can not be changed to Unpaid again!!!',
	 '_aqb_aff_delete_trans' => 'Are you sure you want to delete transaction(s)?',
	 '_aqb_aff_admin_txt_paid' => 'Paid{0}',
	 '_aqb_aff_admin_txt_unpaid' => 'Unpaid{0}',
	 '_aqb_aff_admin_txt_paid_points' => 'Paid(ps.)',
	 '_aqb_aff_admin_txt_unpaid_points' => 'Unpaid(ps.)',
	 '_aqb_aff_txt_view_history' => 'view member\'s history',
	 '_aqb_aff_txt_view_invited' => 'view invited members',
	 '_aqb_aff_txt_view_commission' => 'commission',
	 '_aqb_aff_commission_filter' => 'NickName',
	 '_aqb_aff_banner_width' => 'Width',
	 '_aqb_aff_banner_height' => 'Height',
	 '_aqb_aff_modules_is_not_alowed' => 'Sorry, this possibility is not allowed!',
	 '_aqb_aff_action_name_upgrade' => '{0} upgraded',
	 '_aqb_aff_my_account_referrals' => 'Affiliate\Referrals information',
	 '_aqb_aff_admin_affiliates_forced_matrix' => 'Forced Matrix',
	 '_aqb_aff_matrix_levels_error' => 'Forced Matrix levels deep can not be empty',
	 '_aqb_aff_matrix_levels' => 'Forced matrix levels deep (maximum <b>15</b>)',
	 '_aqb_aff_income' => 'Show the next cells in information block for members',
	 '_aqb_aff_income_percentage' => '<b>percentage</b> of price for every membership upgrade', 
	 '_aqb_aff_income_currency' => 'price in currency <b>{0}</b> for every new member',
	 '_aqb_aff_income_upgrade_points' => '<b>points</b> for every paying membership sold', 
	 '_aqb_aff_income_join_points' => '<b>points</b> for every new member',	 
	 '_aqb_aff_matrix_levels_width' => 'Forced matrix width (maximum <b>5</b>) and <b>0</b> for limitless',
	 '_aqb_aff_matrix_levels_width_info' => 'If you defined here value more then <b>0</b> and less then <b>5</b>, then if new members\' sponsor has his/her first level full all other referring members will be spilled over to sponsor\'s downline. Spillover feature must be enabled for it.<br/> If define {0} there is no limitation',
	 '_aqb_aff_matrix_create' => 'Save settings',
	 '_aqb_aff_admin_txt_level_title' => 'Level',
	 '_aqb_aff_admin_txt_income' => 'Join in {0}',
	 '_aqb_aff_admin_txt_income_upgrade' => 'Upgrade <b>%</b> of price',
	 '_aqb_aff_admin_txt_points' => 'Join in points',
	 '_aqb_aff_admin_txt_points_upgrade' => 'Upgrade in points',
	 '_aqb_aff_matrix_submit' => 'Save',
	 '_aqb_aff_matrix_enable' => 'Enable Forced Martrix feature',
	 '_aqb_aff_matrix_is_not_enabled' => 'Forced Matrix feature is not enabled! You need to enable it.',
	 '_aqb_aff_matrix_is_not_enabled_for_mem' => 'Forced Matrix feature is not available for your membership level!',
	 '_aqb_aff_matrix_confirm_create' => 'If you already has forced matrix with values, it will be removed when you create new matrix. You will loose all values and settings of old matrix. Continue?',
	 '_aqb_aff_matrix_view_info' => 'View possible commission',
	 '_aqb_aff_matrix_info_preview' => 'Commission {0}',
	 '_aqb_aff_admin_txt_amount_join' => 'Amount for join',
	 '_aqb_aff_admin_txt_amount_upgrade' => '% from upgrade',
	 '_aqb_aff_admin_txt_amount_points_join' => 'Amount for join(in points)',
	 '_aqb_aff_admin_txt_amount_points_upgrade' => 'Amount for upgrade(in points)',
	 '_aqb_aff_admin_txt_people' => 'People',
	 '_aqb_aff_admin_txt_income_total' => 'Total Income',
	 '_aqb_aff_standard_view' => 'Standard',
	 '_aqb_aff_tree_view' => 'Tree',
	 '_aqb_aff_tree_level' => 'L-{0}',
	 '_aqb_aff_detele_ref' => 'Delete',
	 '_aqb_aff_price_matrix' => '<b>View referrals matrix price information</b>',
	 '_aqb_aff_matrix_spillover' => 'Use spillover feature',
	 '_aqb_aff_matrix_spillover_info' => 'If you have limited matrix width(more then 0 value). For Example: If you have more then 3 matrix width and If you sponsor more than 3, your new members will be placed under your other recruits to help them get started',
	 '_aqb_aff_count_index' => '{0} invited',
	 '_aqb_aff_best_referrals_index' => 'Top referrals',
	 '_aqb_aff_my_referral' => 'My referral',
	 '_aqb_aff_my_invited_member' => 'My invited members',
	 '_aqb_aff_forced_matrix' => '(Example: if you invite only 3 members)',
	 '_aqb_aff_invited_members' => '{0}\'s invited members by both(referral link and affiliate banners)',
	 '_aqb_aff_matrix_view_info_mem_level' => 'View commission info this membership level',
	 '_aqb_aff_admin_txt_use_matrix' => 'Allow to use matrix for this membership level',
	 '_aqb_aff_admin_txt_deep_for_mem' => 'Forced matrix levels deep for this membership level',
	 '_aqb_aff_admin_per_of_price' => '<b>%</b> of price',
	 '_aqb_aff_admin_txt_points_short' => 'points',
	 '_aqb_aff_matrix_refresh' => 'Refresh Matrix',
	 '_aqb_aff_matrix_refresh_start' => 'Start',
	 '_aqb_aff_matrix_refresh_abort' => 'Abort',
	 '_aqb_aff_matrix_refresh_info' => 'You have {0} reffered members. Refreshment of matrix may take a time. Please don\'t Abort this procces!',
	 '_aqb_aff_matrix_refresh_stop_message' => 'Done!',
	 '_aqb_aff_matrix_tree_parent_node' => 'Parent Node',
	 '_aqb_aff_matrix_tree_real_ref' => 'referred by:{0}',
	 '_aqb_aff_matrix_tree_status' => 'status:{0}',
	 '_aqb_aff_table_view' => 'Table',
	 '_aqb_ref_first_name' => 'Full Name', 
	 '_aqb_ref_last_name' => 'Last Name',
	 '_aqb_ref_username' => 'NickName',
	 '_aqb_ref_reg_date' => 'Reg. Date',
	 '_aqb_ref_referred_by' => 'Referred By',
	 '_aqb_ref_level' => 'Level',
	 '_aqb_ref_search_item' => 'Search',
	 '_aqb_ref_referrals_refresh' => 'Refresh',
	 '_aqb_ref_delete_confirmation' => 'If spillover feature enabled, this member also may be in matrix of other members and if you delete it all members which have him/her in matrix will lose commissions from him/her. Are you sure you want to delete?',
	 '_aqb_ref_admin_show_title' => 'Show transactions',
	 '_aqb_ref_admin_show_item_all' => 'All',
	 '_aqb_ref_admin_show_item_unpaid' => 'Unpaid',
	 '_aqb_ref_admin_show_item_paid' => 'Paid',
	 '_aqb_aff_txt_commission_pay_cart' => 'Direct pay to member using Cart system',
	 '_aqb_aff_txt_commission_manually' => 'Process manually',
	 '_aqb_aff_txt_commission_pay_cart_not_installed' => 'This member has not installed payment details or there is no money commissions!',
	 '_aqb_aff_txt_commission_cart_title' => 'commission',
	 '_aqb_aff_txt_commission_process_manually' => 'Process Manually',
	 '_aqb_aff_txt_commission_form_transaction_id' => 'Transaction ID',
	 '_aqb_aff_txt_commission_form_transaction_id_info' => 'If you put transaction ID, member will be able to see it on his/her Payments page in Processed section. If you don\'t define transaction number member will see only paid commissions on his/her history page, but no records on Payments page.',
	 '_aqb_aff_txt_commission_form_transaction_id_button' => 'Process',
	 '_aqb_aff_txt_payment_providers' => 'This member has the next payment providers',
	 '_aqb_aff_txt_transaction_status' => 'Status',
	 '_aqb_aff_mass_payment' => 'Mass payment(paypal)',
	 '_aqb_aff_txt_paypal_mass_payment' => 'Paypal mass payment',
	 '_aqb_commission_mass_payment' => 'Pay',
	 '_aqb_aff_admin_txt_price_total' => 'Total',
	 '_aqb_commission_mass_payment_success' => 'MassPay Completed Successfully!',
	 '_aqb_commission_mass_payment_failed' => 'MassPay failed!',
	 '_aqb_commission_mass_payment_curl_problem' => 'CURL module problems!',
	 '_aqb_commission_mass_payment_empty' => 'No items to pay!',
	 '_aqb_commission_mass_payment_connect_problems' => 'Unable to connect to remote host to check transaction ({0})',
	 '_aqb_commission_mass_payment_is_not_completed' => 'Payment is not completed!',
	 '_aqb_commission_mass_payment_wrong_transaction' => 'Transaction verification failed.',
	 '_aqb_commission_mass_payment_wrong_verification_status' => 'No verification status received.',
	 '_aqb_commission_mass_payment_mail_subject' => 'Commission Payment',
	 '_aqb_aff_admin_txt_payment_status' => 'Payment Status',
	 '_aqb_commission_mass_payment_API_info' => '<p><i>If you want to use paypal Mass Payment feature you need to get your credentials in your account on paypal. How to do this:</i></p>
			<ul>
				<li>Log in to your PayPal Premier or Business account</li> 
				<li>Click the <b>Profile</b> subtab located in the top navigation area</li>
				<li>Click the <b>API Access</b> link under the Account Information header</li> 
				<li>Click the <b>Request API Credentials</b> link in the right side</li>
				<li>Choose <b>Request API signature</b> option and click on <b>Agree and Submit</b> button</li>
				<li>Now you can see your API <b>username</b>, <b>password</b> and <b>signature</b>. You need to put them to Forced Matrix settings her <a href="{0}modules/index.php?r=aqb_affiliate/administration/settings"/>{0}modules/index.php?r=aqb_affiliate/administration/settings</a></li>
			</ul>',
	 '_aqb_commission_mass_payment_IPN_info' => '<p>If you don\'t want to process all sent payments manually after payment, you need to set IPN in your paypal account and in Dolphin\'s Payment module.</p>
		  <p>How to do this:</p>
			<ul>
						<li>Log in to your PayPal Premier or Business account</li> 
						<li>Click the <b>Profile</b> subtab located in the top navigation area</li>
						<li>Click the <b> Instant Payment Notification Preferences</b> link under the <b>Selling Preferences</b> header</li> 
						<li> Choose the <b>Receive IPN messages (Enabled)</b> option and put to <b>Notification URL</b> text box <b>Data return URL</b> link from <a href="{0}m/payment/admin/">{0}m/payment/admin/</a> page from PayPal area and click Save</li>
						<li> Go to <a href="{0}m/payment/admin/"> {0}m/payment/admin/</a> page  and in <b>Process type</b> choose IPN type and then click Save</li>
			</ul>',
	 '_aqb_aff_commission_limit_to_send_request' => 'The minimum amount for payment request is {1}{0}',
	 '_aqb_aff_membership_info' => 'Settings from this area will be used <b>only</b> if you disable Forced Matrix feature!',
	 '_aqb_aff_invited_upgrade' => 'Reward member for directly invited members with membership level (<b>members number</b> - <b>membership level</b>)',
	 '_aqb_aff_add_membership_invited' => 'Save',
	 '_aqb_aff_invited_upgrade_saved' => 'Successfully saved!',
	 '_aqb_aff_membership_ugrade_info' => 'Settings from area below, will be used for all members which invited direct members and it makes no difference which mode do you use (with Forced Matrix or not)!',
	 '_aqb_aff_my_account_referrals_link' => 'My referral link',
	 '_aqb_aff_my_ref_link_message_title' => 'You can use the referral link below for invitations on this page',
         '_aqb_module_title_aqb_affiliate' => 'Affiliate\Referrals with Forced Martix System'
	 
);

?>