<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Courses';

$aLangContent = array(
  	'_modzzz_formations_na' => 'N/A', 
 	'_modzzz_formations_form_cover_caption_letter' => 'Cover Letter',
 	'_modzzz_formations_form_caption_resume' => 'Resume',
 	'_modzzz_formations_apply_letter_title' => 'New application for Course - {0}',
 	'_modzzz_formations_form_err_email' => 'You must enter an email',
 	'_modzzz_formations_form_err_cover_letter' => 'You must enter some information',
 	'_modzzz_formations_block_formation_sectors' => 'Courses Sectors',
 	'_modzzz_formations_block_company' => 'Info',
 	'_modzzz_formations_add_company' => 'Add New Company',
 	'_modzzz_formations_form_caption_listed_by' => 'Course Listed by',
 	'_modzzz_formations_form_header_location' => 'Course Location (if different from Company Location)',

 	'_modzzz_formations_form_caption_cover_letter' => 'Cover Letter',
 	'_modzzz_formations_expires' => 'Expires',
 
 	'_modzzz_formations_provider' => 'Provider',
 	'_modzzz_formations_seeker' => 'Seeker',
 	'_modzzz_formations_form_caption_post_type' => 'I am a', 
 	'_modzzz_formations_block_seeking' => 'Recent Public Courses (Wanted)',

	'_modzzz_formations_caption_membership_view_filter' => 'Allow viewing by membership',
	'_modzzz_formations_err_membership_view_filter' => 'incorrect value', 
    '_modzzz_formations_info_membership_view_filter' => 'only these members will be able to view this business listing',
    '_modzzz_formations_membership_filter_none' => 'Allow All',	
    '_modzzz_formations_resume_attached' => 'Download Resume',
	'_modzzz_formations_delete_application' => 'Delete Application',

    '_modzzz_formations_block_formations_applied_for' => 'Courses I applied for',	 
    '_modzzz_formations_applied_on' => 'Applied on',	
    '_modzzz_formations_send_message' => 'Send Message',	 
 
   	'_modzzz_formations_form_header_video_embed' => 'Video Embed',
   	'_modzzz_formations_form_caption_video_embed_code' => 'Embed Code',
   	'_modzzz_formations_block_video_embed' => 'External Video',
	'_modzzz_formations_form_info_video_embed_code' => 'Enter either the URL or Embed Code for Youtube Video. Enter the Embed Code for other video sharing site (eg &lt;embed&gt;....&lt;/embed&gt;)',

    '_modzzz_formations_fans' => 'fans',
    '_modzzz_formations_sbs_join' => 'new fan',
    '_modzzz_formations_block_fans' => 'Fans',
    '_modzzz_formations_block_fans_unconfirmed' => 'Unconfirmed Fans',
	'_modzzz_formations_block_my_listings_joined' => 'Joined Courses',
    '_modzzz_formations_caption_manage_fans' => 'Manage Fans',
    '_modzzz_formations_menu_view_fans' => 'Fans',
    '_modzzz_formations_page_title_fans' => 'Course\'s Fans',
    '_modzzz_formations_action_manage_fans' => 'Manage Fans',
    '_modzzz_formations_privacy_view_fans' => 'View Fans',
    '_modzzz_formations_privacy_fans_only' => 'Fans Only',
    '_modzzz_formations_privacy_fans' => 'Fans',

    '_modzzz_formations_spy_join' => '<a href="{profile_link}">{profile_nick}</a> joined formation <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_formations_sbs_join' => 'new fan',
    '_modzzz_formations_page_title_browse_by_author_joined_formations' => '\'s joined formations',
    '_modzzz_formations_msg_joined_already' => 'You have already joined this formation',
    '_modzzz_formations_msg_joined_request_pending' => 'You have already joined this formation. Please wait while your request is processed by formation admin(s).',
    '_modzzz_formations_msg_join_success' => 'You have successfully joined this formation',
    '_modzzz_formations_msg_join_success_pending' => 'You have successfully joined this formation. Please wait while your request is processed by formation admin(s).',
	'_modzzz_formations_msg_leave_success' => 'You have successfully left this formation',
    '_modzzz_formations_form_caption_join_confirmation' => 'Join Confirmation',
    '_modzzz_formations_form_info_join_confirmation' => 'If enabled, formation admin(s) will have to confirm each user before he/she becomes a fan.',
    '_modzzz_formations_form_join_confirmation_disabled' => 'Disabled',
    '_modzzz_formations_form_join_confirmation_enabled' => 'Enabled',
    '_modzzz_formations_form_err_join_confirmation' => 'Join confirmation field must be 0 or 1',
    '_modzzz_formations_action_title_join' => 'Become Fan',
    '_modzzz_formations_action_title_leave' => 'Remove Fan',
    '_modzzz_formations_privacy_join' => 'Become Fan',
 
    '_modzzz_formations_page_title_applications_by_author' => 'Courses {0} applied for',

 	'_modzzz_formations_action_title_apply' => 'Apply',
 	'_modzzz_formations_page_title_apply' => 'Apply for this Course',
 	'_modzzz_formations_msg_application_sent' => 'Your Course Application has been sent',

 	'_modzzz_formations_upwards' => 'Upwards',
 	'_modzzz_formations_block_skills' => 'Skills Required',

	'_modzzz_formations_role' => 'Role',
	'_modzzz_formations_experience' => 'Experience Level',
	'_modzzz_formations_qualification' => 'Educational Qualification',
	'_modzzz_formations_salary' => 'Salary',
	'_modzzz_formations_company' => 'Company',
	'_modzzz_formations_vacancies' => 'Vacancies',
 	'_modzzz_formations_category' => 'Category',

	'_modzzz_formations_permanent' => 'Permanent',
	'_modzzz_formations_intern' => 'Intern / Work Experience',
	'_modzzz_formations_temporary' => 'Temporary/Contract/Project',
	'_modzzz_formations_part_time' => 'Part Time',
	'_modzzz_formations_full_time' => 'Full Time',
 
	'_modzzz_formations_form_caption_role' => 'Role',
	'_modzzz_formations_form_caption_vacancies' => 'Vacancies',
	'_modzzz_formations_form_caption_experience' => 'Experience',
	'_modzzz_formations_form_caption_qualification' => 'Educational Qualification',
	'_modzzz_formations_form_caption_skills' => 'Skills Required',
	'_modzzz_formations_form_caption_min_salary' => 'Min. Salary',
	'_modzzz_formations_form_caption_max_salary' => 'Max. Salary',
	'_modzzz_formations_form_caption_currency' => 'Salary Currency',
	'_modzzz_formations_form_caption_salary_type' => 'Salary Type',
	'_modzzz_formations_form_caption_career_level' => 'Career Level',
	'_modzzz_formations_form_caption_formation_type' => 'Course Type',
	'_modzzz_formations_form_caption_formation_status' => 'Course Status',
 
    '_modzzz_formations_no_preference' => 'no preference',
	'_modzzz_formations_fresher' => 'Fresher',
	'_modzzz_formations_less_than_1_year' => 'Less_than 1 Year',
	'_modzzz_formations_1_to_2_years' => '1 to 2 Years',
	'_modzzz_formations_2_to_5_years' => '2 to 5 Years',
	'_modzzz_formations_5_to_7_years' => '5 to 7 Years',
	'_modzzz_formations_7_to_10_years' => '7 to 10 Years',
	'_modzzz_formations_10_to_15_years' => '10 to 15 Years',
	'_modzzz_formations_more_than_15_years' => 'More than 15 Years', 
	 
	'_modzzz_formations_high_school' => 'High School',
	'_modzzz_formations_certification' => 'Certification (Diploma)',
	'_modzzz_formations_vocational' => 'Vocational (Diploma)',
	'_modzzz_formations_tertiary_education' => 'Tertiary Education',
	'_modzzz_formations_associates_degree' => 'Associates Degree',
	'_modzzz_formations_bachelors' => 'Bachelors',
	'_modzzz_formations_masters' => 'Masters',
	'_modzzz_formations_doctorate' => 'Doctorate',
	'_modzzz_formations_professional_engineering' => 'Professional-Engineering',
	 
	'_modzzz_formations_student_college' => 'Student (College)',
	'_modzzz_formations_student_high_school' => 'Student (High School)',
	'_modzzz_formations_entry_level' => 'Entry Level (less than 2 years experience)',
	'_modzzz_formations_mid_career' => 'Mid Career (2+ years of experience)',
	'_modzzz_formations_management' => 'Management (Manager/Director of Staff)',
	'_modzzz_formations_executive' => 'Executive (SVP, EVP, VP)',
	'_modzzz_formations_senior_executive' => 'Senior Executive (President, CEO)',

	'_modzzz_formations_per_year' => 'Per Year',
	'_modzzz_formations_per_month' => 'Per Month',
	'_modzzz_formations_per_week' => 'Per Week',
	'_modzzz_formations_fortnightly' => 'Fortnightly',
	'_modzzz_formations_per_hour' => 'Per Hour',
	  
   	'_modzzz_formations_form_caption_business_type' => 'Business Type',  
 	'_modzzz_formations_form_caption_employee_count' => 'Employee Count',  
 	'_modzzz_formations_form_caption_office_count' => 'Office Count',  
 
	'_modzzz_formations_caption_state' => 'State',  
	'_modzzz_formations_block_formations_states' => 'States',  
    '_modzzz_formations_regions_for_country' => 'States/Regions for',  
	'_modzzz_formations_block_browse_state' => 'Browse States', 
	'_modzzz_formations_block_browse_state_formations' => 'Browse Courses by State', 
	'_modzzz_formations_block_account' => 'Courses in my Area',  
	'_modzzz_formations_block_browse_country' => 'Browse by Country', 
	'_modzzz_formations_page_title_local' => 'Browse Local Courses',  
	'_modzzz_formations_caption_browse_local' => 'Browse Local Courses in {0}', 
	'_modzzz_formations_menu_local' => 'Local Courses', 
 	'_modzzz_formations_block_local' => 'More Local Courses',
	'_modzzz_formations_block_other' => 'Other Courses by this Company',
 	'_modzzz_formations_caption_browse_other' => 'Other Courses by {0}',	
 	'_modzzz_formations_block_local_formations' => 'Local Courses',
	'_modzzz_formations_block_formations' => 'Courses',
 	'_modzzz_formations_block_stats' => 'Statistics',

	'_modzzz_formations_block_formations_categories' => 'Categories', 
    '_modzzz_formations_block_category_formations' => 'Courses in this Category',
    '_modzzz_formations_block_subcategories' => 'Sub-Categories',  
    '_modzzz_formations_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button', 
	'_modzzz_formations_categ_name' => 'Category',
	'_modzzz_formations_categ_btn_edit' => 'Edit',
	'_modzzz_formations_categ_btn_delete' => 'Delete',
	'_modzzz_formations_categ_btn_add' => 'Add',
	'_modzzz_formations_categ_btn_save' => 'Save',
	'_modzzz_formations_categ_btn_subcategories' => 'Sub-Categories', 
 	'_modzzz_formations_categories' => 'Categories',
 	'_modzzz_formations_menu_admin_manage_categories' => 'Categories',
  	'_modzzz_formations_menu_admin_manage_subcategories' => 'Sub-Cats',
  	'_modzzz_formations_subcategories' => 'Sub-Categories',
  	'_modzzz_formations_categories' => 'Categories',
    '_modzzz_formations_form_caption_parent_category' => 'Category',
    '_modzzz_formations_all_categories' => 'All Categories',
    '_modzzz_formations_block_categories' => 'Categories',
    '_modzzz_formations_block_formations_subcategories' => 'Sub-Categories',
    '_modzzz_formations_block_answer_categories' => 'Courses Categories',
    '_modzzz_formations_menu_categories' => 'Categories',
    '_modzzz_formations_page_title_browse_by_category' => 'Browse Courses By Category: ',
    '_modzzz_formations_form_caption_category' => 'Category',
    '_modzzz_formations_form_err_category' => 'Category is invalid', 
	'_modzzz_formations_page_title_category' => 'Category', 
    '_modzzz_formations_page_title_categories' => 'Courses Categories',
    '_modzzz_formations_page_title_subcategories' => 'Courses Sub-Categories', 
    '_modzzz_formations_formations_in_category' => '<b>Courses</b> in <b>%s</b>',  
 
    '_modzzz_formations_posted_on' => 'Posted on', 
    '_modzzz_formations_listed_by' => 'Listed by', 
    '_modzzz_formations_company' => 'Company', 
  
    '_modzzz_formations_company_page_title_browse_featured' => 'Featured Companies', 
    '_modzzz_formations_posted' => 'Posted', 
    '_modzzz_formations_formations_posted' => 'Courses posted', 

    '_modzzz_formations_block_today_formation' => 'Course for the Day', 
    '_modzzz_formations_block_featured_formations' => 'Featured Available Courses', 
    '_modzzz_formations_block_featured_wanted_formations' => 'Featured Wanted Courses', 
    '_modzzz_formations_block_featured_companies' => 'Featured Companies', 
 
    '_modzzz_formations_menu_companies' => 'Companies', 
    '_modzzz_formations_present_icon' => 'Present Icon', 
    '_modzzz_formations_form_header_company_edit' => 'Edit Company Details', 


    '_modzzz_formations_form_header_select_company' => 'Select Company (Select from existing or choose to add a new one)', 
    '_modzzz_formations_form_header_company' => 'New Company Details',
    '_modzzz_formations_form_icon' => 'Icon', 
    '_modzzz_formations_select_company' => '-- select company ---',
    '_modzzz_formations_select_no_company' => '-- no company added yet ---',
    '_modzzz_formations_form_caption_address' => 'Address',
    '_modzzz_formations_form_caption_company' => 'Company', 
    '_modzzz_formations_form_caption_website' => 'Website Link',
    '_modzzz_formations_form_info_company' => 'Company advertising the Course',
    '_modzzz_formations_caption_country' => 'Country',
    '_modzzz_formations_caption_state' => 'State',
    '_modzzz_formations_caption_name'=> 'Name',
    '_modzzz_formations_form_caption_email'=> 'Email',
    '_modzzz_formations_form_caption_telephone'=> 'Telephone', 
    '_modzzz_formations_form_caption_fax'=> 'Fax', 
    '_modzzz_formations_form_caption_name'=> 'Name',

    '_sbs_txt_title_modzzz_formations' => 'Courses',
    '_modzzz_formations' => 'Courses',
    '_modzzz_formations_fans' => 'fans',
    '_modzzz_formations_add' => 'add',
    '_modzzz_formations_wall_added_new' => 'added new',
    '_modzzz_formations_wall_object' => 'formation',
    '_modzzz_formations_for_formation' => 'for %s',
    '_modzzz_formations_formation_single' => 'formation',
    '_modzzz_formations_formation_plural' => 'formations',
    '_modzzz_formations_user_unknown' => 'Someone',

    '_modzzz_formations_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new formation <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_formations_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed formation <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_formations_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated formation <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_formations_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented formation <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_formations_sbs_change' => 'information was updated',
    '_modzzz_formations_sbs_comment' => 'new comment arrived',
    '_modzzz_formations_sbs_rate' => 'rating was updated',
    '_modzzz_formations_sbs_join' => 'new fan',

    '_modzzz_formations_tab_featured' => 'Featured',
    '_modzzz_formations_tab_recent' => 'Recent',
    '_modzzz_formations_tab_top' => 'Top',
    '_modzzz_formations_tab_popular' => 'Popular',

    '_modzzz_formations_block_submenu_main' => 'Main',
    '_modzzz_formations_block_submenu_add_formation' => 'Add',
    '_modzzz_formations_block_submenu_manage_formations' => 'Manage',
    '_modzzz_formations_block_submenu_pending_formations' => 'Pending Approval',

    '_modzzz_formations_block_actions' => 'Actions',
    '_modzzz_formations_block_rate' => 'Rate',    
    '_modzzz_formations_block_info' => 'Info',
    '_modzzz_formations_block_desc' => 'Description',
    '_modzzz_formations_block_photo' => 'Photos',
    '_modzzz_formations_block_video' => 'Videos',
    '_modzzz_formations_block_sound' => 'Sounds',
    '_modzzz_formations_block_files' => 'Files',
    '_modzzz_formations_block_file' => 'Files',
    '_modzzz_formations_block_comments' => 'Comments',
    '_modzzz_formations_block_latest_featured_formation' => 'Latest Featured Course',
    '_modzzz_formations_block_recent' => 'Recent Public Courses (Offers)',
    '_modzzz_formations_block_administration_owner' => 'Administration',
    '_modzzz_formations_block_users_formations' => 'User\'s Courses',
    '_modzzz_formations_block_my_formations' => 'Courses I posted',
    '_modzzz_formations_block_search_formations' => 'Search Courses', 
    '_modzzz_formations_block_homepage' => 'Courses',
    '_modzzz_formations_block_location' => 'Location',

    '_modzzz_formations_caption_add' => 'Add Course',
    '_modzzz_formations_caption_share_formation' => 'Share Course',
    '_modzzz_formations_caption_share_company' => 'Share Company', 
    '_modzzz_formations_caption_admin_actions' => 'Links',
    '_modzzz_formations_caption_pending_approval' => 'Pending Approval Courses', 

    '_modzzz_formations_menu_root' => 'Courses',
    '_modzzz_formations_menu_main' => 'Courses Home',
    '_modzzz_formations_menu_recent' => 'Recent',
    '_modzzz_formations_menu_top_rated' => 'Top Rated',
    '_modzzz_formations_menu_popular' => 'Popular',
    '_modzzz_formations_menu_featured' => 'Featured',
    '_modzzz_formations_menu_wanted' => 'Wanted', 
    '_modzzz_formations_menu_tags' => 'Tags',
    '_modzzz_formations_menu_categories' => 'Categories',
    '_modzzz_formations_menu_calendar' => 'Calendar',
    '_modzzz_formations_menu_search' => 'Search',
    '_modzzz_formations_menu_view_formation' => 'Main',
    '_modzzz_formations_menu_view_forum' => 'Forum',
    '_modzzz_formations_menu_view_applications' => 'View Applications', 
    '_modzzz_formations_menu_view_comments' => 'Comments',
    '_modzzz_formations_menu_view_photos' => 'Photos',
    '_modzzz_formations_menu_view_videos' => 'Videos',
    '_modzzz_formations_menu_view_sounds' => 'Sounds',
    '_modzzz_formations_menu_view_files' => 'Files',
    '_modzzz_formations_menu_my_formations_profile' => 'Courses',

    '_modzzz_formations_menu_admin_pending_approval' => 'Pending Approval',
    '_modzzz_formations_menu_admin_entries' => 'Admin Courses',
    '_modzzz_formations_menu_admin_add_entry' => 'Add Course',
    '_modzzz_formations_menu_admin_settings' => 'Settings',
    
    '_modzzz_formations_page_title_home' => 'Courses Home',
    '_modzzz_formations_page_title_calendar' => 'Courses Calendar ',
    '_modzzz_formations_page_title_comments' => 'Comments',
    '_modzzz_formations_page_title_photos' => 'Photos',
    '_modzzz_formations_page_title_videos' => 'Videos',
    '_modzzz_formations_page_title_sounds' => 'Sounds',
    '_modzzz_formations_page_title_files' => 'Files',
    '_modzzz_formations_page_title_fans' => 'Course\'s Fans',
    '_modzzz_formations_page_title_applications' => 'Course\'s Applications', 
    '_modzzz_formations_page_title_my_formations' => 'My Courses',
    '_modzzz_formations_page_title_search' => 'Courses Search',
    '_modzzz_formations_page_title_add' => 'Add Course', 
    '_modzzz_formations_page_title_edit' => 'Edit Course',
    '_modzzz_formations_page_company_title_edit' => 'Edit Company',

    '_modzzz_formations_page_title_administration' => 'Courses Administration',
    '_modzzz_formations_page_title_browse' => 'Browse Courses',
    '_modzzz_formations_company_page_title_browse' => 'Browse Companies',
  
    '_modzzz_formations_applicants_page_title_broadcast' => 'Send broadcast message to all applicants for this formation',
	'_modzzz_formations_applicants_msg_broadcast_message_sent' => 'Broadcast message have been sent',
    '_modzzz_formations_applicants_msg_broadcast_no_recipients' => 'There are no applicants for this formation yet',

    '_modzzz_formations_page_title_pending_approval' => 'Pending Approval Courses',
    '_modzzz_formations_page_title_search_results' => 'Courses Search Results',
    '_modzzz_formations_page_title_browse_by_author' => '\'s formations',
    '_modzzz_formations_page_title_admin_formations' => 'Admin Courses',
    '_modzzz_formations_page_title_browse_by_category' => 'Browse Courses By Category: ',
    '_modzzz_formations_page_title_browse_by_tag' => 'Browse Courses By Tag: ',
    '_modzzz_formations_page_title_browse_recent' => 'Recent Courses',
    '_modzzz_formations_page_title_browse_seeking' => 'Wanted Courses', 
    '_modzzz_formations_page_title_browse_top_rated' => 'Top Rated Courses',
    '_modzzz_formations_page_title_browse_popular' => 'Popular Courses',
    '_modzzz_formations_page_title_browse_featured' => 'Featured Courses',
    '_modzzz_formations_page_title_browse_featured_wanted' => 'Featured Wanted Courses',
    '_modzzz_formations_page_title_browse_by_day' => 'Browse Courses By Day: ',
    '_modzzz_formations_page_title_tags' => 'Courses Tags',
    '_modzzz_formations_page_title_categories' => 'Courses Categories',
    '_modzzz_formations_page_title_broadcast' => 'Send broadcast message to all fans for this formation',
    '_modzzz_formations_page_company_title_broadcast' => 'Send broadcast message to all fans of formations listed by this company',
    '_modzzz_formations_page_title_upload_photos' => 'Add Photos',
    '_modzzz_formations_page_title_upload_videos' => 'Add Videos',
    '_modzzz_formations_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_formations_page_title_upload_files' => 'Add Files',
    '_modzzz_formations_page_title_invite' => 'Send Invitation about ',
    '_modzzz_formations_page_company_title_invite' => 'Send Invitation to friends - ', 

    '_modzzz_formations_msg_pending_approval' => 'this formation is pending approval, please wait until it will be activated',
    '_modzzz_formations_msg_formation_was_deleted' => 'Course was deleted',
    '_modzzz_formations_company_msg_formation_was_deleted' => 'Company was deleted',

    '_modzzz_formations_msg_removed_from_featured' => 'Course was removed from featured',
    '_modzzz_formations_msg_added_to_featured' => 'Course was added to featured',

    '_modzzz_formations_msg_removed_from_today' => 'Item was removed as Course for the day',
    '_modzzz_formations_msg_added_to_today' => 'Item was made Course for the day',

    '_modzzz_formations_company_msg_removed_from_featured' => 'Company was removed from featured',
    '_modzzz_formations_company_msg_added_to_featured' => 'Company was added to featured',
 
    '_modzzz_formations_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_formations_msg_you_have_pending_approval_formations' => 'You have <a href="%s">%d pending approval formations</a>',
    '_modzzz_formations_msg_you_have_no_formations' => 'You don\'t have any formations. <a href="%s">Click here</a> to add one.',
    '_modzzz_formations_msg_you_have_some_formations' => 'You have <a href="%s">%d formation listing(s)</a>. <a href="%s">Click here</a> to add more.',
    
	'_modzzz_formations_msg_broadcast_message_sent' => 'Broadcast message have been sent',
    '_modzzz_formations_msg_broadcast_no_recipients' => 'There are no fans of this formation yet',
    '_modzzz_formations_msg_invitation_sent' => '%d invitations have been sent',
    '_modzzz_formations_msg_no_users_to_invite' => 'There are no users in your contacts', 
    '_modzzz_formations_msg_joined_already' => 'You are already a fan of this formation',
    '_modzzz_formations_msg_join_success' => 'You have successfully become a fan of this formation',
	'_modzzz_formations_msg_leave_success' => 'You are no longer a fan of this formation',

    '_modzzz_formations_company_msg_broadcast_no_recipients' => 'There are no fans of any formations listed by this company',
 
    '_modzzz_formations_admin_delete' => 'Delete',
    '_modzzz_formations_admin_activate' => 'Activate',
    '_modzzz_formations_admin_add_new_formation' => 'Add New Course',
    '_modzzz_formations_admin_formations' => 'Admin Courses',
    '_modzzz_formations_admin_settings' => 'Admin Settings',

    '_modzzz_formations_form_header_info' => 'Course\'s Info',
    '_modzzz_formations_form_header_images' => 'Photos',
    '_modzzz_formations_form_header_videos' => 'Videos',
    '_modzzz_formations_form_header_sounds' => 'Sounds',
    '_modzzz_formations_form_header_files' => 'Files',
    '_modzzz_formations_form_header_privacy' => 'Privacy Settings',
    '_modzzz_formations_form_caption_title' => 'Title',
    '_modzzz_formations_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_formations_form_caption_desc' => 'Description',
    '_modzzz_formations_form_err_desc' => 'Please enter at least 20 characters',
    '_modzzz_formations_form_err_tags' => 'Please enter tags',
    '_modzzz_formations_form_caption_author_id' => 'Author',
    '_modzzz_formations_form_info_author' => 'Author profile ID number',
    '_modzzz_formations_form_caption_keyword' => 'Keyword',
    '_modzzz_formations_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_modzzz_formations_form_caption_category' => 'Category',
    '_modzzz_formations_form_err_category' => 'Category is invalid',    
    '_modzzz_formations_form_caption_images_choice' => 'Choose',
    '_modzzz_formations_form_info_images_choice' => 'You can choose several images from your "Courses" category',
    '_modzzz_formations_form_caption_images_upload' => 'Upload',    
    '_modzzz_formations_form_info_images_upload' => 'Image will be placed in the "Courses" category automatically',
    '_modzzz_formations_form_caption_videos_choice' => 'Choose',
    '_modzzz_formations_form_info_videos_choice' => 'You can choose several videos from your "Courses" category',
    '_modzzz_formations_form_caption_videos_upload' => 'Upload',
    '_modzzz_formations_form_info_videos_upload' => 'Video will be placed in the "Courses" category automatically',
    '_modzzz_formations_form_caption_sounds_choice' => 'Choose',
    '_modzzz_formations_form_info_sounds_choice' => 'You can choose several sounds from your "Courses" category',
    '_modzzz_formations_form_caption_sounds_upload' => 'Upload',
    '_modzzz_formations_form_info_sounds_upload' => 'Sound will be placed in the "Courses" category automatically',
    '_modzzz_formations_form_caption_files_choice' => 'Choose',
    '_modzzz_formations_form_info_files_choice' => 'Unclick checkbox to remove file from this formation',
    '_modzzz_formations_form_caption_files_upload' => 'Upload',
    '_modzzz_formations_form_info_files_upload' => 'File will be placed in the "Courses" category and set as private automatically',
    '_modzzz_formations_form_caption_file_title' => 'Title:',
    '_modzzz_formations_form_caption_file_price' => 'Price:',
    '_modzzz_formations_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_formations_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_formations_form_info_thumb_choice' => 'You can choose any image from your "Courses" category as formation thumbnail',
    '_modzzz_formations_form_caption_broadcast_title' => 'Broadcast message title',
    '_modzzz_formations_form_err_broadcast_title' => 'Please enter from 3 to 100 characters', 
    '_modzzz_formations_form_caption_broadcast_message' => 'Broadcast message',
    '_modzzz_formations_form_err_broadcast_message' => 'Please enter at least 10 characters',
    '_modzzz_formations_form_caption_country' => 'Country',
    '_modzzz_formations_form_err_country' => 'Country is a required field',
    '_modzzz_formations_form_caption_city' => 'City',
    '_modzzz_formations_form_err_city' => 'Please enter from 2 to 50 characters',
    '_modzzz_formations_form_caption_zip' => 'Zip/Postal Code',
    '_modzzz_formations_form_err_zip' => 'Zip/Postal code is required',

    '_modzzz_formations_action_title_edit' => 'Edit',
    '_modzzz_formations_action_title_delete' => 'Delete',
    '_modzzz_formations_action_title_share' => 'Share',
    '_modzzz_formations_action_title_broadcast' => 'Mail Fans',
    '_modzzz_formations_action_title_broadcast_applicants' => 'Mail Applicants', 
    '_modzzz_formations_action_title_leave' => 'Leave',
    '_modzzz_formations_action_title_invite' => 'Invite',
    '_modzzz_formations_action_add_to_featured' => 'Feature',    
    '_modzzz_formations_action_remove_from_featured' => 'Unfeature', 
    '_modzzz_formations_action_add_to_today' => 'Feature Today',    
    '_modzzz_formations_action_remove_from_today' => 'Unfeature Today', 
    '_modzzz_formations_action_add_formation' => 'Add Course',
    '_modzzz_formations_action_my_formations' => 'My Courses',
    '_modzzz_formations_action_upload_photos' => 'Add Photos',
    '_modzzz_formations_action_upload_videos' => 'Add Videos',
    '_modzzz_formations_action_upload_sounds' => 'Add Sounds',
    '_modzzz_formations_action_upload_files' => 'Add Files',
    '_modzzz_formations_action_formations_home' => 'Courses Home',
    '_modzzz_formations_privacy_view_fans' => 'View Fans', 
    '_modzzz_formations_privacy_view_formation' => 'View Course',
    '_modzzz_formations_privacy_comment' => 'Comment',
    '_modzzz_formations_privacy_rate' => 'Rate',
    '_modzzz_formations_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_formations_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_formations_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_formations_privacy_upload_files' => 'Upload Files',
    '_modzzz_formations_privacy_edit_formation' => 'Edit Course',
    '_modzzz_formations_privacy_post_in_forum' => 'Post In Forum',
    '_modzzz_formations_privacy_admins_only' => 'Admins Only',
 
    '_mma_formations_files_add' => 'formations files add',  
    '_mma_formations_photos_add' => 'formations photos add',  
    '_mma_formations_videos_add' => 'formations videos add',  
    '_mma_formations_sounds_add' => 'formations sounds add',  
    '_mma_formations_apply' => 'formations apply',  
	'_mma_formations_view_formation' => 'formations view formation', 
    '_mma_formations_browse' => 'formations browse', 
    '_mma_formations_search' => 'formations search', 
    '_mma_formations_add_formation' => 'formations add formation', 
    '_mma_formations_comments_delete_and_edit' => 'formations comments delete and edit', 
    '_mma_formations_edit_any_formation' => 'formations edit any formation', 
    '_mma_formations_delete_any_formation' => 'formations delete any formation', 
    '_mma_formations_mark_as_featured' => 'formations mark as featured', 
    '_mma_formations_approve_formations' => 'formations approve formations', 
    '_mma_formations_broadcast_message' => 'formations broadcast message',

    '_modzzz_formations_packages_empty' => 'There are no Course Packages', 
    '_modzzz_formations_package_description' => 'Description', 
    '_modzzz_formations_package_featured' => 'Featured', 

    '_modzzz_formations_featured_status' => 'Featured Status', 
    '_modzzz_formations_featured_until' => 'Featured until', 
    '_modzzz_formations_not_featured' => 'Not Featured', 
 	'_modzzz_formations_extend_featured' => 'Extend Featured Status',  
	'_modzzz_formations_purchase_featured' => 'Purchase Featured Status', 
	'_modzzz_formations_form_caption_currency' => 'Currency',  

    '_modzzz_formations_menu_packages' => 'Packages', 
    '_modzzz_formations_page_title_packages' => 'Course Packages', 
    '_modzzz_formations_block_packages' => 'Course Packages', 

	'_modzzz_formations_caption_membership_view_filter' => 'Allow viewing by membership',
	'_modzzz_formations_err_membership_view_filter' => 'incorrect value', 
    '_modzzz_formations_info_membership_view_filter' => 'only these members will be able to view this Course listing',
    '_modzzz_formations_membership_filter_none' => 'Allow All',	
  
    '_modzzz_formations_on' => 'on',  
    '_modzzz_formations_yes' => 'yes',  
    '_modzzz_formations_no' => 'no', 

	'_modzzz_formations_categ_btn_edit' => 'Edit',
	'_modzzz_formations_categ_btn_delete' => 'Delete',
	'_modzzz_formations_categ_btn_add' => 'Add',
	'_modzzz_formations_categ_btn_save' => 'Save',
 
	'_modzzz_formations_package_videos' => 'Videos',  	
	'_modzzz_formations_package_photos' => 'Photos',  	
	'_modzzz_formations_package_sounds' => 'Sounds',  	
	'_modzzz_formations_package_files' => 'Files', 
   
    '_mma_formations_purchase_featured' => 'formations purchase featured',  
	'_modzzz_formations_action_title_purchase_featured' => 'Get Featured',
	'_modzzz_formations_action_title_extend_featured' => 'Extend Featured',  
	'_modzzz_formations_purchase_featured_status' => 'Purchase Featured Status',  
	'_modzzz_formations_quantity' => 'Quantity',   
	'_modzzz_formations_purchase_success' => 'You successfully Purchased {0} Days of Featured Status', 
	'_modzzz_formations_purchase_fail' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_formations_transaction_completed_already' => 'This transaction was already completed',  
	'_modzzz_formations_featured_cost_per_day' => 'Cost per Day',  
	'_modzzz_formations_caption_num_featured_days' => 'Number of Featured Days',    
	'_modzzz_formations_caption_err_featured_days' => 'You must enter Number of Featured Days',    
	'_modzzz_formations_get_featured' => 'Get Featured',  

	'_modzzz_formations_packages' => 'Packages',
	'_modzzz_formations_package_name' => 'Package Name',
	'_modzzz_formations_package_price' => 'Package Price',
	'_modzzz_formations_package_days' => 'Package Days',
	'_modzzz_formations_form_caption_package' => 'Payment Package',
	'_modzzz_formations_form_err_package' => 'Please select a Package',  
	'_modzzz_formations_purchaser' => 'Purchaser', 
	'_modzzz_formations_invoice_no' => 'Invoice #', 
	'_modzzz_formations_package' => 'Package', 
	'_modzzz_formations_invoice_date' => 'Invoice Date', 
	'_modzzz_formations_invoice_due_date' => 'Due Date', 
	'_modzzz_formations_status' => 'Status',
	'_modzzz_formations_pending' => 'Pending',
	'_modzzz_formations_paid' => 'Paid',
	'_modzzz_formations_active' => 'Active',
	'_modzzz_formations_inactive' => 'Inactive',
	'_modzzz_formations_approved' => 'Approved',
	'_modzzz_formations_expired' => 'Expired', 
	'_modzzz_formations_block_submenu_pending_invoices' => 'Pending Invoices',
	'_modzzz_formations_block_submenu_orders' => 'Orders',
	'_modzzz_formations_page_title_orders' => 'Orders', 
	'_modzzz_formations_page_title_invoices' => 'Invoices', 
	'_modzzz_formations_menu_manage_invoices' => 'Invoices', 
	'_modzzz_formations_menu_manage_packages' => 'Packages',
	'_modzzz_formations_menu_manage_orders' => 'Orders',
	'_modzzz_formations_payment_method' => 'Payment Method',
	'_modzzz_formations_total' => 'Total',
	'_modzzz_formations_invoice_id' => 'Invoice ID',
	'_modzzz_formations_next_due_date' => 'Next Due Date',
	'_modzzz_formations_order_no' => 'Order #',
	'_modzzz_formations_product_status' => 'Product Status',
	'_modzzz_formations_order_date' => 'Order Date',
	'_modzzz_formations_purchase_failed' => 'Sorry, there was a problem with the Payment.  View your Pending Orders <a href="{0}">here</a>.',
	'_modzzz_formations_transaction_completed_already' => 'The Transaction exists already. Click <a href="{0}">here</a> to view the Course listing.',
	'_modzzz_formations_purchase_success' => 'Thank you. The Payment was successful. Click <a href="{0}">here</a> to view the Course listing.',  
	'_modzzz_formations_trans_save_failed' => 'The Payment was successful but there was a problem saving the transaction. Please contact the administrator with your Paypal transaction details so they can manually process your Order.',
	'_modzzz_formations_post_purchase_header' => 'Course Listing Purchase',  
 
    '_modzzz_formations_block_map' => 'Map',
 
    '_modzzz_formations_week_sun' => 'Sun',
    '_modzzz_formations_week_mon' => 'Mon',
    '_modzzz_formations_week_tue' => 'Tue',
    '_modzzz_formations_week_wed' => 'Wed',
    '_modzzz_formations_week_thu' => 'Thur', 
    '_modzzz_formations_week_fri' => 'Fri',
    '_modzzz_formations_week_sat' => 'Sat',
     
	'_modzzz_formations_continue' => 'Continue',

	'_modzzz_formations_action_title_premium' => 'Get Premium',  
    '_modzzz_formations_page_title_premium' => 'Get Premium Listing',   
	'_mma_formations_purchase' => 'formations purchase package', 
 
    '_modzzz_formations_action_title_extend' => 'Extend',  
    '_modzzz_formations_page_title_extend' => 'Extend Course listing',   
	'_mma_formations_extend' => 'formations extend', 

    '_modzzz_formations_action_title_relist' => 'Re-list',  
    '_modzzz_formations_page_title_relist' => 'Re-list Course listing',  
	'_mma_formations_relist' => 'formations relist', 

    '_modzzz_formations_form_caption_current_no_package' => 'No Package currently',   
    '_modzzz_formations_form_caption_current_package' => 'Current Package',  
    '_modzzz_formations_form_caption_package_price' => 'Package Price',  
    '_modzzz_formations_form_caption_package_days' => 'Length of Listing',   
 	'_modzzz_formations_expires_never' => 'unlimited (never expires)', 
 	'_modzzz_formations_days' => 'days', 
 	'_modzzz_formations_form_caption_current_item' => 'Course Listing', 
    '_modzzz_formations_extend' => 'Extend',  
    '_modzzz_formations_block_statistics' => 'Statistics',  
    '_modzzz_formations_block_price' => 'Price',  
    '_modzzz_formations_block_share' => 'Share', 
    '_modzzz_formations_block_facebook_comments' => 'Facebook Comments', 
    
	'_modzzz_formations_miles' => 'miles', 
    '_modzzz_formations_kilometers' => 'Km', 
	'_modzzz_formations_map_search_explanation' => 'Enter the City and Country (eg. miramer or miramer,US)', 

    '_modzzz_formations_enter_your_formations' => 'Enter your Listing',
    '_modzzz_formations_block_formations_create' => 'Post your Course', 
    '_modzzz_formations_block_latest_comments' => 'Latest Comments',
    '_modzzz_formations_block_forum' => 'Latest Forum Posts',
    '_modzzz_formations_posted_by' => 'Posted by',
    '_modzzz_formations_continue' => 'Continue',  
    '_modzzz_formations_block_search' => 'Course Search',  

    '_modzzz_formations_form_caption_select_resume' => 'Select Resume', 
    '_modzzz_formations_form_info_select_resume' => 'you can select from your list of existing resume', 
    '_modzzz_formations_resume_view_online' => 'View Online Resume',
 
	'_modzzz_formations_allow_num_listings' => 'Number of Listings allowed', 	
	'_modzzz_formations_allow_videos' => 'Allow Videos', 	
	'_modzzz_formations_allow_photos' => 'Allow Photos', 	
	'_modzzz_formations_allow_sounds' => 'Allow Sounds', 	
	'_modzzz_formations_allow_files' => 'Allow Files', 
 	'_modzzz_formations_featured' => 'Featured', 	
 	'_modzzz_formations_package_desc' => 'Package Description',  
    '_modzzz_formations_block_submenu_expired_formations' => 'Expired',
    '_modzzz_formations_page_title_expired' => 'Expired Listings', 
 	'_modzzz_formations_expires' => 'Expires', 	 
 	'_modzzz_formations_never' => 'Never',  
 	'_modzzz_formations_featured_listing' => 'Featured Listing (never expires)',  

	'_modzzz_formations_block_browse_categories_drilldown' => 'Categories Drilldown', 
	'_modzzz_formations_category_drilldown_for_item' => 'Categories Drilldown for <b>{0}</b>', 
 
 	'_modzzz_formations_paypal_item_desc' => 'Payment for Course Listing - {0}',  
 	'_modzzz_formations_paypal_featured_item_desc' => 'Purchase Featured Status - {0}',  
    
	'_modzzz_formations_page_title_embed_video' => 'Embed Video for Course',
    '_modzzz_formations_action_embed_video' => 'Embed Video',

    '_modzzz_formations_caption_search' => 'Search for Courses',

    '_modzzz_formations_location' => 'Location', 
    '_modzzz_formations_read_cover_letter' => 'Read Cover Letter', 
    '_modzzz_formations_cover_letter' => 'Cover Letter', 

	/*added 7.1 */
    '_modzzz_formations_wall_added_new_comment' => 'commented on a',
    '_modzzz_formations_wall_added_new_items' => 'added {0} new formation listing(s)',
	'_modzzz_formations_single' => 'Course Listing',
    '_modzzz_formations_posted_in_topic' => 'Posted in Forum',
    '_modzzz_formations_posted_in_formations' => 'Posted in Course Listing', 
    '_modzzz_formations_adm_stats' => 'Pending Courses', 
	'_sys_module_formations' => 'Courses', 
    '_modzzz_formations_block_calendar' => 'Calendar', 
    '_modzzz_formations_apply_attach_message' => 'Attached is a copy of their resume.', 

    '_modzzz_formations_download_resume_online_at' => 'Download a copy of their Resume <a href="{0}">here</a>', 
    '_modzzz_formations_view_resume_online_at' => 'View their Resume online at ', 
	'_modzzz_formations_browse_formations_in_country' => 'Postings in {0}', 

	'_mma_formations_mark_as_today' => 'formations mark as today', 

	'_modzzz_formations_caption_browse_company_formations' => 'Browse formation openings for Company - {0}', 
    '_modzzz_formations_block_company_formations' => 'Course Openings', 
    '_modzzz_formations_block_location' => 'Location', 
    '_modzzz_formations_block_contact' => 'Contact Information', 

    '_modzzz_formations_form_caption_application_link' => 'Application Link', 
    '_modzzz_formations_form_info_application_link' => 'This is a URL where members can submit their application', 

    '_modzzz_formations_form_caption_sub_category' => 'Sub-Category', 

    '_modzzz_formations_page_title_feature_item' => 'Feature this Listing',
    '_modzzz_formations_feature_listing_desc' => 'Cost for featuring a Listing',

    '_modzzz_formations_buy_link' => '<a href="{0}">Buy more here</a>',
	'_modzzz_formations_form_caption_cost_to_view' => 'Cost to View',
	'_modzzz_formations_form_caption_cost_to_post' => 'Cost to Post',
	'_modzzz_formations_form_caption_cost_to_feature' => 'Cost to Feature',
	'_modzzz_formations_form_caption_credits_balance' => 'Credits Balance',
	'_modzzz_formations_form_caption_points_balance' => 'Points Balance',
	'_modzzz_formations_credits' => 'Credits',
	'_modzzz_formations_points' => 'Points',
	'_modzzz_formations_msg_feature_success' => 'Listing was successfully featured',
	'_modzzz_formations_msg_feature_failure' => 'Failed to feature listing',
	'_modzzz_formations_form_caption_feature' => 'Make this Featured',
	'_modzzz_formations_form_caption_submit' => 'Go Ahead',
    '_mma_formations_allow_embed' => 'formations allow video embed', 
	'_modzzz_formations_form_per_day' => 'per day',
	'_modzzz_formations_caption_num_post_days' => 'Number of days for post',
	'_modzzz_formations_form_caption_post' => 'Post a Course listing for a period specified below',
	'_modzzz_formations_form_caption_view' => 'Pay to view this Course listing',

    '_modzzz_formations_msg_insufficient_credits_view' => 'Your Credits balance is {0}. You need {1} Credits to view listings.',
    '_modzzz_formations_msg_insufficient_points_view' => 'Your Points balance is {0}. You need {1} Points to view listings.',

    '_modzzz_formations_msg_insufficient_credits_post' => 'Your Credits balance is {0}. You need {1} Credits to post listings.',
    '_modzzz_formations_msg_insufficient_points_post' => 'Your Points balance is {0}. You need {1} Points to post listings.',

    '_modzzz_formations_msg_insufficient_credits_feature' => 'Your Credits balance is {0}. You need {1} Credits to feature listings.',
    '_modzzz_formations_msg_insufficient_points_feature' => 'Your Points balance is {0}. You need {1} Points to feature listings.',
	'_modzzz_formations_featured_formations' => 'This listing is featured',

	'_modzzz_formations_block_map_view' => 'Map View',
    '_mma_formations_allow_embed' => 'formations allow video embed', 
   	'_modzzz_formations_block_video_embed' => 'Youtube Videos',
	'_modzzz_formations_form_caption_youtube_link' => 'Video URL', 
	'_modzzz_formations_form_caption_youtube_caption' => 'Video Title',  
	'_modzzz_formations_form_header_youtube' => 'Youtube Videos',
	'_modzzz_formations_form_caption_youtube_attach' => 'Video',
	'_modzzz_formations_form_info_youtube_attach' => 'you can add multiple Youtube Videos',
	'_modzzz_formations_form_caption_youtube_choice' => 'Existing Videos',  
	'_modzzz_formations_form_info_youtube_choice' => 'Uncheck Videos that you want to remove', 
    '_modzzz_formations_page_title_embed_video' => 'Embed Video',
    '_modzzz_formations_action_embed_video' => 'Embed Video',

    '_modzzz_formations_block_logo' => 'Logo', 
    '_modzzz_formations_form_header_logo' => 'Logo', 
    '_modzzz_formations_present_icon' => 'Present Icon', 
    '_modzzz_formations_form_caption_icon' => 'Icon', 
    '_modzzz_formations_remove' => 'Remove', 

	'_wall_reposted_modzzz_formations_add' => 'reposted a formation listing', 

 );
