<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Formations';

$aLangContent = array(
 '_modzzz_formations_continue_search' => 'Rechercher',
   '_modzzz_formations_form_caption_apply_phone' => '<i class="sys-icon phone"> </i> Téléphone
<br><span style="font-size:13px;"> Préfixe du pays + Téléphone (ex: +243 81.....)</span>',
  '_modzzz_formations_form_info_apply_phone' => 'Précisez un numéro de téléphone valide afin que le recruteur puisse vous contacter.',
  '_modzzz_formations_form_err_apply_phone' => 'Veuillez préciser un numéro de téléphone valide afin que le recruteur puisse vous contacter.',


 '_modzzz_formations_na' => 'Non indiqué ',
  '_modzzz_formations_form_cover_caption_letter' => '<span style="color:#26012B;"><span style="font-size:14px;"><strong>Message</strong></span></span>
',
  '_modzzz_formations_form_caption_resume' => '<span style="color:#3B5999;"><span style="font-size:12px;">Télécharger un CV depuis votre ordinateur</span></span>
<br>( Facultatif )',
  '_modzzz_formations_apply_letter_title' => 'Un Candidat a postulé à votre offre de formation :  {0}',
  '_modzzz_formations_form_err_email' => 'Vous devez entrer un e-mail',
  '_modzzz_formations_form_err_cover_letter' => 'Veuillez ajouter un message à  votre candidature (50 caractères minimum).',
  '_modzzz_formations_block_formation_sectors' => '<i class="sys-icon briefcase"></i> Formationss par secteur',
  '_modzzz_formations_block_company' => '<i class="sys-icon key"></i> Info clé',
  '_modzzz_formations_add_company' => 'Ajouter une nouvelle entreprise',
  '_modzzz_formations_form_caption_listed_by' => '<span style="color:#3B5999;"><span style="font-size:12px;"><strong>Offre de formation publiée par</strong></span></span>
',
  '_modzzz_formations_form_header_location' => '<br><span style="font-size:18px;"><strong><i class="sys-icon map-marker"></i> Lieu de poste</strong></span>
',
  '_modzzz_formations_form_caption_cover_letter' => '<i class="sys-icon envelope"></i> Votre message  au recruteur',
  '_modzzz_formations_expires' => 'Expiration',
  '_modzzz_formations_provider' => 'Offre de formation',
  '_modzzz_formations_seeker' => 'Stage',
  '_modzzz_formations_form_caption_post_type' => '<i class="sys-icon sliders"></i> Proposez-vous une <strong>Formation</strong> ou un <strong>Stage</strong>?',
  '_modzzz_formations_block_seeking' => ' <i class="sys-icon puzzle-piece"></i>  Offres de Stage Récentes ',
  '_modzzz_formations_caption_membership_view_filter' => 'Autoriser la visualisation par catégorie de membre',
  '_modzzz_formations_err_membership_view_filter' => 'Valeur incorrecte',
  '_modzzz_formations_info_membership_view_filter' => 'Seulement la catégorie des  membres que vous avez sélectionnées seront en mesure de voir cette offre de formation',
  '_modzzz_formations_membership_filter_none' => 'Autoriser tout le monde',
  '_modzzz_formations_resume_attached' => 'Télécharger son CV',
  '_modzzz_formations_delete_application' => 'Supprimer la candidature',
  '_modzzz_formations_block_formations_applied_for' => 'Offres de formation auxquelles  j\'ai postulé',
  '_modzzz_formations_applied_on' => 'Postulé le',
  '_modzzz_formations_send_message' => 'Envoyer un message',
  '_modzzz_formations_form_header_video_embed' => '--',
  '_modzzz_formations_form_caption_video_embed_code' => 'Vidéo de votre entreprise
<BR>Lien Youtube',
  '_modzzz_formations_block_video_embed' => 'Video',
  '_modzzz_formations_form_info_video_embed_code' => 'Entrez l\'url  la vidéo Youtube. ex: http://www.youtube.com/watch?v=wdEPKh5C1hE',
  '_modzzz_formations_fans' => 'fans',
  '_modzzz_formations_sbs_join' => 'nouveau fan',
  '_modzzz_formations_block_fans' => 'Fans',
  '_modzzz_formations_block_fans_unconfirmed' => 'Fans non confirmés',
  '_modzzz_formations_block_my_listings_joined' => 'Joined Formationss',
  '_modzzz_formations_caption_manage_fans' => 'Gérer des Fans',
  '_modzzz_formations_menu_view_fans' => 'Fans',
  '_modzzz_formations_page_title_fans' => 'Fans de formation',
  '_modzzz_formations_action_manage_fans' => 'Gérer Fans',
  '_modzzz_formations_privacy_view_fans' => 'Qui peut voir les fans?',
  '_modzzz_formations_privacy_fans_only' => 'Fans seulement',
  '_modzzz_formations_privacy_fans' => 'Fans',
  '_modzzz_formations_spy_join' => '<a href="{profile_link}">{profile_nick}</a> a rejoint la formation <a href="{entry_url}">{entry_title}</a>',
  '_modzzz_formations_page_title_browse_by_author_joined_formations' => '\'s joined formations',
  '_modzzz_formations_msg_joined_already' => 'Vous êtes déjà fan de cette offre',
  '_modzzz_formations_msg_joined_request_pending' => 'Vous avez déjà adhéré à cette offre. Veuillez patienter pendant que votre demande soit traitée par l\'annonceur de cette offre de formation .',
  '_modzzz_formations_msg_join_success' => 'Vous êtes fan de cette offre de formation',
  '_modzzz_formations_msg_join_success_pending' => 'You have successfully joined this formation. Please wait while your request is processed by formation admin(s).',
  '_modzzz_formations_msg_leave_success' => 'Vous n\'êtes plus un fan de cette formation',
  '_modzzz_formations_form_caption_join_confirmation' => 'Confirmation',
  '_modzzz_formations_form_info_join_confirmation' => 'Si c\'est activée, vous devez confirmer chaque utilisateur avant qu\'il / elle devienne un fan.',
  '_modzzz_formations_form_join_confirmation_disabled' => 'Désactivé',
  '_modzzz_formations_form_join_confirmation_enabled' => 'Activé',
  '_modzzz_formations_form_err_join_confirmation' => 'Le champ de confirmation d\'inscription doit être 0 ou 1',
  '_modzzz_formations_action_title_join' => 'Devenir Fan',
  '_modzzz_formations_action_title_leave' => 'Annuler "Fan"',
  '_modzzz_formations_privacy_join' => 'Qui peut devenir Fan de cette annonce?',
  '_modzzz_formations_page_title_applications_by_author' => 'Formations {0} applied for',
  '_modzzz_formations_action_title_apply' => '<strong>Postuler</strong>',
  '_modzzz_formations_page_title_apply' => 'POSTULER',
  '_modzzz_formations_msg_application_sent' => 'Votre candidature a été envoyée',
  '_modzzz_formations_upwards' => 'ou plus',
  '_modzzz_formations_block_skills' => '<i class="sys-icon user"></i> Profil recherché ',
   '_modzzz_formations_form_caption_admission' => ' <i class="sys-icon users"></i> Conditions d\'admission',
  '_modzzz_formations_role' => 'Date de début',
   '_modzzz_formations_form_caption_role_view' => 'Date de début de la formation ',
  
  '_modzzz_formations_experience' => 'Niveau d\'expérience',
  '_modzzz_formations_qualification' => 'Niveau d\'études',
  '_modzzz_formations_salary' => 'Salaire',
  '_modzzz_formations_company' => 'Entreprise',
  '_modzzz_formations_vacancies' => 'postes disponibles',
  '_modzzz_formations_category' => 'Catégorie ',
  '_modzzz_formations_permanent' => 'Contrat à  durée indéterminée',
  '_modzzz_formations_intern' => 'Intérim',
  '_modzzz_formations_temporary' => 'Contrat à  durée déterminée',
  '_modzzz_formations_part_time' => 'Temps Partiel',
  '_modzzz_formations_full_time' => 'Temps Plein',
  '_modzzz_formations_form_caption_role' => '<span style="color:#3B5999;"><span style="font-size:12px;">Date de début</span></span>
',
  '_modzzz_formations_form_caption_vacancies' => 'Nombre de postes disponibles 
',
  '_modzzz_formations_form_caption_experience' => 'Expérience',
  '_modzzz_formations_form_caption_qualification' => 'Niveau d\'études
',
  '_modzzz_formations_form_caption_skills' => '<i class="sys-icon user"></i> Profil recherché
',
  '_modzzz_formations_form_caption_min_salary' => 'Salaire minimum',
  '_modzzz_formations_form_caption_max_salary' => 'Salaire Maximum',
  '_modzzz_formations_form_caption_currency' => 'Devise salaire',
  '_modzzz_formations_form_caption_salary_type' => 'Type de salaire',
  '_modzzz_formations_form_caption_career_level' => 'Niveau hiérarchique',
  '_modzzz_formations_form_caption_formation_type' => 'Type de contrat',
  '_modzzz_formations_form_caption_formation_status' => 'Statut du poste',
  '_modzzz_formations_no_preference' => 'Aucune préférence',
  '_modzzz_formations_fresher' => 'Débutant',
  '_modzzz_formations_less_than_1_year' => 'Moins d\'une année',
  '_modzzz_formations_1_to_2_years' => '1 à  2 ans',
  '_modzzz_formations_2_to_5_years' => '2 à  5 ans',
  '_modzzz_formations_5_to_7_years' => '5 à  7 ans',
  '_modzzz_formations_7_to_10_years' => '7 à  10 ans',
  '_modzzz_formations_10_to_15_years' => '10 à  15 ans',
  '_modzzz_formations_more_than_15_years' => 'Plus de 15 ans',
  '_modzzz_formations_high_school' => '< BAC',
  '_modzzz_formations_certification' => 'BEP / CAP',
  '_modzzz_formations_vocational' => 'BAC',
  '_modzzz_formations_tertiary_education' => 'BAC +1',
  '_modzzz_formations_associates_degree' => 'BAC +2',
  '_modzzz_formations_bachelors' => 'BAC +3',
  '_modzzz_formations_masters' => 'BAC +4',
  '_modzzz_formations_doctorate' => 'BAC +5',
  '_modzzz_formations_professional_engineering' => 'BAC +6',
  '_modzzz_formations_student_college' => 'Stagiaire ',
  '_modzzz_formations_student_high_school' => 'Première formation',
  '_modzzz_formations_entry_level' => 'Confirmé',
  '_modzzz_formations_mid_career' => 'Manager',
  '_modzzz_formations_management' => 'Directeur',
  '_modzzz_formations_executive' => 'Président / DG',
  '_modzzz_formations_senior_executive' => 'Dirigeant/Entrepreneur',
  '_modzzz_formations_per_year' => 'par an',
  '_modzzz_formations_per_month' => 'par mois',
  '_modzzz_formations_per_week' => 'par semaine',
  '_modzzz_formations_fortnightly' => 'Tous les quinze jours',
  '_modzzz_formations_per_hour' => 'par heure',
  '_modzzz_formations_form_caption_business_type' => 'Type d\'entreprise',
  '_modzzz_formations_form_caption_employee_count' => '<span style="color:#3B5999;"><span style="font-size:12px;">Nombre d\'employés</span></span>
',
  '_modzzz_formations_form_caption_office_count' => '
<span style="color:#3B5999;"><span style="font-size:12px;">Nbre de Bureau/Branches</span></span>',
  '_modzzz_formations_caption_state' => 'Région',
  '_modzzz_formations_block_formations_states' => '<i class="sys-icon sliders"></i> Régions',
  '_modzzz_formations_regions_for_country' => 'Régions ',
  '_modzzz_formations_block_browse_state' => '<i class="sys-icon map-marker"></i> Formationss dans la région',
  '_modzzz_formations_block_browse_state_formations' => '<i class="sys-icon map-marker"></i> Formationss  dans la région',
  '_modzzz_formations_block_account' => 'Les Formationss dans ma ville',
  '_modzzz_formations_block_browse_country' => 'Parcourir par pays',
  '_modzzz_formations_page_title_local' => 'Parcourir par Formationss locales',
  '_modzzz_formations_caption_browse_local' => 'Parcourir des formations dans {0}',
  '_modzzz_formations_menu_local' => 'Formationss dans ma ville',
  '_modzzz_formations_block_local' => '<i class="sys-icon map"></i> Offres  près de chez moi',
  '_modzzz_formations_block_other' => '<i class="sys-icon building"></i> Autres offres de cette Entreprise',
  '_modzzz_formations_caption_browse_other' => 'Autres Formationss par {0}',
  '_modzzz_formations_block_local_formations' => 'Formationss locales',
  '_modzzz_formations_block_formations' => '<i class="sys-icon building"></i> Offres de formation ',
  '_modzzz_formations_block_stats' => 'Infos clés',
  '_modzzz_formations_block_formations_categories' => '<i class="sys-icon suitcase"></i> Secteurs d\'activité',
  '_modzzz_formations_block_category_formations' => '<i class="sys-icon black-tie"></i>  Offres de formation dans cette catégorie ',
  '_modzzz_formations_block_subcategories' => 'Sous-catégorie ',
  '_modzzz_formations_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button',
  '_modzzz_formations_categ_name' => 'Catégorie ',
  '_modzzz_formations_categ_btn_edit' => 'Modifier',
  '_modzzz_formations_categ_btn_delete' => 'Supprimer',
  '_modzzz_formations_categ_btn_add' => 'Ajouter',
  '_modzzz_formations_categ_btn_save' => 'Enregistrer',
  '_modzzz_formations_categ_btn_subcategories' => 'Sous-Catégories ',
  '_modzzz_formations_categories' => '<i class="sys-icon suitcase"></i> Secteurs d\'activité',
  '_modzzz_formations_menu_admin_manage_categories' => 'Catégories',
  '_modzzz_formations_menu_admin_manage_subcategories' => 'Sous-Catégories',
  '_modzzz_formations_subcategories' => 'Sous-catégorie ',
  '_modzzz_formations_form_caption_parent_category' => 'Secteur d\'activité',
  '_modzzz_formations_all_categories' => 'Voir tous les secteurs d\'activités',
  '_modzzz_formations_block_categories' => '<i class="sys-icon suitcase"></i> Secteurs d\'activité',
  '_modzzz_formations_block_formations_subcategories' => 'Sous-Catégories ',
  '_modzzz_formations_block_answer_categories' => '<i class="sys-icon suitcase"></i> Secteurs d\'activité',
  '_modzzz_formations_menu_categories' => 'Secteur d\'activité',
  '_modzzz_formations_page_title_browse_by_category' => 'Parcourir les formations par catégorie:',
  '_modzzz_formations_form_caption_category' => 'Catégorie ',
  '_modzzz_formations_form_err_category' => 'Ce champ est obligatoire.<br>Veuillez sélectionner un secteur d\'activité',
  '_modzzz_formations_page_title_category' => 'Catégorie ',
  '_modzzz_formations_page_title_categories' => 'Offres par secteur d\'activité <i class="sys-icon suitcase"></i>',
  '_modzzz_formations_page_title_subcategories' => 'Formationss | Sous-Catégories ',
  '_modzzz_formations_formations_in_category' => '<b>Formationss</b> dans <b>%s</b>',
  '_modzzz_formations_posted_on' => 'Publié ',
  '_modzzz_formations_listed_by' => 'Offre déposée par:',
  '_modzzz_formations_company_page_title_browse_featured' => 'Recruteurs à la une',
  '_modzzz_formations_posted' => 'Publié',
  '_modzzz_formations_formations_posted' => 'Formationss publiées ',
  '_modzzz_formations_block_today_formation' => '<i class="sys-icon trophy"></i> Offre du Jour',
  '_modzzz_formations_block_featured_formations' => ' <i class="sys-icon briefcase "></i> Offres de formation à  la Une',

  '_modzzz_formations_block_featured_wanted_formations' => ' <i class="sys-icon puzzle-piece"></i> Stages à  la Une',
  '_modzzz_formations_block_featured_companies' => 'Recruteurs à la une',
  '_modzzz_formations_menu_companies' => '<i class="sys-icon home"> </i> Entreprises qui recrutent  ',
  '_modzzz_formations_present_icon' => 'Logo actuel',
  '_modzzz_formations_form_header_company_edit' => '<span style="color:#26012B;"><span style="font-size:16px;"><strong>Modifier les détails de l\'entreprise</strong></span></span>
',
  '_modzzz_formations_form_header_select_company' => '<span style="font-size:14px;"><strong>Associer votre "Page Entreprise" à  votre annonce  pour Booster votre image </strong></span>

',
  '_modzzz_formations_form_header_company' => 'Détails sur la société (facultatif) - Choisissez parmi les entreprises existantes ci-dessus ou en ajouter un nouvelle ci-dessous',
  '_modzzz_formations_form_icon' => '<span style="color:#3B5999;"><span style="font-size:14px;"><strong>Logo de \'entreprise</strong></span></span>
',
  '_modzzz_formations_select_company' => '-- sélectionner votre entreprise---',
  '_modzzz_formations_select_no_company' => '- Aucune société n\'a  encore été ajoutée  ---',
  '_modzzz_formations_form_caption_address' => 'Adresse
',
  '_modzzz_formations_form_caption_company' => '<i class="sys-icon building"></i> Votre entreprise
',
  '_modzzz_formations_form_caption_website' => '<span style="color:#3B5999;"><span style="font-size:12px;">Site Internet</span></span>
',
  '_modzzz_formations_form_info_company' => 'Société ou Organisation publiant l\'offre de formation',
  '_modzzz_formations_caption_country' => 'Pays',
  '_modzzz_formations_caption_name' => 'Nom',
  '_modzzz_formations_form_caption_email' => '<span style="color:#3B5999;"><span style="font-size:12px;">Email</span></span>
',
  '_modzzz_formations_form_caption_telephone' => '<span style="color:#3B5999;"><span style="font-size:12px;">Téléphone</span></span>
',
  '_modzzz_formations_form_caption_fax' => '<span style="color:#3B5999;"><span style="font-size:12px;">Fax</span></span>',
  '_modzzz_formations_form_caption_name' => '<span style="color:#3B5999;"><span style="font-size:12px;">Nom de l\'Entreprise</span></span>
',
  '_sbs_txt_title_modzzz_formations' => 'Formationss',
  '_modzzz_formation_s' => 'Offres de formation',
  '_modzzz_formations_add' => 'ajouter',
  '_modzzz_formations_wall_added_new' => 'a publié une',
  '_modzzz_formations_wall_object' => 'offre de formation',
  '_modzzz_formations_for_formation' => 'pour %s',
  '_modzzz_formations_formation_single' => 'Offre de formation',
  '_modzzz_formations_formation_plural' => 'Offres de formation',
  '_modzzz_formations_user_unknown' => 'Quelqu\'un',
  '_modzzz_formations_spy_post' => '<a href="{profile_link}">{profile_nick}</a> a ajouté une offre de formation:  <a href="{entry_url}">{entry_title}</a>',
  '_modzzz_formations_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> a modifié l\'offre de formation:  <a href="{entry_url}">{entry_title}</a>',
  '_modzzz_formations_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> a evalué l\'offre de formation <a href="{entry_url}">{entry_title}</a>',
  '_modzzz_formations_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> a commenté sur l\'offre de formation: <a href="{entry_url}">{entry_title}</a>',
  '_modzzz_formations_sbs_change' => 'L\'informations a été mise à  jour',
  '_modzzz_formations_sbs_comment' => 'il y a un nouveau commentaire',
  '_modzzz_formations_sbs_rate' => 'L\'évaluation a été mise à  jour',
  '_modzzz_formations_tab_featured' => 'Formationss à  la une',
  '_modzzz_formations_tab_recent' => 'Récent',
  '_modzzz_formations_tab_top' => 'Top',
  '_modzzz_formations_tab_popular' => 'Populaire',
  '_modzzz_formations_block_submenu_main' => 'Mes offres de formation ',
  '_modzzz_formations_block_submenu_add_formation' => 'Déposer une offre',
  '_modzzz_formations_block_submenu_manage_formations' => 'Gérer offres de formation',
  '_modzzz_formations_block_submenu_pending_formations' => 'En attente d\'approbation',
  '_modzzz_formations_block_actions' => 'Actions',
  '_modzzz_formations_block_rate' => 'Evaluer',
  '_modzzz_formations_block_info' => 'Offre de formation publiée par:',
  '_modzzz_formations_block_desc' => '<i class="sys-icon briefcase"></i> Description du poste',
  '_modzzz_formations_block_photo' => '--',
  '_modzzz_formations_block_video' => 'Vidéos',
  '_modzzz_formations_block_sound' => 'Sons/musiques',
  '_modzzz_formations_block_files' => 'Documents téléchargeables ',
  '_modzzz_formations_block_file' => 'Fichiers',
  '_modzzz_formations_block_comments' => 'Commentaires',
  '_modzzz_formations_block_latest_featured_formation' => 'Offres de formation à  la une',
  '_modzzz_formations_block_recent' => ' <i class="sys-icon briefcase "></i> Offres de formation récentes ',
  '_modzzz_formations_block_administration_owner' => '<i class="sys-icon black-tie"></i>  Administration ',
  '_modzzz_formations_block_users_formations' => 'Mes offres ',
  '_modzzz_formations_block_my_formations' => 'Des Formationss que J\'ai postées',
  '_modzzz_formations_block_search_formations' => 'Rechercher des Formationss',
  '_modzzz_formations_block_homepage' => 'Formation',
  '_modzzz_formations_block_location' => 'Adresse',
  '_modzzz_formations_caption_add' => 'Ajouter une formation',
  '_modzzz_formations_caption_share_formation' => 'Cliquer sur une icône pour partager l\'offre',
  '_modzzz_formations_caption_share_company' => 'Partager la Société',
  '_modzzz_formations_caption_admin_actions' => 'Liens',
  '_modzzz_formations_caption_pending_approval' => 'Formations en attente d\'approbation',
  '_modzzz_formations_menu_root' => '<i class="sys-icon black-tie"></i>  Formation',
  '_modzzz_formations_menu_main' => ' <i class="sys-icon home"></i>  Offres de formation',
  '_modzzz_formations_menu_recent' => '<i class="sys-icon suitcase"> </i> Formation',
  '_modzzz_formations_menu_top_rated' => 'Top noté',
  '_modzzz_formations_menu_popular' => 'Populaire',
  '_modzzz_formations_menu_featured' => 'Offres à  la une',
  '_modzzz_formations_menu_wanted' => '<i class="sys-icon building"> </i> Stages',
  '_modzzz_formations_menu_tags' => 'Tags',
  '_modzzz_formations_menu_calendar' => 'Calendrier',
  '_modzzz_formations_menu_search' => '<i class="sys-icon search"> </i> Rechercher une offre',
  '_modzzz_formations_menu_view_formation' => 'Offre de formation',
  '_modzzz_formations_menu_view_forum' => 'Forum',
  '_modzzz_formations_menu_view_applications' => 'Voir les candidatures',
  '_modzzz_formations_menu_view_comments' => 'Commentaires',
  '_modzzz_formations_menu_view_photos' => 'Photos',
  '_modzzz_formations_menu_view_videos' => 'Vidéos',
  '_modzzz_formations_menu_view_sounds' => 'Sons/Musiques',
  '_modzzz_formations_menu_view_files' => 'Fichiers',
  '_modzzz_formations_menu_my_formations_profile' => '<i class="sys-icon building"></i> Mes Offres de Formation',
  '_modzzz_formations_menu_admin_pending_approval' => 'En attente d\'approbation',
  '_modzzz_formations_menu_admin_entries' => 'Admin Formationss',
  '_modzzz_formations_menu_admin_add_entry' => 'Ajoute une Formations',
  '_modzzz_formations_menu_admin_settings' => 'Settings',
  '_modzzz_formations_page_title_home' => 'Offres de formation',
  '_modzzz_formations_page_title_calendar' => 'Calendrier Formationss',
  '_modzzz_formations_page_title_comments' => 'Commentaires',
  '_modzzz_formations_page_title_photos' => 'Photos',
  '_modzzz_formations_page_title_videos' => 'Videos',
  '_modzzz_formations_page_title_sounds' => 'Sons/Musiques',
  '_modzzz_formations_page_title_files' => 'Fichiers',
  '_modzzz_formations_page_title_applications' => 'Candidats à  votre offre ',
  '_modzzz_formations_page_title_my_formations' => 'Mes offres de formation',
  '_modzzz_formations_page_title_search' => 'Recherche des Formationss',
  '_modzzz_formations_page_title_add' => 'Ajouter une formation',
  '_modzzz_formations_page_title_edit' => 'Modifier la Formations',
  '_modzzz_formations_page_company_title_edit' => 'Modifier la Société',
  '_modzzz_formations_page_title_administration' => 'Administration',
  '_modzzz_formations_page_title_browse' => 'Parcourir des Formationss',
  '_modzzz_formations_company_page_title_browse' => 'Parcourir des Sociétés',
  '_modzzz_formations_applicants_page_title_broadcast' => 'Envoyer un message à  tous les candidats ayant postulé à votre offre de formation',
  '_modzzz_formations_applicants_msg_broadcast_message_sent' => 'Le message a été envoyé',
  '_modzzz_formations_applicants_msg_broadcast_no_recipients' => 'Il n\'y a pas encore de  candidats pour ce poste ',
  '_modzzz_formations_page_title_pending_approval' => 'Formationss en attente d\'approbation',
  '_modzzz_formations_page_title_search_results' => 'Résultats de recherche de formations',
  '_modzzz_formations_page_title_browse_by_author' => '\'s formation',
  '_modzzz_formations_page_title_admin_formations' => 'Admin Formationss',
  '_modzzz_formations_page_title_browse_by_tag' => 'Parcourir des formations par Tag:',
  '_modzzz_formations_page_title_browse_recent' => 'Offres de formation récentes | <i class="sys-icon suitcase"> </i>',
  '_modzzz_formations_page_title_browse_seeking' => ' Stages | <i class="sys-icon building"> </i>',
  '_modzzz_formations_page_title_browse_top_rated' => 'Formationss les plus notées',
  '_modzzz_formations_page_title_browse_popular' => 'Formationss Populaires',
  '_modzzz_formations_page_title_browse_featured' => 'Offres de formation à  la une',
  '_modzzz_formations_page_title_browse_featured_wanted' => 'CV en vedette',
  '_modzzz_formations_page_title_browse_by_day' => 'Parcourir des Formationss par date',
  '_modzzz_formations_page_title_tags' => 'Tags des Formationss',
  '_modzzz_formations_page_title_broadcast' => 'Envoyer un message ',
  '_modzzz_formations_page_company_title_broadcast' => 'Envoyer un message ',
  '_modzzz_formations_page_title_upload_photos' => 'Ajouter des photos',
  '_modzzz_formations_page_title_upload_videos' => 'Ajouter des videos',
  '_modzzz_formations_page_title_upload_sounds' => 'Ajouter des sons',
  '_modzzz_formations_page_title_upload_files' => 'Ajouter des fichiers',
  '_modzzz_formations_page_title_invite' => 'Invitez vos contacts à  consulter cette offre de formation >> ',
  '_modzzz_formations_page_company_title_invite' => 'Inviter vos contacts - ',
  '_modzzz_formations_msg_pending_approval' => '<span style="color:#fff;"><span style="font-size:16px;"><strong>Cette offre de formation est en attente de validation.
<br>Veuillez prendre contact avec notre équipe pour procéder au paiement et être informé de notre Package Recrutement.
<br>Une fois le paiement effectué, votre offre de formation sera activée et mise en ligne.
<br>Tél / WhatsApp : +44 75 000 18 698</strong></span></span>',
  '_modzzz_formations_msg_formation_was_deleted' => 'la formation a été annulé',
  '_modzzz_formations_company_msg_formation_was_deleted' => 'La société a été supprimée',
  '_modzzz_formations_msg_removed_from_featured' => 'L\'offre n\'est plus à  la une',
  '_modzzz_formations_msg_added_to_featured' => 'L\'offre a été mise à  la une',
  '_modzzz_formations_msg_removed_from_today' => 'L\'annonce a été retirée de la liste de formation du jour',
  '_modzzz_formations_msg_added_to_today' => 'L\'annonce a été choisie comme Formations du jour',
  '_modzzz_formations_company_msg_removed_from_featured' => 'La société n\'est plus à  la une',
  '_modzzz_formations_company_msg_added_to_featured' => 'La société a été mise à  la une',
  '_modzzz_formations_msg_photo_is_pending_approval' => 'La photo est en attente d\'approbation',
  '_modzzz_formations_msg_you_have_pending_approval_formations' => '<span style="font-size:16px; text-align: left;"><strong><a href="%s">Vous avez %d offre(s) de formation  en attente d\'approbation</a></strong>
<BR>Veuillez prendre contact avec notre équipe pour procéder au paiement et être informé de notre Package Recrutement. 
<br>Une fois le paiement effectué, votre offre de formation sera activée et mise en ligne. 
<br><strong>Tél / WhatsApp  : <i class="sys-icon phone"></i> +44 75 000 18 
698</strong></span>',
  '_modzzz_formations_msg_you_have_no_formations' => '<i class="sys-icon briefcase"></i> Vous n\'avez publié aucune offre de formation . 
<br><a href="%s"><i class="sys-icon plus-square"></i> Cliquer ici pour en publier une <i class="sys-icon hand-o-left"></i></a>.',
  '_modzzz_formations_msg_you_have_some_formations' => '<div  style="text-align: center;"><span style="color:#3b5998;"><span style="font-size:16px;"> 
 <a href="%s"><i class="sys-icon black-tie"></i> Vous avez publié %d offre(s) de formation </a> 
 </span></span>. 
 </div>
 
<div> 
<button class="ConnectNetwork_MarginTop"  onclick="window.open (\'m/formations/browse/my&filter=add_formation\',\'_self\');">
			<i class="sys-icon plus-square">  </i> Publier une autre offre de formation   <i class="sys-icon hand-o-left"></i>
		</button>  
 </div>

        
<div><button class="ConnectNetwork_MarginTop"  onclick="window.open (\'m/formations/browse/my&filter=manage_formations\',\'_self\');">
			<i class="sys-icon remove">  </i> Supprimer une offre de formation   <i class="sys-icon hand-o-left"></i>
		</button>  
</div>',
  '_modzzz_formations_msg_broadcast_message_sent' => 'Le message groupé  a été envoyée à  tous les fans de votre offre de formation.',
  '_modzzz_formations_msg_broadcast_no_recipients' => 'Il n\'y a pas encore de fan pour cette formation',
  '_modzzz_formations_msg_invitation_sent' => '%d invitations ont été envoyées',
  '_modzzz_formations_msg_no_users_to_invite' => 'Il n\'y a pas d\'utilisateurs dans vos contacts',
  '_modzzz_formations_company_msg_broadcast_no_recipients' => 'Il n\'y a aucun fan pour les Formationss publiées par cette société',
  '_modzzz_formations_admin_delete' => 'Supprimer',
  '_modzzz_formations_admin_activate' => 'Activer',
  '_modzzz_formations_admin_add_new_formation' => 'Publier une Formations',
  '_modzzz_formations_admin_formations' => 'Formationss administrateur',
  '_modzzz_formations_admin_settings' => 'Paramètres administrateur',
  '_modzzz_formations_form_header_info' => '<span style="font-size:20px;"><strong>Publier une offre de formation </strong></span>
<br><span style="font-size:12px;"> [<span style="color:red;">*</span>]  Champs obligatoires

| <span style="font-size:16px;"> <i class="sys-icon info-circle"></i> </span>  info supplémentaires </span>
',
  '_modzzz_formations_form_header_images' => '<strong><i class="sys-icon camera"></i> Ajouter photos </strong>',
  '_modzzz_formations_form_header_videos' => 'Vidéos',
  '_modzzz_formations_form_header_sounds' => 'Sons',
  '_modzzz_formations_form_header_files' => '<span style="color:#26012B;"><span style="font-size:16px;"><strong>Joindre un document / fichier à  votre offre</strong>(ex: Brochure, Prospectus etc.. )</span></span>
',
  '_modzzz_formations_form_header_privacy' => '<span style="font-size:18px;"><strong><i class="sys-icon lock"></i> Paramètres de confidentialité</strong></span>',
  '_modzzz_formations_form_caption_title' => '<strong><i class="sys-icon user"></i> Titre du poste</strong>',
  '_modzzz_formations_form_err_title' => 'Veuillez indiquer le titre du poste à  pourvoir. 100 caractères maximum ',
  '_modzzz_formations_form_caption_desc' => '<strong><i class="sys-icon sliders"></i> Description du poste</strong>',
  '_modzzz_formations_form_err_desc' => 'Veuillez décrire votre offre. Entrez au minimum 20 caractères',
  '_modzzz_formations_form_err_tags' => 'Veuillez entrer des tags',
  '_modzzz_formations_form_caption_author_id' => 'Auteur',
  '_modzzz_formations_form_info_author' => 'Numéro identifiant du profile d\'auteur',
  '_modzzz_formations_form_caption_keyword' => 'Mot clé',
  '_modzzz_formations_form_err_keyword' => 'Veuillez entrer 3 à  100 caractères ',
  '_modzzz_formations_form_caption_images_choice' => 'Choisir',
  '_modzzz_formations_form_info_images_choice' => 'Décocher pour supprimer l\'image de votre annonce ',
  '_modzzz_formations_form_caption_images_upload' => '<br><i class="sys-icon camera"></i> Ajouter des photos
',
  '_modzzz_formations_form_info_images_upload' => 'Vous pouvez ajouter plusieurs photos en cliquant sur le signe plus (+)',
  '_modzzz_formations_form_caption_videos_choice' => 'Choisir',
  '_modzzz_formations_form_info_videos_choice' => 'Vous pouvez choisir plusieurs vidéos ',
  '_modzzz_formations_form_caption_videos_upload' => 'Transférer',
  '_modzzz_formations_form_info_videos_upload' => 'La vidéo sera automatiquement placée dans le  catégorie "Formationss"  ',
  '_modzzz_formations_form_caption_sounds_choice' => 'Choisir',
  '_modzzz_formations_form_info_sounds_choice' => 'Vous pouvez choisir plusieurs sons ',
  '_modzzz_formations_form_caption_sounds_upload' => 'Transférer',
  '_modzzz_formations_form_info_sounds_upload' => 'Le son sera placé automatiquement dans la catégorie "Formationss"',
  '_modzzz_formations_form_caption_files_choice' => 'Choisir',
  '_modzzz_formations_form_info_files_choice' => 'Décochez la case pour supprimer le fichier de cette annonce',
  '_modzzz_formations_form_caption_files_upload' => '<span style="color:#26012B;"><span style="font-size:12px;"><strong>Télécharger</strong></span></span>
',
  '_modzzz_formations_form_info_files_upload' => 'Le fichier sera placé v dans la catégorie  "Formationss" et défini comme privé ',
  '_modzzz_formations_form_caption_file_title' => 'Titre:',
  '_modzzz_formations_form_caption_file_price' => 'Prix:',
  '_modzzz_formations_form_caption_file_allow_purcase_to' => 'Autoriser l\'achat ',
  '_modzzz_formations_form_caption_thumb_choice' => 'Choisir la vignette',
  '_modzzz_formations_form_info_thumb_choice' => 'Choisir l\'une des vignettes comme visuel principal de votre annonce',
  '_modzzz_formations_form_caption_broadcast_title' => 'Titre du message',
  '_modzzz_formations_form_err_broadcast_title' => 'Veuillez entrer 3 à  100 caractères ',
  '_modzzz_formations_form_caption_broadcast_message' => 'Contenu de votre message',
  '_modzzz_formations_form_err_broadcast_message' => 'Veuillez entrer au moins 10 caractères',
  '_modzzz_formations_form_caption_country' => 'Pays',
  '_modzzz_formations_form_err_country' => 'Pays est un champ obligatoire',
  '_modzzz_formations_form_caption_city' => 'Ville
',
  '_modzzz_formations_form_err_city' => 'Veuillez entrer le nom de la ville du lieu de travail',
  '_modzzz_formations_form_caption_zip' => 'Code Postal',
  '_modzzz_formations_form_err_zip' => 'Veuillez entrer le code postal du lieu de travail',
  '_modzzz_formations_action_title_edit' => 'Modifier',
  '_modzzz_formations_action_title_delete' => 'Supprimer',
  '_modzzz_formations_action_title_share' => 'Partager',
  '_modzzz_formations_action_title_broadcast' => 'Ecrire aux Fans',
  '_modzzz_formations_action_title_broadcast_applicants' => 'Ecrire aux candidats',
  '_modzzz_formations_action_title_invite' => 'Inviter',
  '_modzzz_formations_action_add_to_featured' => 'Mettre à  la une',
  '_modzzz_formations_action_remove_from_featured' => 'N\'est plus à  l\'honneur',
  '_modzzz_formations_action_add_to_today' => 'Offre du jour',
  '_modzzz_formations_action_remove_from_today' => 'Retirer du jour',
  '_modzzz_formations_action_add_formation' => 'Déposer une offre de formation ',
  '_modzzz_formations_action_my_formations' => 'Mes offres de formation ',
  '_modzzz_formations_action_upload_photos' => '<i class="sys-icon plus-square"></i> Photos',
  '_modzzz_formations_action_upload_videos' => '+++ Vidéos',
  '_modzzz_formations_action_upload_sounds' => 'Ajouter des sons',
  '_modzzz_formations_action_upload_files' => '<i class="sys-icon plus-square "></i> Documents',
  '_modzzz_formations_action_formations_home' => 'Accueil Formations',
  '_modzzz_formations_privacy_view_formation' => 'Qui peut consulter cette annonce?',
  '_modzzz_formations_privacy_comment' => 'Qui peut commenter sur cette offre?',
  '_modzzz_formations_privacy_rate' => 'Qui peut évaluer votre offre de formation?',
  '_modzzz_formations_privacy_upload_photos' => 'Qui peut transférer des photos?',
  '_modzzz_formations_privacy_upload_videos' => 'Qui peut transférer des vidéos?',
  '_modzzz_formations_privacy_upload_sounds' => 'Qui peut transférer des sons?',
  '_modzzz_formations_privacy_upload_files' => 'Qui peut transférer des fichiers?',
  '_modzzz_formations_privacy_edit_formation' => 'Modifier la formation',
  '_modzzz_formations_privacy_post_in_forum' => 'Qui peut poster dans le forum?',
  '_modzzz_formations_privacy_admins_only' => 'Moi uniquement',
  '_mma_formations_photos_add' => 'Ajouter un Logo',
  '_modzzz_formations_packages_empty' => 'Il n\'y a aucun forfait Formation',
  '_modzzz_formations_package_description' => 'Description',
  '_modzzz_formations_package_featured' => 'Mettre à la une une offre de formation',
  '_modzzz_formations_featured_status' => 'Formations à  la une',
  '_modzzz_formations_featured_until' => 'A la une  jusqu\'au',
  '_modzzz_formations_not_featured' => 'Cette formation n\'est pas à la Une',
  '_modzzz_formations_extend_featured' => 'Remettre à  la une',
  '_modzzz_formations_purchase_featured' => 'Acheter l\'option "Mettre à la une " pour  votre annonce de formation',
  '_modzzz_formations_menu_packages' => 'Forfaits',
  '_modzzz_formations_page_title_packages' => 'Forfaits Annonce de Formation',
  '_modzzz_formations_block_packages' => 'Forfaits Publication d\'une Formation',
  '_modzzz_formations_on' => 'sur',
  '_modzzz_formations_yes' => 'oui',
  '_modzzz_formations_no' => 'non',
  '_modzzz_formations_package_videos' => 'Videos',
  '_modzzz_formations_package_photos' => 'Photos',
  '_modzzz_formations_package_sounds' => 'Sons/Musiques',
  '_modzzz_formations_package_files' => 'Fichiers',
  '_modzzz_formations_action_title_purchase_featured' => 'Mettre à la une',
  '_modzzz_formations_action_title_extend_featured' => 'Remettre à la une',
  '_modzzz_formations_purchase_featured_status' => 'Mettre à la une',
  '_modzzz_formations_quantity' => 'Quantité',
  '_modzzz_formations_purchase_success' => 'Merci! Le paiement a été un succès. Cliquer <a href="{0}">ici</a> pour voir la publication de votre annonce de formation',
  '_modzzz_formations_purchase_fail' => 'Votre tentative d\'achat de l\'option "Mettre à la une" a échoué',
  '_modzzz_formations_transaction_completed_already' => 'La transaction existe déjà . Cliquer <a href="{0}">ici</a> pour voir l\'annonce de formation',
  '_modzzz_formations_featured_cost_per_day' => 'Coût par Jour',
  '_modzzz_formations_caption_num_featured_days' => 'Nombre des Jours pour la  mise à la une',
  '_modzzz_formations_caption_err_featured_days' => 'Vous devez entrer le nombre de jours ',
  '_modzzz_formations_get_featured' => 'Mettre à la Une',
  '_modzzz_formations_packages' => 'Forfaits',
  '_modzzz_formations_package_name' => 'Nom du Forfait',
  '_modzzz_formations_package_price' => 'Prix du Forfait',
  '_modzzz_formations_package_days' => 'Jours de Forfait',
  '_modzzz_formations_form_caption_package' => '<i class="sys-icon black-tie"></i>',
  '_modzzz_formations_form_err_package' => 'Veuillez sélectionner le forfait',
  '_modzzz_formations_purchaser' => 'Acheteur',
  '_modzzz_formations_invoice_no' => 'Facture #',
  '_modzzz_formations_package' => 'Forfait',
  '_modzzz_formations_invoice_date' => 'Date de la Facture',
  '_modzzz_formations_invoice_due_date' => 'Date d\'échéance',
  '_modzzz_formations_status' => 'Statut',
  '_modzzz_formations_pending' => 'En attente',
  '_modzzz_formations_paid' => 'Payé',
  '_modzzz_formations_active' => 'Actif',
  '_modzzz_formations_inactive' => 'Inactif',
  '_modzzz_formations_approved' => 'Approuvé',
  '_modzzz_formations_expired' => 'Expiré',
  '_modzzz_formations_block_submenu_pending_invoices' => 'Commandes en attente',
  '_modzzz_formations_block_submenu_orders' => 'Commandes',
  '_modzzz_formations_page_title_orders' => 'Commandes',
  '_modzzz_formations_page_title_invoices' => 'Factures',
  '_modzzz_formations_menu_manage_invoices' => 'Factures',
  '_modzzz_formations_menu_manage_packages' => 'Forfaits',
  '_modzzz_formations_menu_manage_orders' => 'Commandes',
  '_modzzz_formations_payment_method' => 'Mode de paiement',
  '_modzzz_formations_total' => 'Total',
  '_modzzz_formations_invoice_id' => 'Identifiant de la facture',
  '_modzzz_formations_next_due_date' => 'Prochaine date d\'échéance',
  '_modzzz_formations_order_no' => 'Commande #',
  '_modzzz_formations_product_status' => 'Statut du Produit',
  '_modzzz_formations_order_date' => 'Date de commande',
  '_modzzz_formations_purchase_failed' => 'Désolé, il n\'y a un problème avec le paiement.  Voir vos commandes en attente <a href="{0}">ici</a>.',
  '_modzzz_formations_trans_save_failed' => 'Le paiement a été un succès mais il y avait un problème sauvegarde de la transaction. Veuillez contacter l\'administrateur avec vos détails de la transaction Paypal afin qu\'ils puissent traiter manuellement votre commande.',
  '_modzzz_formations_post_purchase_header' => 'Achat de la Publication d\'annonce de formation',
  '_modzzz_formations_block_map' => 'Carte',
  '_modzzz_formations_week_sun' => 'Dim',
  '_modzzz_formations_week_mon' => 'Lu',
  '_modzzz_formations_week_tue' => 'Mar',
  '_modzzz_formations_week_wed' => 'Mer',
  '_modzzz_formations_week_thu' => 'Jeu',
  '_modzzz_formations_week_fri' => 'Ven',
  '_modzzz_formations_week_sat' => 'Sam',
  '_modzzz_formations_continue' => 'Continuer',
  '_modzzz_formations_action_title_premium' => 'Option Premium',
  '_modzzz_formations_page_title_premium' => 'Option Premium pour la visibilité de votre annonce',
  '_modzzz_formations_action_title_extend' => 'Prolonger',
  '_modzzz_formations_page_title_extend' => 'Prolonger l\'annonce',
  '_modzzz_formations_action_title_relist' => 'Republier',
  '_modzzz_formations_page_title_relist' => 'Re-publier votre annonce de formation',
  '_modzzz_formations_form_caption_current_no_package' => 'Aucun Forfait actuellement',
  '_modzzz_formations_form_caption_current_package' => 'Forfait actuel',
  '_modzzz_formations_form_caption_package_price' => 'Prix du Forfait',
  '_modzzz_formations_form_caption_package_days' => 'Durée de l\'annonce',
  '_modzzz_formations_expires_never' => 'illimité (n\'expire jamais)',
  '_modzzz_formations_days' => 'jours',
  '_modzzz_formations_form_caption_current_item' => 'Annonce de formation',
  '_modzzz_formations_extend' => 'Prolonger',
  '_modzzz_formations_block_statistics' => 'Statistiques',
  '_modzzz_formations_block_price' => 'Prix',
  '_modzzz_formations_block_share' => 'Partager',
  '_modzzz_formations_block_facebook_comments' => 'Commentaires Facebook',
  '_modzzz_formations_miles' => 'miles',
  '_modzzz_formations_kilometers' => 'Km',
  '_modzzz_formations_map_search_explanation' => 'Entrez la ville (par exemple Lille)',
  '_modzzz_formations_enter_your_formations' => 'Entrez votre annonce',
  '_modzzz_formations_block_formations_create' => 'Publier votre offre de formation',
  '_modzzz_formations_block_latest_comments' => 'Derniers commentaires',
  '_modzzz_formations_block_forum' => 'Derniers messages du forum',
  '_modzzz_formations_posted_by' => 'Publiée par ',
  '_modzzz_formations_block_search' => '<i class="sys-icon search"></i>  Je recherche une formation',
  '_modzzz_formations_form_caption_select_resume' => '<span style="color:#3B5999;"><span style="font-size:12px;"><strong>Sélectionnez votre CV </strong>
</span></span><br><a target="_blank" title="Si vous n\'avez pas encore un CV, Cliquer sur ce lien pour le créer" href="http://resosenior.fr/m/resume/browse/my&filter=add_resume"><span style="font-size:10px;">Vous n\'avez pas  un Cv ? <strong> cliquer ici </strong> pour le créer
</span></a>
',
  '_modzzz_formations_form_info_select_resume' => 'Un CV augmente votre visibilité auprès des recruteurs et leur permet de le consulter en un Clic. En plus des information d\'un CV classique vous pouvez joindre vos éléments multimédia tels que des photos et Vdeo Youtube; Ceci augmentera votre chance d\'être recruté ou du moins de recevoir une convocation pour un entretien d\'embauche! ',
  '_modzzz_formations_allow_num_listings' => 'Nombre d\'annonces autorisés',
  '_modzzz_formations_allow_videos' => 'Vidéos',
  '_modzzz_formations_allow_photos' => 'Photos',
  '_modzzz_formations_allow_sounds' => 'Je peux insérer des sons',
  '_modzzz_formations_allow_files' => 'Documents',
  '_modzzz_formations_featured' => 'A la Une',
  '_modzzz_formations_package_desc' => 'Lisez ceci avant de continuer:',
  '_modzzz_formations_block_submenu_expired_formations' => 'Offres expirées ',
  '_modzzz_formations_page_title_expired' => 'Annonces Expirées',
  '_modzzz_formations_never' => 'Jamais',
  '_modzzz_formations_featured_listing' => 'Annonce vedette (n\'expire jamais)',
  '_modzzz_formations_block_browse_categories_drilldown' => '<i class="sys-icon suitcase"></i> Formationss  par secteur',
  '_modzzz_formations_category_drilldown_for_item' => ' <span style="font-size:16px;"> <i class="sys-icon map-marker"></i> Catégories <i class="sys-icon chevron-right"></i>  <strong>{0}</strong></span>',
  '_modzzz_formations_paypal_item_desc' => 'Paiement pour la publication de l\'offre de formation {0}',
  '_modzzz_formations_paypal_featured_item_desc' => 'Mettre à la Une (Achat) - {0}',
  '_modzzz_formations_page_title_embed_video' => 'Ajouter une Vidéo (Youtube) pour l\'offre -  ',
  '_modzzz_formations_action_embed_video' => '<i class="sys-icon plus-square"></i> Youtube',
  '_modzzz_formations_caption_search' => 'Recherche de formations',
  '_modzzz_formations_location' => 'Localisation géographique ',
  '_modzzz_formations_read_cover_letter' => 'Lire le message ',
  '_modzzz_formations_cover_letter' => 'Message de ',
  '_modzzz_formations_wall_added_new_comment' => 'a commenté sur une',
  '_modzzz_formations_wall_added_new_items' => 'a ajouté  {0}  offre(s ) de formation',
  '_modzzz_formations_single' => 'Offre de formation',
  '_modzzz_formations_posted_in_topic' => 'Posté dans le forum',
  '_modzzz_formations_posted_in_formations' => 'Posté dans Annonce Formations',
  '_modzzz_formations_adm_stats' => 'Formationss en attente',
  '_sys_module_formations' => 'Offres Formation',
  '_modzzz_formations_block_calendar' => 'Calendrier',
  '_modzzz_formations_apply_attach_message' => '<span style="color:#60056E;"><span style="font-size:14px;"><strong>NB: Veuillez trouver en pièce jointe le CV du candidat</strong></span></span>

',
  '_modzzz_formations_view_resume_online_at' => '<strong>Voir son CV en ligne >> </strong>

',
  '_modzzz_formations_browse_formations_in_country' => '<i class="sys-icon  map-marker"></i>  Formationss en {0} par région',
  '_modzzz_formations_block_company_formations' => 'Nos Offres de formations',
  '_modzzz_formations_block_contact' => 'Détails de contact',
  '_modzzz_formations_form_caption_application_link' => '<i class="sys-icon desktop"></i> <strong>Rediriger les candidats vers votre site Carrières.</strong> <br><span style="font-size:13px;"> Laisser ce champ vide pour être averti par email à  chaque candidature</span>',
  '_modzzz_formations_form_info_application_link' => 'Par exemple: https://yourcompany.com/formations <br><br> Nous vous recommandons de laisser ce champ vide pour gérer des candidatures sur la plateforme Formation de CongoConnect.com et être averti par email à chaque fois qu\'un candidat postule. ',
  '_modzzz_formations_form_caption_sub_category' => 'Sélectionner une catégorie',
  '_modzzz_formations_form_caption_post' => 'Poster une offre de formation pour une période spécifiée ci-dessous',
  '_modzzz_formations_featured_formations' => 'Cette annonce est à la Une',
  '_modzzz_formations_form_caption_youtube_link' => '<i class="sys-icon link"></i> Lien de la vidéo Youtube',
  '_modzzz_formations_form_caption_youtube_caption' => '<i class="sys-icon certificate"></i> Titre de la vidéo',
  '_modzzz_formations_form_caption_youtube_attach' => '<i class="sys-icon youtube"></i>  Vidéo Youtube (optionnel)',
  '_modzzz_formations_form_info_youtube_attach' => 'Exemple: https://youtu.be/DKimfuAWNvQ',
  '_modzzz_formations_form_caption_youtube_choice' => 'Vidéos existantes',
  
   '_modzzz_formations_add_business_buton_register' => '<div class=" message-inscription" >
<i class="sys-icon  warning"></i> Vous devez premièrement inscrire votre entreprise avant de publier une offre de formation.
<br>
<i class="sys-icon  arrow-down"></i> <br>
   <button class="bx-btn bx-btn-small bx-btn-ifont"   onclick="window.open (\'m/listing/browse/my&filter=add_listing\',\'_self\');">
						<i class="sys-icon briefcase">  </i><strong>J\'inscris mon entreprise <i class="sys-icon hand-o-left"> </i> </strong>
					</button> 

</div>',


				   
 '_modzzz_formations_message_suppression' => '<span style="font-size:14px;"> Pour supprimer, cocher l\'offre ou les offres <span class="supprimercenterspace"> <span style="color:#E0E1E2;"><i class="sys-icon square"></i></span></span> puis cliquer sur supprimer </span>',
  '_modzzz_formations_block_home_formations_espace_formation' => '<i class="sys-icon building"> </i> Espace Formation <i class="sys-icon user"> </i>',
  '_modzzz_formations_block_home_formations' => ' <i class="sys-icon black-tie"> </i>  Espace Recrutement ',
  '_modzzz_formations_block_companies_recruteurs' => '<i class="sys-icon briefcase"> </i> Les Entreprises qui recrutent...',
  '_modzzz_formations_offres_formation_home_plural' => 'Mes offres de formation: ',
  '_modzzz_formations_offres_stage_home_plural' => 'offres de stage',
  '_modzzz_formations_offres_formation_home_single' => 'Offre de formation publiée',
  '_modzzz_formations_offres_enregistrees' => 'Offres sauvegardées: ',
  '_modzzz_formations_offres_enregistrees_single' => 'Offre enregistrée',
  '_modzzz_formations_offres_formation_application_count_plural' => 'Candidats à  mes offres: ',
  '_modzzz_formations_offres_formation_application_count_single' => 'candidature à  vos offres de formation',
  '_modzzz_formations_offres_stage_home_single' => 'offre de stage',
  '_modzzz_formations_acceder_votre_espace_formation' => 'Gérez mes offres de formation ',
  '_modzzz_formations_deposer_une_offre' => 'Publier une offre',
  '_modzzz_formations_mes_offres' => 'Mes offres de formation ',
  '_modzzz_formations_mes_candidatures' => 'Offres auxquelles j\'ai postulé:',
  '_modzzz_formations_mes_candidatures_single' => 'Offres auxquelles j\'ai postulé:',
  '_modzzz_formations_page_title_browse_favorite' => 'Mes offres sauvegardées',
  '_modzzz_formations_action_remove_from_favorite' => '<i class="sys-icon check"></i> Favori',
  '_modzzz_formations_action_add_to_favorite' => ' <i class="sys-icon heart-o"></i>  Enregistrer',
  '_modzzz_formations_menu_favorite' => '<i class="sys-icon save"></i>  Offres sauvegardées',
  '_modzzz_formations_msg_added_to_favorite' => 'Vous avez enregistré cette offre de formation !',
  '_modzzz_formations_msg_removed_from_favorite' => 'L\'offre de formation n\'est plus enregistrée',
  '_modzzz_formations_action_supprimer_favorite' => ' Supprimer',
  '_modzzz_formations_action_afficher_formation_favorite' => 'Offre sauvegardée ',
  '_modzzz_formations_form_unit_view_applications' => 'candidatures',
  '_modzzz_formations_form_unit_view_applications_desc' => 'Candidatures',
  '_modzzz_formations_form_unit_view_applications_single' => 'candidature',
  '_modzzz_formations_voir_candidats' => 'Voir candidats',
  '_modzzz_formations_vous_avez_home' => 'vous avez publié',
  '_modzzz_formations_vous_avez' => 'Offres de formation publiées',
  '_modzzz_formations_block_gerer_formations' => '<i class="sys-icon suitcase"> </i> Mes Offres de Formation',
  '_modzzz_formations_voir_offres_formations' => 'Supprimer une offre de formation',
  '_modzzz_formations_aucune_candidature' => 'Il n\'y a pas encore de candidatures à  votre offre <i class="sys-icon users"> </i>',
  '_modzzz_formations_form_caption_secteur_activity_unit' => 'Secteur d\'activité',
  '_modzzz_formations_date_publication' => 'Publié',
  '_modzzz_formations_form_caption_career_level_unit' => 'Niveau hiérarchique',
  '_modzzz_formations_form_caption_qualification_unit' => 'Niveau d\'études',
  '_modzzz_formations_form_caption_experience_unit' => 'Expérience',
  '_modzzz_formations_post_type_formation' => ' Offre de formation',
  '_modzzz_formations_action_edit' => 'Modifier',
  '_modzzz_formations_action_manage_applicant' => 'Voir les candidatures',
  '_modzzz_formations_action_broadcast_applicants' => 'Ecrire aux candidats',
  '_modzzz_formations_form_info_title' => 'Indiquez le titre du poste à  pourvoir<br />(ex : Analyste programmeur .)<br>100 caractères maximum',
  '_modzzz_formations_form_err_formation_type' => 'Veuillez sélectionner un type de contrat ',
  '_modzzz_formations_form_err_experience' => 'Veuillez sélectionner le niveau d\'expérience professionnel ',
  '_modzzz_formations_form_err_qualification' => 'Veuillez sélectionner le niveau d\'études que doit avoir le candidat',
  '_modzzz_formations_Be_one_of_the_first_ten_applicants' => 'Soyez l\'un des dix premiers candidats',
  '_modzzz_formations_unit_by' => 'par',
  '_modzzz_formations_already_applied_for' => ' <span style="color:green;"><span style="font-size:14px;"> Vous avez déjà  postulé pour ce poste </span></span>',
  '_modzzz_formations_candidater' => 'Postuler',
  '_modzzz_formations_type_details' => 'Type de contrat',
  '_modzzz_formations_equalification_details' => 'Qualification',
  '_modzzz_formations_career_level_details' => 'Niveau hiérarchique',
  '_modzzz_formations_industry_details' => 'Secteur',
  '_modzzz_formations_menu_mes_candidatures' => '<i class="sys-icon black-tie"></i> Mes candidatures ',
 '_modzzz_formations_unit_posted_by' => 'Posté par ',
  '_modzzz_formations_action_en_savoir_plus' => 'Consulter cette offre',
    '_modzzz_formations_profile_incomplet' => 'Mettre à  jour mon profil',
  '_modzzz_formations_profile_update' => 'Mettre à jour mon profil',
  '_modzzz_formations_action_retour_annonce' => 'Annuler',
  '_modzzz_formations_form_caption_apply_Email' => 'Email',
  '_modzzz_formations_form_info_apply_Email' => 'Précisez un email valide afin que le recruteur puisse vous contacter.',
  '_modzzz_formations_listing_form_err_apply_Email' => 'Précisez un email valide afin que le recruteur puisse vous contacter.',
  '_modzzz_formations_view_Email' => 'Email',
  '_modzzz_formations_view_Telephone' => 'Téléphone',
  '_modzzz_formations_read_of' => 'de',
  '_modzzz_formations_send_to' => 'à ',
  '_modzzz_formations_form_caption_Email' => 'Email',
  '_modzzz_formations_skills_details_profil' => '<i class="sys-icon user"></i> Profil recherché',
  '_modzzz_formations_easy_apply' => 'Postuler en 1 click',


 '_modzzz_formations_allow_prix' => 'Prix',
  '_modzzz_formations_allow_duree' => 'Durée de diffusion de votre offre',
  '_modzzz_formations_attach_message_title' => 'Veuillez trouver ci-dessous le message',
  '_modzzz_formation_Empty_formations_commande_attente' => ' <div style="text-align: center;">Vous n\'avez pas de commandes en attente de paiement.</div>
<div style="text-align: center;"> 
<button class="ConnectNetwork_MarginTop"  onclick="window.open (\'m/formations/browse/my&filter=add_formation\',\'_self\');">
			<i class="sys-icon plus-square">  </i> Déposer une offre de formation  <i class="sys-icon hand-o-left"></i>
		</button>  
 </div>
',
  '_modzzz_formation_Empty_formations_invoices' => ' <div style="text-align: center;">Vous n\'avez pas de commandes.</div>
<div style="text-align: center;"> 
<button class="ConnectNetwork_MarginTop"  onclick="window.open (\'m/formations/browse/my&filter=add_formation\',\'_self\');">
			<i class="sys-icon plus-square">  </i> Déposer une offre de formation  <i class="sys-icon hand-o-left"></i>
		</button>  
 </div>',
  '_modzzz_formation_Empty_formations_expire' => '<div style="text-align: center;"> Vous n\'avez aucune offre de formation expirée.</div>
<div style="text-align: center;"> 
<button class="ConnectNetwork_MarginTop"  onclick="window.open (\'m/formations/browse/my&filter=add_formation\',\'_self\');">
			<i class="sys-icon plus-square">  </i> Déposez une offre de formation  <i class="sys-icon hand-o-left"></i>
		</button>  
 </div>',
  '_modzzz_formation_Empty_formations_en_attente' => '<div style="text-align: center;"> Vous n\'avez aucune offre de formation en attente de validation.</div>
<div style="text-align: center;"> 
<button class="ConnectNetwork_MarginTop"  onclick="window.open (\'m/formations/browse/my&filter=add_formation\',\'_self\');">
			<i class="sys-icon plus-square">  </i> Déposer une offre de formation    <i class="sys-icon hand-o-left"></i>
		</button>  
 </div>',
   '_modzzz_formations_page_title_browse_application' => 'Offres de formation auxquelles j\'ai postulé',
  '_modzzz_formations_titre_home_page' => 'OFFRES DE FORMATION',
  '_modzzz_formations_ajouter_formation' => 'Publier une offre de formation',
  '_modzzz_formations_form_err_formation_status' => 'Champ obligatoire. <br> Veuillez sélectionner',
  '_modzzz_formations_changer_logo' => 'Changer de logo',
  '_modzzz_formations_ajouter_logo' => 'Ajouter un logo',
  '_modzzz_formations_action_invite' => 'Promouvoir',
  '_modzzz_formations_views' => 'vues',
   '_modzzz_formations_action_remove_from_preselection' => 'Retirer',
  '_modzzz_formations_action_add_to_preselection' => 'Présélection ',
  '_modzzz_formations_msg_removed_from_Preselection' => 'Le candidat a été retiré de la présélection ',
  '_modzzz_formations_msg_added_to_Preselection' => 'Le candidat a été présélectionné ',
  '_modzzz_formations_block_manage_apply_favorite' => 'Formations - Sauvegarder - Postuler',
  '_modzzz_formations_block_manage_formation' => 'Gérer cette offre de formation',
  '_modzzz_formations_description_details' => 'Description du poste',


 
  	

 );
