<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx News
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz News';

$aLangContent = array(

	'_sys_module_news' => 'News', 


    '_modzzz_news_membership_filter_none' => 'Allow All',	

    '_modzzz_news_info_membership_filter' => 'only these members will be able to view this news',
     '_modzzz_news_membership_filter_none' => 'Allow All',	
	'_modzzz_news_caption_membership_filter' => 'Allow viewing by membership',
	'_modzzz_news_err_membership_filter' => 'incorrect value',
    '_modzzz_news_info_membership_filter' => 'only these members will be able to view this news',
    '_modzzz_news_form_caption_publish_date' => 'Publish Date',
    '_modzzz_news_form_caption_publish_now' => 'Publish Now',
    '_modzzz_news_form_info_publish_now' => 'Yes - News will be immediately Published.<br>No - News will be published on Publish Date entered below',
    '_modzzz_news_block_related' => 'Related News',
    '_modzzz_news_block_related_category' => 'Other News in this Category', 
    '_modzzz_news_form_info_snippet' => 'Snippet length cannot be greater than {0}',
 
    '_modzzz_news_menu_admin_pending_publish' => 'Pending Publish',
    '_modzzz_news_admin_publish' => 'Publish',

    '_modzzz_news_calendar' => 'Calendar',
    '_modzzz_news_enter_your_news_topic' => 'Enter your Topic',
    '_modzzz_news_continue' => 'Continue',
    '_modzzz_news_block_search' => 'Search News',
    '_modzzz_news_block_news_create' => 'Post News',
    '_modzzz_news_block_calendar' => 'Calendar',
    '_modzzz_news_block_archive' => 'Archive',
    '_modzzz_news_block_map_view' => 'Map View',

    '_modzzz_news_week_sun' => 'Sun',
    '_modzzz_news_week_mon' => 'Mon',
    '_modzzz_news_week_tue' => 'Tue',
    '_modzzz_news_week_wed' => 'Wed',
    '_modzzz_news_week_thu' => 'Thur', 
    '_modzzz_news_week_fri' => 'Fri',
    '_modzzz_news_week_sat' => 'Sat',

    '_sbs_txt_title_modzzz_news' => 'News',
    '_modzzz_news' => 'News',
    '_modzzz_news_fans' => 'fans',
    '_modzzz_news_add' => 'add',
    '_modzzz_news_wall_added_new' => 'added new',
    '_modzzz_news_wall_object' => 'news',
    '_modzzz_news_for_news' => 'for %s',
    '_modzzz_news_news_single' => 'news',
    '_modzzz_news_news_plural' => 'news',
    '_modzzz_news_user_unknown' => 'Unknown',
    '_modzzz_news_disabled' => 'disabled',
    '_modzzz_news_enabled' => 'enabled',

    '_modzzz_news_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new news <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_news_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed news <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_news_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated news <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_news_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented news <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_news_sbs_change' => 'information was updated',
    '_modzzz_news_sbs_comment' => 'new comment arrived',
    '_modzzz_news_sbs_rate' => 'rating was updated',
 
    '_modzzz_news_tab_featured' => 'Featured',
    '_modzzz_news_tab_recent' => 'Recent',
    '_modzzz_news_tab_top' => 'Top',
    '_modzzz_news_tab_popular' => 'Popular',

    '_modzzz_news_block_submenu_main' => 'Main',
    '_modzzz_news_block_submenu_add_news' => 'Add',
    '_modzzz_news_block_submenu_manage_news' => 'Manage',
    '_modzzz_news_block_submenu_pending_news' => 'Pending Approval',

    '_modzzz_news_block_actions' => 'Actions',
    '_modzzz_news_block_rate' => 'Rate',    
    '_modzzz_news_block_info' => 'Info',
    '_modzzz_news_block_desc' => 'Description',
    '_modzzz_news_block_photo' => 'Photos',
    '_modzzz_news_block_video' => 'Videos',
    '_modzzz_news_block_sound' => 'Sounds',
    '_modzzz_news_block_files' => 'Files',
    '_modzzz_news_block_file' => 'Files',
    '_modzzz_news_block_comments' => 'Comments',
    '_modzzz_news_block_latest_featured_news' => 'Latest Featured News',
    '_modzzz_news_block_recent' => 'Recent News',
    '_modzzz_news_block_popular' => 'Popular News',
    '_modzzz_news_block_top' => 'Top Rated News',
    '_modzzz_news_block_search' => 'Search News',
    '_modzzz_news_block_news_categories' => 'News Categories',

    '_modzzz_news_block_administration_owner' => 'Administration',
    '_modzzz_news_block_users_news' => 'User\'s News',
    '_modzzz_news_block_my_news' => 'My News',
    '_modzzz_news_block_homepage' => 'Site News',

    '_modzzz_news_caption_add' => 'Add News',
    '_modzzz_news_caption_share_news' => 'Share News',
    '_modzzz_news_caption_admin_actions' => 'Links',
    '_modzzz_news_caption_pending_approval' => 'Pending Approval News', 

    '_modzzz_news_menu_root' => 'News',
    '_modzzz_news_menu_main' => 'News Home',
    '_modzzz_news_menu_recent' => 'Recent',
    '_modzzz_news_menu_top_rated' => 'Top Rated',
    '_modzzz_news_menu_popular' => 'Popular',
    '_modzzz_news_menu_featured' => 'Featured',
    '_modzzz_news_menu_tags' => 'Tags',
    '_modzzz_news_menu_categories' => 'Categories',
    '_modzzz_news_menu_calendar' => 'Calendar',
    '_modzzz_news_menu_search' => 'Search',
    '_modzzz_news_menu_view_news' => 'Main',
    '_modzzz_news_menu_view_comments' => 'Comments',
    '_modzzz_news_menu_view_photos' => 'Photos',
    '_modzzz_news_menu_view_videos' => 'Videos',
    '_modzzz_news_menu_view_sounds' => 'Sounds',
    '_modzzz_news_menu_view_files' => 'Files',
    '_modzzz_news_menu_my_news_profile' => 'News',

    '_modzzz_news_menu_admin_pending_approval' => 'Pending Approval',
    '_modzzz_news_menu_admin_entries' => 'Admin News',
    '_modzzz_news_menu_admin_add_entry' => 'Add News',
    '_modzzz_news_menu_admin_settings' => 'Settings',
    
    '_modzzz_news_page_title_home' => 'News Home',
    '_modzzz_news_page_title_calendar' => 'News Calendar ',
    '_modzzz_news_page_title_comments' => 'Comments',
    '_modzzz_news_page_title_photos' => 'Photos',
    '_modzzz_news_page_title_videos' => 'Videos',
    '_modzzz_news_page_title_sounds' => 'Sounds',
    '_modzzz_news_page_title_files' => 'Files',
    '_modzzz_news_page_title_my_news' => 'My News',
    '_modzzz_news_page_title_search' => 'News Search',
    '_modzzz_news_page_title_add' => 'Add News', 
    '_modzzz_news_page_title_edit' => 'Edit News',
    '_modzzz_news_page_title_administration' => 'News Administration',
    '_modzzz_news_page_title_browse' => 'Browse News',
    '_modzzz_news_page_title_pending_approval' => 'Pending Approval News',
    '_modzzz_news_page_title_search_results' => 'News Search Results',
    '_modzzz_news_page_title_browse_by_author' => '\'s news',
    '_modzzz_news_page_title_admin_news' => 'Admin News',
    '_modzzz_news_page_title_browse_by_category' => 'Browse News By Category: ',
    '_modzzz_news_page_title_browse_by_tag' => 'Browse News By Tag: ',
    '_modzzz_news_page_title_browse_recent' => 'Recent News',
    '_modzzz_news_page_title_browse_top_rated' => 'Top Rated News',
    '_modzzz_news_page_title_browse_popular' => 'Popular News',
    '_modzzz_news_page_title_browse_featured' => 'Featured News',
    '_modzzz_news_page_title_browse_by_day' => 'Browse News By Day: ',
    '_modzzz_news_page_title_browse_by_period' => 'Browse News By Period: ',
    '_modzzz_news_page_title_tags' => 'News Tags',
    '_modzzz_news_page_title_categories' => 'News Categories',
    '_modzzz_news_page_title_upload_photos' => 'Add Photos',
    '_modzzz_news_page_title_upload_videos' => 'Add Videos',
    '_modzzz_news_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_news_page_title_upload_files' => 'Add Files',

    '_modzzz_news_msg_pending_approval' => 'this news is pending approval, please wait until it will be activated',
    '_modzzz_news_msg_news_was_deleted' => 'News was deleted',
    '_modzzz_news_msg_removed_from_featured' => 'News was removed from featured',
    '_modzzz_news_msg_added_to_featured' => 'News was added to featured',
    '_modzzz_news_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_news_msg_you_have_pending_approval_news' => 'You have <a href="%s">%d pending approval news</a>',
    '_modzzz_news_msg_you_have_no_news' => 'You don\'t have any news. <a href="%s">Click here</a> to add one.',
    '_modzzz_news_msg_you_have_some_news' => 'You have <a href="%s">%d news(s)</a>. <a href="%s">Click here</a> to add more.',

    '_modzzz_news_admin_delete' => 'Delete',
    '_modzzz_news_admin_activate' => 'Activate',
    '_modzzz_news_admin_add_new_news' => 'Add New News',
    '_modzzz_news_admin_news' => 'Admin News',
    '_modzzz_news_admin_settings' => 'Admin Settings',

    '_modzzz_news_form_header_info' => 'News\'s Info',
    '_modzzz_news_form_header_images' => 'News\'s Photos',
    '_modzzz_news_form_header_videos' => 'News\'s Videos',
    '_modzzz_news_form_header_sounds' => 'News\'s Sounds',
    '_modzzz_news_form_header_files' => 'News\'s Files',
    '_modzzz_news_form_header_privacy' => 'Privacy Settings',
    '_modzzz_news_form_caption_title' => 'Title',
    '_modzzz_news_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_news_form_caption_desc' => 'Description',
    '_modzzz_news_form_err_desc' => 'Please enter at least 20 characters',
    '_modzzz_news_form_err_tags' => 'Please enter tags',
    '_modzzz_news_form_caption_author_id' => 'Author',
    '_modzzz_news_form_info_author' => 'Author profile ID number',
    '_modzzz_news_form_caption_keyword' => 'Keyword',
    '_modzzz_news_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_modzzz_news_form_caption_category' => 'Category',
    '_modzzz_news_form_err_category' => 'Category is invalid',    
    '_modzzz_news_form_caption_images_choice' => 'Choose',
    '_modzzz_news_form_info_images_choice' => 'You can choose several images from your "News" category',
    '_modzzz_news_form_caption_images_upload' => 'Upload',    
    '_modzzz_news_form_info_images_upload' => 'Image will be placed in the "News" category automatically',
    '_modzzz_news_form_caption_videos_choice' => 'Choose',
    '_modzzz_news_form_info_videos_choice' => 'You can choose several videos from your "News" category',
    '_modzzz_news_form_caption_videos_upload' => 'Upload',
    '_modzzz_news_form_info_videos_upload' => 'Video will be placed in the "News" category automatically',
    '_modzzz_news_form_caption_sounds_choice' => 'Choose',
    '_modzzz_news_form_info_sounds_choice' => 'You can choose several sounds from your "News" category',
    '_modzzz_news_form_caption_sounds_upload' => 'Upload',
    '_modzzz_news_form_info_sounds_upload' => 'Sound will be placed in the "News" category automatically',
    '_modzzz_news_form_caption_files_choice' => 'Choose',
    '_modzzz_news_form_info_files_choice' => 'Unclick checkbox to remove file from this news',
    '_modzzz_news_form_caption_files_upload' => 'Upload',
    '_modzzz_news_form_info_files_upload' => 'File will be placed in the "News" category and set as private automatically',
    '_modzzz_news_form_caption_file_title' => 'Title:',
    '_modzzz_news_form_caption_file_price' => 'Price:',
    '_modzzz_news_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_news_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_news_form_info_thumb_choice' => 'You can choose any image from your "News" category as news thumbnail',
    '_modzzz_news_form_caption_country' => 'Country',
    '_modzzz_news_form_err_country' => 'Country is a required field',
    '_modzzz_news_form_caption_city' => 'City',
    '_modzzz_news_form_err_city' => 'Please enter from 2 to 50 characters',
    '_modzzz_news_form_caption_zip' => 'Zip/Postal Code',
    '_modzzz_news_form_err_zip' => 'Zip/Postal code is required',
    '_modzzz_news_form_caption_anonymous' => 'Anonymous',
    '_modzzz_news_someone' => 'someone',

    '_modzzz_news_action_title_edit' => 'Edit',
    '_modzzz_news_action_title_delete' => 'Delete',
    '_modzzz_news_action_title_share' => 'Share',
    '_modzzz_news_action_add_to_featured' => 'Make Featured',    
    '_modzzz_news_action_remove_from_featured' => 'Unfeature',
    '_modzzz_news_action_add_news' => 'Add News',
    '_modzzz_news_action_my_news' => 'My News',
    '_modzzz_news_action_upload_photos' => 'Add Photos',
    '_modzzz_news_action_upload_videos' => 'Add Videos',
    '_modzzz_news_action_upload_sounds' => 'Add Sounds',
    '_modzzz_news_action_upload_files' => 'Add Files',
    '_modzzz_news_action_news_home' => 'Home',

    '_modzzz_news_privacy_view_news' => 'View News',
    '_modzzz_news_privacy_comment' => 'Comment',
    '_modzzz_news_privacy_rate' => 'Rate',
    '_modzzz_news_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_news_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_news_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_news_privacy_upload_files' => 'Upload Files',
    '_modzzz_news_privacy_edit_news' => 'Edit News',
    '_modzzz_news_privacy_admins_only' => 'Admins Only',
    '_modzzz_news_anonymous_note' => 'your name will not appear as the poster', 
    '_mma_news_view_news' => 'news view news', 
    '_mma_news_browse' => 'news browse', 
    '_mma_news_search' => 'news search', 
    '_mma_news_add_news' => 'news add news', 
    '_mma_news_comments_delete_and_edit' => 'news comments delete and edit', 
    '_mma_news_edit_any_news' => 'news edit any news', 
    '_mma_news_delete_any_news' => 'news delete any news', 
    '_mma_news_mark_as_featured' => 'news mark as featured', 
    '_mma_news_approve_news' => 'news approve news', 
    '_mma_news_autoapprove_news' => 'news autoapprove news', 

   	'_modzzz_news_form_header_video_embed' => 'Video Embed',
   	'_modzzz_news_form_caption_video_embed' => 'Embed Code',
   	'_modzzz_news_form_info_video_embed' => 'Enter either the URL or Embed Code for Youtube Video. Enter the Embed Code for other video sharing site (eg &lt;embed&gt;....&lt;/embed&gt;)',
	'_modzzz_news_block_video_embed' => 'External Videos',
    '_modzzz_news_caption_browse_related' => 'Browse Related News', 

	'_modzzz_news_block_rss_feed' => 'News Feed',
	'_modzzz_news_form_caption_rss' => 'RSS Link', 
	'_modzzz_news_form_caption_rss_caption' => 'Feed Caption',  
	'_modzzz_news_form_caption_rss_link' => 'Feed Link', 
	'_modzzz_news_form_header_rss' => 'RSS Feeds',
	'_modzzz_news_form_caption_rss_attach' => 'New Feed',
	'_modzzz_news_form_info_rss_attach' => 'you can add multiple RSS Feeds',
	'_modzzz_news_form_caption_rss_choice' => 'Existing Feeds',  
	'_modzzz_news_form_info_rss_choice' => 'Un-check to remove Existing Feed',  

	'_modzzz_news_posted_by' => 'Posted by',  
	'_modzzz_news_posted' => 'Posted',  
  
	'_modzzz_news_block_submenu_draft_news' => 'Pending Publishing',  

    '_modzzz_news_page_title_browse_letter' => 'Browse News begining with the letter {0}',
 
	'_modzzz_news_letter_a' => 'A',
	'_modzzz_news_letter_b' => 'B',
	'_modzzz_news_letter_c' => 'C',
	'_modzzz_news_letter_d' => 'D',
	'_modzzz_news_letter_e' => 'E',
	'_modzzz_news_letter_f' => 'F',
	'_modzzz_news_letter_g' => 'G',
	'_modzzz_news_letter_h' => 'H',
	'_modzzz_news_letter_i' => 'I',
	'_modzzz_news_letter_j' => 'J',
	'_modzzz_news_letter_k' => 'K',
	'_modzzz_news_letter_l' => 'L',
	'_modzzz_news_letter_m' => 'M',
	'_modzzz_news_letter_n' => 'N',
	'_modzzz_news_letter_o' => 'O',
	'_modzzz_news_letter_p' => 'P',
	'_modzzz_news_letter_q' => 'Q',
	'_modzzz_news_letter_r' => 'R',
	'_modzzz_news_letter_s' => 'S',
	'_modzzz_news_letter_t' => 'T',
	'_modzzz_news_letter_u' => 'U',
	'_modzzz_news_letter_v' => 'V',
	'_modzzz_news_letter_w' => 'W',
	'_modzzz_news_letter_x' => 'X',
	'_modzzz_news_letter_y' => 'Y',
	'_modzzz_news_letter_z' => 'Z', 

	'_modzzz_news_form_caption_language' => 'Language', 

	/*added 7.1 */
    '_modzzz_news_wall_added_new_comment' => 'commented on a',
    '_modzzz_news_wall_added_new_items' => 'added {0} new news item(s)',
	'_modzzz_news_single' => 'News',
    '_modzzz_news_posted_in_topic' => 'Posted in Forum',
    '_modzzz_news_posted_in_news' => 'Posted for News item',
	'_modzzz_news_browse_alphabetically' => 'Browse Alphabetically',
	'_modzzz_news_go' => 'Go',
    '_modzzz_news_adm_stats' => 'Pending News',

	'_modzzz_news_tags' => 'Tags',
 
    '_modzzz_news_all_items_posted' => '<a href="{0}">All News</a> by {1}',

	'_modzzz_news_views' => 'Views',
	'_modzzz_news_subscribers' => 'Subscribers',
    '_modzzz_news_form_header_location' => 'Location (optional)',
    '_modzzz_news_form_caption_country' => 'Country',
    '_modzzz_news_form_caption_state' => 'State',
    '_modzzz_news_form_caption_city' => 'City',
    '_modzzz_news_form_caption_address' => 'Address',
    '_modzzz_news_form_caption_zip' => 'Zip/Postal Code',
	'_modzzz_news_caption_browse_by_country' => 'Browse by Country',

	'_modzzz_news_form_caption_youtube_link' => 'Video URL', 
	'_modzzz_news_form_caption_youtube_caption' => 'Video Title',  
	'_modzzz_news_form_header_youtube' => 'Youtube Videos',
	'_modzzz_news_form_caption_youtube_attach' => 'Video',
	'_modzzz_news_form_info_youtube_attach' => 'you can add multiple Youtube Videos',
	'_modzzz_news_form_caption_youtube_choice' => 'Existing Videos',  
	'_modzzz_news_form_info_youtube_choice' => 'Uncheck Videos that you want to remove',  
    '_modzzz_news_page_title_embed_video' => 'Embed Video',
    '_modzzz_news_action_embed_video' => 'Embed Video',


    '_modzzz_news_parent_categories' => 'Parent', 
    '_modzzz_news_block_category_news' => 'News in this Category',
    '_modzzz_news_block_subcategories' => 'Sub-Categories',  
    '_modzzz_news_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button', 
	'_modzzz_news_categ_name' => 'Category',
	'_modzzz_news_categ_btn_edit' => 'Edit',
	'_modzzz_news_categ_btn_delete' => 'Delete',
	'_modzzz_news_categ_btn_add' => 'Add',
	'_modzzz_news_categ_btn_save' => 'Save',
	'_modzzz_news_categ_btn_subcategories' => 'Sub-Categories', 
 	'_modzzz_news_categories' => 'Categories',
 	'_modzzz_news_menu_admin_manage_categories' => 'Categories',
  	'_modzzz_news_menu_admin_manage_subcategories' => 'Sub-Cats',
  	'_modzzz_news_subcategories' => 'Sub-Categories',
    '_modzzz_news_all_categories' => 'All Categories',
    '_modzzz_news_block_categories' => 'Categories',
    '_modzzz_news_block_answer_categories' => 'News Categories',
    '_modzzz_news_menu_categories' => 'Categories',
    '_modzzz_news_page_title_browse_by_category' => 'Browse News By Category: ',
    '_modzzz_news_form_caption_category' => 'Category',
    '_modzzz_news_form_err_category' => 'Category is invalid', 
	'_modzzz_news_page_title_category' => 'Category', 
    '_modzzz_news_page_title_categories' => 'News Categories',
    '_modzzz_news_page_title_subcategories' => 'News Sub-Categories', 
    '_modzzz_news_news_in_category' => '<b>News</b> in <b>%s</b>',    
	'_modzzz_news_menu_manage_parents' => 'Parent Cats',
    '_modzzz_news_menu_manage_categories' => 'Cats', 
    '_modzzz_news_categ_name' => 'Name',
	'_modzzz_news_form_caption_categories' => 'Categories',
	'_modzzz_news_form_caption_subcategories' => 'Sub-Categories', 
    '_modzzz_news_block_news' => 'News',
    '_modzzz_news_block_news_categories' => 'Categories',

    '_mma_news_allow_embed' => 'news allow video embed', 
    '_modzzz_news_anonymous' => 'A guest', 
 
    '_wall_reposted_modzzz_news_add' => 'reposted a news item',
    '_wall_reposted_title_modzzz_news_add' => '{0} reposted a news item',
    '_wall_reposted_modzzz_news_comment_add' => 'reposted a news comment',
    '_wall_reposted_title_modzzz_news_comment_add' => '{0} reposted a news comment',
 
    '_wall_reposted_modzzz_news_add' => 'reposted a news item',
    '_wall_reposted_title_modzzz_news_add' => '{0} reposted a news item',
    '_wall_reposted_modzzz_news_comment_add' => 'reposted a comment on a news item',
    '_wall_reposted_title_modzzz_news_comment_add' => '{0} reposted a comment on a news item',

    '_modzzz_news_wall_added_new_title' => '{0} added new {1}',
    '_modzzz_news_wall_added_new_title_items' => '{0} added {1} new news',
    '_modzzz_news_wall_added_new_title_comment' => '{0} commented on a {1}',
 
    '_modzzz_news_caption_news_for_business' => 'News for Business',
    '_modzzz_news_caption_news_for_band' => 'News for Band',
    '_modzzz_news_caption_news_for_group' => 'News for Group',
    '_modzzz_news_caption_news_for_event' => 'News for Event',
    '_modzzz_news_caption_news_for_school' => 'News for School',



);