<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'BooneEx Events';

$aLangContent = array(
    '_sbs_txt_title_bx_events' => 'Events',
    '_bx_events' => 'Events',
    '_bx_events_single' => 'event',
    '_bx_events_plural' => 'events',
    '_bx_events_action_events_home' => 'Events Home',
    '_bx_events_action_remove_from_featured' => 'Unfeature',
    '_bx_events_action_add_to_featured' => 'Feature',
    '_bx_events_action_create_event' => 'Create Event',
    '_bx_events_action_my_events' => 'My Events',
	'_bx_events_action_title_delete' => 'Delete',
	'_bx_events_action_title_edit' => 'Edit',
	'_bx_events_action_title_invite' => 'Invite',
	'_bx_events_action_title_leave' => 'Leave',
	'_bx_events_action_title_join' => 'Join',
    '_bx_events_action_title_share' => 'Share',
    '_bx_events_action_title_broadcast' => 'Broadcast',    
    '_bx_events_action_manage_fans' => 'Edit Participants',
    '_bx_events_action_upload_photos' => 'Add Photos',
    '_bx_events_action_upload_videos' => 'Add Videos',
    '_bx_events_action_upload_sounds' => 'Add Sounds',
    '_bx_events_action_upload_files' => 'Add Files',
    '_bx_events_add_new_event_admin' => 'Create Event',
    '_bx_events_user_unknown' => 'Someone',
    '_bx_events_admin' => 'admin',    
	'_bx_events_admin_activate' => 'Activate',	
    '_bx_events_admin_delete' => 'Delete',
    '_bx_events_admin_events' => 'Active Events',
    '_bx_events_admin_home' => 'Home',
    '_bx_events_administration' => 'Events Administration',
    '_bx_events_administration_create_event' => 'Create Event', 
    '_bx_events_administration_settings' => 'Settings', 
    '_bx_events_administration_admin_events' => 'Active Events',
	'_bx_events_all_countries' => 'All Countries',
	'_bx_events_allow_comments_all' => 'All',
	'_bx_events_allow_comments_friends' => 'Friends Only',
	'_bx_events_allow_comments_none' => 'Nobody',
	'_bx_events_allow_comments_participants' => 'Participants Only',
	'_bx_events_allow_rate_all' => 'All',
	'_bx_events_allow_rate_friends' => 'Friends Only',
	'_bx_events_allow_rate_none' => 'Nobody',
	'_bx_events_allow_rate_participants' => 'Participants Only',
    '_bx_events_calendar' => 'Calendar ',
    '_bx_events_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new event <a href="{entry_url}">{entry_title}</a>',
    '_bx_events_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed event <a href="{entry_url}">{entry_title}</a>',
    '_bx_events_spy_join' => '<a href="{profile_link}">{profile_nick}</a> joined event <a href="{entry_url}">{entry_title}</a>',
    '_bx_events_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated event <a href="{entry_url}">{entry_title}</a>',
    '_bx_events_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented on event <a href="{entry_url}">{entry_title}</a>',

    '_bx_events_sbs_change' => 'information was updated',
    '_bx_events_sbs_comment' => 'new comment arrived',
    '_bx_events_sbs_rate' => 'rating was updated',
    '_bx_events_sbs_join' => 'new participant',

	'_bx_events_caption_add' => 'Create Event', 
	'_bx_events_caption_allow_comments' => 'Allow to view and post comments',
	'_bx_events_caption_allow_rate' => 'Allow rating',
	'_bx_events_caption_allow_view_participants' => 'Allow viewinging participants',
	'_bx_events_caption_author_id' => 'Author ID',
    '_bx_events_caption_browse_by_author' => 'Browse Events By Author: ',
    '_bx_events_caption_browse_by_author_joined_events' => 'Browse Author Joined Events: ',
    '_bx_events_caption_browse_by_country' => 'Browse Events By Country: ',
    '_bx_events_caption_browse_by_city' => 'Browse Events By City: ',
    '_bx_events_caption_browse_by_category' => 'Browse Events By Category: ',
    '_bx_events_caption_browse_by_day' => 'Browse Events By Day: ',
    '_bx_events_caption_browse_by_tag' => 'Browse Events By Tag: ',
    '_bx_events_caption_browse_featured' => 'Featured Events',
    '_bx_events_caption_browse_popular' => 'Popular Events',
    '_bx_events_caption_browse_recently_added' => 'Recently Added Events',
    '_bx_events_caption_browse_top_rated' => 'Top Rated Events',
    '_bx_events_caption_browse_upcoming' => 'Upcoming Events',
    '_bx_events_caption_browse_past' => 'Past Events',
	'_bx_events_form_caption_city' => 'City',
	'_bx_events_form_caption_country' => 'Country',
	'_bx_events_form_caption_address1' => 'Address1',
	'_bx_events_form_caption_zip' => 'Zip',


	'_bx_events_caption_desc' => 'Description',
	'_bx_events_caption_edit' => 'Edit Event',
	'_bx_events_caption_event_end' => 'Date end',
	'_bx_events_caption_event_start' => 'Date start',
	'_bx_events_caption_invite' => 'Send Invitation To ',
	'_bx_events_caption_join_filter' => 'Allow to join',
	'_bx_events_caption_keyword' => 'Keyword',
	'_bx_events_caption_membership_filter' => 'Allow joining by membership',
	'_bx_events_caption_photo' => 'Photo',
	'_bx_events_caption_place' => 'Place name',
    '_bx_events_caption_search' => 'Search',
    '_bx_events_caption_search_results' => 'Search Results:',
	'_bx_events_caption_title' => 'Title',	
    '_bx_events_caption_share_event' => 'Share',
    '_bx_events_caption_videos' => 'Videos',
    '_bx_events_caption_photos' => 'Photos',
    '_bx_events_caption_sounds' => 'Sounds',
    '_bx_events_caption_files' => 'Files',
    '_bx_events_caption_comments' => 'Comments',
    '_bx_events_caption_participants' => 'Participants',
    '_bx_events_caption_broadcast' => 'Broadcast message to event\'s participants',
    '_bx_events_caption_manage_fans' => 'Manage Participants',
    '_bx_events_caption_upload_photos' => 'Add Photos',
    '_bx_events_caption_upload_videos' => 'Add Videos',
    '_bx_events_caption_upload_sounds' => 'Add Sounds',
    '_bx_events_caption_upload_files' => 'Add Files',

	'_bx_events_err_allow_comments' => 'incorrect value',
	'_bx_events_err_allow_rate' => 'incorrect value',
	'_bx_events_err_allow_view_participants' => 'incorrect value',
	'_bx_events_err_city' => 'please fill in city name',
	'_bx_events_err_country' => 'please specify country',
	'_bx_events_err_desc' => 'please specify description from 20 characters',
	'_bx_events_err_event_end' => 'date format is incorrect',
	'_bx_events_err_event_start' => 'date format is incorrect',
	'_bx_events_err_join_filter' => 'incorrect value',
	'_bx_events_err_keyword' => 'please specify keyword from 3 to 100 characters',
	'_bx_events_err_membership_filter' => 'incorrect value',
	'_bx_events_err_photo' => 'please select a photo',
	'_bx_events_err_place' => 'this is a required field',
	'_bx_events_err_tags' => 'please enter at least one word which describes this event',
	'_bx_events_err_title' => 'please specify title from 3 to 100 characters',
    '_bx_events_error_occured' => 'Error Occurred',

    '_bx_events_form_header_info' => 'Event\'s Info',
    '_bx_events_form_header_privacy' => 'Privacy Settings',

    '_bx_events_form_caption_file_title' => 'Title:',
    '_bx_events_form_header_images' => 'Event\'s Photos',
    '_bx_events_form_caption_thumb_choice' => 'Choose thumbnail',
    '_bx_events_form_info_thumb_choice' => 'You can choose any uploaded image as event thumnail',
    '_bx_events_form_caption_images_choice' => 'Choose',
    '_bx_events_form_info_images_choice' => 'Unchecked images will be deleted',
    '_bx_events_form_caption_images_upload' => 'Upload',
    '_bx_events_form_info_images_upload' => 'Image will be placed in the "Events" category automatically',

    '_bx_events_form_header_videos' => 'Event\'s Videos',
    '_bx_events_form_caption_videos_choice' => 'Choose',
    '_bx_events_form_info_videos_choice' => 'Unchecked videos will be deleted',
    '_bx_events_form_caption_videos_upload' => 'Upload',
    '_bx_events_form_info_videos_upload' => 'Video will be placed in the "Events" category automatically',

    '_bx_events_form_header_sounds' => 'Event\'s Sounds',
    '_bx_events_form_caption_sounds_choice' => 'Choose',
    '_bx_events_form_info_sounds_choice' => 'Unchecked sounds will be deleted',
    '_bx_events_form_caption_sounds_upload' => 'Upload',
    '_bx_events_form_info_sounds_upload' => 'Sound will be placed in the "Events" category automatically',

    '_bx_events_form_header_files' => 'Event\'s Files',
    '_bx_events_form_caption_files_choice' => 'Choose',
    '_bx_events_form_info_files_choice' => 'Unchecked files will be deleted',
    '_bx_events_form_caption_files_upload' => 'Upload',
    '_bx_events_form_info_files_upload' => 'File will be placed in the "Events" category automatically',

    '_bx_events_form_caption_broadcast_title' => 'Broadcast Title',
    '_bx_events_form_err_broadcast_title' => 'Please enter from 3 to 100 characters',
    '_bx_events_form_caption_broadcast_message' => 'Broadcast Message',
    '_bx_events_form_err_broadcast_message' => 'Please enter at least 10 characters',

    '_bx_events_form_caption_join_confirmation' => 'Join confirmation',
    '_bx_events_form_info_join_confirmation' => 'If enabled, event admin(s) will have to confirm each user before he/she becomes a participant.',
    '_bx_events_form_join_confirmation_disabled' => 'Disabled',
    '_bx_events_form_join_confirmation_enabled' => 'Enabled',

    '_bx_events_event_join_success' => 'You have successfully joined this event',
    '_bx_events_event_joined_already' => 'You have already joined this event',
    '_bx_events_event_join_success_pending' => 'You have successfully joined this event, please wait while your request is reviewed by event admin(s)',
    '_bx_events_event_joined_already_pending' => 'Your join request is pending approval.',    
	'_bx_events_event_leave_success' => 'You have successfully left this event',
	'_bx_events_event_was_deleted' => 'Event was deleted',	
	'_bx_events_info_allow_comments' => 'only these members will be able to view and post comments',
	'_bx_events_info_allow_rete' => 'only these members will be able to rate the event',
    '_bx_events_info_allow_view_participants' => 'only these members will be able to view the participants list',
    '_bx_events_info_author' => 'you can see profile\\\'s ID in admin panel member\\\'s list',
	'_bx_events_info_join_filter' => 'only these members will be able to join this event',	
    '_bx_events_info_membership_filter' => 'only these members will be able to join this event',
    '_bx_events_invitation_sent' => '%d invitations have been sent',

	'_bx_events_join_all' => 'All',
	'_bx_events_join_friends_only' => 'Friends Only',
	'_bx_events_main' => 'Events',
    '_bx_events_membership_filter_none' => 'Allow All',	
	'_bx_events_msg_access_denied' => 'Access Denied',
	'_bx_events_msg_page_not_found' => 'Page Not Found',
    '_bx_events_msg_pending_approval' => 'This event is pending administrator approval. Please, wait.',
    '_bx_events_msg_added_to_featured' => 'Event was added to featured',
    '_bx_events_msg_removed_from_featured' => 'Event was removed from featured',
    '_bx_events_msg_you_have_pending_approval_events' => 'You have <a href="%s">%d pending approval events</a>',
    '_bx_events_msg_you_have_no_events' => 'You have not added any events. <a href="%s">Click here</a> to add one.',
    '_bx_events_msg_you_have_some_events' => 'You have <a href="%s">%d event(s)</a>. <a href="%s">Click here</a> to add more.',
    '_bx_events_msg_broadcast_no_participants' => 'This event has no participants yet',
    '_bx_events_msg_broadcast_message_sent' => 'Broadcast message has been successfully sent',
	'_bx_events_no_users_msg' => 'There are no users in your contacts',
	'_bx_events_pending_approval' => 'Pending Approval',
	'_bx_events_photo_is_pending_approval' => 'Photo is pending approval. Please be patient.',	
	'_bx_events_settings_admin' => 'Settings',

    '_bx_events_privacy_view_event' => 'View Event',
    '_bx_events_privacy_join' => 'Allow joining',
    '_bx_events_privacy_comment' => 'Allow to view and post comments',
    '_bx_events_privacy_rate' => 'Allow rating',
    '_bx_events_privacy_view_participants' => 'Allow viewing participants',
    '_bx_events_privacy_post_in_forum' => 'Allow posting in forum',
    '_bx_events_privacy_participants_only' => 'Participants only',    
    '_bx_events_privacy_participants' => 'Participants',    
    '_bx_events_privacy_admins_only' => 'Admins Only',
    '_bx_events_privacy_upload_photos' => 'Upload Photos',
    '_bx_events_privacy_upload_videos' => 'Upload Videos',
    '_bx_events_privacy_upload_sounds' => 'Upload Sounds',
    '_bx_events_privacy_upload_files' => 'Upload Files',    

    '_bx_events_tags' => 'Events Tags',
    '_bx_events_categories' => 'Events Categories',
	'_bx_events_view_participants_all' => 'All',
	'_bx_events_view_participants_friends' => 'Friends Only',
	'_bx_events_view_participants_none' => 'Nobody',    

    '_bx_events_block_actions' => 'Actions',
    '_bx_events_block_info' => 'Information',
    '_bx_events_block_desc' => 'Description',
    '_bx_events_block_participants' => 'Participants',
    '_bx_events_block_participants_unconfirmed' => 'Unconfirmed Participants',
    '_bx_events_block_photos' => 'Photos',
    '_bx_events_block_videos' => 'Videos',
    '_bx_events_block_sounds' => 'Sounds',
    '_bx_events_block_files' => 'Files',
    '_bx_events_block_rate' => 'Rate',
    '_bx_events_block_comments' => 'Comments',
    '_bx_events_block_calendar' => 'Events Calendar ',
    '_bx_events_block_upcoming_photo' => 'Upcoming Public Event',
    '_bx_events_block_upcoming_list' => 'Upcoming Public Events',
    '_bx_events_block_past_list' => 'Past Public Events',
    '_bx_events_block_recently_added_list' => 'Recently Added Public Events',
    '_bx_events_block_my_events' => 'My Events',
	'_bx_events_block_joined_events' => 'Joined Events',
    '_bx_events_block_administration' => 'Administration',
    '_bx_events_block_user_events' => 'My Events',
    '_bx_events_block_home' => 'Public Events',

    '_bx_events_block_submenu_main' => 'Main',
    '_bx_events_block_submenu_add' => 'Add',
    '_bx_events_block_submenu_manage' => 'Manage',
    '_bx_events_block_submenu_pending' => 'Pending Approval',

    '_bx_events_menu_root' => 'Events',
    '_bx_events_menu_main' => 'Events Home',
    '_bx_events_menu_upcoming_events' => 'Upcoming',
    '_bx_events_menu_past_events' => 'Past',
    '_bx_events_menu_recently_added' => 'Recently Added',
    '_bx_events_menu_featured' => 'Featured',
    '_bx_events_menu_my_events' => 'My Events',
    '_bx_events_menu_my_events_profile' => 'Events',
    '_bx_events_menu_my_pending_events' => 'Pending Approval',
    '_bx_events_menu_calendar' => 'Calendar',
    '_bx_events_menu_popular' => 'Popular',
    '_bx_events_menu_search' => 'Search',
    '_bx_events_menu_tags' => 'Tags',
    '_bx_events_menu_categories' => 'Categories',
    '_bx_events_menu_top_rated' => 'Top Rated',
    '_bx_events_menu_add' => 'Create Event',
    '_bx_events_menu_view' => 'Main',
    '_bx_events_menu_view_forum' => 'Forum',
    '_bx_events_menu_view_comments' => 'Comments',
    '_bx_events_menu_view_participants' => 'Participants',
    '_bx_events_menu_view_photos' => 'Photos',
    '_bx_events_menu_view_videos' => 'Videos',
    '_bx_events_menu_view_sounds' => 'Sounds',
    '_bx_events_menu_view_files' => 'Files',

    '_bx_events_tab_recent' => 'Recently Added',
    '_bx_events_tab_upcoming' => 'Upcoming',
    '_bx_events_tab_featured' => 'Featured',
    '_bx_events_tab_top' => 'Top',
    '_bx_events_tab_popular' => 'Popular',

    '_bx_event_wall_added_new' => 'added new',
    '_bx_event_wall_object' => 'event',

    '_bx_events_announce' => 'announce',

    '_mma_events_view' => 'events view', 
    '_mma_events_browse' => 'events browse', 
    '_mma_events_search' => 'events search', 
    '_mma_events_add' => 'events add', 
    '_mma_events_comments_delete_and_edit' => 'events comments delete and edit', 
    '_mma_events_edit_any_event' => 'events edit any event', 
    '_mma_events_delete_any_event' => 'events delete any event', 
    '_mma_events_mark_as_featured' => 'events marked as featured', 
    '_mma_events_approve' => 'events approve', 
    '_mma_events_broadcast_message' => 'events broadcast message',

    '_bx_events_block_joined' => 'Joined Events',   
     '_bx_events_block_search' => 'Quick Search',  
	'_bx_events_accept_invitation' => 'Accept Event Invitation - ', 
	'_bx_events_caption_participants_info' => 'Participants Information', 
	'_bx_events_info_participants_info' => 'This information is viewable only to Participants',  
	'_bx_events_block_rss_feed' => 'RSS Feed',
	'_bx_events_form_caption_rss' => 'RSS Link', 
    '_bx_events_block_participants_info' => 'Participants Information',
 	
	'_mma_events_rss_add' => 'events rss add',  
    '_mma_events_files_add' => 'events files add',  
    '_mma_events_photos_add' => 'events photos add',  
    '_mma_events_videos_add' => 'events videos add',  
    '_mma_events_sounds_add' => 'events sounds add',  
  
    '_bx_events_block_forum_feed' => 'Forum Feed',
 
	'_bx_events_caption_membership_view_filter' => 'Allow viewing by membership',
	'_bx_events_err_membership_view_filter' => 'incorrect value', 
    '_bx_events_info_membership_view_filter' => 'only these members will be able to view this event',

   	'_bx_events_caption_browse_other' => 'Other Events by {0}',
	'_bx_events_form_header_reminder' => 'Remind Participants',  
	'_bx_events_caption_reminder' => 'Send Reminder',  
	'_bx_events_caption_reminder_days' => 'Days before Event Begins',  
	'_bx_events_info_reminder_days' => 'The reminder will be sent this number of Days before the Event Ends', 
	'_bx_events_yes' => 'Yes',  
	'_bx_events_no' => 'No',  
  
	'_bx_events_starts' => 'Starts',  
	'_bx_events_ends' => 'Ends',  
	'_bx_events_comments' => 'Comments',  
	
	'_bx_events_caption_categories' => 'Categories',  
	'_bx_events_all_categories' => 'All Categories',  
	
	'_bx_events_regions_for_country' => 'Regions for {0}',  
	'_bx_events_block_browse_state' => 'Browse States', 
	'_bx_events_block_browse_state_events' => 'Browse Events by State', 
	'_bx_events_block_common_categories' => 'Common Categories', 
	'_bx_events_block_latest_activities' => 'Latest Activities', 
	'_bx_events_block_account' => 'Events in my Area', 
	'_bx_events_block_latest_comments' => 'Latest Public Comments', 

	'_bx_events_block_browse_country' => 'Browse by Country', 
	'_bx_events_page_title_local' => 'Browse Local Events',  
	'_bx_events_caption_browse_local' => 'Browse Local Events in {0}', 
	'_bx_events_menu_local' => 'Local', 
	'_bx_events_block_organizer' => 'Promoter', 
	'_bx_events_block_local' => 'More Local Events',
  	'_bx_events_block_other' => 'Other Events by this member',
  	'_bx_events_caption_organizer_name' => 'Name',
  	'_bx_events_caption_organizer_email' => 'Email',
  	'_bx_events_caption_organizer_phone' => 'Telephone',
  	'_bx_events_caption_organizer_website' => 'Website',
  	'_bx_events_caption_organizer_fax' => 'Fax',
   	'_bx_events_form_header_organizer' => 'Promoter Info',
	
	'_bx_events_recurring_unlimited' => 'unlimited',  
 	'_bx_events_recurring_daily' => 'daily',  
 	'_bx_events_recurring_weekly' => 'weekly',  
 	'_bx_events_recurring_biweekly' => 'bi-weekly',  
 	'_bx_events_recurring_monthly' => 'monthly',  
 	'_bx_events_recurring_quarterly' => 'quarterly',  
 	'_bx_events_recurring_yearly' => 'yearly',  
  	'_bx_events_frequency' => 'Event Frequency',  
  	'_bx_events_recurring_period' => 'Period',  
   	'_bx_events_recurring' => 'Recurring',  
 	'_bx_events_stop_after' => 'stop after',   
  	'_bx_events_occurences_explanation' => 'occurences - <b>leave blank for unlimited</b>', 
   	'_bx_events_recurring_period_message' => 'This Event will be hosted {0}',  
  	'_bx_events_block_recurring' => 'History of this Event',  
 
   	'_bx_events_form_header_recurring' => 'Recurring Info',  
   	'_bx_events_caption_recurring' => 'Recurring',  
   	'_bx_events_recurring_no' => 'No',  
   	'_bx_events_recurring_yes' => 'Yes',  
   	'_bx_events_caption_recurring_number' => 'Number of Occurences',  
   	'_bx_events_caption_recurring_period' => 'Period',  
 
   	'_bx_events_block_create' => 'What will be happening soon?',  
   	'_bx_events_block_top_list' => 'Top Rated Public Events',  
   	'_bx_events_block_popular_list' => 'Popular Public Events',  
	'_bx_events_block_featured' => 'Recently Featured Events',  
   	'_bx_events_block_calendar' => 'Events Calendar',  
	'_bx_events_block_forum' => 'Latest Public Forum Posts',  
  
	'_bx_events_continue' => 'Continue',  
	'_bx_events_enter_your_event_name' => 'Enter your event name',  
	'_bx_events_caption_state' => 'State',  


	'_bx_events_feed_make_admin' => '<a href="{profile_link}">{profile_nick}</a> is now an admin for event <a href="{entry_url}">{entry_title}</a>',  

	'_bx_events_feed_remove_admin' => '<a href="{profile_link}">{profile_nick}</a> is no longer an admin for event <a href="{entry_url}">{entry_title}</a>',  

	'_bx_events_feed_featured' => '<a href="{profile_link}">{profile_nick}</a> has featured event <a href="{entry_url}">{entry_title}</a>',  

	'_bx_events_feed_unfeatured' => '<a href="{profile_link}">{profile_nick}</a> has un-featured event <a href="{entry_url}">{entry_title}</a>',  
 
	'_bx_events_feed_delete' => '<a href="{profile_link}">{profile_nick}</a> removed event <a href="{entry_url}">{entry_title}</a>',  

	'_bx_events_feed_post' => '<a href="{profile_link}">{profile_nick}</a> added new event <a href="{entry_url}">{entry_title}</a>',  

	'_bx_events_feed_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed event <a href="{entry_url}">{entry_title}</a>',  

	'_bx_events_feed_join' => '<a href="{profile_link}">{profile_nick}</a> is attending event <a href="{entry_url}">{entry_title}</a>',  

	'_bx_events_feed_unjoin' => '<a href="{profile_link}">{profile_nick}</a> is no longer attending event <a href="{entry_url}">{entry_title}</a>',  

	'_bx_events_feed_rate' => '<a href="{profile_link}">{profile_nick}</a> rated event <a href="{entry_url}">{entry_title}</a>',  

	'_bx_events_feed_comment' => '<a href="{profile_link}">{profile_nick}</a> commented on event <a href="{entry_url}">{entry_title}</a>' ,
 
    '_bx_events_packages_empty' => 'There are no Event Packages', 
    '_bx_events_package_description' => 'Description', 
    '_bx_events_package_featured' => 'Featured', 

    '_bx_events_featured_status' => 'Featured Status', 
    '_bx_events_featured_until' => 'Featured until', 
    '_bx_events_not_featured' => 'Not Featured', 
 	'_bx_events_extend_featured' => 'Extend Featured Status',  
	'_bx_events_purchase_featured' => 'Purchase Featured Status', 
	'_bx_events_form_caption_currency' => 'Currency',  

    '_bx_events_menu_packages' => 'Packages', 
    '_bx_events_page_title_packages' => 'Event Packages', 
    '_bx_events_block_packages' => 'Event Packages', 

    '_bx_events_on' => 'on',  
    '_bx_events_yes' => 'yes',  
    '_bx_events_no' => 'no', 

	'_bx_events_categ_btn_edit' => 'Edit',
	'_bx_events_categ_btn_delete' => 'Delete',
	'_bx_events_categ_btn_add' => 'Add',
	'_bx_events_categ_btn_save' => 'Save',
 
	'_bx_events_package_videos' => 'Videos',  	
	'_bx_events_package_photos' => 'Photos',  	
	'_bx_events_package_sounds' => 'Sounds',  	
	'_bx_events_package_files' => 'Files', 
 
    '_mma_events_purchase_featured' => 'events purchase featured', 
	'_bx_events_action_title_purchase_featured' => 'Get Featured',
	'_bx_events_action_title_extend_featured' => 'Extend Featured',  
	'_bx_events_purchase_featured_status' => 'Purchase Featured Status',  
	'_bx_events_quantity' => 'Quantity',   
	'_bx_events_purchase_success' => 'You successfully Purchased {0} Days of Featured Status', 
	'_bx_events_purchase_fail' => 'Your attempt to Purchase Featured Status has failed',  
	'_bx_events_purchase_failed' => 'Your attempt to Purchase Featured Status has failed',  
	'_bx_events_transaction_completed_already' => 'This transaction was already completed',  
	'_bx_events_featured_cost_per_day' => 'Cost per Day',  
	'_bx_events_caption_num_featured_days' => 'Number of Featured Days',    
	'_bx_events_caption_err_featured_days' => 'You must enter Number of Featured Days',    
	'_bx_events_get_featured' => 'Get Featured',  

	'_bx_events_packages' => 'Packages',
	'_bx_events_package_name' => 'Package Name',
	'_bx_events_package_price' => 'Package Price',
	'_bx_events_package_days' => 'Package Days',
	'_bx_events_form_caption_package' => 'Payment Package',
	'_bx_events_form_err_package' => 'Please select a Package',  
	'_bx_events_purchaser' => 'Purchaser', 
	'_bx_events_invoice_no' => 'Invoice #', 
	'_bx_events_package' => 'Package', 
	'_bx_events_invoice_date' => 'Invoice Date', 
	'_bx_events_invoice_due_date' => 'Due Date', 
	'_bx_events_status' => 'Status',
	'_bx_events_pending' => 'Pending',
	'_bx_events_paid' => 'Paid',
	'_bx_events_active' => 'Active',
	'_bx_events_inactive' => 'Inactive',
	'_bx_events_approved' => 'Approved',
	'_bx_events_expired' => 'Expired', 
	'_bx_events_block_submenu_pending_invoices' => 'Pending Invoices',
	'_bx_events_block_submenu_orders' => 'Orders',
	'_bx_events_page_title_orders' => 'Orders', 
	'_bx_events_page_title_invoices' => 'Invoices', 
	'_bx_events_menu_manage_invoices' => 'Invoices', 
	'_bx_events_menu_manage_packages' => 'Packages',
	'_bx_events_menu_manage_orders' => 'Orders',
	'_bx_events_payment_method' => 'Payment Method',
	'_bx_events_total' => 'Total',
	'_bx_events_invoice_id' => 'Invoice ID',
	'_bx_events_next_due_date' => 'Next Due Date',
	'_bx_events_order_no' => 'Order #',
	'_bx_events_product_status' => 'Product Status',
	'_bx_events_order_date' => 'Order Date',
	'_bx_events_purchase_failed' => 'Sorry, there was a problem with the Payment.  View your Pending Orders <a href="{0}">here</a>.',
	'_bx_events_transaction_completed_already' => 'The Transaction exists already. Click <a href="{0}">here</a> to view the Event.',
	'_bx_events_purchase_success' => 'Thank you. The Payment was successful. Click <a href="{0}">here</a> to view the Event.',  
	'_bx_events_trans_save_failed' => 'The Payment was successful but there was a problem saving the transaction. Please contact the administrator with your Paypal transaction details so they can manually process your Order.',
	'_bx_events_post_purchase_header' => 'Event Listing Purchase' ,

    '_bx_events_block_states' => 'States',
    '_bx_events_posted' => 'Posted',

    '_bx_events_action_title_excel' => 'Export List', 
    '_bx_events_action_title_print' => 'Print List',  
 
	'_bx_events_block_browse_sponsors' => 'Browse Event Sponsors',
	'_bx_events_page_title_sponsor_add' => 'Add a Sponsor for Event - {0}',
	'_bx_events_page_title_sponsor_browse' => 'Browse Sponsors for Event - {0}',  
    '_bx_events_action_title_add_sponsor' => 'Add Sponsor',
    '_bx_events_page_title_sponsor_edit' => 'Edit Sponsor',
    '_bx_events_msg_event_was_sponsor_deleted' => 'Sponsor was successfully deleted',
    '_bx_events_msg_pending_sponsor_approval' => 'this sponsor is pending approval, please wait until it will be activated',
    '_bx_events_menu_view_sponsors' => 'Sponsors', 
    '_bx_events_block_sponsors' => 'Sponsors',
	
	'_bx_events_block_browse_venues' => 'Browse Event Venues',
	'_bx_events_page_title_venue_add' => 'Add a Venue for Event - {0}',
	'_bx_events_page_title_venue_browse' => 'Browse Venues for Event - {0}',  
    '_bx_events_action_title_add_venue' => 'Add Venue',
    '_bx_events_page_title_venue_edit' => 'Edit Venue',
    '_bx_events_msg_event_was_venue_deleted' => 'Venue was successfully deleted',
    '_bx_events_msg_pending_venue_approval' => 'this venue is pending approval, please wait until it will be activated',
    '_bx_events_menu_view_venues' => 'Venues', 
    '_bx_events_block_venues' => 'Venues',

	'_bx_events_block_browse_news' => 'Browse Event News',
	'_bx_events_page_title_news_add' => 'Add News for Event - {0}',
	'_bx_events_page_title_news_browse' => 'Browse News for Event - {0}',  
    '_bx_events_action_title_add_news' => 'Add News',
    '_bx_events_page_title_news_edit' => 'Edit News',
    '_bx_events_msg_event_was_news_deleted' => 'News was successfully deleted',
    '_bx_events_msg_pending_news_approval' => 'this news is pending approval, please wait until it will be activated',
    '_bx_events_menu_view_news' => 'News', 
    '_bx_events_block_news' => 'News',
 
	'_bx_events_action_title_premium' => 'Get Premium',  
    '_bx_events_page_title_premium' => 'Get Premium Listing',   
	'_mma_events_purchase' => 'events purchase package', 

    '_bx_events_action_title_extend' => 'Extend',  
    '_bx_events_page_title_extend' => 'Extend Event listing',   
	'_mma_events_extend' => 'events extend', 

    '_bx_events_action_title_relist' => 'Re-list',  
    '_bx_events_page_title_relist' => 'Re-list Event listing',  
	'_mma_events_relist' => 'events relist', 
  
    '_bx_events_form_caption_current_no_package' => 'No Package currently',   
    '_bx_events_form_caption_current_package' => 'Current Package',  
    '_bx_events_form_caption_package_price' => 'Package Price',  
    '_bx_events_form_caption_package_days' => 'Length of Listing',   
 	'_bx_events_expires_never' => 'unlimited (never expires)', 
 	'_bx_events_days' => 'days', 
 	'_bx_events_form_caption_current_item' => 'Event', 
    '_bx_events_extend' => 'Extend',  
    '_bx_events_block_statistics' => 'Statistics',  


	'_bx_events_block_rss_feed' => 'RSS Feed',
	'_bx_events_form_caption_rss' => 'RSS Link', 
	'_bx_events_form_caption_rss_caption' => 'Feed Caption',  
	'_bx_events_form_caption_rss_link' => 'Feed Link', 
	'_bx_events_form_header_rss' => 'RSS Feeds',
	'_bx_events_form_caption_rss_attach' => 'New Feed',
	'_bx_events_form_info_rss_attach' => 'you can add multiple RSS Feeds',
	'_bx_events_form_caption_rss_choice' => 'Existing Feeds', 
  	'_bx_events_form_info_rss_choice' => 'Uncheck the Feeds you want to remove', 

 	'_bx_events_caption_public_only' => 'Public only',  
    '_bx_events_block_joined' => 'Joined Events',  
    
    '_bx_events_subprofile_form_header_info' => 'Info',
    '_bx_events_subprofile_form_header_images' => 'Photos',
    '_bx_events_subprofile_form_header_videos' => 'Videos',
    '_bx_events_subprofile_form_header_sounds' => 'Sounds',
    '_bx_events_subprofile_form_header_files' => 'Files', 
 	
    '_bx_events_caption_allow_join_after_start' => 'Allow Join after Event Start',

 	'_bx_events_package_desc' => 'Package Description',  
    '_bx_events_block_submenu_expired_events' => 'Expired',
    '_bx_events_page_title_expired' => 'Expired Listings', 

 	'_bx_events_expires' => 'Expires', 	 
 	'_bx_events_never' => 'Never',  
 
	'_bx_events_posted_in_event' => 'Posted in Event',   
 	'_bx_events_featured_listing' => 'Featured Listing (never expires)',  
 	
	'_bx_events_form_header_location' => 'Location',  
 	'_bx_events_block_location' => 'Location',  
 	'_bx_events_caption_street' => 'Street',  
 

	'_bx_events_menu_drilldown' => 'Drilldown', 
	'_bx_events_caption_browse_my_local' => 'Events in my area', 
	'_bx_events_block_created' => 'Events I Created', 
	'_bx_events_block_joined' => 'Events I Joined', 
	'_bx_events_action_events_joined' => 'Joined', 

    '_bx_events_pay_invoice' => 'PAY INVOICE',
   
	'_bx_events_allow_num_listings' => 'Number of Listings allowed', 	
	'_bx_events_allow_videos' => 'Allow Videos', 	
	'_bx_events_allow_photos' => 'Allow Photos', 	
	'_bx_events_allow_sounds' => 'Allow Sounds', 	
	'_bx_events_allow_files' => 'Allow Files', 	
 	'_bx_events_featured' => 'Featured Listing',  
	'_bx_events_package_desc' => 'Package Description',  

    '_bx_events_block_submenu_expired_listing' => 'Expired', 
 	'_bx_events_not_featured_listing' => 'Listing is not Featured',  
 
	'_bx_events_block_youtubes' => 'Youtube Videos', 
	'_bx_events_form_caption_youtube_link' => 'Video URL', 
	'_bx_events_form_caption_youtube_caption' => 'Video Title',  
	'_bx_events_form_header_youtube' => 'Youtube Videos',
	'_bx_events_form_caption_youtube_attach' => 'Video',
	'_bx_events_form_info_youtube_attach' => 'you can add multiple Youtube Videos',
	'_bx_events_form_caption_youtube_choice' => 'Existing Videos',  
	'_bx_events_form_info_youtube_choice' => 'Uncheck Videos that you want to remove',  
    '_bx_events_page_title_embed_video' => 'Embed Video',
    '_bx_events_action_embed_video' => 'Embed Video',

	'_bx_events_posted_by' => 'Posted by', 
	'_bx_events_posted_in' => 'In', 
    '_bx_events_event_is_in_process' => 'In Progress',
    '_bx_events_adm_stats' => 'Pending Events',
    '_sys_module_events' => 'Events',
	'_bx_events_posted_in_topic' => 'Posted in Forum', 


	'_bx_events_form_header_contact' => 'Contact Details',  
	'_bx_events_form_caption_website' => 'Website',  
	'_bx_events_form_caption_email' => 'Email',  
	'_bx_events_form_caption_telephone' => 'Telephone',  
	'_bx_events_form_caption_fax' => 'Fax',  
	'_bx_events_block_contact' => 'Contact Information',  
	'_bx_events_block_map' => 'Map View',

	'_bx_events_block_starts' => 'Starts',
	'_bx_events_block_ends' => 'Ends',
	'_bx_events_happening' => 'happening',
	'_bx_events_block_facebook_comments' => 'Facebook Comments',

	'_mma_events_extend' => 'events extend',
	'_mma_events_files_add' => 'events files add',
	'_mma_events_photos_add' => 'events photos add',
	'_mma_events_purchase' => 'events purchase',
	'_mma_events_purchase_featured' => 'events purchase featured',
	'_mma_events_relist' => 'events relist',
	'_mma_events_rss_add' => 'events rss_add',
	'_mma_events_sounds_add' => 'events sounds add',
	'_mma_events_videos_add' => 'events videos add',

	'_bx_events_form_caption_enter_participant' => 'Enter Participant(s)', 
	'_bx_events_form_info_enter_participant' => 'You can enter multiple participant names (separated by a comma)', 
	'_bx_events_title_add_participants' => 'Add Participants to Event',
	'_bx_events_or' => 'OR', 
	'_bx_events_form_caption_select_group' => 'Select Group', 
	'_bx_events_form_info_select_group' => 'This will add all participants of the selected Group as participants of the Event', 
	'_bx_events_action_title_add_participant' => 'Add Participant', 

	'_bx_events_block_video_embed' => 'Embedded Videos',


	'_bx_events_block_admins' => 'Administrators',
 	'_bx_events_form_header_add_admin' => 'Add new administrator for this Event', 
 	'_bx_events_form_caption_new_admin' => 'New Administrator', 
 	'_bx_events_page_title_admin_add' => 'Add new administrator for Event - {0}', 
  	'_bx_events_form_err_invalid_admin' => '{0} is not a registered member of this site',
  	'_bx_events_form_err_already_admin' => '{0} is already an administrator of this Event',
 	'_bx_events_action_title_add_admin' => '+ Administrator', 
 	'_bx_events_form_err_new_admin' => 'Enter the name of a registered site member', 
 	'_bx_events_action_manage_admins' => 'Manage Admins', 
 	'_bx_events_caption_manage_admins' => 'Manage Admins', 

 	'_bx_events_caption_event_for_band' => 'Event for Band', 
 	'_bx_events_caption_event_for_club' => 'Event for Club', 
 	'_bx_events_caption_event_for_group' => 'Event for Group', 
 	'_bx_events_caption_event_for_location' => 'Event for Location', 
 
    '_bx_events_block_discounts' => 'Price & Discounts', 
    '_bx_events_action_title_add_discount' => 'Manage Discounts',  
	'_bx_events_page_title_discount' => 'Price & Discounts',
    '_bx_events_msg_discount_added_success' => 'Price & Discounts have been successfully added', 
	'_bx_events_form_caption_discounts' => 'Discounts', 
	'_bx_events_form_header_discount_choices' => 'Price & Discounts', 
    '_bx_events_form_caption_discount_choice' => 'Existing Prices',  
	'_bx_events_form_info_discounts' => 'You can click the plus button to create a new set', 
 
    '_bx_events_price_event_date' => 'Event Date',  
    '_bx_events_price_tickets' => 'Tickets',  
    '_bx_events_price_cost' => 'Cost',  
    '_bx_events_price_deadline' => 'Deadline',  
    '_bx_events_price_info' => 'Info',  
    '_bx_events_sponsor' => 'Event Sponsors',  

  	'_bx_events_msg_private_join' => 'This Event is Private. You have to become a participant to access it',  
  	'_bx_events_msg_private_join_pending' => 'This Event is Private. You have already sent a participant request to access it. The Event Administrator will review your request and make a decision shortly',  
 	'_bx_events_login' => '<a href="{0}">Login</a>',  

    '_bx_events_wall_added_new' => 'added new',
    '_bx_events_wall_added_new_comment' => 'commented on a',
    '_bx_events_wall_added_new_items' => 'added {0} new events',
    '_bx_events_wall_object' => 'event', 
    '_bx_events_views' => 'views',

    '_bx_events_page_title_embed_video' => 'Embed Video', 
	'_bx_events_action_embed_video' => 'Embed Video',

    '_bx_events_caption_browse_recurring' => 'Browse Recurring Events',

	/*begin - added patch 2.1.7*/
	'_bx_events_privacy_view_forum' => 'View Forum', 
	'_bx_events_block_submenu_group_events' => 'Upcoming Group Events',  
	/*end - added patch 2.1.7*/

	'_bx_events_caption_event_for_listing' => 'Event for Business', 

	'_bx_events_caption_news_for_event' => 'News for Event',  

    '_bx_events_page_title_feature_item' => 'Feature this Listing',
    '_bx_events_feature_listing_desc' => 'Cost for featuring a Listing',

    '_bx_events_insufficient_credits_message' => 'Your Credits balance is {0}. You need {1} Credits to feature this listing.',
    '_bx_events_insufficient_points_message' => 'Your Points balance is {0}. You need {1} Points to feature this listing.',
    '_bx_events_buy_link' => '<a href="{0}">Buy more here</a>',
	'_bx_events_form_caption_cost_to_feature' => 'Cost to Feature',
	'_bx_events_form_caption_credits_balance' => 'Credits Balance',
	'_bx_events_form_caption_points_balance' => 'Points Balance',
	'_bx_events_credits' => 'Credits',
	'_bx_events_points' => 'Points',
	'_bx_events_msg_feature_success' => 'Listing was successfully featured',
	'_bx_events_msg_feature_failure' => 'Failed to feature listing',
	'_bx_events_form_caption_feature' => 'Make this Featured',
	'_bx_events_form_caption_submit' => 'Go Ahead',
    '_mma_events_allow_embed' => 'events allow video embed', 
	'_bx_events_form_per_day' => 'per day',
	'_bx_events_err_msg_date_span' => 'Event End Date cannot be earlier than the Start Date',
	'_bx_events_admin_activate' => 'Activate',

	'_bx_events_caption_browse_local' => 'Browse local Events in {0}', 

	'_wall_reposted_bx_events_add' => 'reposted an event',
	'_wall_reposted_title_bx_events_add' => '{0} reposted an event',
	'_wall_reposted_bx_events_comment_add' => 'reposted an event comment',
	'_wall_reposted_title_bx_events_comment_add' => '{0} reposted an event comment',

	'_bx_events_caption_event_for_group' => 'Event for Group',

	'_bx_events_block_logo' => 'Logo', 
	'_bx_events_form_header_logo' => 'Logo', 
	'_bx_events_present_icon' => 'Present Icon', 
	'_bx_events_form_caption_icon' => 'Icon', 
	'_bx_events_remove' => 'Remove', 
  
	'_bx_events_popup_title_ban_member' => 'Ban Member', 
	'_bx_events_msg_ban_success' => 'Successfully banned member',  
	'_bx_events_msg_ban_fail' => 'Failed to ban member', 
	'_bx_events_action_title_ban' => 'Ban Member', 
	'_bx_events_btn_members_unban' => 'UnBan Members', 
	'_bx_events_block_banned_members' => 'Banned Members', 
	'_bx_events_form_caption_enter_member' => 'Member Name',  
	'_bx_events_block_owner_rss' => 'Owner RSS Feed', 


);

