<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Professional
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Services Directory';

$aLangContent = array(
  

    '_modzzz_professional_fans' => 'fans',
    '_modzzz_professional_sbs_join' => 'new fan',
    '_modzzz_professional_block_fans' => 'Fans',
    '_modzzz_professional_block_fans_unconfirmed' => 'Unconfirmed Fans',
	'_modzzz_professional_block_my_professionals_joined' => 'Joined Professionals',
    '_modzzz_professional_caption_manage_fans' => 'Manage Fans',
    '_modzzz_professional_menu_view_fans' => 'Fans',
    '_modzzz_professional_page_title_fans' => 'Professional\'s Fans',
    '_modzzz_professional_action_manage_fans' => 'Manage Fans',
    '_modzzz_professional_privacy_view_fans' => 'View Fans',
    '_modzzz_professional_privacy_fans_only' => 'Fans Only',
    '_modzzz_professional_privacy_fans' => 'Fans',

    '_modzzz_professional_spy_join' => '<a href="{profile_link}">{profile_nick}</a> joined professional <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_professional_page_title_browse_by_author_joined_professionals' => '\'s joined professionals',
    '_modzzz_professional_msg_joined_already' => 'You have already joined this professional',
    '_modzzz_professional_msg_joined_request_pending' => 'You have already joined this professional. Please wait while your request is processed by professional admin(s).',
    '_modzzz_professional_msg_join_success' => 'You have successfully joined this professional',
    '_modzzz_professional_msg_join_success_pending' => 'You have successfully joined this professional. Please wait while your request is processed by professional admin(s).',
	'_modzzz_professional_msg_leave_success' => 'You have successfully left this professional',
    '_modzzz_professional_form_caption_join_confirmation' => 'Join Confirmation',
    '_modzzz_professional_form_info_join_confirmation' => 'If enabled, professional admin(s) will have to confirm each user before he/she becomes a fan.',
    '_modzzz_professional_form_join_confirmation_disabled' => 'Disabled',
    '_modzzz_professional_form_join_confirmation_enabled' => 'Enabled',
    '_modzzz_professional_form_err_join_confirmation' => 'Join confirmation field must be 0 or 1',
    '_modzzz_professional_action_title_join' => 'Become Fan',
    '_modzzz_professional_action_title_leave' => 'Remove Fan',
    '_modzzz_professional_privacy_join' => 'Become Fan',
 
    '_modzzz_professional_packages_empty' => 'There are no Business Packages', 
    '_modzzz_professional_package_description' => 'Description', 
    '_modzzz_professional_package_featured' => 'Featured', 

    '_modzzz_professional_featured_status' => 'Featured Status', 
    '_modzzz_professional_featured_until' => 'Featured until', 
    '_modzzz_professional_not_featured' => 'Not Featured', 
 	'_modzzz_professional_extend_featured' => 'Extend Featured Status',  
	'_modzzz_professional_purchase_featured' => 'Purchase Featured Status', 
	'_modzzz_professional_form_caption_currency' => 'Currency',  

    '_modzzz_professional_menu_packages' => 'Packages', 
    '_modzzz_professional_page_title_packages' => 'Business Packages', 
    '_modzzz_professional_block_packages' => 'Business Packages', 

    '_modzzz_professional_menu_view_forum' => 'Forum', 
    '_modzzz_professional_privacy_post_in_forum' => 'Post In Forum',
 
   	'_modzzz_professional_form_header_video_embed' => 'Video Embed',
   	'_modzzz_professional_caption_video_embed_code' => 'Embed Code',
	'_modzzz_professional_form_info_video_embed_code' => 'Enter either the URL or Embed Code for Youtube Video. Enter the Embed Code for other video sharing site (eg &lt;embed&gt;....&lt;/embed&gt;)',
   	'_modzzz_professional_block_video_embed' => 'External Video',
 
	'_modzzz_professional_caption_membership_view_filter' => 'Allow viewing by membership',
	'_modzzz_professional_err_membership_view_filter' => 'incorrect value', 
    '_modzzz_professional_info_membership_view_filter' => 'only these members will be able to view this professional listing',
    '_modzzz_professional_membership_filter_none' => 'Allow All',	

    '_mma_professional_files_add' => 'professional files add',  
    '_mma_professional_photos_add' => 'professional photos add',  
    '_mma_professional_videos_add' => 'professional videos add',  
    '_mma_professional_sounds_add' => 'professional sounds add',  
	
    '_modzzz_professional_continue' => 'Continue',  
    '_modzzz_professional_admin_assign' => 'Assign to Claimant',  
    '_modzzz_professional_menu_manage_claims' => 'Claims',  
    '_modzzz_professional_claimed_by' => 'Claimed by',  
    '_modzzz_professional_on' => 'on',  
    '_modzzz_professional_yes' => 'Yes',  
    '_modzzz_professional_no' => 'No',  
 
	'_modzzz_professional_package_videos' => 'Videos',  	
	'_modzzz_professional_package_photos' => 'Photos',  	
	'_modzzz_professional_package_sounds' => 'Sounds',  	
	'_modzzz_professional_package_files' => 'Files', 

	'_modzzz_professional_block_professional_states' => 'States', 
 
    '_mma_professional_purchase_featured' => 'professional purchase featured', 
    '_mma_professional_make_claim' => 'professional make claim', 
 
	'_modzzz_professional_block_browse_categories_drilldown' => 'Categories Drilldown', 
	'_modzzz_professional_category_drilldown_for_item' => 'Categories Drilldown for <b>{0}</b>', 

    '_modzzz_professional_regions_for_country' => 'States/Regions for',  
	'_modzzz_professional_block_browse_state' => 'Browse States', 
	'_modzzz_professional_block_browse_state_professionals' => 'Browse Professionals by State', 
	'_modzzz_professional_block_account' => 'Professionals in my Area',  
	'_modzzz_professional_block_browse_country' => 'Browse by Country', 
	'_modzzz_professional_page_title_local' => 'Browse Local Professionals',  
	'_modzzz_professional_caption_browse_local' => 'Browse Local Professionals in {0}', 
	'_modzzz_professional_menu_local' => 'Local', 
 	'_modzzz_professional_block_local' => 'More Local Professionals',
	'_modzzz_professional_block_other' => 'Other Professionals by this member',
 	'_modzzz_professional_caption_browse_other' => 'Other Professionals by {0}',


	'_modzzz_professional_action_title_purchase_featured' => 'Get Featured',
	'_modzzz_professional_action_title_extend_featured' => 'Extend Featured',  
	'_modzzz_professional_purchase_featured_status' => 'Purchase Featured Status',  
	'_modzzz_professional_quantity' => 'Quantity',   
	'_modzzz_professional_purchase_success' => 'You successfully Purchased {0} Days of Featured Status', 
	'_modzzz_professional_purchase_fail' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_professional_purchase_failed' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_professional_transaction_completed_already' => 'This transaction was already completed',  
	'_modzzz_professional_featured_cost_per_day' => 'Cost per Day',  
	'_modzzz_professional_caption_num_featured_days' => 'Number of Featured Days',    
	'_modzzz_professional_caption_err_featured_days' => 'You must enter Number of Featured Days',    
	'_modzzz_professional_get_featured' => 'Get Featured',  
 

    '_modzzz_professional_parent_categories' => 'Parent', 
    '_modzzz_professional_block_category_professional' => 'Professionals in this Category',
    '_modzzz_professional_block_subcategories' => 'Sub-Categories',  
    '_modzzz_professional_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button', 
	'_modzzz_professional_categ_name' => 'Category',
	'_modzzz_professional_categ_btn_edit' => 'Edit',
	'_modzzz_professional_categ_btn_delete' => 'Delete',
	'_modzzz_professional_categ_btn_add' => 'Add',
	'_modzzz_professional_categ_btn_save' => 'Save',
	'_modzzz_professional_categ_btn_subcategories' => 'Sub-Categories', 
 	'_modzzz_professional_categories' => 'Categories',
 	'_modzzz_professional_menu_admin_manage_categories' => 'Categories',
  	'_modzzz_professional_menu_admin_manage_subcategories' => 'Sub-Cats',
  	'_modzzz_professional_subcategories' => 'Sub-Categories',
    '_modzzz_professional_all_categories' => 'All Categories',
    '_modzzz_professional_block_categories' => 'Categories',
    '_modzzz_professional_block_professional_subcategories' => 'Sub-Categories',
    '_modzzz_professional_block_answer_categories' => 'Professional Categories',
    '_modzzz_professional_menu_categories' => 'Categories',
    '_modzzz_professional_page_title_browse_by_category' => 'Browse Professionals By Category: ',
    '_modzzz_professional_form_caption_category' => 'Category',
    '_modzzz_professional_form_err_category' => 'Category is invalid', 
	'_modzzz_professional_page_title_category' => 'Category', 
    '_modzzz_professional_page_title_categories' => 'Professional listing Categories',
    '_modzzz_professional_page_title_subcategories' => 'Professional listing Sub-Categories', 
    '_modzzz_professional_professionals_in_category' => '<b>Professionals</b> in <b>%s</b>',  
    '_modzzz_professional_block_professional' => 'Professionals', 
    
	'_modzzz_professional_packages' => 'Packages',
	'_modzzz_professional_package_name' => 'Package Name',
	'_modzzz_professional_package_price' => 'Package Price',
	'_modzzz_professional_package_days' => 'Package Days',
	'_modzzz_professional_form_caption_package' => 'Business Package',
	'_modzzz_professional_form_err_package' => 'Please select a Business Package',  
	'_modzzz_professional_purchaser' => 'Purchaser', 
	'_modzzz_professional_invoice_no' => 'Invoice #', 
	'_modzzz_professional_package' => 'Package', 
	'_modzzz_professional_invoice_date' => 'Invoice Date', 
	'_modzzz_professional_invoice_due_date' => 'Due Date', 
	'_modzzz_professional_status' => 'Status',
	'_modzzz_professional_pending' => 'Pending',
	'_modzzz_professional_paid' => 'Paid',
	'_modzzz_professional_active' => 'Active',
	'_modzzz_professional_inactive' => 'Inactive',
	'_modzzz_professional_approved' => 'Approved',
	'_modzzz_professional_expired' => 'Expired', 
	'_modzzz_professional_block_submenu_pending_invoices' => 'Pending Invoices',
	'_modzzz_professional_block_submenu_orders' => 'Orders',
	'_modzzz_professional_page_title_orders' => 'Orders', 
	'_modzzz_professional_page_title_invoices' => 'Invoices', 
	'_modzzz_professional_menu_manage_invoices' => 'Invoices', 
	'_modzzz_professional_menu_manage_packages' => 'Packages',
	'_modzzz_professional_menu_manage_orders' => 'Orders',
	'_modzzz_professional_payment_method' => 'Payment Method',
	'_modzzz_professional_total' => 'Total',
	'_modzzz_professional_invoice_id' => 'Invoice ID',
	'_modzzz_professional_next_due_date' => 'Next Due Date',
	'_modzzz_professional_order_no' => 'Order #',
	 '_modzzz_professional_product_status' => 'Product Status',
	'_modzzz_professional_order_date' => 'Order Date',
	'_modzzz_professional_purchase_failed' => 'Sorry, there was a problem with the Payment.  View your Pending Orders <a href="{0}">here</a>.',
	'_modzzz_professional_transaction_completed_already' => 'The Transaction exists already. Click <a href="{0}">here</a> to view the Professional.',
	'_modzzz_professional_purchase_success' => 'Thank you. The Payment was successful. Click <a href="{0}">here</a> to view the Professional.',  
	'_modzzz_professional_trans_save_failed' => 'The Payment was successful but there was a Problem saving the transaction. Please contact the administrator with your Paypal transaction details so they can manually process your Order.',
	'_modzzz_professional_post_purchase_header' => 'Professional listing Purchase',  
 

	'_modzzz_professional_caption_state' => 'State',  
	'_modzzz_professional_regions_for_country' => 'States/Regions for',  
	'_modzzz_professional_block_browse_state' => 'Browse States', 
	'_modzzz_professional_block_browse_state_events' => 'Browse Professionals by State',
	'_modzzz_professional_block_browse_country' => 'Browse by Country', 
	'_modzzz_professional_page_title_local' => 'Browse Local Professionals',  
	'_modzzz_professional_caption_browse_local' => 'Browse Local Professionals in {0}', 
	'_modzzz_professional_menu_local' => 'Local',
 	'_modzzz_professional_caption_search' => 'Search Professional listings',
 

    '_modzzz_professional_no_professionals' => 'There are no Professionals',
    '_sbs_txt_title_modzzz_professional' => 'Professionals',
    '_modzzz_professional' => 'Professional',
    '_modzzz_professional_plural' => 'Professionals',
    '_modzzz_professional_add' => 'add',
    '_modzzz_professional_wall_added_new' => 'added new',
    '_modzzz_professional_wall_object' => 'professional listing',
    '_modzzz_professional_for_professional' => 'for %s',
    '_modzzz_professional_professional_single' => 'professional listing',
    '_modzzz_professional_professional_plural' => 'professional listings',
    '_modzzz_professional_user_unknown' => 'Someone',
    '_modzzz_professional_disabled' => 'disabled',
    '_modzzz_professional_enabled' => 'enabled',
    '_modzzz_professional_cannot_delete_default_parent' => 'Cannot Delete Default Parent Category',
	    
	 '_modzzz_professional_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new professional listing <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_professional_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed professional listing <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_professional_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated professional listing <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_professional_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented professional listing <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_professional_sbs_change' => 'information was updated',
    '_modzzz_professional_sbs_comment' => 'new comment arrived',
    '_modzzz_professional_sbs_rate' => 'rating was updated',
 
    '_modzzz_professional_tab_featured' => 'Featured',
    '_modzzz_professional_tab_recent' => 'Recent',
    '_modzzz_professional_tab_top' => 'Top',
    '_modzzz_professional_tab_popular' => 'Popular',

    '_modzzz_professional_block_submenu_main' => 'Main',
    '_modzzz_professional_block_submenu_add_professional' => 'Add',
    '_modzzz_professional_block_submenu_manage_professional' => 'Manage',
    '_modzzz_professional_block_submenu_pending_professional' => 'Pending Approval',

    '_modzzz_professional_block_actions' => 'Actions',
    '_modzzz_professional_block_rate' => 'Rate',    
    '_modzzz_professional_block_info' => 'Info',
    '_modzzz_professional_block_desc' => 'Description',
    '_modzzz_professional_block_photo' => 'Photos',
    '_modzzz_professional_block_video' => 'Videos',
    '_modzzz_professional_block_sound' => 'Sounds',
    '_modzzz_professional_block_files' => 'Files',
    '_modzzz_professional_block_file' => 'Files',
    '_modzzz_professional_block_comments' => 'Comments',
    '_modzzz_professional_block_latest_featured_professional' => 'Latest Featured Professionals',
    '_modzzz_professional_block_recent' => 'Recent Professionals',
    '_modzzz_professional_block_popular' => 'Popular Professionals',
    '_modzzz_professional_block_top' => 'Top Rated Professionals',
    '_modzzz_professional_block_search' => 'Search Professionals',
    '_modzzz_professional_block_professional_categories' => 'Business Categories',

    '_modzzz_professional_block_administration_owner' => 'Administration',
    '_modzzz_professional_block_users_professional' => "User Professionals",
    '_modzzz_professional_block_my_professional' => 'My Professional Profile',
    '_modzzz_professional_block_area_professionals' => 'Professionals in my Area',

    '_modzzz_professional_block_homepage' => 'Professional listings',

    '_modzzz_professional_caption_add' => 'Add Professional',
    '_modzzz_professional_caption_share_professional' => 'Share Professional',
    '_modzzz_professional_caption_admin_actions' => 'Links',
    '_modzzz_professional_caption_pending_approval' => 'Pending Approval Professionals', 
    
	'_modzzz_professional_menu_manage_parents' => 'Parent Cats',
    '_modzzz_professional_menu_manage_categories' => 'Cats',
    '_modzzz_professional_categ_btn_save' => 'Save',
    '_modzzz_professional_categ_btn_edit' => 'Edit',
    '_modzzz_professional_categ_btn_delete' => 'Delete',
    '_modzzz_professional_categ_name' => 'Name',
    '_modzzz_professional_categ_icon' => 'Icon',
    '_modzzz_professional_categ_present_icon' => 'Present Icon',
    '_modzzz_professional_categ_btn_add' => 'Add',

    '_modzzz_professional_menu_root' => 'Professionals',
    '_modzzz_professional_menu_main' => 'Professionals Home',
    '_modzzz_professional_menu_recent' => 'Recent',
    '_modzzz_professional_menu_top_rated' => 'Top Rated',
    '_modzzz_professional_menu_popular' => 'Popular',
    '_modzzz_professional_menu_featured' => 'Featured',
    '_modzzz_professional_menu_tags' => 'Tags',
    '_modzzz_professional_menu_categories' => 'Categories',
    '_modzzz_professional_menu_calendar' => 'Calendar',
    '_modzzz_professional_menu_search' => 'Search',
    '_modzzz_professional_menu_view_professional' => 'Main',
    '_modzzz_professional_menu_view_comments' => 'Comments',
    '_modzzz_professional_menu_view_photos' => 'Photos',
    '_modzzz_professional_menu_view_videos' => 'Videos',
    '_modzzz_professional_menu_view_sounds' => 'Sounds',
    '_modzzz_professional_menu_view_files' => 'Files',
    '_modzzz_professional_menu_my_professional_profile' => 'Professionals',

    '_modzzz_professional_menu_admin_pending_approval' => 'Pending',
    '_modzzz_professional_menu_admin_entries' => 'Admin Professionals',
    '_modzzz_professional_menu_admin_add_entry' => 'Add',
    '_modzzz_professional_menu_admin_settings' => 'Settings',
    
    '_modzzz_professional_page_title_home' => 'Professional Home',
    '_modzzz_professional_page_title_calendar' => 'Professional Calendar',
    '_modzzz_professional_page_title_comments' => 'Comments',
    '_modzzz_professional_page_title_photos' => 'Photos',
    '_modzzz_professional_page_title_videos' => 'Videos',
    '_modzzz_professional_page_title_sounds' => 'Sounds',
    '_modzzz_professional_page_title_files' => 'Files',
    '_modzzz_professional_page_title_my_professional' => 'My Professionals',
    '_modzzz_professional_page_title_search' => 'Business Search',
    '_modzzz_professional_page_title_add' => 'Add Professional', 
    '_modzzz_professional_page_title_edit' => 'Edit Professional',
    '_modzzz_professional_page_title_administration' => 'Professionals Administration',
    '_modzzz_professional_admin_block_administration' => 'Admin.',

    '_modzzz_professional_page_title_browse' => 'Browse Professionals',
    '_modzzz_professional_page_title_pending_approval' => 'Pending Approval Professionals',
    '_modzzz_professional_page_title_search_results' => 'Professional Search Results',
    '_modzzz_professional_page_title_browse_by_author' => "\'s professionals",
    '_modzzz_professional_page_title_admin_professional' => 'Admin Professionals',
    '_modzzz_professional_page_title_browse_by_category' => 'Browse Professionals By Category: ',
    '_modzzz_professional_page_title_browse_by_tag' => 'Browse Professionals By Tag: ',
    '_modzzz_professional_page_title_browse_recent' => 'Recent Professionals',
    '_modzzz_professional_page_title_browse_top_rated' => 'Top Rated Professionals',
    '_modzzz_professional_page_title_browse_popular' => 'Popular Professionals',
    '_modzzz_professional_page_title_browse_featured' => 'Featured Professionals',
    '_modzzz_professional_page_title_browse_by_day' => 'Browse Professionals By Day: ',
    '_modzzz_professional_page_title_tags' => 'Professionals Tags',
    '_modzzz_professional_page_title_upload_photos' => 'Add Photos',
    '_modzzz_professional_page_title_upload_videos' => 'Add Videos',
    '_modzzz_professional_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_professional_page_title_upload_files' => 'Add Files',

    '_modzzz_professional_msg_pending_approval' => 'this professional is pending approval, please wait until it will be activated',
    '_modzzz_professional_msg_professional_was_deleted' => 'Professional was deleted',
    '_modzzz_professional_msg_removed_from_featured' => 'Professional was removed from featured',
    '_modzzz_professional_msg_added_to_featured' => 'Professional was added to featured',
    '_modzzz_professional_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_professional_msg_you_have_pending_approval_professional' => 'You have <a href="%s">%d pending approval professionals</a>',
    '_modzzz_professional_msg_you_have_no_professional' => 'You do not have any professional listings. <a href="%s">Click here</a> to add one.',
    '_modzzz_professional_msg_you_have_some_professional' => 'You have <a href="%s">%d professional(s)</a>. <a href="%s">Click here</a> to add more.',

    '_modzzz_professional_admin_delete' => 'Delete',
    '_modzzz_professional_admin_activate' => 'Activate',
    '_modzzz_professional_admin_add_new_professional' => 'Add New Professional',
    '_modzzz_professional_admin_professional' => 'Admin Professional',
    '_modzzz_professional_admin_settings' => 'Admin Settings',


    '_modzzz_professional_form_header_business_location' => 'Business Location',  
    '_modzzz_professional_form_header_location' => 'Location',  
    '_modzzz_professional_form_header_contact' => 'Business Contact Details',   
    '_modzzz_professional_form_header_info' => 'Info',
    '_modzzz_professional_form_header_images' => 'Photos',
    '_modzzz_professional_form_header_videos' => 'Videos',
    '_modzzz_professional_form_header_sounds' => 'Sounds',
    '_modzzz_professional_form_header_files' => 'Files',
    '_modzzz_professional_form_header_privacy' => 'Privacy Settings',
    '_modzzz_professional_form_caption_client_details' => 'Client details', 
    '_modzzz_professional_form_caption_client_name' => 'Client Name',
    '_modzzz_professional_form_caption_title' => 'Title', 
    '_modzzz_professional_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_professional_form_caption_desc' => 'Description',
    '_modzzz_professional_form_err_desc' => 'Please enter at least 20 characters',
    '_modzzz_professional_form_err_tags' => 'Please enter tags',
    '_modzzz_professional_form_caption_author_id' => 'Author',
    '_modzzz_professional_form_info_author' => 'Author profile ID number',
    '_modzzz_professional_form_caption_keyword' => 'Keyword',
    '_modzzz_professional_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_modzzz_professional_form_caption_category' => 'Category',
    '_modzzz_professional_form_err_category' => 'Category is invalid',    
    '_modzzz_professional_form_caption_images_choice' => 'Choose',
    '_modzzz_professional_form_info_images_choice' => 'You can choose several images from your "Professional" category',
    '_modzzz_professional_form_caption_images_upload' => 'Upload',    
    '_modzzz_professional_form_info_images_upload' => 'Image will be placed in the "Professional" category automatically',
    '_modzzz_professional_form_caption_videos_choice' => 'Choose',
    '_modzzz_professional_form_info_videos_choice' => 'You can choose several videos from your "Professional" category',
    '_modzzz_professional_form_caption_videos_upload' => 'Upload',
    '_modzzz_professional_form_info_videos_upload' => 'Video will be placed in the "Professional" category automatically',
    '_modzzz_professional_form_caption_sounds_choice' => 'Choose',
    '_modzzz_professional_form_info_sounds_choice' => 'You can choose several sounds from your "Professional" category',
    '_modzzz_professional_form_caption_sounds_upload' => 'Upload',
    '_modzzz_professional_form_info_sounds_upload' => 'Sound will be placed in the "Professional" category automatically',
    '_modzzz_professional_form_caption_files_choice' => 'Choose',
    '_modzzz_professional_form_info_files_choice' => 'Unclick checkbox to remove file from this professional',
    '_modzzz_professional_form_caption_files_upload' => 'Upload',
    '_modzzz_professional_form_info_files_upload' => 'File will be placed in the "Professional" category and set as private automatically',
    '_modzzz_professional_form_caption_file_title' => 'Title:',
    '_modzzz_professional_form_caption_file_price' => 'Price:',
    '_modzzz_professional_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_professional_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_professional_form_info_thumb_choice' => 'You can choose any image from your "Professional" category as professional thumbnail',
    '_modzzz_professional_form_caption_country' => 'Country',
    '_modzzz_professional_form_err_country' => 'Country is required',
    '_modzzz_professional_form_caption_city' => 'City',
    '_modzzz_professional_form_err_city' => 'City is required',
    '_modzzz_professional_form_caption_zip' => 'Zip/Postal Code',
    '_modzzz_professional_form_err_zip' => 'Zip/Postal code is required',
    '_modzzz_professional_form_err_email' => 'Invalid Email entered',

    '_modzzz_professional_action_title_edit' => 'Edit',
    '_modzzz_professional_action_title_delete' => 'Delete',
    '_modzzz_professional_action_title_share' => 'Share',
    '_modzzz_professional_action_add_to_featured' => 'Feature',    
    '_modzzz_professional_action_remove_from_featured' => 'Unfeature',
    '_modzzz_professional_action_add_professional' => 'Add Professional',
    '_modzzz_professional_action_my_professional' => 'My Profile',
    '_modzzz_professional_action_upload_photos' => 'Add Photos',
    '_modzzz_professional_action_upload_videos' => 'Add Videos',
    '_modzzz_professional_action_upload_sounds' => 'Add Sounds',
    '_modzzz_professional_action_upload_files' => 'Add Files',
    '_modzzz_professional_action_professional_home' => 'Home',

    '_modzzz_professional_action_title_inquire' => 'Send us an Inquiry', 
    '_modzzz_professional_action_title_spread' => 'Spread This', 
    '_modzzz_professional_action_title_promote' => 'Promote', 
    '_modzzz_professional_invitation_sent' => '%d Invitations have been sent',
	'_modzzz_professional_no_users_msg' => 'There are no users in your contacts',
	'_modzzz_professional_caption_invite' => 'Send Invitation',

    '_modzzz_professional_inquiry_subject' => 'Subject', 
    '_modzzz_professional_inquiry_subject_info' => 'Enter the Subject of your inquiry', 
    '_modzzz_professional_inquiry_text' => 'Message', 
    '_modzzz_professional_inquiry_text_info' => 'Enter your inquiry here. It will be forwarded to the Professional',  
	'_modzzz_professional_caption_make_inquiry' => 'Make Inquiry',
    '_modzzz_professional_inquiry_sent' => 'your inquiry has been sent',
    '_modzzz_professional_inquiry_not_sent' => 'your inquiry has not been sent',
	'_mma_professional_make_inquiry' => 'professional make inquiry',
  
	'_modzzz_professional_action_title_claim' => 'Claim Professional',
    '_modzzz_professional_claim_subject' => 'Subject', 
    '_modzzz_professional_claim_subject_info' => 'Enter the Subject of your claim', 
    '_modzzz_professional_claim_text' => 'Message', 
    '_modzzz_professional_claim_text_info' => 'Enter your proof of claim here. It will be forwarded to the Administrators',  
	'_modzzz_professional_caption_make_claim' => 'Make Claim - ',
    '_modzzz_professional_claim_sent' => 'your claim request has been sent',
    '_modzzz_professional_claim_not_sent' => 'your claim request has not been sent',
	 
	'_modzzz_professional_user_unknown' => 'Unknown', 
    '_modzzz_professional_price' => 'Price',

	'_modzzz_professional_block_contact' => 'Contact Details', 
	'_modzzz_professional_form_header_contact' => 'Contact Details', 
	'_modzzz_professional_form_header_business_contact' => 'Business Information / Contact Details', 
	'_modzzz_professional_location' => 'Location',
	'_modzzz_professional_map' => 'Google Map', 
	'_modzzz_professional_form_caption_fax' => 'Fax',
	'_modzzz_professional_form_caption_telephone' => 'Telephone',
	'_modzzz_professional_form_caption_mobile' => 'Mobile', 
	'_modzzz_professional_form_caption_email' => 'Email',
	'_modzzz_professional_form_info_website' => 'must be a valid URL (eg. http://www.mybusiness.com)', 
	'_modzzz_professional_form_caption_businessname' => 'Business Name',
	'_modzzz_professional_form_caption_address1' => 'Address 1',
	'_modzzz_professional_form_caption_address2' => 'Address 2', 
	'_modzzz_professional_form_err_professionaloption' => 'Please select an Option', 
	'_modzzz_professional_form_err_professionaltype' => 'Please select a Type',
 
	'_modzzz_professional_privacy_view_services' => 'View Services',
	'_modzzz_professional_menu_view_services' => 'Services',

    '_modzzz_professional_privacy_view_professional' => 'View Professional',
    '_modzzz_professional_privacy_comment' => 'Comment',
    '_modzzz_professional_privacy_rate' => 'Rate',
    '_modzzz_professional_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_professional_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_professional_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_professional_privacy_upload_files' => 'Upload Files',
    '_modzzz_professional_privacy_edit_professional' => 'Edit Professional',
    '_modzzz_professional_privacy_admins_only' => 'Admins Only',
    '_modzzz_professional_anonymous_note' => 'your name will not appear as the poster', 
    '_mma_professional_view_professional' => 'professional view professional', 
    '_mma_professional_browse' => 'professional browse', 
    '_mma_professional_search' => 'professional search', 
    '_mma_professional_add_professional' => 'professional add professional', 
    '_mma_professional_comments_delete_and_edit' => 'professional comments delete and edit', 
    '_mma_professional_edit_any_professional' => 'professional edit any professional', 
    '_mma_professional_delete_any_professional' => 'professional delete any professional', 
    '_mma_professional_mark_as_featured' => 'professional mark as featured', 
    '_mma_professional_approve_professional' => 'professional approve professional',   


	'_modzzz_professional_action_title_premium' => 'Get Premium',  
    '_modzzz_professional_page_title_premium' => 'Get Premium Professional',   
	'_mma_professional_purchase' => 'professional purchase package', 

    '_modzzz_professional_action_title_extend' => 'Extend',  
    '_modzzz_professional_page_title_extend' => 'Extend Professional listing',   
	'_mma_professional_extend' => 'professional extend', 

    '_modzzz_professional_action_title_relist' => 'Re-list',  
    '_modzzz_professional_page_title_relist' => 'Re-list Professional listing',  
	'_mma_professional_relist' => 'professional relist', 
  
    '_modzzz_professional_form_caption_current_no_package' => 'No Package currently',   
    '_modzzz_professional_form_caption_current_package' => 'Current Package',  
    '_modzzz_professional_form_caption_package_price' => 'Package Price',  
    '_modzzz_professional_form_caption_package_days' => 'Length of Professional',   
 	'_modzzz_professional_expires_never' => 'unlimited (never expires)', 
 	'_modzzz_professional_days' => 'days', 
 	'_modzzz_professional_form_caption_current_item' => 'Professional', 
    '_modzzz_professional_extend' => 'Extend',  
    '_modzzz_professional_block_statistics' => 'Statistics',  
    '_modzzz_professional_block_price' => 'Price',  
	 
	'_modzzz_professional_miles' => 'miles', 
    '_modzzz_professional_kilometers' => 'Km', 
	'_modzzz_professional_map_search_explanation' => 'Enter the City and Country (eg. miramer or miramer,US)', 

    '_modzzz_professional_enter_your_professional' => 'Enter Your Business Title',
    '_modzzz_professional_block_professional_create' => 'Post your Info', 
    '_modzzz_professional_block_latest_comments' => 'Latest Comments',
    '_modzzz_professional_block_forum' => 'Latest Forum Posts',
    '_modzzz_professional_posted_by' => 'Posted by',
    '_modzzz_professional_posted_in' => 'Posted In',
 
	'_modzzz_professional_allow_num_professionals' => 'Number of Professionals allowed', 	
	'_modzzz_professional_allow_videos' => 'Allow Videos', 	
	'_modzzz_professional_allow_photos' => 'Allow Photos', 	
	'_modzzz_professional_allow_sounds' => 'Allow Sounds', 	
	'_modzzz_professional_allow_files' => 'Allow Files', 	
 	'_modzzz_professional_featured' => 'Featured', 

	'_modzzz_professional_package_desc' => 'Package Description',  

    '_modzzz_professional_block_submenu_expired_professional' => 'Expired',
    '_modzzz_professional_page_title_expired' => 'Expired Professionals', 
	'_modzzz_professional_expires' => 'Expires',  
	'_modzzz_professional_never' => 'Never',  
 	'_modzzz_professional_featured_professional' => 'Featured Professional (never expires)',  
 
    '_modzzz_professional_page_title_broadcast' => 'Send broadcast message to all fans of this professional',
    '_modzzz_professional_msg_broadcast_message_sent' => 'Broadcast messages have been sent',
    '_modzzz_professional_msg_broadcast_no_recipients' => 'There are no fans for this professional yet',
    '_modzzz_professional_form_caption_broadcast_title' => 'Broadcast message title',
    '_modzzz_professional_form_err_broadcast_title' => 'Please enter from 3 to 100 characters', 
    '_modzzz_professional_form_caption_broadcast_message' => 'Broadcast message',
    '_modzzz_professional_form_err_broadcast_message' => 'Please enter at least 10 characters',
    '_modzzz_professional_action_title_broadcast' => 'Broadcast',
    '_mma_professional_broadcast_message' => 'professional broadcast message',

    '_modzzz_professional_block_coupons' => 'Coupons', 
    '_modzzz_professional_block_deals' => 'Deals',
    '_modzzz_professional_block_reviews' => 'Reviews',
    '_modzzz_professional_block_jobs' => 'Jobs',
  
    '_modzzz_professional_form_caption_subcategories' => 'Sub-Categories',
    '_modzzz_professional_form_caption_categories' => 'Categories',

    '_mma_professional_mark_as_favorite' => 'professional mark as favorite', 
    '_modzzz_professional_menu_favorite' => 'Favorites',
    '_modzzz_professional_msg_removed_from_favorite' => 'Professional was removed from favorite',
    '_modzzz_professional_msg_added_to_favorite' => 'Professional was added to favorite',
    '_modzzz_professional_page_title_browse_favorite' => 'Favorite Professionals',
    '_modzzz_professional_action_add_to_favorite' => 'Favorite',    
    '_modzzz_professional_action_remove_from_favorite' => 'Not Favorite',
    '_modzzz_professional_pay_invoice' => 'PAY INVOICE',

	'_modzzz_professional_menu_drilldown' => 'Drilldown',
    '_modzzz_professional_caption_browse_area_professionals' => 'Professionals in my Area',
 

    '_mma_professional_post_reviews' => 'professional post reviews',  
    '_modzzz_professional_page_title_reviews' => 'Professional\'s Testimonials', 
    '_modzzz_professional_block_latest_reviews' => 'Latest Testimonials', 
	'_modzzz_professional_action_title_review' => 'Post Testimonial', 
    '_modzzz_professional_review_text' => 'Testimonial', 
    '_modzzz_professional_review_text_info' => 'If you have used the services of this professional, you can post a testimonial for the benefit of others who may wish to use their services', 
    '_modzzz_professional_form_caption_post_review' => 'Post Testimonial - ', 
    '_modzzz_professional_review_saved' => 'Testimonial has been saved', 
    '_modzzz_professional_review_not_saved' => 'Testimonial has not been saved',  
    '_modzzz_professional_review' => 'Testimonial', 
    '_modzzz_professional_block_professional_reviews' => 'Testimonials',
    '_modzzz_professional_menu_view_reviews' => 'Testimonials', 
	'_modzzz_professional_review_for' => 'Testimonial for', 
	'_modzzz_professional_block_reviews' => 'Testimonials', 
	'_modzzz_professional_block_my_reviews' => 'My Professional Testimonials',  
 	'_modzzz_professional_action_title_post_review' => 'Post Review', 
	'_modzzz_professional_block_browse_reviews' => 'Browse Professional Testimonials',
	'_modzzz_professional_page_title_review_add' => 'Add a Testimonial',
	'_modzzz_professional_page_title_review_browse' => 'Browse Testimonials for Professional listing - {0}', 
    '_modzzz_professional_action_title_add_review' => 'Add Testimonial',
    '_modzzz_professional_page_title_review_edit' => 'Edit Testimonial',
    '_modzzz_professional_msg_professional_review_was_deleted' => 'Testimonial was successfully deleted',
    '_modzzz_professional_msg_pending_review_approval' => 'this testimonial is pending approval, please wait until it will be activated',
    '_modzzz_professional_menu_view_reviews' => 'Testimonials',  
	'_modzzz_professional_posted_for' => 'Posted for Professional',  
	'_modzzz_professional_posted_for_service' => 'Posted for Service',  
	'_modzzz_professional_posted' => 'Posted', 
	'_modzzz_professional_form_review_header_info' => 'Review Info',
	'_modzzz_professional_block_details' => 'Details',
	'_modzzz_professional_request_for' => 'Request for',

	'_modzzz_professional_friend' => 'Friend',
	
	/*added 7.1 */
    '_modzzz_professional_wall_added_new_comment' => 'commented on a',
    '_modzzz_professional_wall_added_new_items' => 'added {0} new professional listing(s)',
	'_modzzz_professional_single' => 'Professional listing',
    '_modzzz_professional_posted_in_topic' => 'Posted in Forum',
    '_modzzz_professional_posted_in_professional' => 'Posted in Professional', 
    '_modzzz_professional_block_calendar' => 'Calendar', 
	'_modzzz_professional_block_business_location' => 'Business Location', 
	'_modzzz_professional_block_location' => 'Location', 
    '_modzzz_professional_block_map' => 'Map View', 
    '_modzzz_professional_caption_location_for_professional' => 'Located at Place',
 	'_modzzz_professional_tags' => 'Tags',
 	'_sys_module_professional' => 'Professional listings', 
    '_modzzz_professional_adm_stats' => 'Pending Professional listings',
 
 	'_modzzz_professional_title_add_service' => 'Add Service to professional - ',
 	'_modzzz_professional_add_service_success' => 'Successfully added Service <b>{0}</b> to professional',
 	'_modzzz_professional_add_service_failed' => 'Failed to add Service <b>{0}</b>. Please double check the name',
   
	'_modzzz_professional_form_caption_service' => 'Service',
	'_modzzz_professional_form_info_service' => 'Enter username of member you want to add as service',
	'_modzzz_professional_form_caption_length' => 'Length',
	'_modzzz_professional_form_caption_currency' => 'Currency',
	'_modzzz_professional_form_err_length' => 'You must select Length',
	'_modzzz_professional_form_err_currency' => 'You must select Currency',
	'_modzzz_professional_form_caption_price' => 'Price',
	'_modzzz_professional_form_caption_price_type' => 'Price Type',
	'_modzzz_professional_fixed' => 'Fixed',
	'_modzzz_professional_minimum' => 'Minimum',
	'_modzzz_professional_negotiable' => 'Negotiable',
   
	'_modzzz_professional_form_caption_display_service' => 'Enable this service',
	'_modzzz_professional_form_caption_book_service' => 'Disable booking online for this service', 

	'_modzzz_professional_jobs_available' => 'Jobs Available',
    '_modzzz_professional_browse_professional_in_country' => 'Professionals in {0}', 

	'_modzzz_professional_located' => 'Located at',
 
	'_modzzz_professional_menu_view_website' => 'Website',  
 	'_modzzz_professional_title_website' => '{0} - Website', 

	'_modzzz_professional_role_renter' => 'Renter / Independent Contractor',
	'_modzzz_professional_role_owner' => 'Owner',
	'_modzzz_professional_role_employee' => 'Employee',

	'_modzzz_professional_form_th_open' => 'Open',  
	'_modzzz_professional_form_th_close' => 'Close',  
	'_modzzz_professional_form_option_am' => 'am',  
	'_modzzz_professional_form_option_pm' => 'pm',  
	'_modzzz_professional_form_caption_timezone' => 'Timezone',  
	'_modzzz_professional_form_header_availability' => 'What hours do you work?', 
	'_modzzz_professional_form_caption_book_online' => 'Allow my clients to book online', 

	'_modzzz_professional_week_days_sunday' => 'Sunday',   
	'_modzzz_professional_week_days_monday' => 'Monday',   
	'_modzzz_professional_week_days_tuesday' => 'Tuesday',   
	'_modzzz_professional_week_days_wednesday' => 'Wednesday',   
	'_modzzz_professional_week_days_thursday' => 'Thursday',   
	'_modzzz_professional_week_days_friday' => 'Friday',   
	'_modzzz_professional_week_days_saturday' => 'Saturday',

	'_modzzz_professional_service_length_15min' => '15 Mins', 
	'_modzzz_professional_service_length_30min' => '30 Mins', 
	'_modzzz_professional_service_length_45min' => '45 Mins', 
	'_modzzz_professional_service_length_1hr' => '1 Hour', 
	'_modzzz_professional_service_length_1hr_15min' => '1 Hour 15 Mins', 
	'_modzzz_professional_service_length_1hr_30min' => '1 Hour 30 Mins', 
	'_modzzz_professional_service_length_1hr_45min' => '1 Hour 45 Mins', 
	'_modzzz_professional_service_length_2hr' => '2 Hours',
	'_modzzz_professional_service_length_2hr_15min' => '2 Hours 15 Mins', 
	'_modzzz_professional_service_length_2hr_30min' => '2 Hours 30 Mins', 
	'_modzzz_professional_service_length_2hr_45min' => '2 Hours 45 Mins', 
	'_modzzz_professional_service_length_3hr' => '3 Hours',
	'_modzzz_professional_service_length_3hr_15min' => '3 Hours 15 Mins', 
	'_modzzz_professional_service_length_3hr_30min' => '3 Hours 30 Mins', 
	'_modzzz_professional_service_length_3hr_45min' => '3 Hours 45 Mins', 
	'_modzzz_professional_service_length_4hr' => '4 Hours',
	'_modzzz_professional_service_length_5hr' => '5 Hours',
	'_modzzz_professional_service_length_6hr' => '6 Hours',
 
	'_modzzz_professional_block_photo_samples' => 'Photo Samples',
	'_modzzz_professional_block_youtube_video_samples' => 'Video Samples (Youtube)',
	'_modzzz_professional_block_video_samples' => 'Video Samples',
 	'_modzzz_professional_action_upload_youtube' => 'Youtube Videos',
 
	'_modzzz_professional_form_caption_youtube_link' => 'Video URL', 
	'_modzzz_professional_form_caption_youtube_caption' => 'Video Title',  
	'_modzzz_professional_form_header_youtube' => 'Youtube Videos',
	'_modzzz_professional_form_caption_youtube_attach' => 'Video',
	'_modzzz_professional_form_info_youtube_attach' => 'you can add multiple Youtube Videos',
	'_modzzz_professional_form_caption_youtube_choice' => 'Existing Videos',  
	'_modzzz_professional_form_info_youtube_choice' => 'Uncheck Videos that you want to remove',  
    '_modzzz_professional_page_title_embed_video' => 'Embed Video',
    '_modzzz_professional_action_embed_video' => 'Embed Video',
 
	'_modzzz_professional_menu_view_clients' => 'Clients',

	'_modzzz_professional_form_service_header_info' => 'Service Info',
	'_modzzz_professional_action_title_post_service' => 'Add Service',
	'_modzzz_professional_page_title_service_add' => 'Post a Service',

	'_modzzz_professional_action_title_post_client' => 'Add Client',
	'_modzzz_professional_form_client_header_info' => 'Client Info',
	'_modzzz_professional_page_title_client_add' => 'Post a Client',
	'_modzzz_professional_page_title_manage_youtube' => 'Manage Youtube Videos',
  
	'_modzzz_professional_block_browse_services' => 'Browse Services',
	'_modzzz_professional_block_browse_clients' => 'Browse Clients',


	'_modzzz_professional_form_header_schedule' => 'Business Hours',
	'_modzzz_professional_from' => 'from',
	'_modzzz_professional_to' => 'to',
	'_modzzz_professional_closed' => 'Closed',
	'_modzzz_professional_time_am' => 'AM',
	'_modzzz_professional_time_pm' => 'PM',

	'_modzzz_professional_short_mon' => 'Mon',
	'_modzzz_professional_short_tue' => 'Tue',
	'_modzzz_professional_short_wed' => 'Wed',
	'_modzzz_professional_short_thur' => 'Thur',
	'_modzzz_professional_short_fri' => 'Fri',
	'_modzzz_professional_short_sat' => 'Sat',
	'_modzzz_professional_short_sun' => 'Sun',

	'_modzzz_professional_long_mon' => 'Monday',
	'_modzzz_professional_long_tue' => 'Tuesday',
	'_modzzz_professional_long_wed' => 'Wednesday',
	'_modzzz_professional_long_thur' => 'Thursday',
	'_modzzz_professional_long_fri' => 'Friday',
	'_modzzz_professional_long_sat' => 'Saturday',
	'_modzzz_professional_long_sun' => 'Sunday',

 	'_modzzz_professional_form_caption_schedule_choice' => 'Existing Business Hours',
	'_modzzz_professional_form_caption_schedule_attach' => 'Add Business Hours', 
	'_modzzz_professional_form_info_schedule_choice' => 'Uncheck business hours that you want to remove',
	'_modzzz_professional_form_info_schedule_attach' => 'You can add multiple business hours',

	'_modzzz_professional_form_caption_firstname' => 'First Name',
	'_modzzz_professional_form_caption_lastname' => 'Last Name',
	'_modzzz_professional_form_caption_phone_type' => 'Phone type',
	'_modzzz_professional_form_caption_note' => 'Note for Professional', 
	'_modzzz_professional_form_err_firstname' => 'You must enter First Name',
	'_modzzz_professional_form_err_lastname' => 'You must enter Last Name',
	'_modzzz_professional_form_err_note' => 'You must enter a Note for Professional',

	'_modzzz_professional_form_caption_requested_service' => 'Requested Service',
 
	'_modzzz_professional_phone_type_cell' => 'Cell',
	'_modzzz_professional_phone_type_home' => 'Home',
	'_modzzz_professional_phone_type_work' => 'Work',

    '_mma_professional_make_booking' => 'professional make booking', 
    '_modzzz_professional_action_title_book_me' => 'Book Me',  
    '_modzzz_professional_action_title_request_quote' => 'Request Quote', 
 	'_modzzz_professional_caption_request_quote' => 'Request Quote',
    '_modzzz_professional_request_sent' => 'your quote request has been sent',
    '_modzzz_professional_request_not_sent' => 'your quote request has not been sent',
     '_modzzz_professional_action_title_respond' => 'Respond', 

	'_modzzz_professional_and_up' => 'and up',
	'_modzzz_professional_negotiable_lower' => 'negotiable',
	'_modzzz_professional_for' => 'for',
 
	'_modzzz_professional_form_header_online_presence' => 'Online Presence',
	'_modzzz_professional_form_caption_website' => 'Website',
	'_modzzz_professional_form_caption_blog' => 'Blog',
	'_modzzz_professional_form_caption_facebook' => 'Facebook',
	'_modzzz_professional_form_caption_twitter' => 'Twitter',
	'_modzzz_professional_form_caption_linkedin' => 'Linkedin',
	'_modzzz_professional_form_caption_youtube' => 'Youtube',
	'_modzzz_professional_form_caption_pinterest' => 'Pinterest',

	'_modzzz_professional_my_website' => 'My Website',
	'_modzzz_professional_my_blog' => 'My Blog',
 	'_modzzz_professional_form_caption_service' => 'In reference to',
 	'_modzzz_professional_general_feedback' => 'General Feedback',
 
	'_modzzz_professional_block_quote_requests' => 'Requests for Quotes',
	'_modzzz_professional_page_title_service_edit' => 'Edit Service',

	'_modzzz_professional_caption_respond_quote' => 'Respond to Quote Request',
	'_modzzz_professional_form_caption_response_to' => 'Response to', 	 
	'_modzzz_professional_form_caption_response' => 'Response', 	
	'_modzzz_professional_respond_sent' => 'Response has been sent', 	
	'_modzzz_professional_respond_not_sent' => 'Response is not sent', 	
  
	'_modzzz_professional_caption_browse_professional_reviews' => 'Browse Reviews - {0}', 	
	'_modzzz_professional_caption_browse_professional_service_reviews' => 'Browse Reviews for Service - {0}', 	
 	'_modzzz_professional_page_title_service_browse' => 'Browse Services', 	
 	'_modzzz_professional_page_title_client_browse' => 'Browse Clients', 	

	'_modzzz_professional_form_header_online' => 'Online Presence', 

	'_modzzz_professional_regions_in_country' => 'Regions in {0}', 
    '_modzzz_professional_listed_in' => 'Listed in', 
    '_modzzz_professional_located_at' => 'Located at', 
	'_modzzz_restaurant_block_inquire' => 'Contact Us',
	'_modzzz_professional_block_schedule' => 'Business Hours',

	'_modzzz_professional_page_title_booking_add' => 'Post a Booking',
	'_modzzz_professional_page_title_booking_edit' => 'Edit Booking',
	'_modzzz_professional_msg_professional_booking_was_deleted' => 'Booking was deleted',
 
 	'_modzzz_professional_caption_price_service' => 'Price of Service',
	'_modzzz_professional_caption_length_service' => 'Length of Service',
 
	'_modzzz_professional_block_bookings' => 'Bookings',
	'_modzzz_professional_block_book_me' => 'Book Me',
	'_modzzz_professional_block_contact_me' => 'Contact Me',
	'_modzzz_professional_block_contacts' => 'Contact History',
	'_modzzz_professional_action_title_book_me' => 'Book Me',
	'_modzzz_professional_action_title_contact_me' => 'Contact Me',
 
	'_modzzz_professional_block_services' => 'Services', 
	'_modzzz_professional_form_booking_header_info' => 'Booking Info', 
	'_modzzz_professional_form_caption_booking_name' => 'Services', 
	'_modzzz_professional_form_caption_name' => 'Your Name',
 	'_modzzz_professional_form_caption_booking_details' => 'Booking details',
	'_modzzz_professional_contact' => 'Contact', 
	'_modzzz_professional_form_caption_start_time' => 'Start Time', 
	'_modzzz_professional_form_err_start_time' => 'You must enter start time', 
	'_modzzz_professional_form_caption_end_time' => 'End Time', 
	'_modzzz_professional_form_err_end_time' => 'You must enter end time', 
 	'_modzzz_professional_form_header_booking_schedule' => 'Booking Schedule Requested', 
	'_modzzz_professional_action_title_confirmed' => 'Confirmed', 
	'_modzzz_professional_action_title_cancel' => 'Cancel', 
	'_modzzz_professional_msg_professional_booking_was_confirmed' => 'The booking was confirmed', 
 
	'_modzzz_professional_tab_pending' => 'Pending', 
	'_modzzz_professional_tab_approved' => 'Approved', 
 	'_modzzz_professional_block_post_review' => 'Service Feedback', 
	'_modzzz_professional_caption_browse_by_country' => 'Browse by Country', 
	'_modzzz_professional_form_caption_proprietor' => 'Proprietor', 
	'_modzzz_professional_form_caption_businessname' => 'Business Name',  
	'_modzzz_professional_block_inquire' => 'Inquire', 
	'_modzzz_professional_msg_access_denied' => 'Your Membership Level does not allow access to this feature', 

);
