<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Professional
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Services Directory';

$aLangContent = array(
  

    '_modzzz_professional_fans' => 'fans',
    '_modzzz_professional_sbs_join' => 'nouveau fan',
    '_modzzz_professional_block_fans' => 'Fans',
    '_modzzz_professional_block_fans_unconfirmed' => 'Fans non confirmés',
	'_modzzz_professional_block_my_professionals_joined' => 'Joined Professionals',
    '_modzzz_professional_caption_manage_fans' => 'Gérer Fans',
    '_modzzz_professional_menu_view_fans' => 'Fans',
    '_modzzz_professional_page_title_fans' => 'Fans du Professionnel',
    '_modzzz_professional_action_manage_fans' => 'Gérer Fans',
    '_modzzz_professional_privacy_view_fans' => 'Voir Fans',
    '_modzzz_professional_privacy_fans_only' => 'Fans uniquement',
    '_modzzz_professional_privacy_fans' => 'Fans',

    '_modzzz_professional_spy_join' => '<a href="{profile_link}">{profile_nick}</a> est entrain de suivre <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_professional_page_title_browse_by_author_joined_professionals' => '\'s joined professionals',
    '_modzzz_professional_msg_joined_already' => 'Vous êtes dejà fan de ce professionnel',
    '_modzzz_professional_msg_joined_request_pending' => 'Vous êtes dejà fan de ce professionnel. Veuillez patienter pendant que votre demande est entain d\'être traitée ce professionnel.',
    '_modzzz_professional_msg_join_success' => 'Vous êtes devenu fan de ce professionnel',
    '_modzzz_professional_msg_join_success_pending' => 'Vous êtes devenu fan de ce professionnel.Veuillez patienter pendant que votre demande est entain d\'être traitée ce professionnel.',
	'_modzzz_professional_msg_leave_success' => 'Vous n\'êtes plus fan de ce professionnel',
    '_modzzz_professional_form_caption_join_confirmation' => 'Confirmation de devenir fan',
    '_modzzz_professional_form_info_join_confirmation' => 'If enabled, professional admin(s) will have to confirm each user before he/she becomes a fan.',
    '_modzzz_professional_form_join_confirmation_disabled' => 'Désactivé',
    '_modzzz_professional_form_join_confirmation_enabled' => 'Activé',
    '_modzzz_professional_form_err_join_confirmation' => 'Join confirmation field must be 0 or 1',
    '_modzzz_professional_action_title_join' => 'Devenir Fan',
    '_modzzz_professional_action_title_leave' => 'Ne plus être Fan',
    '_modzzz_professional_privacy_join' => 'Devenir Fan',
 
    '_modzzz_professional_packages_empty' => 'Il n\'y a aucun forfait tarifaire ', 
    '_modzzz_professional_package_description' => 'Description', 
    '_modzzz_professional_package_featured' => 'En vedette', 

    '_modzzz_professional_featured_status' => 'Statut en vedette', 
    '_modzzz_professional_featured_until' => 'En vedette jusqu\'au', 
    '_modzzz_professional_not_featured' => 'N\'est pas en vedette', 
 	'_modzzz_professional_extend_featured' => 'Prolonger la mise en vedette',  
	'_modzzz_professional_purchase_featured' => 'Mettez en vedette votre annonce', 
	'_modzzz_professional_form_caption_currency' => 'Devise',  

    '_modzzz_professional_menu_packages' => 'Packages', 
    '_modzzz_professional_page_title_packages' => 'Business Packages', 
    '_modzzz_professional_block_packages' => 'Business Packages', 

    '_modzzz_professional_menu_view_forum' => 'Forum', 
    '_modzzz_professional_privacy_post_in_forum' => 'Post In Forum',
 
   	'_modzzz_professional_form_header_video_embed' => 'Ajouter une vidéo Youtube',
   	'_modzzz_professional_caption_video_embed_code' => 'Lien de la vidéo Youtube',
	'_modzzz_professional_form_info_video_embed_code' => 'Enter soit le lien de la vidéo ou le code d\'intégration de votre vidéo. Enter the Embed Code for other video sharing site (eg &lt;embed&gt;....&lt;/embed&gt;)',
   	'_modzzz_professional_block_video_embed' => 'External Video',
 
	'_modzzz_professional_caption_membership_view_filter' => 'Autoriser la consultation de votre fiche professionnelle par catégorie des membres',
	'_modzzz_professional_err_membership_view_filter' => 'Valeur incorrecte', 
    '_modzzz_professional_info_membership_view_filter' => 'seuls ces membres pourront voir cette fiche professionnelle',
    '_modzzz_professional_membership_filter_none' => 'Autoriser tout le monde',	

    '_mma_professional_files_add' => 'professional files add',  
    '_mma_professional_photos_add' => 'professional photos add',  
    '_mma_professional_videos_add' => 'professional videos add',  
    '_mma_professional_sounds_add' => 'professional sounds add',  
	
    '_modzzz_professional_continue' => 'Continuer',  
    '_modzzz_professional_admin_assign' => 'Assign to Claimant',  
    '_modzzz_professional_menu_manage_claims' => 'Claims',  
    '_modzzz_professional_claimed_by' => 'Claimed by',  
    '_modzzz_professional_on' => 'on',  
    '_modzzz_professional_yes' => 'Yes',  
    '_modzzz_professional_no' => 'No',  
 
	'_modzzz_professional_package_videos' => 'Vidéos',  	
	'_modzzz_professional_package_photos' => 'Photos',  	
	'_modzzz_professional_package_sounds' => 'Sounds',  	
	'_modzzz_professional_package_files' => 'Documents', 

	'_modzzz_professional_block_professional_states' => 'Régions', 
 
    '_mma_professional_purchase_featured' => 'professional purchase featured', 
    '_mma_professional_make_claim' => 'professional make claim', 
 
	'_modzzz_professional_block_browse_categories_drilldown' => 'Catégories', 
	'_modzzz_professional_category_drilldown_for_item' => 'Catégories pour <b>{0}</b>', 

    '_modzzz_professional_regions_for_country' => 'Régions pour',  
	'_modzzz_professional_block_browse_state' => 'Parcours des professionnels par région', 
	'_modzzz_professional_block_browse_state_professionals' => ' <i class="sys-icon map-marker"></i> Professionnels par région', 
	'_modzzz_professional_block_account' => 'Professionels près de chez moi',  
	'_modzzz_professional_block_browse_country' => 'Parcourir des professionnels par pays', 
	'_modzzz_professional_page_title_local' => 'Parcourir des professionnels locaux',  
	'_modzzz_professional_caption_browse_local' => 'Parcourir des professionnels | {0}', 
	'_modzzz_professional_menu_local' => 'Local', 
 	'_modzzz_professional_block_local' => 'Plus de professionnels locaux',
	'_modzzz_professional_block_other' => 'Autres fiches professionnelles de ce membre',
 	'_modzzz_professional_caption_browse_other' => 'Autres professionnels par {0}',


	'_modzzz_professional_action_title_purchase_featured' => 'Mettre en vedette',
	'_modzzz_professional_action_title_extend_featured' => 'Prolonger la mise en vedette',  
	'_modzzz_professional_purchase_featured_status' => 'Mettez en vedette votre fiche',  
	'_modzzz_professional_quantity' => 'Quantité',   
	'_modzzz_professional_purchase_success' => 'Vous avez acheté avec succès {0} jours de mise en vedette de votre fiche professionnelle', 
	'_modzzz_professional_purchase_fail' => 'Votre tentative d\'achat du statut en vedette a échoué',  
	'_modzzz_professional_purchase_failed' => 'Votre tentative d\'achat du statut en vedette a échoué',  
	'_modzzz_professional_transaction_completed_already' => 'Cette transaction a déjà eu lieu',  
	'_modzzz_professional_featured_cost_per_day' => 'Coût par jour',  
	'_modzzz_professional_caption_num_featured_days' => 'Nombre de jours de mise en vedette',    
	'_modzzz_professional_caption_err_featured_days' => 'Vous devez entrer le nombre de jours de mise en vedette de votre fiche professionnelle',    
	'_modzzz_professional_get_featured' => 'Mettez en vedette votre fiche professionnelle',  
 

    '_modzzz_professional_parent_categories' => 'Parent', 
    '_modzzz_professional_block_category_professional' => 'Professionels dans cette catégorie',
    '_modzzz_professional_block_subcategories' => 'Sous-Catégories',  
    '_modzzz_professional_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button', 
	'_modzzz_professional_categ_name' => 'Category',
	'_modzzz_professional_categ_btn_edit' => 'Edit',
	'_modzzz_professional_categ_btn_delete' => 'Delete',
	'_modzzz_professional_categ_btn_add' => 'Add',
	'_modzzz_professional_categ_btn_save' => 'Save',
	'_modzzz_professional_categ_btn_subcategories' => 'Sub-Categories', 
 	'_modzzz_professional_categories' => 'Categories',
 	'_modzzz_professional_menu_admin_manage_categories' => 'Categories',
  	'_modzzz_professional_menu_admin_manage_subcategories' => 'Sub-Cats',
  	'_modzzz_professional_subcategories' => 'Sub-Categories',
    '_modzzz_professional_all_categories' => 'Toutes les catégories',
    '_modzzz_professional_block_categories' => 'Catégories',
    '_modzzz_professional_block_professional_subcategories' => 'Sous-Catégories',
    '_modzzz_professional_block_answer_categories' => 'Catégories',
    '_modzzz_professional_menu_categories' => 'Catégories',
    '_modzzz_professional_page_title_browse_by_category' => 'Parcourir les professionnels par catégorie: ',
    '_modzzz_professional_form_caption_category' => 'Catégorie',
    '_modzzz_professional_form_err_category' => 'Catégorie non valide', 
	'_modzzz_professional_page_title_category' => 'Category', 
    '_modzzz_professional_page_title_categories' => 'Catégories des fiches professionnelles',
    '_modzzz_professional_page_title_subcategories' => 'Sous-Catégories des fiches professionnelles', 
    '_modzzz_professional_professionals_in_category' => '<b>Professionels</b> dans <b>%s</b>',  
    '_modzzz_professional_block_professional' => 'Professionels', 
    
	'_modzzz_professional_packages' => 'Packages',
	'_modzzz_professional_package_name' => 'Package Name',
	'_modzzz_professional_package_price' => 'Package Price',
	'_modzzz_professional_package_days' => 'Package Days',
	'_modzzz_professional_form_caption_package' => 'Business Package',
	'_modzzz_professional_form_err_package' => 'Veuillez sélection un Business Package',  
	'_modzzz_professional_purchaser' => 'Acheteur', 
	'_modzzz_professional_invoice_no' => 'Facture #', 
	'_modzzz_professional_package' => 'Package', 
	'_modzzz_professional_invoice_date' => 'Date de la facture', 
	'_modzzz_professional_invoice_due_date' => 'Date d\'échéance', 
	'_modzzz_professional_status' => 'Statut',
	'_modzzz_professional_pending' => 'En attente',
	'_modzzz_professional_paid' => 'Payé',
	'_modzzz_professional_active' => 'Actif',
	'_modzzz_professional_inactive' => 'Non actif',
	'_modzzz_professional_approved' => 'Approuvé',
	'_modzzz_professional_expired' => 'Expiré', 
	'_modzzz_professional_block_submenu_pending_invoices' => 'Factures en attente',
	'_modzzz_professional_block_submenu_orders' => 'Commandes',
	'_modzzz_professional_page_title_orders' => 'Commandes', 
	'_modzzz_professional_page_title_invoices' => 'Factures', 
	'_modzzz_professional_menu_manage_invoices' => 'Factures', 
	'_modzzz_professional_menu_manage_packages' => 'Packages',
	'_modzzz_professional_menu_manage_orders' => 'Commandes',
	'_modzzz_professional_payment_method' => 'Mode de paiement
',
	'_modzzz_professional_total' => 'Total',
	'_modzzz_professional_invoice_id' => 'Facture ID',
	'_modzzz_professional_next_due_date' => 'Prochaine date d\'échéance',
	'_modzzz_professional_order_no' => 'Commande #',
	 '_modzzz_professional_product_status' => 'Statut du produit',
	'_modzzz_professional_order_date' => 'Date de commande',
	'_modzzz_professional_purchase_failed' => 'Désolé, il y avait un problème avec le paiement. Affichez vos commandes en attente <a href="{0}"> ici </a>.',
	'_modzzz_professional_transaction_completed_already' => 'La transaction existe déjà. Cliquez <a href="{0}"> ici </a> pour afficher votre fiche professionnelle.',
	'_modzzz_professional_purchase_success' => 'Merci pour votre paiement. Cliquez <a href="{0}"> ici </a> pour afficher votre fiche professionnelle.',  
	'_modzzz_professional_trans_save_failed' => 'Votre paiement est confirmé, mais un problème est survenu lors de l\'enregistrement de la transaction. Veuillez contacter l\'administrateur avec vos détails de transaction Paypal afin qu\'ils puissent traiter manuellement votre commande.',
	'_modzzz_professional_post_purchase_header' => 'Inscription dans l\'annuaire des professionnels',  
 

	'_modzzz_professional_caption_state' => 'Région',  
	'_modzzz_professional_regions_for_country' => 'Régions pour',  
	'_modzzz_professional_block_browse_state' => 'Consulter les professionnels par régions', 
	'_modzzz_professional_block_browse_state_events' => 'Consulter les professionnels par région',
	'_modzzz_professional_block_browse_country' => 'Consulter les professionnels par pays', 
	'_modzzz_professional_page_title_local' => 'Consulter les professionnels locaux',  
	'_modzzz_professional_caption_browse_local' => 'Consulter les professionnels loacux | {0}', 
	'_modzzz_professional_menu_local' => 'Local',
 	'_modzzz_professional_caption_search' => 'rechercher des professionnels',
 

    '_modzzz_professional_no_professionals' => 'Il n\'y a aucun professionnel',
    '_sbs_txt_title_modzzz_professional' => 'Professionnels',
    '_modzzz_professional' => 'Professionnel',
    '_modzzz_professional_plural' => 'vs',
    '_modzzz_professional_add' => 'Ajouter un professionnel ',
    '_modzzz_professional_wall_added_new' => 'added new',
    '_modzzz_professional_wall_object' => 'Fiche professionnelle',
    '_modzzz_professional_for_professional' => 'pour %s',
    '_modzzz_professional_professional_single' => 'Fiche professionnelle',
    '_modzzz_professional_professional_plural' => 'Fiche professionnelles',
    '_modzzz_professional_user_unknown' => 'Quelqu\'un',
    '_modzzz_professional_disabled' => 'Désactivé',
    '_modzzz_professional_enabled' => 'Activé',
    '_modzzz_professional_cannot_delete_default_parent' => 'Cannot Delete Default Parent Category',
	    
	 '_modzzz_professional_spy_post' => '<a href="{profile_link}">{profile_nick}</a> s\'est inscrit dans l\'annuaire des professionnels: <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_professional_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> a modifié sa fiche professionnele: <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_professional_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> a noté un professionnel: <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_professional_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> a commenté sur la fiche d\'un professionnel: <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_professional_sbs_change' => 'information mise à jour',
    '_modzzz_professional_sbs_comment' => 'un nouveau commentaire',
    '_modzzz_professional_sbs_rate' => 'Evaluation mise à jour',
 
    '_modzzz_professional_tab_featured' => 'En vedette',
    '_modzzz_professional_tab_recent' => 'Récent',
    '_modzzz_professional_tab_top' => 'Top',
    '_modzzz_professional_tab_popular' => 'Populaire',

    '_modzzz_professional_block_submenu_main' => 'Principal',
    '_modzzz_professional_block_submenu_add_professional' => 'Ajouter',
    '_modzzz_professional_block_submenu_manage_professional' => 'Gérer',
    '_modzzz_professional_block_submenu_pending_professional' => 'En attente d\'approbation',

    '_modzzz_professional_block_actions' => 'Actions',
    '_modzzz_professional_block_rate' => 'Noter',    
    '_modzzz_professional_block_info' => 'Info',
    '_modzzz_professional_block_desc' => 'Description',
    '_modzzz_professional_block_photo' => 'Photos',
    '_modzzz_professional_block_video' => 'Vidéos',
    '_modzzz_professional_block_sound' => 'Sounds',
    '_modzzz_professional_block_files' => 'Documents',
    '_modzzz_professional_block_file' => 'Documents',
    '_modzzz_professional_block_comments' => 'Commentaires',
    '_modzzz_professional_block_latest_featured_professional' => ' <i class="sys-icon trophy"></i>  Professionnels à l\'honneur',
    '_modzzz_professional_block_recent' => 'Professionnels récemment inscrits',
    '_modzzz_professional_block_popular' => 'Professionnels les plus populaires',
    '_modzzz_professional_block_top' => 'Professionnels les plus notés',
    '_modzzz_professional_block_search' => '<i class="sys-icon search"></i> Rechercher des professionnels',
    '_modzzz_professional_block_professional_categories' => 'Catégories des professionnels',

    '_modzzz_professional_block_administration_owner' => 'Administration',
    '_modzzz_professional_block_users_professional' => "Ma fiche professionnell",
    '_modzzz_professional_block_my_professional' => 'Ma fiche professionnelle',
    '_modzzz_professional_block_area_professionals' => 'Professionnels près de chez moi',

    '_modzzz_professional_block_homepage' => 'Professionnels',

    '_modzzz_professional_caption_add' => 'Inscription dans l\'annuaire des professionnels',
    '_modzzz_professional_caption_share_professional' => 'Partager',
    '_modzzz_professional_caption_admin_actions' => 'Links',
    '_modzzz_professional_caption_pending_approval' => 'Professionnel en attente d\'a^^robation', 
    
	'_modzzz_professional_menu_manage_parents' => 'Parent Cats',
    '_modzzz_professional_menu_manage_categories' => 'Cats',
    '_modzzz_professional_categ_btn_save' => 'Save',
    '_modzzz_professional_categ_btn_edit' => 'Edit',
    '_modzzz_professional_categ_btn_delete' => 'Delete',
    '_modzzz_professional_categ_name' => 'Name',
    '_modzzz_professional_categ_icon' => 'Icon',
    '_modzzz_professional_categ_present_icon' => 'Present Icon',
    '_modzzz_professional_categ_btn_add' => 'Add',

    '_modzzz_professional_menu_root' => 'Professionnels',
    '_modzzz_professional_menu_main' => 'Annuaire des professionnels',
    '_modzzz_professional_menu_recent' => 'Récent',
    '_modzzz_professional_menu_top_rated' => 'Lesmieux notés',
    '_modzzz_professional_menu_popular' => 'Populaire',
    '_modzzz_professional_menu_featured' => 'En Vedette',
    '_modzzz_professional_menu_tags' => 'Tags',
    '_modzzz_professional_menu_categories' => 'Catégories',
    '_modzzz_professional_menu_calendar' => 'Calendrier',
    '_modzzz_professional_menu_search' => 'Rechercher des professionnels',
    '_modzzz_professional_menu_view_professional' => 'Fiche Pro',
    '_modzzz_professional_menu_view_comments' => 'Commentaires',
    '_modzzz_professional_menu_view_photos' => 'Photos',
    '_modzzz_professional_menu_view_videos' => 'Videos',
    '_modzzz_professional_menu_view_sounds' => 'Sounds',
    '_modzzz_professional_menu_view_files' => 'Documents',
    '_modzzz_professional_menu_my_professional_profile' => 'Ma fiche professionnelle',

    '_modzzz_professional_menu_admin_pending_approval' => 'En attente',
    '_modzzz_professional_menu_admin_entries' => 'Admin Professionals',
    '_modzzz_professional_menu_admin_add_entry' => 'Add',
    '_modzzz_professional_menu_admin_settings' => 'Settings',
    
    '_modzzz_professional_page_title_home' => 'Accueil - Annuaire des professionnels',
    '_modzzz_professional_page_title_calendar' => 'Calendrier des inscrptions des professionnels',
    '_modzzz_professional_page_title_comments' => 'Commentaires',
    '_modzzz_professional_page_title_photos' => 'Photos',
    '_modzzz_professional_page_title_videos' => 'Vidéos',
    '_modzzz_professional_page_title_sounds' => 'Sounds',
    '_modzzz_professional_page_title_files' => 'Documents',
    '_modzzz_professional_page_title_my_professional' => 'Mes fiches Professionnelles',
    '_modzzz_professional_page_title_search' => 'Rechercher des professionnels',
    '_modzzz_professional_page_title_add' => 'Inscription dans l\'annuaire des professionnels', 
    '_modzzz_professional_page_title_edit' => 'Modifier Fiche Professionnelle',
    '_modzzz_professional_page_title_administration' => 'Professionals Administration',
    '_modzzz_professional_admin_block_administration' => 'Admin.',

    '_modzzz_professional_page_title_browse' => 'Consulter les fiches des professionnels',
    '_modzzz_professional_page_title_pending_approval' => 'Fiche professionnelle en attente d\'approbation',
    '_modzzz_professional_page_title_search_results' => 'Résultats de votre recherche sur les professionnels',
    '_modzzz_professional_page_title_browse_by_author' => "\'s professionals",
    '_modzzz_professional_page_title_admin_professional' => 'Administer ma fiche professionnelle',
    '_modzzz_professional_page_title_browse_by_category' => 'Professionnels par catégorie: ',
    '_modzzz_professional_page_title_browse_by_tag' => 'Browse Professionals By Tag: ',
    '_modzzz_professional_page_title_browse_recent' => 'Professionnels récemment inscrits',
    '_modzzz_professional_page_title_browse_top_rated' => 'Professionnels les mieux notés',
    '_modzzz_professional_page_title_browse_popular' => 'Professionels les plus populaires',
    '_modzzz_professional_page_title_browse_featured' => 'Des professionnels en vedette',
    '_modzzz_professional_page_title_browse_by_day' => 'Consulter des professionnels par date: ',
    '_modzzz_professional_page_title_tags' => 'Mots clés',
    '_modzzz_professional_page_title_upload_photos' => 'Ajouter des Photos',
    '_modzzz_professional_page_title_upload_videos' => 'Ajouter des Vidéos',
    '_modzzz_professional_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_professional_page_title_upload_files' => 'Ajouter des documents',

    '_modzzz_professional_msg_pending_approval' => 'Votre inscription dans l\'annuaire des professionnels est en attente d\'approbation par notre staff , veuillez patienter jusqu\'à ce qu\'elle soit approuvée',
    '_modzzz_professional_msg_professional_was_deleted' => 'Fiche professionnelle supprimée',
    '_modzzz_professional_msg_removed_from_featured' => 'Fiche professionnelle n\'est plus en vedette',
    '_modzzz_professional_msg_added_to_featured' => 'Fiche professionnelle mise en vedette',
    '_modzzz_professional_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_professional_msg_you_have_pending_approval_professional' => 'Vous avez <a href="%s">%d fiche professionnelle(s) en attente d\'approbation</a>',
    '_modzzz_professional_msg_you_have_no_professional' => 'Vous n\'avez aucune fiche professionnelle. <a href="%s">Cliquer ici</a> pour vous inscrire dans l\'annuaire des professionnels indépendants.',
    '_modzzz_professional_msg_you_have_some_professional' => 'Vous avez <a href="%s">%d fiche professionnelle(s)</a>. <a href="%s">Cliquer ici</a> pour ajouter une autre si possible.',

    '_modzzz_professional_admin_delete' => 'Delete',
    '_modzzz_professional_admin_activate' => 'Activate',
    '_modzzz_professional_admin_add_new_professional' => 'Add New Professional',
    '_modzzz_professional_admin_professional' => 'Admin Professional',
    '_modzzz_professional_admin_settings' => 'Admin Settings',


    '_modzzz_professional_form_header_business_location' => 'Localisation de votre entreprise ou activités',  
    '_modzzz_professional_form_header_location' => 'Localisation',  
    '_modzzz_professional_form_header_contact' => 'Détails de contact',   
    '_modzzz_professional_form_header_info' => 'Info',
    '_modzzz_professional_form_header_images' => 'Photos',
    '_modzzz_professional_form_header_videos' => 'Vidéos',
    '_modzzz_professional_form_header_sounds' => 'Sounds',
    '_modzzz_professional_form_header_files' => 'Documents',
    '_modzzz_professional_form_header_privacy' => 'Paramètres de confidentialité',
    '_modzzz_professional_form_caption_client_details' => 'Détails sur le client', 
    '_modzzz_professional_form_caption_client_name' => 'Nom du client',
    '_modzzz_professional_form_caption_title' => 'Titre', 
    '_modzzz_professional_form_err_title' => 'Veuillez entrer de 3 à 100 caractères',
    '_modzzz_professional_form_caption_desc' => 'Description',
    '_modzzz_professional_form_err_desc' => 'Veuillez entrer au moins 20 caractères',
    '_modzzz_professional_form_err_tags' => 'Please enter tags',
    '_modzzz_professional_form_caption_author_id' => 'Auteur',
    '_modzzz_professional_form_info_author' => 'Author profile ID number',
    '_modzzz_professional_form_caption_keyword' => 'Mot clé',
    '_modzzz_professional_form_err_keyword' => 'Veuillez entrer de 3 à 100 caractères',
    '_modzzz_professional_form_caption_category' => 'Catégorie',
    '_modzzz_professional_form_err_category' => 'Veuillez sélectionner une catégorie',    
    '_modzzz_professional_form_caption_images_choice' => 'Choisir',
    '_modzzz_professional_form_info_images_choice' => 'You can choose several images from your "Professional" category',
    '_modzzz_professional_form_caption_images_upload' => 'Upload',    
    '_modzzz_professional_form_info_images_upload' => 'Image will be placed in the "Professional" category automatically',
    '_modzzz_professional_form_caption_videos_choice' => 'Choose',
    '_modzzz_professional_form_info_videos_choice' => 'You can choose several videos from your "Professional" category',
    '_modzzz_professional_form_caption_videos_upload' => 'Upload',
    '_modzzz_professional_form_info_videos_upload' => 'Video will be placed in the "Professional" category automatically',
    '_modzzz_professional_form_caption_sounds_choice' => 'Choose',
    '_modzzz_professional_form_info_sounds_choice' => 'You can choose several sounds from your "Professional" category',
    '_modzzz_professional_form_caption_sounds_upload' => 'Upload',
    '_modzzz_professional_form_info_sounds_upload' => 'Sound will be placed in the "Professional" category automatically',
    '_modzzz_professional_form_caption_files_choice' => 'Choisir',
    '_modzzz_professional_form_info_files_choice' => 'Décochez la case pour supprimer le fichier de cette fiche professionnelle',
    '_modzzz_professional_form_caption_files_upload' => 'Transférer un document',
    '_modzzz_professional_form_info_files_upload' => 'File will be placed in the "Professional" category and set as private automatically',
    '_modzzz_professional_form_caption_file_title' => 'Titre:',
    '_modzzz_professional_form_caption_file_price' => 'Tarif:',
    '_modzzz_professional_form_caption_file_allow_purcase_to' => 'Autoriser l\'achat à:',
    '_modzzz_professional_form_caption_thumb_choice' => 'Choisir une vignette',
    '_modzzz_professional_form_info_thumb_choice' => 'You can choose any image from your "Professional" category as professional thumbnail',
    '_modzzz_professional_form_caption_country' => 'Pays',
    '_modzzz_professional_form_err_country' => 'Veuille sélectionner le pays',
    '_modzzz_professional_form_caption_city' => 'Ville',
    '_modzzz_professional_form_err_city' => 'Veuille entrer le nom de la ville',
    '_modzzz_professional_form_caption_zip' => 'Code Postal',
    '_modzzz_professional_form_err_zip' => 'Le code postal est requis',
    '_modzzz_professional_form_err_email' => 'Vous avez saisi un email non valide',

    '_modzzz_professional_action_title_edit' => 'Modifier',
    '_modzzz_professional_action_title_delete' => 'Supprimer',
    '_modzzz_professional_action_title_share' => 'Partager',
    '_modzzz_professional_action_add_to_featured' => 'Mettre en vedette',    
    '_modzzz_professional_action_remove_from_featured' => 'Ne plus mettre en vedette',
    '_modzzz_professional_action_add_professional' => 'Ajouter une fiche professionnelle',
    '_modzzz_professional_action_my_professional' => 'Mon Profil',
    '_modzzz_professional_action_upload_photos' => 'Ajouter des Photos',
    '_modzzz_professional_action_upload_videos' => 'Ajouter des Viéeos',
    '_modzzz_professional_action_upload_sounds' => 'Add Sounds',
    '_modzzz_professional_action_upload_files' => 'Ajouter des documents',
    '_modzzz_professional_action_professional_home' => 'Accueil',

    '_modzzz_professional_action_title_inquire' => 'Envoyez-nous une demande de renseignements', 
    '_modzzz_professional_action_title_spread' => 'Envoyer un message', 
    '_modzzz_professional_action_title_promote' => 'Promouvoir', 
    '_modzzz_professional_invitation_sent' => '%d Invitations envoyée',
	'_modzzz_professional_no_users_msg' => 'Votre liste de contacts est vide',
	'_modzzz_professional_caption_invite' => 'Envoyer des invitation',

    '_modzzz_professional_inquiry_subject' => 'Objet de votre demande de renseignements ', 
    '_modzzz_professional_inquiry_subject_info' => 'Entrez l\'objet de votre demande de renseignement', 
    '_modzzz_professional_inquiry_text' => 'Message', 
    '_modzzz_professional_inquiry_text_info' => 'Entrez votre demande de renseignement ici. Elle sera transmise au professionnel',  
	'_modzzz_professional_caption_make_inquiry' => 'Se renseigner',
    '_modzzz_professional_inquiry_sent' => 'Votre demande a été envoyée',
    '_modzzz_professional_inquiry_not_sent' => 'Votre demande n\'a pas été envoyée',
	'_mma_professional_make_inquiry' => 'professional make inquiry',
  
	'_modzzz_professional_action_title_claim' => 'Claim Professional',
    '_modzzz_professional_claim_subject' => 'Subject', 
    '_modzzz_professional_claim_subject_info' => 'Enter the Subject of your claim', 
    '_modzzz_professional_claim_text' => 'Message', 
    '_modzzz_professional_claim_text_info' => 'Enter your proof of claim here. It will be forwarded to the Administrators',  
	'_modzzz_professional_caption_make_claim' => 'Make Claim - ',
    '_modzzz_professional_claim_sent' => 'your claim request has been sent',
    '_modzzz_professional_claim_not_sent' => 'your claim request has not been sent',
	 
	'_modzzz_professional_user_unknown' => 'Inconnu', 
    '_modzzz_professional_price' => 'Tarif',

	'_modzzz_professional_block_contact' => 'Détails de contact', 
	'_modzzz_professional_form_header_contact' => 'Détails de contact', 
	'_modzzz_professional_form_header_business_contact' => 'Information de votre activité/entreprise |  Détails de contact', 
	'_modzzz_professional_location' => 'Localisation',
	'_modzzz_professional_map' => 'Google Map', 
	'_modzzz_professional_form_caption_fax' => 'Fax',
	'_modzzz_professional_form_caption_telephone' => 'Téléphone',
	'_modzzz_professional_form_caption_mobile' => 'Mobile', 
	'_modzzz_professional_form_caption_email' => 'Email',
	'_modzzz_professional_form_info_website' => 'doit être un url valide(eg. http://www.mybusiness.com)', 
	'_modzzz_professional_form_caption_businessname' => 'Nom de votre entreprise',
	'_modzzz_professional_form_caption_address1' => 'Adresse 1',
	'_modzzz_professional_form_caption_address2' => 'Adresse 2', 
	'_modzzz_professional_form_err_professionaloption' => 'PVeuillez sélectionner une option', 
	'_modzzz_professional_form_err_professionaltype' => 'Veuillez sélectionner un type',
 
	'_modzzz_professional_privacy_view_services' => 'Qui peut consulter mes services?',
	'_modzzz_professional_menu_view_services' => 'Services',

    '_modzzz_professional_privacy_view_professional' => 'Qui peut consulter ma fiche professionnelle?',
    '_modzzz_professional_privacy_comment' => 'Qui peut commenter sur ma fiche?',
    '_modzzz_professional_privacy_rate' => 'Qui peut noter ma fiche ',
    '_modzzz_professional_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_professional_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_professional_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_professional_privacy_upload_files' => 'Upload Files',
    '_modzzz_professional_privacy_edit_professional' => 'Qui peut modifier ma fiche',
    '_modzzz_professional_privacy_admins_only' => 'Admins Only',
    '_modzzz_professional_anonymous_note' => 'your name will not appear as the poster', 
    '_mma_professional_view_professional' => 'professional view professional', 
    '_mma_professional_browse' => 'professional browse', 
    '_mma_professional_search' => 'professional search', 
    '_mma_professional_add_professional' => 'professional add professional', 
    '_mma_professional_comments_delete_and_edit' => 'professional comments delete and edit', 
    '_mma_professional_edit_any_professional' => 'professional edit any professional', 
    '_mma_professional_delete_any_professional' => 'professional delete any professional', 
    '_mma_professional_mark_as_featured' => 'professional mark as featured', 
    '_mma_professional_approve_professional' => 'professional approve professional',   


	'_modzzz_professional_action_title_premium' => 'Mettre en vedette',  
    '_modzzz_professional_page_title_premium' => 'Mettre en vedette ma fiche professionnelle',   
	'_mma_professional_purchase' => 'professional purchase package', 

    '_modzzz_professional_action_title_extend' => 'Prolonger',  
    '_modzzz_professional_page_title_extend' => 'Prolonger la publication de ma fiche professionnelle',   
	'_mma_professional_extend' => 'professional extend', 

    '_modzzz_professional_action_title_relist' => 'Re-publier',  
    '_modzzz_professional_page_title_relist' => 'Re-publier ma fiche professionnelle',  
	'_mma_professional_relist' => 'professional relist', 
  
    '_modzzz_professional_form_caption_current_no_package' => 'Aucun Package actuellement',   
    '_modzzz_professional_form_caption_current_package' => 'Package actuel',  
    '_modzzz_professional_form_caption_package_price' => 'Tarif du Package',  
    '_modzzz_professional_form_caption_package_days' => 'Durée de diffusion',   
 	'_modzzz_professional_expires_never' => 'Illimité (n\'expire jamais)', 
 	'_modzzz_professional_days' => 'days', 
 	'_modzzz_professional_form_caption_current_item' => 'Professionel', 
    '_modzzz_professional_extend' => 'Prolonger',  
    '_modzzz_professional_block_statistics' => 'Statistiques',  
    '_modzzz_professional_block_price' => 'Tarif',  
	 
	'_modzzz_professional_miles' => 'miles', 
    '_modzzz_professional_kilometers' => 'Km', 
	'_modzzz_professional_map_search_explanation' => 'Enter the City and Country (eg. miramer or miramer,US)', 

    '_modzzz_professional_enter_your_professional' => 'Entrer le titre de votre activité',
    '_modzzz_professional_block_professional_create' => 'Inscription dans l\'annuaire des Professionnels', 
    '_modzzz_professional_block_latest_comments' => 'Latest Comments',
    '_modzzz_professional_block_forum' => 'Latest Forum Posts',
    '_modzzz_professional_posted_by' => 'Posté par',
    '_modzzz_professional_posted_in' => 'Posté dans',
 
	'_modzzz_professional_allow_num_professionals' => 'Nombre des fiches professionnels autorisées', 	
	'_modzzz_professional_allow_videos' => 'Autoriser des Videos', 	
	'_modzzz_professional_allow_photos' => 'Autoriser des Photos', 	
	'_modzzz_professional_allow_sounds' => 'Autoriser des sons', 	
	'_modzzz_professional_allow_files' => 'Autoriser des documents', 	
 	'_modzzz_professional_featured' => 'En Vedette', 

	'_modzzz_professional_package_desc' => 'Description du Package ',  

    '_modzzz_professional_block_submenu_expired_professional' => 'Expiré',
    '_modzzz_professional_page_title_expired' => 'Fiche Professionnelle expirée', 
	'_modzzz_professional_expires' => 'Expire',  
	'_modzzz_professional_never' => 'Jamais',  
 	'_modzzz_professional_featured_professional' => 'Statut "En vedette" (N\'expire jamis)',  
 
    '_modzzz_professional_page_title_broadcast' => 'Envoyer un message à tous vos fans ',
    '_modzzz_professional_msg_broadcast_message_sent' => 'Message envoyé',
    '_modzzz_professional_msg_broadcast_no_recipients' => 'Vous n\'avez pas encore des fans',
    '_modzzz_professional_form_caption_broadcast_title' => 'Titre du message',
    '_modzzz_professional_form_err_broadcast_title' => 'Veuillez entrer de 3 à 100 caractères', 
    '_modzzz_professional_form_caption_broadcast_message' => 'Message',
    '_modzzz_professional_form_err_broadcast_message' => 'Veuillez entrer au moins 10 caractères',
    '_modzzz_professional_action_title_broadcast' => 'Messages aux fans',
    '_mma_professional_broadcast_message' => 'professional broadcast message',

    '_modzzz_professional_block_coupons' => 'Coupons', 
    '_modzzz_professional_block_deals' => 'Deals',
    '_modzzz_professional_block_reviews' => 'Avis',
    '_modzzz_professional_block_jobs' => 'Jobs',
  
    '_modzzz_professional_form_caption_subcategories' => 'Sous-Catégories',
    '_modzzz_professional_form_caption_categories' => 'Catégories',

    '_mma_professional_mark_as_favorite' => 'professional mark as favorite', 
    '_modzzz_professional_menu_favorite' => 'Mes Professionnels favorites',
    '_modzzz_professional_msg_removed_from_favorite' => 'Le professionnel a été retiré du favori',
    '_modzzz_professional_msg_added_to_favorite' => 'Le Professional a été ajouté à vos favoris',
    '_modzzz_professional_page_title_browse_favorite' => 'Mes Professionnels favorites',
    '_modzzz_professional_action_add_to_favorite' => 'Ajouter aux favoris',    
    '_modzzz_professional_action_remove_from_favorite' => 'Retirer de mes favoris',
    '_modzzz_professional_pay_invoice' => 'PAYER UNE FACTURE',

	'_modzzz_professional_menu_drilldown' => 'Drilldown',
    '_modzzz_professional_caption_browse_area_professionals' => 'Professionels près de chez moi',
 

    '_mma_professional_post_reviews' => 'professional post reviews',  
    '_modzzz_professional_page_title_reviews' => 'Témoignages', 
    '_modzzz_professional_block_latest_reviews' => 'Derniers témoignages', 
	'_modzzz_professional_action_title_review' => 'Poster un témoignages', 
    '_modzzz_professional_review_text' => 'Témoignage', 
    '_modzzz_professional_review_text_info' => 'Si vous avez utilisé les services de ce professionnel, vous pouvez publier un témoignage au profit d’autres personnes souhaitant utiliser les mêmes services .', 
    '_modzzz_professional_form_caption_post_review' => 'Poster Témoignage - ', 
    '_modzzz_professional_review_saved' => 'Le témoignage a été enregistré', 
    '_modzzz_professional_review_not_saved' => 'Le témoignage n\'a pas été enregistré',  
    '_modzzz_professional_review' => 'Témoignage', 
    '_modzzz_professional_block_professional_reviews' => 'Témoignages',
    '_modzzz_professional_menu_view_reviews' => 'Témoignages', 
	'_modzzz_professional_review_for' => 'Témoignage pour ', 
	'_modzzz_professional_block_reviews' => 'Témoignages', 
	'_modzzz_professional_block_my_reviews' => 'Témoignages concernant ma fiche professionnelle',  
 	'_modzzz_professional_action_title_post_review' => 'Poster un témoignage', 
	'_modzzz_professional_block_browse_reviews' => 'Consulter les témoignages de la fiche professionnelle',
	'_modzzz_professional_page_title_review_add' => 'Poster un témoignage',
	'_modzzz_professional_page_title_review_browse' => 'Consulter les témoignages pour la fiche professionnelle - {0}', 
    '_modzzz_professional_action_title_add_review' => 'Poster un témoignage',
    '_modzzz_professional_page_title_review_edit' => 'Modifier Témoignage',
    '_modzzz_professional_msg_professional_review_was_deleted' => 'Témoignage supprimé avec succès',
    '_modzzz_professional_msg_pending_review_approval' => 'Ce témoignage est en attente d\'approbation, veuillez attendre qu\'il soit activé',
    '_modzzz_professional_menu_view_reviews' => 'Témoignages',  
	'_modzzz_professional_posted_for' => 'Posted for Professional',  
	'_modzzz_professional_posted_for_service' => 'Posté pour service',  
	'_modzzz_professional_posted' => 'Posté', 
	'_modzzz_professional_form_review_header_info' => 'Info sur l\'avis',
	'_modzzz_professional_block_details' => 'Détails',
	'_modzzz_professional_request_for' => 'Demande',

	'_modzzz_professional_friend' => 'Amis',
	
	/*added 7.1 */
    '_modzzz_professional_wall_added_new_comment' => 'a commenté sur ',
    '_modzzz_professional_wall_added_new_items' => 'a ajouté {0} fiche professionnelle(s)',
	'_modzzz_professional_single' => 'Fiche Professionnelle',
    '_modzzz_professional_posted_in_topic' => 'Posted in Forum',
    '_modzzz_professional_posted_in_professional' => 'Posté dans l\'annuaire des professionnels', 
    '_modzzz_professional_block_calendar' => 'Calendrier', 
	'_modzzz_professional_block_business_location' => 'Localisation du business', 
	'_modzzz_professional_block_location' => 'Localisation', 
    '_modzzz_professional_block_map' => 'Vue de la carte', 
    '_modzzz_professional_caption_location_for_professional' => 'Situé à la place',
 	'_modzzz_professional_tags' => 'Mots clés',
 	'_sys_module_professional' => 'Fiches Professionnelles', 
    '_modzzz_professional_adm_stats' => 'Inscription de votre fiche professionnelle en attente',
 
 	'_modzzz_professional_title_add_service' => 'Ajouter un service à un professionnel - ',
 	'_modzzz_professional_add_service_success' => 'Ajout réussi du service <b> {0} </ b> au professionnel',
 	'_modzzz_professional_add_service_failed' => 'Échec de l\'ajout du service <b>{0}</b>. Veuillez vérifier le nom',
   
	'_modzzz_professional_form_caption_service' => 'Service',
	'_modzzz_professional_form_info_service' => 'Entrez le nom d\'utilisateur du membre que vous souhaitez ajouter comme service',
	'_modzzz_professional_form_caption_length' => 'Durée du service',
	'_modzzz_professional_form_caption_currency' => 'Devise',
	'_modzzz_professional_form_err_length' => 'Vous devez sélectionner la durée du service',
	'_modzzz_professional_form_err_currency' => 'Vous devez sélectionner une devise',
	'_modzzz_professional_form_caption_price' => 'Tarif',
	'_modzzz_professional_form_caption_price_type' => ' Type de tarif',
	'_modzzz_professional_fixed' => 'Fixe',
	'_modzzz_professional_minimum' => 'Minimum',
	'_modzzz_professional_negotiable' => 'Négotiable',
   
	'_modzzz_professional_form_caption_display_service' => 'Activer ce service',
	'_modzzz_professional_form_caption_book_service' => 'Désactiver la réservation en ligne pour ce service', 

	'_modzzz_professional_jobs_available' => 'Offres d\emploi disponible',
    '_modzzz_professional_browse_professional_in_country' => 'Professionels | {0}', 

	'_modzzz_professional_located' => 'Situé à',
 
	'_modzzz_professional_menu_view_website' => 'Website',  
 	'_modzzz_professional_title_website' => '{0} - Website', 

	'_modzzz_professional_role_renter' => 'Locataire / entrepreneur indépendant',
	'_modzzz_professional_role_owner' => 'Propriétaire',
	'_modzzz_professional_role_employee' => 'Employé',

	'_modzzz_professional_form_th_open' => 'Ouverture',  
	'_modzzz_professional_form_th_close' => 'Fermeture',  
	'_modzzz_professional_form_option_am' => 'am',  
	'_modzzz_professional_form_option_pm' => 'pm',  
	'_modzzz_professional_form_caption_timezone' => 'Fuseau horaire',  
	'_modzzz_professional_form_header_availability' => 'Quelles sont vos heures de travail?', 
	'_modzzz_professional_form_caption_book_online' => 'Permettre à mes clients de réserver en ligne', 

	'_modzzz_professional_week_days_sunday' => 'Dimanche',   
	'_modzzz_professional_week_days_monday' => 'Lundi',   
	'_modzzz_professional_week_days_tuesday' => 'Mardi',   
	'_modzzz_professional_week_days_wednesday' => 'Mercredi',   
	'_modzzz_professional_week_days_thursday' => 'Jeudi',   
	'_modzzz_professional_week_days_friday' => 'Vendredi',   
	'_modzzz_professional_week_days_saturday' => 'Samedi',

	'_modzzz_professional_service_length_15min' => '15 Mins', 
	'_modzzz_professional_service_length_30min' => '30 Mins', 
	'_modzzz_professional_service_length_45min' => '45 Mins', 
	'_modzzz_professional_service_length_1hr' => '1 Heure', 
	'_modzzz_professional_service_length_1hr_15min' => '1 Heures 15 Mins', 
	'_modzzz_professional_service_length_1hr_30min' => '1 Heures 30 Mins', 
	'_modzzz_professional_service_length_1hr_45min' => '1 Heures 45 Mins', 
	'_modzzz_professional_service_length_2hr' => '2 Heures',
	'_modzzz_professional_service_length_2hr_15min' => '2 Heures 15 Mins', 
	'_modzzz_professional_service_length_2hr_30min' => '2 Heures 30 Mins', 
	'_modzzz_professional_service_length_2hr_45min' => '2 Heures 45 Mins', 
	'_modzzz_professional_service_length_3hr' => '3 Heures',
	'_modzzz_professional_service_length_3hr_15min' => '3 Heures 15 Mins', 
	'_modzzz_professional_service_length_3hr_30min' => '3 Heures 30 Mins', 
	'_modzzz_professional_service_length_3hr_45min' => '3 Heures 45 Mins', 
	'_modzzz_professional_service_length_4hr' => '4 Heures',
	'_modzzz_professional_service_length_5hr' => '5 Heures',
	'_modzzz_professional_service_length_6hr' => '6 Heures',
 
	'_modzzz_professional_block_photo_samples' => 'Échantillons photo',
	'_modzzz_professional_block_youtube_video_samples' => 'Échantillons vidéo (Youtube)',
	'_modzzz_professional_block_video_samples' => 'Échantillons vidéo',
 	'_modzzz_professional_action_upload_youtube' => 'Youtube Videos',
 
	'_modzzz_professional_form_caption_youtube_link' => 'Lien de la vidéo', 
	'_modzzz_professional_form_caption_youtube_caption' => 'Titre de la vidéo',  
	'_modzzz_professional_form_header_youtube' => 'Youtube Videos',
	'_modzzz_professional_form_caption_youtube_attach' => 'Vidéo',
	'_modzzz_professional_form_info_youtube_attach' => 'Vous pouvez ajouter plusieurs vidéos Youtube',
	'_modzzz_professional_form_caption_youtube_choice' => 'Vidéos existantes',  
	'_modzzz_professional_form_info_youtube_choice' => 'Décochez les vidéos que vous souhaitez supprimer',  
    '_modzzz_professional_page_title_embed_video' => 'Vidéo Youtube',
    '_modzzz_professional_action_embed_video' => 'Vidéo Youtube',
 
	'_modzzz_professional_menu_view_clients' => 'Clients',

	'_modzzz_professional_form_service_header_info' => 'Info sur le service',
	'_modzzz_professional_action_title_post_service' => 'Ajouter un Service',
	'_modzzz_professional_page_title_service_add' => 'Ajouter un service',

	'_modzzz_professional_action_title_post_client' => 'Ajouter un clien',
	'_modzzz_professional_form_client_header_info' => 'Info sur le client',
	'_modzzz_professional_page_title_client_add' => 'Ajouter un client',
	'_modzzz_professional_page_title_manage_youtube' => 'Gérer Youtube Videos',
  
	'_modzzz_professional_block_browse_services' => 'Consulter lesServices',
	'_modzzz_professional_block_browse_clients' => 'Consulter les clients Clients',


	'_modzzz_professional_form_header_schedule' => 'Heures de travail ou d\'ouverture',
	'_modzzz_professional_from' => 'de',
	'_modzzz_professional_to' => 'à',
	'_modzzz_professional_closed' => 'Fermé',
	'_modzzz_professional_time_am' => 'AM',
	'_modzzz_professional_time_pm' => 'PM',

	'_modzzz_professional_short_mon' => 'Lu',
	'_modzzz_professional_short_tue' => 'Mar',
	'_modzzz_professional_short_wed' => 'Mer',
	'_modzzz_professional_short_thur' => 'Jeu',
	'_modzzz_professional_short_fri' => 'Ven',
	'_modzzz_professional_short_sat' => 'Sam',
	'_modzzz_professional_short_sun' => 'Dim',

	'_modzzz_professional_long_mon' => 'Lundi',
	'_modzzz_professional_long_tue' => 'Mardi',
	'_modzzz_professional_long_wed' => 'Mercredi',
	'_modzzz_professional_long_thur' => 'Jeudi',
	'_modzzz_professional_long_fri' => 'Vendredi',
	'_modzzz_professional_long_sat' => 'Samedi',
	'_modzzz_professional_long_sun' => 'Dimanche',

 	'_modzzz_professional_form_caption_schedule_choice' => 'Heures de travail ou d\'ouverture existantes',
	'_modzzz_professional_form_caption_schedule_attach' => 'Ajouter vos heures de travail/d\'ouverture', 
	'_modzzz_professional_form_info_schedule_choice' => 'Décochez les heures d\'ouverture que vous souhaitez supprimer',
	'_modzzz_professional_form_info_schedule_attach' => 'Vous pouvez ajouter plusieurs heures d\'ouverture',

	'_modzzz_professional_form_caption_firstname' => 'Prénom',
	'_modzzz_professional_form_caption_lastname' => 'Nom',
	'_modzzz_professional_form_caption_phone_type' => 'Phone type',
	'_modzzz_professional_form_caption_note' => 'Un mot pour ce professionnel', 
	'_modzzz_professional_form_err_firstname' => 'Vous devez entrer prénom',
	'_modzzz_professional_form_err_lastname' => 'Vous devez entrer le nom de famille',
	'_modzzz_professional_form_err_note' => 'Vous devez entrer une note pour ce professionnel',

	'_modzzz_professional_form_caption_requested_service' => 'Service demandé',
 
	'_modzzz_professional_phone_type_cell' => 'Mobile',
	'_modzzz_professional_phone_type_home' => 'Privé',
	'_modzzz_professional_phone_type_work' => 'Professionnel',

    '_mma_professional_make_booking' => 'professional make booking', 
    '_modzzz_professional_action_title_book_me' => 'Faite une réservation',  
    '_modzzz_professional_action_title_request_quote' => 'Demander un devis', 
 	'_modzzz_professional_caption_request_quote' => 'Demander un devis',
    '_modzzz_professional_request_sent' => 'Votre demande de devis a pas été envoyée',
    '_modzzz_professional_request_not_sent' => 'Votre demande de devis n\'a pas été envoyée',
     '_modzzz_professional_action_title_respond' => 'Répondre', 

	'_modzzz_professional_and_up' => 'et jusqu\'à',
	'_modzzz_professional_negotiable_lower' => 'négociable',
	'_modzzz_professional_for' => 'pour',
 
	'_modzzz_professional_form_header_online_presence' => 'Présence en ligne',
	'_modzzz_professional_form_caption_website' => 'Site Internet',
	'_modzzz_professional_form_caption_blog' => 'Blog',
	'_modzzz_professional_form_caption_facebook' => 'Facebook',
	'_modzzz_professional_form_caption_twitter' => 'Twitter',
	'_modzzz_professional_form_caption_linkedin' => 'Linkedin',
	'_modzzz_professional_form_caption_youtube' => 'Youtube',
	'_modzzz_professional_form_caption_pinterest' => 'Pinterest',

	'_modzzz_professional_my_website' => 'Mon Site Internet',
	'_modzzz_professional_my_blog' => 'Mon Blog',
 	'_modzzz_professional_form_caption_service' => 'En référence à',
 	'_modzzz_professional_general_feedback' => 'Avis ',
 
	'_modzzz_professional_block_quote_requests' => 'Demandes de devis',
	'_modzzz_professional_page_title_service_edit' => 'Modier le service',

	'_modzzz_professional_caption_respond_quote' => 'Répondre à la demande de devis',
	'_modzzz_professional_form_caption_response_to' => 'Réponse à', 	 
	'_modzzz_professional_form_caption_response' => 'Réponse', 	
	'_modzzz_professional_respond_sent' => 'La réponse a été envoyée', 	
	'_modzzz_professional_respond_not_sent' => 'La réponse n\'est pas envoyée', 	
  
	'_modzzz_professional_caption_browse_professional_reviews' => 'Consulter des avis - {0}', 	
	'_modzzz_professional_caption_browse_professional_service_reviews' => 'Consulter des avis pour ce service - {0}', 	
 	'_modzzz_professional_page_title_service_browse' => 'Parcourir des Services', 	
 	'_modzzz_professional_page_title_client_browse' => 'Parcourir des Clients', 	

	'_modzzz_professional_form_header_online' => 'Présence en ligne', 

	'_modzzz_professional_regions_in_country' => ' <i class="sys-icon map-marker"></i> Professionnels par région |  {0}', 
    '_modzzz_professional_listed_in' => 'Publié dans', 
    '_modzzz_professional_located_at' => 'Situé à', 
	'_modzzz_restaurant_block_inquire' => 'Contactez nous',
	'_modzzz_professional_block_schedule' => 'Heures de travail',

	'_modzzz_professional_page_title_booking_add' => 'Poster une réservation',
	'_modzzz_professional_page_title_booking_edit' => 'Modifier la réservation',
	'_modzzz_professional_msg_professional_booking_was_deleted' => 'Réservation annulée',
 
 	'_modzzz_professional_caption_price_service' => 'Prix du service',
	'_modzzz_professional_caption_length_service' => 'Durée du service',
 
	'_modzzz_professional_block_bookings' => 'Réservations',
	'_modzzz_professional_block_book_me' => 'Faites une réservation',
	'_modzzz_professional_block_contact_me' => 'Contactez Moi',
	'_modzzz_professional_block_contacts' => 'Historique des contacts',
	'_modzzz_professional_action_title_book_me' => 'Faites une réservation',
	'_modzzz_professional_action_title_contact_me' => 'Contactez moi',
 
	'_modzzz_professional_block_services' => 'Services', 
	'_modzzz_professional_form_booking_header_info' => 'Informations de réservation', 
	'_modzzz_professional_form_caption_booking_name' => 'Services', 
	'_modzzz_professional_form_caption_name' => 'Votre nom',
 	'_modzzz_professional_form_caption_booking_details' => 'Détails de la réservation',
	'_modzzz_professional_contact' => 'Contact', 
	'_modzzz_professional_form_caption_start_time' => 'Heure de début', 
	'_modzzz_professional_form_err_start_time' => 'Vous devez entrer l\'heure de début', 
	'_modzzz_professional_form_caption_end_time' => 'Heure de fin', 
	'_modzzz_professional_form_err_end_time' => 'Vous devez saisir l\'heure de fin', 
 	'_modzzz_professional_form_header_booking_schedule' => 'Calendrier des demande de réservation', 
	'_modzzz_professional_action_title_confirmed' => 'Confirmé', 
	'_modzzz_professional_action_title_cancel' => 'Annuler', 
	'_modzzz_professional_msg_professional_booking_was_confirmed' => 'La réservation a été confirmée', 
 
	'_modzzz_professional_tab_pending' => 'En attente', 
	'_modzzz_professional_tab_approved' => 'Approouvé', 
 	'_modzzz_professional_block_post_review' => 'Avis sur les services de ce professionnel', 
	'_modzzz_professional_caption_browse_by_country' => 'Parcourir par pay', 
	'_modzzz_professional_form_caption_proprietor' => 'Nom', 
	'_modzzz_professional_form_caption_businessname' => 'Nom de votre business',  
	'_modzzz_professional_block_inquire' => 'Se renseigner', 
	'_modzzz_professional_msg_access_denied' => 'Votre abonnement ne permet pas d\'accéder à cette fonctionnalité', 

);
