<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Church
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Church';

$aLangContent = array(
  
    '_modzzz_church_yes' => 'Yes',
    '_modzzz_church_no' => 'No',
 
    '_modzzz_church_form_caption_capacity' => 'Church Capacity',
    '_modzzz_church_form_caption_about_us' => 'About us',
    '_modzzz_church_form_caption_dress_code' => 'Dress Code',
    '_modzzz_church_caption_desc' => 'Description',
    '_modzzz_church_block_details' => 'Details',
    '_modzzz_church_form_caption_position' => 'Position',
    '_modzzz_church_form_caption_member_name' => 'Member Name',
    '_modzzz_church_form_caption_staff_name' => 'Staff Name',
    '_modzzz_church_form_caption_ministry_name' => 'Ministry',
    '_modzzz_church_form_caption_branch_name' => 'Branch',
    '_modzzz_church_block_location' => 'Location',

    '_modzzz_church_fans' => 'fans',
    '_modzzz_church_sbs_join' => 'new fan',
    '_modzzz_church_block_fans' => 'Fans',
    '_modzzz_church_block_fans_unconfirmed' => 'Unconfirmed Fans',
	'_modzzz_church_block_my_churches_joined' => 'Joined Churches',
    '_modzzz_church_caption_manage_fans' => 'Manage Fans',
    '_modzzz_church_menu_view_fans' => 'Fans',
    '_modzzz_church_page_title_fans' => 'Church\'s Fans',
    '_modzzz_church_action_manage_fans' => 'Manage Fans',
    '_modzzz_church_privacy_view_fans' => 'View Fans',
    '_modzzz_church_privacy_fans_only' => 'Fans Only',
    '_modzzz_church_privacy_fans' => 'Fans',

    '_modzzz_church_spy_join' => '<a href="{profile_link}">{profile_nick}</a> joined church <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_church_sbs_join' => 'new fan',
    '_modzzz_church_page_title_browse_by_author_joined_churches' => '\'s joined churches',
    '_modzzz_church_msg_joined_already' => 'You have already joined this church',
    '_modzzz_church_msg_joined_request_pending' => 'You have already joined this church. Please wait while your request is processed by church admin(s).',
    '_modzzz_church_msg_join_success' => 'You have successfully joined this church',
    '_modzzz_church_msg_join_success_pending' => 'You have successfully joined this church. Please wait while your request is processed by church admin(s).',
	'_modzzz_church_msg_leave_success' => 'You have successfully left this church',
    '_modzzz_church_form_caption_join_confirmation' => 'Join Confirmation',
    '_modzzz_church_form_info_join_confirmation' => 'If enabled, church admin(s) will have to confirm each user before he/she becomes a fan.',
    '_modzzz_church_form_join_confirmation_disabled' => 'Disabled',
    '_modzzz_church_form_join_confirmation_enabled' => 'Enabled',
    '_modzzz_church_form_err_join_confirmation' => 'Join confirmation field must be 0 or 1',
    '_modzzz_church_action_title_join' => 'Become Fan',
    '_modzzz_church_action_title_leave' => 'Remove Fan',
    '_modzzz_church_privacy_join' => 'Become Fan',
 
    '_modzzz_church_packages_empty' => 'There are no Paid Packages', 
    '_modzzz_church_package_description' => 'Description', 
    '_modzzz_church_package_featured' => 'Featured', 

    '_modzzz_church_featured_status' => 'Featured Status', 
    '_modzzz_church_featured_until' => 'Featured until', 
    '_modzzz_church_not_featured' => 'Not Featured', 
 	'_modzzz_church_extend_featured' => 'Extend Featured Status',  
	'_modzzz_church_purchase_featured' => 'Purchase Featured Status', 
	'_modzzz_church_form_caption_currency' => 'Currency',  
  
    '_modzzz_church_menu_packages' => 'Packages', 
    '_modzzz_church_page_title_packages' => 'Paid Packages', 
    '_modzzz_church_block_packages' => 'Paid Packages', 

    '_modzzz_church_menu_view_forum' => 'Forum', 
    '_modzzz_church_privacy_post_in_forum' => 'Post In Forum',
 
   	'_modzzz_church_form_header_video_embed' => 'Video Embed',
   	'_modzzz_church_caption_video_embed_code' => 'Embed Code',
	'_modzzz_church_form_info_video_embed_code' => 'Enter either the URL or Embed Code for Youtube Video. Enter the Embed Code for other video sharing site (eg &lt;embed&gt;....&lt;/embed&gt;)',
   	'_modzzz_church_block_video_embed' => 'External Video',
  
	'_modzzz_church_caption_membership_view_filter' => 'Allow viewing by membership',
	'_modzzz_church_err_membership_view_filter' => 'incorrect value', 
    '_modzzz_church_info_membership_view_filter' => 'only these members will be able to view this church',
    '_modzzz_church_membership_filter_none' => 'Allow All',	

    '_mma_church_files_add' => 'church files add',  
    '_mma_church_photos_add' => 'church photos add',  
    '_mma_church_videos_add' => 'church videos add',  
    '_mma_church_sounds_add' => 'church sounds add',  
    '_mma_church_post_reviews' => 'church post reviews',  
    '_mma_church_view_donors' => 'church view donors',  
    '_mma_church_create_faqs' => 'church create FAQ',  
	
    '_modzzz_church_continue' => 'Continue',  
    '_modzzz_church_admin_assign' => 'Assign to Claimant',  
    '_modzzz_church_menu_manage_claims' => 'Claims',  
    '_modzzz_church_claimed_by' => 'Claimed by',  
    '_modzzz_church_on' => 'on',  
  
	'_modzzz_church_package_videos' => 'Videos',  	
	'_modzzz_church_package_photos' => 'Photos',  	
	'_modzzz_church_package_sounds' => 'Sounds',  	
	'_modzzz_church_package_files' => 'Files', 

	'_modzzz_church_block_church_states' => 'States', 
 
    '_mma_church_purchase_featured' => 'church purchase featured', 
    '_mma_church_make_claim' => 'church make claim', 
    '_mma_church_make_inquiry' => 'church make inquiry', 

    '_modzzz_church_regions_for_country' => 'States/Regions for',  
	'_modzzz_church_block_browse_state' => 'Browse States', 
	'_modzzz_church_block_browse_state_churches' => 'Browse Churches by State', 
	'_modzzz_church_block_account' => 'Churches in my Area',  
	'_modzzz_church_block_browse_country' => 'Browse by Country', 
	'_modzzz_church_page_title_local' => 'Browse Local Churches',  
	'_modzzz_church_caption_browse_local' => 'Browse Local Churches in {0}', 
	'_modzzz_church_menu_local' => 'Local', 
 	'_modzzz_church_block_local' => 'More Local Churches',
	'_modzzz_church_block_other' => 'Other Churches by this member',
 	'_modzzz_church_caption_browse_other' => 'Other Churches by {0}',


	'_modzzz_church_action_title_purchase_featured' => 'Get Featured',
	'_modzzz_church_action_title_extend_featured' => 'Extend Featured',  
	'_modzzz_church_purchase_featured_status' => 'Purchase Featured Status',  
	'_modzzz_church_quantity' => 'Quantity',   
	'_modzzz_church_purchase_success' => 'You successfully Purchased {0} Days of Featured Status', 
	'_modzzz_church_purchase_failed' => 'Your attempt to Purchase Premium Listing has failed',  
	'_modzzz_church_purchase_featured_failed' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_church_transaction_completed_already' => 'This transaction was already completed',  
	'_modzzz_church_featured_cost_per_day' => 'Cost per Day',  
	'_modzzz_church_caption_num_featured_days' => 'Number of Featured Days',    
	'_modzzz_church_caption_err_featured_days' => 'You must enter Number of Featured Days',    
	'_modzzz_church_get_featured' => 'Get Featured',  
 

    '_modzzz_church_parent_categories' => 'Religion', 
    '_modzzz_church_sub_categories' => 'Sector', 

    '_modzzz_church_block_category_church' => 'Churches in this Religion',
    '_modzzz_church_block_subcategories' => 'Sectors',  
    '_modzzz_church_manage_subcategories_msg' => 'To manage Sectors, go to Religions and select the Sector of interest. Then click the Sectors button', 
	'_modzzz_church_categ_name' => 'Religion',
	'_modzzz_church_categ_btn_edit' => 'Edit',
	'_modzzz_church_categ_btn_delete' => 'Delete',
	'_modzzz_church_categ_btn_add' => 'Add',
	'_modzzz_church_categ_btn_save' => 'Save',
	'_modzzz_church_categ_btn_subcategories' => 'Sectors', 
 	'_modzzz_church_menu_admin_manage_categories' => 'Religions',
  	'_modzzz_church_menu_admin_manage_subcategories' => 'Sectors',
  	'_modzzz_church_subcategories' => 'Sectors',
  	'_modzzz_church_category' => 'Religion',
  	'_modzzz_church_categories' => 'Religions',
    '_modzzz_church_all_categories' => 'All Religions',
    '_modzzz_church_block_categories' => 'Religions',
    '_modzzz_church_block_church_subcategories' => 'Sectors',
    '_modzzz_church_block_answer_categories' => 'Religions',
    '_modzzz_church_menu_categories' => 'Religions',
    '_modzzz_church_page_title_browse_by_category' => 'Browse Churches By Religion: ',
    '_modzzz_church_form_caption_category' => 'Religion',
    '_modzzz_church_form_err_category' => 'Religion is invalid', 
	'_modzzz_church_page_title_category' => 'Religion', 
    '_modzzz_church_page_title_categories' => 'Religions',
    '_modzzz_church_page_title_subcategories' => 'Sectors', 
    '_modzzz_church_churches_in_category' => '<b>Churches</b> in <b>%s</b>',  
    '_modzzz_church_block_church' => 'Churches', 
    
	'_modzzz_church_packages' => 'Packages',
	'_modzzz_church_package_name' => 'Package Name',
	'_modzzz_church_package_price' => 'Package Price',
	'_modzzz_church_package_days' => 'Package Days',
	'_modzzz_church_form_caption_package' => 'Package',
	'_modzzz_church_form_err_package' => 'Please select a Package',  
	'_modzzz_church_purchaser' => 'Purchaser', 
	'_modzzz_church_invoice_no' => 'Invoice #', 
	'_modzzz_church_package' => 'Package', 
	'_modzzz_church_invoice_date' => 'Invoice Date', 
	'_modzzz_church_invoice_due_date' => 'Due Date', 
	'_modzzz_church_status' => 'Status',
	'_modzzz_church_pending' => 'Pending',
	'_modzzz_church_paid' => 'Paid',
	'_modzzz_church_active' => 'Active',
	'_modzzz_church_inactive' => 'Inactive',
	'_modzzz_church_approved' => 'Approved',
	'_modzzz_church_expired' => 'Expired', 
	'_modzzz_church_block_submenu_pending_invoices' => 'Pending Invoices',
	'_modzzz_church_block_submenu_orders' => 'Orders',
	'_modzzz_church_page_title_orders' => 'Orders', 
	'_modzzz_church_page_title_invoices' => 'Invoices', 
	'_modzzz_church_menu_manage_invoices' => 'Invoices', 
	'_modzzz_church_menu_manage_packages' => 'Packages',
	'_modzzz_church_menu_manage_orders' => 'Orders',
	'_modzzz_church_payment_method' => 'Payment Method',
	'_modzzz_church_total' => 'Total',
	'_modzzz_church_invoice_id' => 'Invoice ID',
	'_modzzz_church_next_due_date' => 'Next Due Date',
	'_modzzz_church_order_no' => 'Order #',
	 '_modzzz_church_product_status' => 'Product Status',
	'_modzzz_church_order_date' => 'Order Date',
	'_modzzz_church_purchase_failed' => 'Sorry, there was a problem with the Payment.  View your Pending Orders <a href="{0}">here</a>.',
	'_modzzz_church_transaction_completed_already' => 'The Transaction exists already. Click <a href="{0}">here</a> to view the Church.',
	'_modzzz_church_purchase_success' => 'Thank you. The Payment was successful. Click <a href="{0}">here</a> to view the Church.',  
	'_modzzz_church_trans_save_failed' => 'The Payment was successful but there was a Problem saving the transaction. Please contact the administrator with your Paypal transaction details so they can manually process your Order.',
	'_modzzz_church_post_purchase_header' => 'Church Purchase',  
 

	'_modzzz_church_caption_state' => 'State',  
	'_modzzz_church_regions_for_country' => 'States/Regions for',  
	'_modzzz_church_block_browse_state' => 'Browse States', 
	'_modzzz_church_block_browse_country' => 'Browse by Country', 
	'_modzzz_church_page_title_local' => 'Browse Local Churches',  
	'_modzzz_church_caption_browse_local' => 'Browse Local Churches in {0}', 
	'_modzzz_church_menu_local' => 'Local',
 	'_modzzz_church_caption_search' => 'Search Churches',
 

    '_modzzz_church_no_churches' => 'There are no Churches',
    '_sbs_txt_title_modzzz_church' => 'Churches',
    '_modzzz_church' => 'Church',
    '_modzzz_church_add' => 'add',
    '_modzzz_church_wall_added_new' => 'added new',
    '_modzzz_church_wall_object' => 'church',
    '_modzzz_church_for_church' => 'for %s',
    '_modzzz_church_church_single' => 'church',
    '_modzzz_church_church_plural' => 'churches',
    '_modzzz_church_user_unknown' => 'Unknown',
    '_modzzz_church_disabled' => 'disabled',
    '_modzzz_church_enabled' => 'enabled',
    '_modzzz_church_cannot_delete_default_parent' => 'Cannot Delete Default Religion',
	  
    '_modzzz_church_edit' => 'Edit Church Location',
    '_modzzz_church_box_footer_edit' => 'Edit location',
    '_modzzz_church_current_location' => 'Current Location:',
    '_modzzz_church_privacy_view_location' => 'Allow viewing location to',
    '_modzzz_church_privacy_update_ok' => 'Privacy setting has been successfully updated',
    '_modzzz_church_privacy_update_fail' => 'Error occurred',
    '_modzzz_church_the_same_address' => 'the same as primary address',  
    '_modzzz_church_msg_locations_is_not_defined' => 'Your location is not defined',
    '_modzzz_church_msg_incorrect_google_key' => 'Your Google API key is invalid or your browser is incompatible with Google Maps', 
	'_modzzz_church_title_block_edit_location' => 'Edit Location',  
	'_modzzz_church_title_block_edit_location_info' => 'Location Info',   
	'_modzzz_church_unknown_city' => 'Unknown',  
	'_modzzz_church_current_location' => 'Current Location', 
    '_modzzz_church_block_map' => 'Map',
    '_modzzz_church_admin_links' => 'Links',
    '_modzzz_church_admin_links_explanation' => 'You can get your google API key for your domain here:<br /><a href="http://code.google.com/apis/maps/signup.html">http://code.google.com/apis/maps/signup.html</a>.',  
    '_modzzz_church_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new church <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_church_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed church <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_church_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated church <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_church_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented church <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_church_sbs_change' => 'information was updated',
    '_modzzz_church_sbs_comment' => 'new comment arrived',
    '_modzzz_church_sbs_rate' => 'rating was updated',
 
    '_modzzz_church_tab_featured' => 'Featured',
    '_modzzz_church_tab_recent' => 'Recent',
    '_modzzz_church_tab_top' => 'Top',
    '_modzzz_church_tab_popular' => 'Popular',

    '_modzzz_church_block_submenu_main' => 'Main',
    '_modzzz_church_block_submenu_add_church' => 'Add',
    '_modzzz_church_block_submenu_manage_church' => 'Manage',
    '_modzzz_church_block_submenu_pending_church' => 'Pending Approval',

    '_modzzz_church_block_actions' => 'Actions',
    '_modzzz_church_block_rate' => 'Rate',    
    '_modzzz_church_block_info' => 'Church Info',
    '_modzzz_church_block_listed_by' => 'Listed By', 
    '_modzzz_church_block_desc' => 'Description',
    '_modzzz_church_block_photo' => 'Photos',
    '_modzzz_church_block_video' => 'Videos',
    '_modzzz_church_block_sound' => 'Sounds',
    '_modzzz_church_block_files' => 'Files',
    '_modzzz_church_block_file' => 'Files',
    '_modzzz_church_block_comments' => 'Comments',
    '_modzzz_church_block_latest_featured_church' => 'Latest Featured Churches',
    '_modzzz_church_block_recent' => 'Recent Churches',
    '_modzzz_church_block_popular' => 'Popular Churches',
    '_modzzz_church_block_top' => 'Top Rated Churches',
    '_modzzz_church_block_search' => 'Search Churches',
    '_modzzz_church_block_church_categories' => 'Religions',

    '_modzzz_church_block_administration_owner' => 'Administration',
    '_modzzz_church_block_users_church' => "User Churches",
    '_modzzz_church_block_my_church' => 'My Church',
    '_modzzz_church_block_my_churches' => 'My Churches',
    '_modzzz_church_block_area_churches' => 'Churches in my Area',

    '_modzzz_church_block_homepage' => 'Churches',

    '_modzzz_church_caption_add' => 'Add Church',
    '_modzzz_church_caption_share_church' => 'Share Church',
    '_modzzz_church_caption_admin_actions' => 'Links',
    '_modzzz_church_caption_pending_approval' => 'Pending Approval Churches', 
    
	'_modzzz_church_menu_manage_parents' => 'Parent Cats',
    '_modzzz_church_menu_manage_categories' => 'Cats',
    '_modzzz_church_categ_btn_save' => 'Save',
    '_modzzz_church_categ_btn_edit' => 'Edit',
    '_modzzz_church_categ_btn_delete' => 'Delete',
    '_modzzz_church_categ_name' => 'Name',
    '_modzzz_church_categ_icon' => 'Icon',
    '_modzzz_church_categ_present_icon' => 'Present Icon',
    '_modzzz_church_categ_btn_add' => 'Add',

    '_modzzz_church_menu_root' => 'Churches',
    '_modzzz_church_menu_main' => 'Church Home',
    '_modzzz_church_menu_recent' => 'Recent',
    '_modzzz_church_menu_top_rated' => 'Top Rated',
    '_modzzz_church_menu_popular' => 'Popular',
    '_modzzz_church_menu_featured' => 'Featured',
    '_modzzz_church_menu_tags' => 'Tags',
    '_modzzz_church_menu_categories' => 'Religions',
    '_modzzz_church_menu_calendar' => 'Calendar',
    '_modzzz_church_menu_search' => 'Search',
    '_modzzz_church_menu_view_church' => 'Main',
    '_modzzz_church_menu_view_comments' => 'Comments',
    '_modzzz_church_menu_view_photos' => 'Photos',
    '_modzzz_church_menu_view_videos' => 'Videos',
    '_modzzz_church_menu_view_sounds' => 'Sounds',
    '_modzzz_church_menu_view_files' => 'Files',
    '_modzzz_church_menu_my_church_profile' => 'Churches',

    '_modzzz_church_menu_admin_pending_approval' => 'Pending',
    '_modzzz_church_menu_admin_entries' => 'Churches',
    '_modzzz_church_menu_admin_add_entry' => 'Add',
    '_modzzz_church_menu_admin_settings' => 'Settings',
    
    '_modzzz_church_page_title_home' => 'Church Home',
    '_modzzz_church_page_title_calendar' => 'Church Calendar',
    '_modzzz_church_page_title_comments' => 'Comments',
    '_modzzz_church_page_title_photos' => 'Photos',
    '_modzzz_church_page_title_videos' => 'Videos',
    '_modzzz_church_page_title_sounds' => 'Sounds',
    '_modzzz_church_page_title_files' => 'Files',
    '_modzzz_church_page_title_my_church' => 'My Churches',
    '_modzzz_church_page_title_search' => 'Search',
    '_modzzz_church_page_title_add' => 'Add Church', 
    '_modzzz_church_page_title_edit' => 'Edit Church',
    '_modzzz_church_page_title_administration' => 'Churches Administration',
    '_modzzz_church_page_title_browse' => 'Browse Churches',
    '_modzzz_church_page_title_pending_approval' => 'Pending Approval Churches',
    '_modzzz_church_page_title_search_results' => 'Church Search Results',
    '_modzzz_church_page_title_browse_by_author' => "\'s churches",
    '_modzzz_church_page_title_admin_church' => 'Admin Churches',
    '_modzzz_church_page_title_browse_by_category' => 'Browse Churches By Religion: ',
    '_modzzz_church_page_title_browse_by_tag' => 'Browse Churches By Tag: ',
    '_modzzz_church_page_title_browse_recent' => 'Recent Churches',
    '_modzzz_church_page_title_browse_top_rated' => 'Top Rated Churches',
    '_modzzz_church_page_title_browse_popular' => 'Popular Churches',
    '_modzzz_church_page_title_browse_featured' => 'Featured Churches',
    '_modzzz_church_page_title_browse_by_day' => 'Browse Churches By Day: ',
    '_modzzz_church_page_title_tags' => 'Church Tags',
    '_modzzz_church_page_title_categories' => 'Church Religions',
    '_modzzz_church_page_title_upload_photos' => 'Add Photos',
    '_modzzz_church_page_title_upload_videos' => 'Add Videos',
    '_modzzz_church_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_church_page_title_upload_files' => 'Add Files',

    '_modzzz_church_msg_pending_approval' => 'this church is pending approval, please wait until it will be activated',
    '_modzzz_church_msg_church_was_deleted' => 'Church was deleted',
    '_modzzz_church_msg_removed_from_featured' => 'Church was removed from featured',
    '_modzzz_church_msg_added_to_featured' => 'Church was added to featured',
    '_modzzz_church_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_church_msg_you_have_pending_approval_church' => 'You have <a href="%s">%d pending approval churches</a>',
    '_modzzz_church_msg_you_have_no_church' => 'You do not have any churches. <a href="%s">Click here</a> to add one.',
    '_modzzz_church_msg_you_have_some_church' => 'You have <a href="%s">%d church(s)</a>. <a href="%s">Click here</a> to add more.',

    '_modzzz_church_admin_delete' => 'Delete',
    '_modzzz_church_admin_activate' => 'Activate',
    '_modzzz_church_admin_add_new_church' => 'Add New Church',
    '_modzzz_church_admin_church' => 'Admin Church',
    '_modzzz_church_admin_settings' => 'Admin Settings',

    '_modzzz_church_form_header_info' => 'Church Info',
    '_modzzz_church_form_header_images' => 'Church Photos',
    '_modzzz_church_form_header_videos' => 'Church Videos',
    '_modzzz_church_form_header_sounds' => 'Church Sounds',
    '_modzzz_church_form_header_files' => 'Church Files',
    '_modzzz_church_form_header_privacy' => 'Privacy Settings',
    '_modzzz_church_form_caption_title' => 'Title',
    '_modzzz_church_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_church_form_caption_desc' => 'Description',
    '_modzzz_church_form_err_desc' => 'Please enter at least 5 characters',
    '_modzzz_church_form_err_tags' => 'Please enter tags',
    '_modzzz_church_form_caption_author_id' => 'Author',
    '_modzzz_church_form_info_author' => 'Author profile ID number',
    '_modzzz_church_form_caption_keyword' => 'Keyword',
    '_modzzz_church_form_err_keyword' => 'Please enter from 3 to 100 characters', 
    '_modzzz_church_form_caption_images_choice' => 'Choose',
    '_modzzz_church_form_info_images_choice' => 'You can choose several images from your "Church" category',
    '_modzzz_church_form_caption_images_upload' => 'Upload',    
    '_modzzz_church_form_info_images_upload' => 'Image will be placed in the "Church" category automatically',
    '_modzzz_church_form_caption_videos_choice' => 'Choose',
    '_modzzz_church_form_info_videos_choice' => 'You can choose several videos from your "Church" category',
    '_modzzz_church_form_caption_videos_upload' => 'Upload',
    '_modzzz_church_form_info_videos_upload' => 'Video will be placed in the "Church" category automatically',
    '_modzzz_church_form_caption_sounds_choice' => 'Choose',
    '_modzzz_church_form_info_sounds_choice' => 'You can choose several sounds from your "Church" category',
    '_modzzz_church_form_caption_sounds_upload' => 'Upload',
    '_modzzz_church_form_info_sounds_upload' => 'Sound will be placed in the "Church" category automatically',
    '_modzzz_church_form_caption_files_choice' => 'Choose',
    '_modzzz_church_form_info_files_choice' => 'Unclick checkbox to remove file from this church',
    '_modzzz_church_form_caption_files_upload' => 'Upload',
    '_modzzz_church_form_info_files_upload' => 'File will be placed in the "Church" category and set as private automatically',
    '_modzzz_church_form_caption_file_title' => 'Title:',
    '_modzzz_church_form_caption_file_price' => 'Price:',
    '_modzzz_church_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_church_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_church_form_info_thumb_choice' => 'You can choose any image from your "Church" category as church thumbnail',
    '_modzzz_church_form_caption_country' => 'Country',
    '_modzzz_church_form_err_country' => 'Country is a required field',
    '_modzzz_church_form_caption_city' => 'City',
    '_modzzz_church_form_err_city' => 'Please enter from 2 to 50 characters',
    '_modzzz_church_form_caption_zip' => 'Zip/Postal Code',
    '_modzzz_church_form_err_zip' => 'Zip/Postal code is required',
    '_modzzz_church_form_err_email' => 'Invalid Email entered',

    '_modzzz_church_action_title_edit' => 'Edit',
    '_modzzz_church_action_title_delete' => 'Delete',
    '_modzzz_church_action_title_share' => 'Share',
    '_modzzz_church_action_add_to_featured' => 'Feature',    
    '_modzzz_church_action_remove_from_featured' => 'Unfeature',
    '_modzzz_church_action_add_church' => 'Add Church',
    '_modzzz_church_action_my_church' => 'My Church',
    '_modzzz_church_action_upload_photos' => 'Add Photos',
    '_modzzz_church_action_upload_videos' => 'Add Videos',
    '_modzzz_church_action_upload_sounds' => 'Add Sounds',
    '_modzzz_church_action_upload_files' => 'Add Files',
    '_modzzz_church_action_church_home' => 'Home',

    '_modzzz_church_action_title_claim' => 'Claim Church',
    '_modzzz_church_action_title_inquire' => 'Inquire About', 
    '_modzzz_church_action_title_spread' => 'Spread This', 
    '_modzzz_church_action_title_promote' => 'Promote', 
    '_modzzz_church_invitation_sent' => '%d Invitations have been sent',
	'_modzzz_church_no_users_msg' => 'There are no users in your contacts',
 
    '_modzzz_church_inquiry_subject' => 'Subject', 
    '_modzzz_church_inquiry_subject_info' => 'Enter the Subject of your inquiry', 
    '_modzzz_church_inquiry_text' => 'Message', 
    '_modzzz_church_inquiry_text_info' => 'Enter your inquiry here. It will be forwarded to the Church Owner',  
	'_modzzz_church_caption_make_inquiry' => 'Make Inquiry',
    '_modzzz_church_inquiry_sent' => 'your inquiry has been sent',
    '_modzzz_church_inquiry_not_sent' => 'your inquiry has not been sent',
   
    '_modzzz_church_claim_subject' => 'Subject', 
    '_modzzz_church_claim_subject_info' => 'Enter the Subject of your claim', 
    '_modzzz_church_claim_text' => 'Message', 
    '_modzzz_church_claim_text_info' => 'Enter your proof of claim here. It will be forwarded to the Administrators',  
	'_modzzz_church_caption_make_claim' => 'Make Claim - ',
    '_modzzz_church_claim_sent' => 'your claim request has been sent',
    '_modzzz_church_claim_not_sent' => 'your claim request has not been sent',
	 
	'_modzzz_church_user_unknown' => 'Unknown', 
    '_modzzz_church_price' => 'Price',

	'_modzzz_church_business_contact' => 'Church Contact Details', 
	'_modzzz_church_location' => 'Location',
	'_modzzz_church_map' => 'Google Map', 
	'_modzzz_church_form_caption_businessfax' => 'Fax',
	'_modzzz_church_form_caption_businesstelephone' => 'Telephone',
	'_modzzz_church_form_caption_businessemail' => 'Email',
	'_modzzz_church_form_caption_businesswebsite' => 'Website',
	'_modzzz_church_form_caption_businessname' => 'Business Name',
	'_modzzz_church_form_caption_address1' => 'Address 1',
	'_modzzz_church_form_caption_address2' => 'Address 2', 
	'_modzzz_church_form_err_churchoption' => 'Please select an Option', 
	'_modzzz_church_form_err_churchtype' => 'Please select a Type',
    '_modzzz_church_form_err_city' => 'Please enter from 3 to 150 characters',
  
    '_modzzz_church_privacy_view_church' => 'View Church',
    '_modzzz_church_privacy_comment' => 'Comment',
    '_modzzz_church_privacy_rate' => 'Rate',
    '_modzzz_church_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_church_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_church_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_church_privacy_upload_files' => 'Upload Files',
    '_modzzz_church_privacy_edit_church' => 'Edit Church',
    '_modzzz_church_privacy_admins_only' => 'Admins Only',
    '_modzzz_church_anonymous_note' => 'your name will not appear as the poster', 
    '_mma_church_view_church' => 'church view church', 
    '_mma_church_browse' => 'church browse', 
    '_mma_church_search' => 'church search', 
    '_mma_church_add_church' => 'church add church', 
    '_mma_church_comments_delete_and_edit' => 'church comments delete and edit', 
    '_mma_church_edit_any_church' => 'church edit any church', 
    '_mma_church_delete_any_church' => 'church delete any church', 
    '_mma_church_mark_as_featured' => 'church mark as featured', 
    '_mma_church_approve_church' => 'church approve church',   


	'_modzzz_church_action_title_premium' => 'Get Premium',  
    '_modzzz_church_page_title_premium' => 'Get Premium Church',   
	'_mma_church_purchase' => 'church purchase package', 

    '_modzzz_church_action_title_extend' => 'Extend',  
    '_modzzz_church_page_title_extend' => 'Extend church listing',   
	'_mma_church_extend' => 'church extend', 

    '_modzzz_church_action_title_relist' => 'Re-list',  
    '_modzzz_church_page_title_relist' => 'Re-list church listing',  
	'_mma_church_relist' => 'church relist', 
  
    '_modzzz_church_form_caption_current_no_package' => 'No Package currently',   
    '_modzzz_church_form_caption_current_package' => 'Current Package',  
    '_modzzz_church_form_caption_package_price' => 'Package Price',  
    '_modzzz_church_form_caption_package_days' => 'Length of Church',   
 	'_modzzz_church_expires_never' => 'unlimited (never expires)', 
 	'_modzzz_church_days' => 'days', 
 	'_modzzz_church_form_caption_current_item' => 'Church', 
    '_modzzz_church_extend' => 'Extend',  
    '_modzzz_church_block_statistics' => 'Statistics',  
    '_modzzz_church_block_price' => 'Price',  
	
    '_modzzz_church_form_header_headquarters' => 'HeadQuarters Location',  
    '_modzzz_church_form_header_location' => 'Location',  
    '_modzzz_church_form_header_contact' => 'Church Contact Details',  
    '_modzzz_church_block_share' => 'Share', 
    '_modzzz_church_block_facebook_comments' => 'Facebook Comments', 
    
	'_modzzz_church_miles' => 'miles', 
    '_modzzz_church_kilometers' => 'Km', 
	'_modzzz_church_map_search_explanation' => 'Enter the City and Country (eg. miramer or miramer,US)', 

    '_modzzz_church_enter_your_church' => 'Enter your church name',
    '_modzzz_church_block_church_create' => 'List your Church with us', 
    '_modzzz_church_block_latest_comments' => 'Latest Comments',
    '_modzzz_church_block_forum' => 'Latest Forum Posts',
    '_modzzz_church_posted_by' => 'Posted by',
    '_modzzz_church_posted_in' => 'In', 
 	'_modzzz_church_posted_on' => 'on', 
 	'_modzzz_church_remove' => 'Remove',   
     '_modzzz_church_posted' => 'Posted',

    '_modzzz_church_subprofile_form_header_info' => 'Info',
    '_modzzz_church_subprofile_form_header_images' => 'Photos',
    '_modzzz_church_subprofile_form_header_videos' => 'Videos',
    '_modzzz_church_subprofile_form_header_sounds' => 'Sounds',
    '_modzzz_church_subprofile_form_header_files' => 'Files',
   
	'_modzzz_church_caption_invite' => 'Send Invitation to Friends',
	'_modzzz_church_caption_join_filter' => 'Allow to join',
	'_modzzz_church_caption_keyword' => 'Keyword',
	'_modzzz_church_caption_membership_filter' => 'Allow joining by membership',  
    '_modzzz_church_caption_search_results' => 'Search Results:',
	'_modzzz_church_caption_title' => 'Title',	

	'_modzzz_church_allow_num_listings' => 'Number of Listings allowed', 	
	'_modzzz_church_allow_videos' => 'Allow Videos', 	
	'_modzzz_church_allow_photos' => 'Allow Photos', 	
	'_modzzz_church_allow_sounds' => 'Allow Sounds', 	
	'_modzzz_church_allow_files' => 'Allow Files', 	
 	'_modzzz_church_featured' => 'Featured', 	
 	'_modzzz_church_package_desc' => 'Package Description',  

    '_modzzz_church_block_submenu_expired_church' => 'Expired',
    '_modzzz_church_page_title_expired' => 'Expired Listings', 
 	'_modzzz_church_expires' => 'Expires', 	 
 	'_modzzz_church_never' => 'Never',  
 	'_modzzz_church_featured_listing' => 'Featured Listing (never expires)',  
 	'_modzzz_church_not_featured_listing' => 'Listing is not Featured',  

    '_modzzz_church_page_title_broadcast' => 'Send broadcast message to all fans of this church',
    '_modzzz_church_msg_broadcast_message_sent' => 'Broadcast messages have been sent',
    '_modzzz_church_msg_broadcast_no_recipients' => 'There are no fans for this church yet',
    '_modzzz_church_form_caption_broadcast_title' => 'Broadcast message title',
    '_modzzz_church_form_err_broadcast_title' => 'Please enter from 3 to 100 characters', 
    '_modzzz_church_form_caption_broadcast_message' => 'Broadcast message',
    '_modzzz_church_form_err_broadcast_message' => 'Please enter at least 10 characters',
    '_modzzz_church_action_title_broadcast' => 'Broadcast',
    '_mma_church_broadcast_message' => 'church broadcast message',
 
    '_modzzz_church_form_caption_church_name' => 'Church Name',
    '_modzzz_church_form_caption_believe' => 'What We Believe',
    '_modzzz_church_form_caption_history' => 'History', 
    '_modzzz_church_form_caption_service_hours' => 'Service Hours',

    '_modzzz_church_block_believe' => 'What We Believe',
    '_modzzz_church_block_history' => 'History', 
    '_modzzz_church_block_service_hours' => 'Service Hours',
 
    '_modzzz_church_page_title_reviews' => 'Church\'s Testimonials', 
    '_modzzz_church_block_latest_reviews' => 'Latest Testimonials', 
	'_modzzz_church_action_title_review' => 'Testimonial', 
    '_modzzz_church_review_text' => 'Testimonial', 
    '_modzzz_church_review_text_info' => 'If you have been to services at this church, you can post a testimonial for the benefit of others who may wish to visit', 
    '_modzzz_church_form_caption_post_review' => 'Post Testimonial - ', 
    '_modzzz_church_review_saved' => 'Testimonial has been saved', 
    '_modzzz_church_review_not_saved' => 'Testimonial has not been saved',  
    '_modzzz_church_review' => 'Testimonial', 
    '_modzzz_church_block_church_reviews' => 'Testimonials',
    '_modzzz_church_menu_view_reviews' => 'Testimonials', 
	'_modzzz_church_review_for' => 'Testimonial for', 
	'_modzzz_church_block_reviews' => 'Testimonials', 
	'_modzzz_church_block_my_reviews' => 'My Church Testimonials',  
 	'_modzzz_church_action_title_post_review' => 'Testimonial', 
	'_modzzz_church_block_browse_reviews' => 'Browse Church Testimonials',
	'_modzzz_church_page_title_review_add' => 'Add a Testimonial for Church',
	'_modzzz_church_page_title_review_browse' => 'Browse Testimonials for Church',  
    '_modzzz_church_action_title_add_review' => 'Add Testimonial',
    '_modzzz_church_page_title_review_edit' => 'Edit Testimonial',
    '_modzzz_church_msg_church_review_was_deleted' => 'Church Testimonial was successfully deleted',
    '_modzzz_church_msg_pending_review_approval' => 'this church testimonial is pending approval, please wait until it will be activated',
    '_modzzz_church_menu_view_reviews' => 'Testimonials',  
	'_mma_church_add_review' => 'church add testimonial', 
	'_modzzz_church_posted_for' => 'Posted for Church',  
	'_modzzz_church_by' => 'by',

 	'_modzzz_church_action_title_add_to_faq' => 'Manage FAQ',
	'_modzzz_church_faqs_no_items' => 'No items in this Faq',
	'_modzzz_church_faq' => 'FAQ',   
	'_modzzz_church_form_header_faq_info' => 'FAQ Info',  
	'_modzzz_church_privacy_view_faq' => 'View FAQ',  
    '_modzzz_church_block_faq' => 'FAQ', 
    '_modzzz_church_block_faqs_items' => 'Faq Questions',  
	'_modzzz_church_block_browse_faqs' => 'Browse FAQ',
	'_modzzz_church_page_title_faq_add' => 'Manage Faq for Church',
	'_modzzz_church_page_title_faq_browse' => 'Browse FAQ for Church',  
    '_modzzz_church_action_title_add_faq' => 'Add FAQ',
    '_modzzz_church_page_title_faq_edit' => 'Edit FAQ',
    '_modzzz_church_msg_church_faq_was_deleted' => 'FAQ was successfully deleted',
    '_modzzz_church_msg_pending_faq_approval' => 'this FAQ is pending approval, please wait until it will be activated',
    '_modzzz_church_menu_view_faqs' => 'FAQ',
    '_modzzz_church_faq_items' => '{0} questions', 
    '_modzzz_church_form_caption_question' => 'Question',
    '_modzzz_church_form_caption_answer' => 'Answer (for Question above)',
    '_modzzz_church_add_another_question' => 'Add another Question', 
    '_modzzz_church_form_header_church_faq' => 'Select Questions you want to remove from FAQ ',
    '_modzzz_church_form_caption_church_faq_choice' => 'Existing Questions',
    '_modzzz_church_form_info_church_faq_choice' => 'These are FAQ Questions that you have created already',


	'_modzzz_church_block_browse_events' => 'Browse Church Events',
	'_modzzz_church_page_title_event_add' => 'Add an Event for Church',
	'_modzzz_church_page_title_event_browse' => 'Browse Events for Church',  
    '_modzzz_church_action_title_add_event' => 'Add Event',
    '_modzzz_church_page_title_event_edit' => 'Edit Event',
    '_modzzz_church_msg_church_event_was_deleted' => 'Event was successfully deleted',
    '_modzzz_church_msg_pending_event_approval' => 'this event is pending approval, please wait until it will be activated',
    '_modzzz_church_menu_view_events' => 'Events', 
    '_modzzz_church_block_events' => 'Events', 
	'_modzzz_church_caption_event_end' => 'Date end',
	'_modzzz_church_caption_event_start' => 'Date start',
	'_modzzz_church_caption_place' => 'Place name',
 
	'_modzzz_church_block_browse_sermons' => 'Browse Church Sermons',
	'_modzzz_church_page_title_sermon_add' => 'Add a Sermon for Church',
	'_modzzz_church_page_title_sermon_browse' => 'Browse Sermons for Church',  
    '_modzzz_church_action_title_add_sermon' => 'Add Sermon',
    '_modzzz_church_page_title_sermon_edit' => 'Edit Sermon',
    '_modzzz_church_msg_church_sermon_was_deleted' => 'Sermon was successfully deleted',
    '_modzzz_church_msg_pending_sermon_approval' => 'this sermon is pending approval, please wait until it will be activated',
    '_modzzz_church_menu_view_sermons' => 'Sermons', 
    '_modzzz_church_block_sermons' => 'Sermons',

	'_modzzz_church_block_browse_staffs' => 'Browse Church Staff',
	'_modzzz_church_page_title_staff_add' => 'Add a Staff for Church',
	'_modzzz_church_page_title_staff_browse' => 'Browse Staff for Church',  
    '_modzzz_church_action_title_add_staff' => 'Add Staff',
    '_modzzz_church_page_title_staff_edit' => 'Edit Staff',
    '_modzzz_church_msg_church_staff_was_deleted' => 'Staff was successfully deleted',
    '_modzzz_church_msg_pending_staff_approval' => 'this staff is pending approval, please wait until it will be activated',
    '_modzzz_church_menu_view_staffs' => 'Staff', 
    '_modzzz_church_block_staffs' => 'Staff', 

	'_modzzz_church_block_browse_doctrines' => 'Browse Church Doctrines',
	'_modzzz_church_page_title_doctrine_add' => 'Add a Doctrine for Church',
	'_modzzz_church_page_title_doctrine_browse' => 'Browse Doctrines for Church',  
    '_modzzz_church_action_title_add_doctrine' => 'Add Doctrine',
    '_modzzz_church_page_title_doctrine_edit' => 'Edit Doctrine',
    '_modzzz_church_msg_church_doctrine_was_deleted' => 'Doctrine was successfully deleted',
    '_modzzz_church_msg_pending_doctrine_approval' => 'this doctrine is pending approval, please wait until it will be activated',
    '_modzzz_church_menu_view_doctrines' => 'Doctrines', 
    '_modzzz_church_block_doctrines' => 'Doctrines', 

 	'_modzzz_church_block_browse_news' => 'Browse Church News',
	'_modzzz_church_page_title_news_add' => 'Add News for Church',
	'_modzzz_church_page_title_news_browse' => 'Browse News for Church',  
    '_modzzz_church_action_title_add_news' => 'Add News',
    '_modzzz_church_page_title_news_edit' => 'Edit News',
    '_modzzz_church_msg_church_news_was_deleted' => 'News was successfully deleted',
    '_modzzz_church_msg_pending_news_approval' => 'this news is pending approval, please wait until it will be activated',
    '_modzzz_church_menu_view_news' => 'News', 
    '_modzzz_church_block_news' => 'News',

	'_modzzz_church_block_browse_branches' => 'Browse Church Branches',
	'_modzzz_church_page_title_branches_add' => 'Add a Branch for Church',
	'_modzzz_church_page_title_branches_browse' => 'Browse Branches for Church',  
    '_modzzz_church_action_title_add_branches' => 'Add Branch',
    '_modzzz_church_page_title_branches_edit' => 'Edit Branch',
    '_modzzz_church_msg_church_branches_was_deleted' => 'Branches was successfully deleted',
    '_modzzz_church_msg_pending_branches_approval' => 'this branches is pending approval, please wait until it will be activated',
    '_modzzz_church_menu_view_branches' => 'Branches', 
    '_modzzz_church_block_branches' => 'Branches',

	'_modzzz_church_block_browse_ministries' => 'Browse Church Ministries',
	'_modzzz_church_page_title_ministries_add' => 'Add a Ministry for Church',
	'_modzzz_church_page_title_ministries_browse' => 'Browse Ministries for Church',  
    '_modzzz_church_action_title_add_ministries' => 'Add Ministry',
    '_modzzz_church_page_title_ministries_edit' => 'Edit Ministry',
    '_modzzz_church_msg_church_ministries_was_deleted' => 'Ministries was successfully deleted',
    '_modzzz_church_msg_pending_ministries_approval' => 'this ministries is pending approval, please wait until it will be activated',
    '_modzzz_church_menu_view_ministries' => 'Ministries', 
    '_modzzz_church_block_ministries' => 'Ministries',

	'_modzzz_church_block_browse_members' => 'Browse Church Members',
	'_modzzz_church_page_title_members_add' => 'Add a Member for Church',
	'_modzzz_church_page_title_members_browse' => 'Browse Members for Church',  
    '_modzzz_church_action_title_add_members' => 'Add Member',
    '_modzzz_church_page_title_members_edit' => 'Edit Member',
    '_modzzz_church_msg_church_members_was_deleted' => 'Members was successfully deleted',
    '_modzzz_church_msg_pending_members_approval' => 'this members is pending approval, please wait until it will be activated',
    '_modzzz_church_menu_view_members' => 'Members', 
    '_modzzz_church_block_members' => 'Members',
  
    '_modzzz_church_subprofile_form_header_info' => 'Info',
    '_modzzz_church_subprofile_form_header_images' => 'Photos',
    '_modzzz_church_subprofile_form_header_videos' => 'Videos',
    '_modzzz_church_subprofile_form_header_sounds' => 'Sounds',
    '_modzzz_church_subprofile_form_header_files' => 'Files',

    '_modzzz_church_form_caption_paypal' => 'Paypal',
    '_modzzz_church_form_info_paypal' => 'Paypal account for accepting donations. Leave blank if you do not wish to receive donations',
    '_modzzz_church_action_title_make_donation' => 'Make Donation', 
    '_modzzz_church_page_title_donation_add' => 'Make Donation',
    '_modzzz_church_page_title_donation_browse' => 'Browse Donations', 
    '_modzzz_church_form_caption_error_message' => 'Error Message',
    '_modzzz_church_form_caption_amount' => 'Amount', 
    '_modzzz_church_form_error_amount' => 'you must enter amount',
    '_modzzz_church_paypal_donation_desc' => 'Donation to Church',
    '_modzzz_church_donation_failed' => 'Donation failed. Please try again',   
    '_mma_church_make_donation' => 'church accept donation',  
    '_modzzz_church_donation_err_wrong_transaction' => 'There was a problem with donation transaction',  
    '_modzzz_church_donation_err_wrong_verification_status' => 'There was a problem verifying your Paypal information',  
    '_modzzz_church_caption_browse_church_donors' => 'Browse donors to Church',  
    '_modzzz_church_donation' => 'Donation', 
    '_modzzz_church_block_donors' => 'Donors',  
    '_modzzz_church_donated_to' => 'Donated to', 
    '_modzzz_church_donated_by' => 'Donated by', 
    '_modzzz_church_donated' => 'Donated',   
    '_modzzz_church_someone' => 'Someone',  
    '_modzzz_church_form_caption_first_name' => 'First Name',   
    '_modzzz_church_form_caption_last_name' => 'Last Name',   
    '_modzzz_church_form_caption_anonymous' => 'Anonymous',   
    '_modzzz_church_form_info_anonymous' => 'You will not be listed in the Donors list',
    '_modzzz_church_privacy_view_donors' => 'View Donors',
    '_modzzz_church_menu_manage_donors' => 'Donors',
    '_modzzz_church_churches' => 'Churches',
 
 
 
  	/*added 7.1 */
    '_modzzz_church_wall_added_new_comment' => 'commented on a',
    '_modzzz_church_wall_added_new_items' => 'added {0} new churches',
	'_modzzz_church_single' => 'Church',
    '_modzzz_church_posted_in_topic' => 'Posted in Forum',
    '_modzzz_church_posted_in_church' => 'Posted for Church',
	'_modzzz_church_message' => 'Message',
    '_modzzz_church_block_calendar' => 'Calendar', 
    '_modzzz_church_adm_stats' => 'Pending Churches',
 	'_sys_module_church' => 'Church',  

	'_modzzz_church_event_single' => 'Church Event',
	'_modzzz_church_event' => 'Church Event',
  
	'_modzzz_church_branch_single' => 'Church Branch',
	'_modzzz_church_branch' => 'Church Branch',
 
	'_modzzz_church_views' => 'views',
	'_modzzz_church_more_details' => 'more details ..',
 	
	'_modzzz_church_branches' => 'Church Branches',
	'_modzzz_church_event' => 'Church Event',
	'_modzzz_church_members' => 'Church Members',
	'_modzzz_church_news' => 'Church News',
	'_modzzz_church_doctrine' => 'Church Doctrine',
	'_modzzz_church_staff' => 'Church Staff',
	'_modzzz_church_ministries' => 'Church Ministries',

	'_modzzz_church_browse_church_in_country' => 'Churches in {0}',
 
	'_modzzz_church_event_anniversary' => 'Anniversary',
	'_modzzz_church_event_birthday' => 'Birthday',
	'_modzzz_church_event_christening' => 'Christening',
	'_modzzz_church_event_community_event' => 'Community Event', 
	'_modzzz_church_event_club' => 'Club',
	'_modzzz_church_event_corporate_function' => 'Corporate function',
	'_modzzz_church_event_festival' => 'Festival', 
	'_modzzz_church_event_fund_raiser' => 'Fund Raiser', 
	'_modzzz_church_event_tour' => 'Tour',  
	'_modzzz_church_event_wedding' => 'Wedding',
	'_modzzz_church_event_other' => 'Other',
    '_modzzz_church_form_info_position' => 'This states the office that the person holds (eg. Deacon)',

 );