<?php
/**********************************************************************************
*                            IBDW EvoWall for Dolphin Smart Community Builder
*                              -------------------
*     begin                : July 23 2012
*     copyright            : (C) 2012 IlBelloDelWEB.it di Ferraro Raffaele Pietro
*     website              : http://www.ilbellodelweb.it
* This file was created but is NOT part of Dolphin Smart Community Builder 7
*
* IBDW EvoWall is not free and you cannot redistribute and/or modify it.
* 
* IBDW EvoWall is protected by a commercial software license.
* The license allows you to obtain updates and bug fixes for free.
* Any requests for customization or advanced versions can be requested 
* at the email info@ilbellodelweb.it. You can modify freely only your language file
* 
* For more details see license.txt file; if not, write to info@ilbellodelweb.it
**********************************************************************************/
$sLangCategory = 'evowall';
$aLangContent = array(
'_sys_module_evowall' => 'News Feed',

 '_ibdw_evowall_informations' => 'IBDW EvoWall information',
  '_ibdw_evowall_writeapost' => 'Ecrire un commentaire',
  '_ibdw_evowall_not_allowed' => 'This module is not allowed, please confirm your registrantion',
  '_ibdw_evowall_notify_comment_like_yown' => '<a class="usernamestyle" href="{sender_p_link}">{sender_p_nick}</a> aime une photo: <a href="{album_url}"><b>{album_caption}</b></a>',
  '_ibdw_evowall_notify_like_modzzz_listing' => '<i class="sys-icon briefcase"></i> <a href="{sender_p_link}">{sender_p_nick}</a> aime <a href="{url}">l\'entreprise</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_listing' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté sur une<a href="{url}">entreprise</a>',
  '_ibdw_evowall_bx_resume_add_condivisione' => '<i class="sys-icon user"></i> <a href="{entry_url}">{entry_title}</a>
<br><a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé une fiche des compétences  </span>',
  '_ibdw_evowall_bx_listing_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé une page d\' entreprise <i class="sys-icon hand-o-right"></i> <a href="{entry_url}">{entry_title}</a> </span>',
  '_ibdw_evowall_listing_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté une entreprise <i class="sys-icon hand-o-right"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_listing_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté une entreprise <i class="sys-icon hand-o-right"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_listing_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">est entrain de suivre cette entreprise <i class="sys-icon hand-o-right"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_listing_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx"> a mis à jour  sa page entreprise <i class="sys-icon hand-o-right"></i>  <a href="{entry_url}">{entry_title}</a>
</span>',
  '_ibdw_evowall_listing_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx"> a créé une page entreprise <i class="sys-icon hand-o-right"></i> <a href="{entry_url}">{entry_title}</a>.
 </span>',
  '_ibdw_evowall_notify_like_modzzz_jobs' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime l\' <a href="{url}">offre d\'emploi</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_jobs' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une <a href="{url}">offre d\'emploi</a>',
  '_ibdw_evowall_bx_job_add_condivisione' => '<i class="sys-icon desktop"></i>  <a href="{entry_url}">{entry_title}</a>
<br><a href="{profile_link}">{profile_nick}</a> <span class="actionx"> a partagé une offre d\'emploi</span>',
  '_ibdw_evowall_job_comment' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté cette offre  </span>',
  '_ibdw_evowall_job_rate' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté cette offre <i class="sys-icon briefcase"></i> </span>',
  '_ibdw_evowall_job_join' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">est entrain de suivre une annonce d\'emploi  <i class="sys-icon briefcase"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_job_editaw' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a modifié son offre d\'emploi  <i class="sys-icon briefcase"></i></span>',
  '_ibdw_evowall_job_add' => '<a href="{profile_link}">{profile_nick}</a> a publié une offre d\'emploi  <i class="sys-icon briefcase"></i>',
  
  '_ibdw_evowall_notify_like_modzzz_articles' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime l\' <a href="{url}">article</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_articles' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">article</a>',
  '_ibdw_evowall_bx_article_add_condivisione' => '<i class="sys-icon desktop"></i>  <a href="{entry_url}">{entry_title}</a>
<br><a href="{profile_link}">{profile_nick}</a> <span class="actionx"> a partagé un article</span>',
  '_ibdw_evowall_article_comment' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté cet article </span>',
  '_ibdw_evowall_article_rate' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté cet article <i class="sys-icon briefcase"></i> </span>',
  '_ibdw_evowall_article_join' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">est entrain de suivre un article:  <i class="sys-icon briefcase"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_article_editaw' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a modifié son article:  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_article_add' => '<a href="{profile_link}">{profile_nick}</a> a publié un article: <i class="sys-icon briefcase"></i>',
  
  
  
  
  
   '_ibdw_evowall_notify_like_modzzz_formations' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime la <a href="{url}">formation</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_formations' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une <a href="{url}">formation</a>',
  '_ibdw_evowall_bx_formation_add_condivisione' => '<i class="sys-icon desktop"></i>  <a href="{entry_url}">{entry_title}</a>
<br><a href="{profile_link}">{profile_nick}</a> <span class="actionx"> a partagé une formation</span>',
  '_ibdw_evowall_formation_comment' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté cette formation </span>',
  '_ibdw_evowall_formation_rate' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté cette formation <i class="sys-icon briefcase"></i> </span>',
  '_ibdw_evowall_formation_join' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">est entrain de suivre cette formation:  <i class="sys-icon briefcase"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_formation_editaw' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a modifié sa formation:  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_formation_add' => '<a href="{profile_link}">{profile_nick}</a> a publié une formation: <i class="sys-icon briefcase"></i>',

  
  
   '_ibdw_evowall_notify_like_modzzz_investment' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime le <a href="{url}">projet</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_investment' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">projet</a>',
  '_ibdw_evowall_bx_investment_add_condivisione' => '<i class="sys-icon desktop"></i>  <a href="{entry_url}">{entry_title}</a>
<br><a href="{profile_link}">{profile_nick}</a> <span class="actionx"> a partagé un projet</span>',
  '_ibdw_evowall_investment_comment' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté ce projet </span>',
  '_ibdw_evowall_investment_rate' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté ce projet <i class="sys-icon briefcase"></i> </span>',
  '_ibdw_evowall_investment_join' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">est entrain de suivre ce projet:  <i class="sys-icon briefcase"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_investment_editaw' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a modifié son projet:  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_investment_add' => '<a href="{profile_link}">{profile_nick}</a> a publié un projet: <i class="sys-icon briefcase"></i>',

  
  
  
  
  '_ibdw_evowall_notify_like_modzzz_news' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime <a href="{url}">la publication</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_news' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une <a href="{url}">publication</a>',
  '_ibdw_evowall_bx_news_add_condivisione' => '<a href="{entry_url}">{entry_title}</a>
<br><a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé une publication</span>',
  '_ibdw_evowall_news_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté une publication <i class="sys-icon hand-o-right"></i>   <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_news_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté une publication <i class="sys-icon hand-o-right"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_news_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a modifié une publication <i class="sys-icon hand-o-right"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_news_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a publié un article <i class="sys-icon hand-o-right"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_notify_like_modzzz_classified' => '<i class="sys-icon shopping-cart"></i>  <a href="{sender_p_link}">{sender_p_nick}</a> aime <a href="{url}">l\'annonce </a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_classified' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté <a href="{url}">une annonce </a>',
  '_ibdw_evowall_bx_classified_add_condivisione' => '<i class="sys-icon shopping-cart"></i>  <a href="{entry_url}">{entry_title}</a>
<br><a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé une annonce  </span>',
  '_ibdw_evowall_classified_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté une annonce  <i class="sys-icon hand-o-right"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_classified_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté une annonce  <i class="sys-icon hand-o-right"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_classified_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a modifié son annonce <i class="sys-icon hand-o-right"></i> <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_classified_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a publié une annonce  <i class="sys-icon hand-o-right"></i> <a href="{entry_url}">{entry_title}</a> </span>',
  '_ibdw_evowall_notify_like_modzzz_notices' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime l\' <a href="{url}">avis</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_notices' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">avis</a>',
  '_ibdw_evowall_notify_like_modzzz_schools' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime l\' <a href="{url}">école</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_schools' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une <a href="{url}">école</a>',
  '_ibdw_evowall_school_comment' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx"> a commenté cette école <i class="sys-icon university"></i> </span>',
  '_ibdw_evowall_school_rate' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">vient de noter cette école  <i class="sys-icon university"></i></span>',
  '_ibdw_evowall_school_join' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx"> est devenu follower de cette école <i class="sys-icon university"></i></span>',
  '_ibdw_evowall_school_editaw' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a mis à jour les infos de cette école  <i class="sys-icon university"></i></span>',
  '_ibdw_evowall_school_add' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a inscrit une école sur le réseau CongoConnect.com  <i class="sys-icon university"></i></span>',
  '_ibdw_evowall_notify_like_modzzz_bands' => '<a href="{sender_p_link}">{sender_p_nick}</a> like a <a href="{url}">band</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_bands' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">band</a>',
  '_ibdw_evowall_notify_like_modzzz_pets' => '<a href="{sender_p_link}">{sender_p_nick}</a> like a <a href="{url}">pet</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_pets' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">pet</a>',
  '_ibdw_evowall_notify_like_modzzz_petitions' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime la <a href="{url}">pétition</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_petitions' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté sur une <a href="{url}">pétition</a>',
  '_ibdw_evowall_bx_petition_add_condivisione' => '<i class="sys-icon tablet"></i>  <a href="{entry_url}">{entry_title}</a> 
<br><a href="{profile_link}">{profile_nick}</a> <span class="actionx"> a partagé une  pétition </span>',
  '_ibdw_evowall_notify_like_modzzz_clubs' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime le <a href="{url}">club</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_clubs' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">club</a>',
  '_ibdw_evowall_rate_photo_multi' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté des photos</span>',
  '_ibdw_evowall_comment_nphoto_multi' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté des photos</span>',
  '_ibdw_evowall_alertprivacyprofileviewexplain' => '{ProfileName} autorise la consultation son propre mur ',
  '_ibdw_evowall_wait_button' => 'Patientez',
  '_ibdw_evowall_alertprivacyprofileview' => 'Ce mur est privé',
  '_ibdw_evowall_currency_price' => '? ',
  '_ibdw_evowall_newsupdate' => 'Mettre ',
  '_ibdw_evowall_mostrecent' => 'News',
  '_ibdw_evowall_mostpopular' => 'les plus populaires',
  '_ibdw_evowall_similarevonews' => 'Voir d\'autres messages similaires',
  '_ibdw_evowall_similarevonews_photo' => 'Voir en détails {number} autres publications similaires <i class="sys-icon hand-o-left"></i>',
  '_ibdw_evowall_event_end' => 'Fin de l\'événement: ',
  '_ibdw_evowall_event_start' => 'Début de l\'événement: ',
  '_ibdw_evowall_parent_photo' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a ajouté {number} nouvelles photos',
  '_ibdw_evowall_allcomm2' => ' commentaires',
  '_ibdw_evowall_allcomm' => 'Tout afficher ',
  '_ibdw_evowall_minimize' => 'Click on the picture to minimize the image',
  '_ibdw_evowall_maximize' => 'Cliquez ici pour agrandir la photo',
  '_ibdw_evowall_messageandpreview' => 'Tout partager',
  '_ibdw_evowall_justmessage' => 'Message uniquement',
  '_ibdw_evowall_closelink' => 'Cancel',
  '_ibdw_evowall_surlmess' => ' a partagé le lien: ',
  '_ibdw_evowall_urlmess' => ' a partagé ce lien <i class="sys-icon external-link-square"></i>   ',
  '_ibdw_evowall_qzone_share' => 'Qzone share',
  '_ibdw_evowall_weibo_share' => 'Weibo share',
  '_ibdw_evowall_baidu_share' => 'Baidu share',
  '_ibdw_evowall_pinterest_share' => 'Pinterest share',
  '_ibdw_evowall_google_share' => 'Partager sur Google+ ',
  '_ibdw_evowall_twitter_share' => 'Partager sur Twitter',
  '_ibdw_evowall_linkedin_share' => 'Partager sur LinkedIn ',
  '_ibdw_evowall_facebook_share' => 'Partager sur Facebook',
  '_ibdw_evowall_qzone_share_p' => 'Allow Qzone share to',
  '_ibdw_evowall_weibo_share_p' => 'Allow Weibo share to',
  '_ibdw_evowall_baidu_share_p' => 'Allow Baidu share to',
  '_ibdw_evowall_pinterest_share_p' => 'Allow Pinterest share to',
  '_ibdw_evowall_linkedin_share_p' => 'Autoriser le partage sur  LinkedIn ',
  '_ibdw_evowall_google_share_p' => 'Autoriser le partage sur Google+ share ',
  '_ibdw_evowall_twitter_share_p' => 'Allow Twitter share to',
  '_ibdw_evowall_facebook_share_p' => 'Autorise le partage sue Facebook',
  '_ibdw_evowall_Allow_share' => 'Autoriser le partage ',
  '_ibdw_evowall_Privacy_View' => 'Autoriser la visualisation ',
  '_ibdw_evowall_Privacy_ContentBox' => 'Autoriser le tableau de bord ',
  '_ibdw_evowall_Privacy_Like' => 'Autoriser "J\'aime" ',
  '_ibdw_evowall_Privacy_Comment' => 'Autoriser des commentaires ',
  '_ibdw_evowall_welcome_hidemessage' => 'Masquer ce message',
  '_ibdw_evowall_welcome_message' => '<br>Welcome sur CongoConnect.com, Réseau Social Professionnel - 100% Congolais',
  '_ibdw_evowall_welcome_title' => 'Bienvenue!',
  '_ibdw_evowall_notify_like_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime votre message',
  '_ibdw_evowall_notify_like_ads_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime une <a href="{url}">annonce</a>',
  '_ibdw_evowall_notify_like_sites_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime un <a href="{url}">site</a>',
  '_ibdw_evowall_notify_like_events_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime un <a href="{url}">événement</a>',
  '_ibdw_evowall_notify_like_groups_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime un <a href="{url}">groupe</a>',
 '_ibdw_evowall_notify_like_poll_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime un <a href="{url}">sondage</a>',
  '_ibdw_evowall_notify_like_video_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime une <a href="{url}">vidéo</a>',
  '_ibdw_evowall_notify_like_photo_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime une <a href="{url}">photo</a>',
  '_ibdw_evowall_notify_comment_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté votre message',
  '_ibdw_evowall_notify_comment_ads_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une <a href="{url}">annonce</a>',
  '_ibdw_evowall_notify_comment_sites_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">site</a>',
  '_ibdw_evowall_notify_comment_events_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">événement</a></a>',
  '_ibdw_evowall_notify_comment_groups_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">groupe</a>',
  '_ibdw_evowall_notify_comment_poll_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">sondage</a>',
  '_ibdw_evowall_notify_comment_video_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une <a href="{url}">vidéo</a>',
  '_ibdw_evowall_notify_comment_photo_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une <a href="{album_url}">photo</a>',
  '_ibdw_evowall_notify_like_url' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime l\' <a href="{url}">url</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_like_modzzz_property' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime l\' <a href="{url}">annonce immobilière</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_like_ue30location' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime le <a href="{url}">lieu</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_like_sounds' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime la <a href="{url}">musique</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_like_blogs' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime le <a href="{url}">blog</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_like' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime le message de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_like_ads' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime l\' <a href="{url}">annoce</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_like_sites' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime le <a href="{url}">site</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_like_events' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime l\' <a href="{url}">événementt</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_like_groups' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime le <a href="{url}">groupe</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_like_poll' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime le <a href="{url}">sondage</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_like_video' => '<i class="sys-icon film"></i> <a href="{sender_p_link}">{sender_p_nick}</a>    aime la  <a href="{url}">vidéo</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_like_photo' => '<a href="{sender_p_link}">{sender_p_nick}</a> aime la <a href="{url}">photo</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_url' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">url</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_modzzz_property' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une <a href="{url}">annonce immobilière</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_ue30location' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une <a href="{url}">lieu</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_sounds' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une <a href="{url}">musique</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_blogs' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">blog</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un message de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_ads' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une <a href="{url}">annonce</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_sites' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">site</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_events' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">événement</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_groups' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">groupe</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_poll' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté un <a href="{url}">sondage</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_video' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une <a href="{url}">vidéo</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_notify_comment_photo' => '<a href="{sender_p_link}">{sender_p_nick}</a> a commenté une  <a href="{url}">photo</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>',
  '_ibdw_evowall_introcontent' => 'Partager',
  '_ibdw_evowall_bx_url_share' => '<a href="{sender_p_link}">{sender_p_nick}</a> a partagé le site: <i class="sys-icon external-link-square"></i> <a href="{indirizzo}" target="_blank">{indirizzo}</a>',
  '_ibdw_evowall_bx_url_add' => '<a href="{sender_p_link}">{sender_p_nick}</a> a ajouté un site:  <i class="sys-icon external-link-square"></i>   <a href="{indirizzo}" target="_blank">{indirizzo}</a>',
  '_ibdw_evowall_nopreview' => 'Aucun aperçu',
  '_ibdw_evowall_erroreurl' => 'Erreur: cet URL semble ne pas être valide ou le site est hors ligne.<br/><a href="javascript:url();">Cliquer ici pour essayer encore</a>',
  '_ibdw_evowall_totpreviewno' => 'Aucune image pour ce site',
  '_ibdw_evowall_totpreview2s' => '  image',
  '_ibdw_evowall_totpreview1s' => 'Il y a ',
  '_ibdw_evowall_totpreview2' => ' images',
  '_ibdw_evowall_totpreview1' => 'Il y a ',
  '_ibdw_evowall_selezionapreview' => 'Sélectionner l\'aperçu:',
  '_ibdw_evowall_url' => 'Partager un lien',
  '_ibdw_evowall_urlspecial' => 'Insérer le lien/url ici:',
  '_ibdw_evowall_bx_evowall_messageseitu' => '<a href="{sender_p_link}">{sender_p_nick}</a> a envoyé un message',
  '_ibdw_evowall_bx_evowall_message' => '<a href="{sender_p_link}">{sender_p_nick}</a> a envoyé un message ',
  '_ibdw_evowall_uploadfromyoutube' => 'Transférer Youtube',
  '_ibdw_evowall_linktoyoutube' => 'Lien de la vidéo',
  '_ibdw_evowall_comment_album' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté l\'album <a href="{album_url}">{album_caption}</a></span>',
  '_ibdw_evowall_share_album' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé  cet album <a href="{album_url}">{album_caption}</a></span>',
  '_ibdw_evowall_cancellupload' => 'Annuler le transfert',
  '_ibdw_evowall_selectfiles' => 'Sélectionner le fichier',
  '_ibdw_evowall_notificalikefriend' => 'Votre demande a été envoyé. Veuillez attendre la confirmation',
  '_ibdw_evowall_wallprofile' => '\'s Wall',
  '_ibdw_evowall_mywall' => 'My Wall',
  '_ibdw_evowall_notifica_condivisioneok' => 'Le contenu a été partagé',
  '_ibdw_evowall_bott_notifica_2' => 'Ok',
  '_ibdw_evowall_bott_notifica_sharenotify' => 'This post has been shared into your profile\'s wall',
  '_ibdw_evowall_bott_notifica_1' => 'Information',
  '_ibdw_evowall_bott_condividi_4' => 'Annuler',
  '_ibdw_evowall_bott_condividi_3' => 'Partager',
  '_ibdw_evowall_bott_condividi_2' => '',
  '_ibdw_evowall_bott_condividi_1' => 'Poster ',
  '_ibdw_evowall_bott_elimina_4' => 'Annuler',
  '_ibdw_evowall_bott_elimina_3' => 'Confirmer',
  '_ibdw_evowall_bott_elimina_2' => 'Etes-vous sûr de vouloir supprimer cette publication? ',
  '_ibdw_evowall_bott_elimina_1' => 'Supprimer le post',
  '_ibdw_evowall_conf_email_pay' => 'Oui',
  '_ibdw_evowall_send_rqs' => 'Envoyer la demande',
  '_ibdw_evowall_eml_t_add' => 'Entrer votre email (Paypal/Echeck)',
  '_ibdw_evowall_2step' => 'Etape 2',
  '_ibdw_evowall_1step' => 'Etape 1',
  '_ibdw_evowall_infocoferma2' => ') le même email que vous avez utilisé pour payer?',
  '_ibdw_evowall_infocoferma1' => 'Est-ce (',
  '_ibdw_evowall_exlinkyb' => 'http://www.youtube.com/watch?v=0yW8ZIDuXls',
  '_ibdw_evowall_example' => 'Exemple',
  '_ibdw_evowall_continue' => 'Continuer',
  '_ibdw_evowall_iveright' => 'J\'ai le droit de diffuser ces photos ',
  '_ibdw_evowall_uploadfrompc' => 'Transférer ',
  '_ibdw_evowall_introattivazione' => 'TO ACTIVATE EVO WALL YOU NEED INSERT THE SAME EMAIL ADRESS (PAYPAL/ECHECK) USED FOR MODULE\'S PURCHASING AND THEN CLICK \'\'SEND REQUEST\'\'. YOU WILL RECEIVE AN EMAIL AT THE SAME ADDRESS CONTAINING THE ACTIVATION\'S CODE. THEN INSERT THIS CODE AND CLICK THE BUTTON \'ACTIVATE\'',
  '_ibdw_evowall_yosattiva' => 'Attention, your copy of EVO Wall is already active!',
  '_ibdw_evowall_spycodereq' => 'activation\'s code request',
  '_ibdw_evowall_activaintro' => 'EVO Wall activation\'s procedure',
  '_ibdw_evowall_unsure' => 'NOT (Back)',
  '_ibdw_evowall_updater' => 'Update completed successfully',
  '_ibdw_evowall_sicurity' => '<div style="padding:20px;color:red;">The EVO Wall (NEWS FEED) is not active, you must insert a valid activation code.<br>Visit the module configurator to get and insert the activation code.<br><br>This message is visible only to the administrator</div>',
  '_ibdw_evowall_msgformhome' => 'Exprimez-vous',
  '_ibdw_evowall_mutualfriendonlyone' => 'ami en commun',
  '_ibdw_evowall_mutualfriend' => 'amis en commun',
  '_ibdw_evowall_unlikethis' => 'Je n\'aime plus!',
  '_ibdw_evowall_sender' => 'Partager',
  '_ibdw_evowall_likethis' => 'J\'aime!',
  '_ibdw_evowall_likeyou' => 'Vous',
  '_ibdw_evowall_likeand' => 'et',
  '_ibdw_evowall_thiselementlike' => 'J\'aime:',
  '_ibdw_evowall_ilikeit' => 'Vous aimez',
  '_ibdw_evowall_friendlike2' => 'demande envoyée',
  '_ibdw_evowall_friendlike' => 'Ajouter à votre liste d\'amis',
  '_ibdw_evowall_elementlike2' => 'aime ça',
  '_ibdw_evowall_elementlike1' => 'membres',
  '_ibdw_evowall_bx_alert_notify' => 'Vous n\'avez pas la permission de poster ce message ',
  '_ibdw_evowall_bx_video_undernotify' => '(cette vidéo sera disponible une fois approuvée)',
  '_ibdw_evowall_bx_video_under' => 'a ajouté une vidéo:',
  '_ibdw_evowall_bx_access_denied' => 'Privé: Vous n\'avez pas l\'autorisation d\'acceder ce contenu!',
  '_ibdw_evowall_bx_share_message' => 'Le contenu a été partagé avec succés.',
  '_ibdw_evowall_bx_share_title' => 'Vous avez partagé un contenu',
  '_ibdw_evowall_fotoalbum' => 'Mur-Photo',
  '_ibdw_evowall_videoalbum' => 'Mur-Video',
  '_ibdw_evowall_bx_messaggio' => 'a posté un message personnel',
  '_ibdw_evowall_ue30_locations_add_condivisione' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé un lieu <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_modzzz_property_share' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé une annonce immobilière <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_ue30_event_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé un événement <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_bx_event_add_condivisione' => '<i class="sys-icon calendar"></i>  <a href="{entry_url}">{entry_title}</a>
<br><a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a publié un événement</span>',
  '_ibdw_evowall_bx_site_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé un site <a href="{site_url}">{site_caption}</a></span>',
  '_ibdw_evowall_bx_poll_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé un sondage <a href="{poll_url}">{poll_caption}</a></span>',
  '_ibdw_evowall_bx_photo_add_condivisione' => '<i class="sys-icon camera"></i>  <a href="{entry_url}">{entry_caption}</a> 
<br><a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a posté une photo </span>',
  '_ibdw_evowall_bx_gruppo_add_condivisione' => '<i class="sys-icon users"></i>  <a href="{entry_url}">{entry_title}</a>
<br><a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a créé un groupe</span>',
  '_ibdw_evowall_bx_video_add_condivisione' => '<i class="sys-icon film"></i>  <a href="{entry_url}">{entry_caption}</a> 
<br><a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé une vidéo </span>',
  '_ibdw_evowall_bx_sounds_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé une musique <a href="{entry_url}">{entry_caption}</a></span>',
  '_ibdw_evowall_bx_blogs_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé un blog <a href="{post_url}">{post_caption}</a></span>',
  '_ibdw_evowall_bx_ads_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a partagé une annonce <a href="{ads_url}">{ads_caption}</a></span>',
  '_ibdw_evowall_delete' => 'Supprimer',
  '_ibdw_evowall_send' => 'Partager',
  '_ibdw_evowall_second' => 'Veuillez patienter',
  '_ibdw_evowall_profile_news' => '<i class="sys-icon rss"></i> Fil d\'actualité',
  '_ibdw_evowall_member_news' => '<i class="sys-icon rss"></i> Fil d\'actualité',
  '_ibdw_evowall_altricommenti' => 'Afficher plud',
  '_ibdw_evowall_inseriscivideo' => 'Ajouter une vidéo',
  '_ibdw_evowall_soloio' => 'Moi uniquement',
  '_ibdw_evowall_altrimetodi' => 'Autres methodes',
  '_ibdw_evowall_inseriscifoto' => 'Insérer une photo',
  '_ibdw_evowall_inseriscisondaggio' => 'Publier un Sondage',
  '_ibdw_evowall_inseriscisito' => 'Lien',
  '_ibdw_evowall_sitoup' => 'Site',
  '_ibdw_evowall_adsup' => 'Petites annonces',
  '_ibdw_evowall_sondaggioup' => 'Créer un sondage',
  '_ibdw_evowall_gruppoup' => 'Créer un groupe',
  '_ibdw_evowall_videoup' => 'Partager une vidéo',
  '_ibdw_evowall_fotoup' => 'Partager une photo',
  '_ibdw_evowall_altrenews' => 'Plus de news du réseau ',
  '_ibdw_evowall_condividi' => 'Envoyer',
  '_ibdw_evowall_ins_comm' => 'Commenter',
  '_ibdw_evowall_comment_titlef2' => 'commentaires',
  '_ibdw_evowall_comment_titlef1' => 'commentaire',
  '_ibdw_evowall_comment_title2' => 'Il y a ',
  '_ibdw_evowall_comment_title1' => 'Il y a',
  '_ibdw_evowall_comment_title_first' => 'Be the first',
  '_ibdw_evowall_now' => 'ajouté maintenant',
  '_ibdw_evowall_otherday' => 'Publié le ',
  '_ibdw_evowall_yesterday' => 'hier',
  '_ibdw_evowall_today' => 'aujourd\'hui',
  '_ibdw_evowall_plushoursecond' => '  heures',
  '_ibdw_evowall_plushourfirst' => 'il y a ',
  '_ibdw_evowall_onehour' => 'environ 1 heure',
  '_ibdw_evowall_plusminutesecond' => ' minutes',
  '_ibdw_evowall_plusminutefirst' => 'il y a ',
  '_ibdw_evowall_oneminute' => 'il y a environ une minute',
  '_ibdw_evowall_group_forum' => 'Groupe de discussion',
  '_ibdw_evowall_event_name' => 'Publier un événement',
  '_ibdw_evowall_original_size' => 'Vous vot dans un format original',
  '_ibdw_evowall_modzzz_polls_change' => '<a href="{profile_link}">{profile_nick}</a> a modifié sa publication de sondage:  <a href="{entry_url}">{entry_title}</a>',
  '_ibdw_evowall_poll_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a publié un sondage <a href="{poll_url}">{poll_caption}</a></span>',
  '_ibdw_evowall_event_edit' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a mis à jour la publication de son événement  <i class="sys-icon calendar"></i></span>',
  '_ibdw_evowall_event_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté un événement  <i class="sys-icon calendar"></i></span>',
  '_ibdw_evowall_event_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté  un événement  <i class="sys-icon calendar"></i></span>',
  '_ibdw_evowall_event_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx"> va participer à cet événement:  <i class="sys-icon calendar"></i> <a href="{entry_url}">{entry_title}</a>',
  '_ibdw_evowall_event_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a publié un événement <i class="sys-icon calendar"></i></span>',
  '_ibdw_evowall_group_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté un groupe <i class="sys-icon hand-o-right"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_group_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté un groupe <i class="sys-icon hand-o-right"></i>  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_group_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a rejoint  <a href="{entry_url}">{entry_title}</a></span>',
  '_ibdw_evowall_group_editaw' => '<i class="sys-icon users"></i> <a href="{entry_url}">{entry_title}</a>
<br><a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx"> a mis à jour  son groupe</span>',
  '_ibdw_evowall_group_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a créé un nouveau groupe <i class="sys-icon hand-o-right"></i>   <a href="{entry_url}">{entry_title}</a></span>  ',
  '_ibdw_evowall_site_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a ajouté un nouveau site <a href="{site_url}">{site_caption}</a></span>',
  '_ibdw_evowall_video_add' => '<i class="sys-icon film"></i>  <a href="{video_url}">{entry_caption}</a>
<br><a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a ajouté une nouvelle vidéo</span>',
  '_ibdw_evowall_photo_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a ajouté une nouvelle photo <i class="sys-icon camera"></i>  <a href="{entry_url}">{entry_caption}</a> </span>',
  '_ibdw_evowall_sounds_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté la musique <a href="{entry_url}">{entry_caption}</a></span>',
  '_ibdw_evowall_sounds_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté la <a href="{entry_url}">musique</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
  '_ibdw_evowall_sounds_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a ajouté une musique <a href="{entry_url}">{entry_caption}</a></span>',
  '_ibdw_evowall_blogs_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté le blog <a href="{post_url}">{post_caption}</a></span>',
  '_ibdw_evowall_blogs_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a créé un nouveau blog <a href="{post_url}">{post_caption}</a></span>',
  '_ibdw_evowall_blogs_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté le blog <a href="{post_url}">{post_caption}</a></span>',
  '_ibdw_evowall_ads_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a publié une petite annonce <a href="{ads_url}">{ads_caption}</a></span>',
  '_ibdw_evowall_ads_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté l\'annonce de <a href="{ads_url}">{ads_caption}</a></span>',
  '_ibdw_evowall_rate_photo' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté la <a href="{entry_url}">photo</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
  '_ibdw_evowall_comment_polls' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté le <a href="{entry_url}">sondage</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
  '_ibdw_evowall_rated_polls' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a évalué le <a href="{entry_url}">sondage</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
  '_ibdw_evowall_reply_polls' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a répondu au <a href="{entry_url}">sondage</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
  '_ibdw_evowall_rated_videos' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté la <a href="{entry_url}">vidéo</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
  '_ibdw_evowall_comment_name' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté la <a href="{entry_url}">vidéo</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
  '_ibdw_evowall_comment_nphoto' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté la <a href="{entry_url}">photo</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
  '_ibdw_evowall_site_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a commenté sur le site <a href="{site_url}">{site_caption}</a></span>',
  '_ibdw_evowall_site_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a noté le site <a href="{site_url}">{site_caption}</a></span>',
  '_ibdw_evowall_site_edit' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a modifié le site <a href="{site_url}">{site_caption}</a></span>',
  '_ibdw_evowall_isfriend' => '<a class="usernamestyle" href="{recipient_p_link}">{recipient_p_nick}</a> <span class="actionx">est maintenant connecté avec <i class="sys-icon user"></i>   <a href="{sender_p_link}">{sender_p_nick}</a></span>',
  '_ibdw_evowall_profile_rate' => '<a class="usernamestyle" href="{sender_p_link}">{sender_p_nick}</a> <span class="actionx">a noté le profil de <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
  '_ibdw_evowall_profile_edit' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a modifié son profil <i class="sys-icon user"></i></span>',
  '_ibdw_evowall_spyprofile' => '<a class="usernamestyle" href="{sender_p_link}">{sender_p_nick}</a> <span class="actionx">a consulté le profil de <i class="sys-icon user"></i>  <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
  '_ibdw_evowall_member_subscribed' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">a rejoint le réseau CongoConnect.com </span>',
  '_ibdw_evowall_comment_add' => '<a class="usernamestyle" href="{sender_p_link}">{sender_p_nick}</a> <span class="actionx">a ajouté un commentaire sur <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
  '_ibdw_evowall_information_block' => 'To get your "License Key" (Activation Code), click <a target="_blank" href="ibdw/evowall/activation.php">HERE</a><br /><br />Remember to insert <b>the same email address you have used to buy this module</b>.<br /><br />After completing these steps, check your email and put the code received into the first field of the following form:',
  

'_mma_EVO_WALL_-_Ads' => 'EVO WALL - Ads',
'_mma_EVO_WALL_-_Blogs' => 'EVO WALL - Blogs',
'_mma_EVO_WALL_-_Comments_add' => 'EVO WALL - Comments add',
'_mma_EVO_WALL_-_Comments_view' => 'EVO WALL - Comments view',
'_mma_EVO_WALL_-_Content_Box' => 'EVO WALL - Content Box',
'_mma_EVO_WALL_-_Events' => 'EVO WALL - Events',
'_mma_EVO_WALL_-_Groups' => 'EVO WALL - Groups',
'_mma_EVO_WALL_-_Pages' => 'EVO WALL - Pages',
'_mma_EVO_WALL_-_Like_add' => 'EVO WALL - Like add',
'_mma_EVO_WALL_-_Like_view' => 'EVO WALL - Like view',
'_mma_EVO_WALL_-_Personal_messages' => 'EVO WALL - Personal messages',
'_mma_EVO_WALL_-_Photos' => 'EVO WALL - Photos',
'_mma_EVO_WALL_-_Polls' => 'EVO WALL - Polls',
'_mma_EVO_WALL_-_Post_sharing' => 'EVO WALL - Post sharing',
'_mma_EVO_WALL_-_Sites' => 'EVO WALL - Sites',
'_mma_EVO_WALL_-_Sounds' => 'EVO WALL - Sounds',
'_mma_EVO_WALL_-_Videos' => 'EVO WALL - Videos',
);