<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Jobs';

$aLangContent = array(
  	'_modzzz_jobs_na' => 'N/A', 
 	'_modzzz_jobs_form_cover_caption_letter' => 'Cover Letter',
 	'_modzzz_jobs_form_caption_resume' => 'Resume',
 	'_modzzz_jobs_apply_letter_title' => 'New application for Job - {0}',
 	'_modzzz_jobs_form_err_email' => 'You must enter an email',
 	'_modzzz_jobs_form_err_cover_letter' => 'You must enter some information',
 	'_modzzz_jobs_block_job_sectors' => 'Job Sectors',
 	'_modzzz_jobs_block_company' => 'Info',
 	'_modzzz_jobs_add_company' => 'Add New Company',
 	'_modzzz_jobs_form_caption_listed_by' => 'Job Listed by',
 	'_modzzz_jobs_form_header_location' => 'Job Location (if different from Company Location)',

 	'_modzzz_jobs_form_caption_cover_letter' => 'Cover Letter',
 	'_modzzz_jobs_expires' => 'Expires',
 
 	'_modzzz_jobs_provider' => 'Provider',
 	'_modzzz_jobs_seeker' => 'Seeker',
 	'_modzzz_jobs_form_caption_post_type' => 'I am a', 
 	'_modzzz_jobs_block_seeking' => 'Recent Public Jobs (Wanted)',

	'_modzzz_jobs_caption_membership_view_filter' => 'Allow viewing by membership',
	'_modzzz_jobs_err_membership_view_filter' => 'incorrect value', 
    '_modzzz_jobs_info_membership_view_filter' => 'only these members will be able to view this business listing',
    '_modzzz_jobs_membership_filter_none' => 'Allow All',	
    '_modzzz_jobs_resume_attached' => 'Download Resume',
	'_modzzz_jobs_delete_application' => 'Delete Application',

    '_modzzz_jobs_block_jobs_applied_for' => 'Jobs I applied for',	 
    '_modzzz_jobs_applied_on' => 'Applied on',	
    '_modzzz_jobs_send_message' => 'Send Message',	 
 
   	'_modzzz_jobs_form_header_video_embed' => 'Video Embed',
   	'_modzzz_jobs_form_caption_video_embed_code' => 'Embed Code',
   	'_modzzz_jobs_block_video_embed' => 'External Video',
	'_modzzz_jobs_form_info_video_embed_code' => 'Enter either the URL or Embed Code for Youtube Video. Enter the Embed Code for other video sharing site (eg &lt;embed&gt;....&lt;/embed&gt;)',

    '_modzzz_jobs_fans' => 'fans',
    '_modzzz_jobs_sbs_join' => 'new fan',
    '_modzzz_jobs_block_fans' => 'Fans',
    '_modzzz_jobs_block_fans_unconfirmed' => 'Unconfirmed Fans',
	'_modzzz_jobs_block_my_listings_joined' => 'Joined Jobs',
    '_modzzz_jobs_caption_manage_fans' => 'Manage Fans',
    '_modzzz_jobs_menu_view_fans' => 'Fans',
    '_modzzz_jobs_page_title_fans' => 'Job\'s Fans',
    '_modzzz_jobs_action_manage_fans' => 'Manage Fans',
    '_modzzz_jobs_privacy_view_fans' => 'View Fans',
    '_modzzz_jobs_privacy_fans_only' => 'Fans Only',
    '_modzzz_jobs_privacy_fans' => 'Fans',

    '_modzzz_jobs_spy_join' => '<a href="{profile_link}">{profile_nick}</a> joined job <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_jobs_sbs_join' => 'new fan',
    '_modzzz_jobs_page_title_browse_by_author_joined_jobs' => '\'s joined jobs',
    '_modzzz_jobs_msg_joined_already' => 'You have already joined this job',
    '_modzzz_jobs_msg_joined_request_pending' => 'You have already joined this job. Please wait while your request is processed by job admin(s).',
    '_modzzz_jobs_msg_join_success' => 'You have successfully joined this job',
    '_modzzz_jobs_msg_join_success_pending' => 'You have successfully joined this job. Please wait while your request is processed by job admin(s).',
	'_modzzz_jobs_msg_leave_success' => 'You have successfully left this job',
    '_modzzz_jobs_form_caption_join_confirmation' => 'Join Confirmation',
    '_modzzz_jobs_form_info_join_confirmation' => 'If enabled, job admin(s) will have to confirm each user before he/she becomes a fan.',
    '_modzzz_jobs_form_join_confirmation_disabled' => 'Disabled',
    '_modzzz_jobs_form_join_confirmation_enabled' => 'Enabled',
    '_modzzz_jobs_form_err_join_confirmation' => 'Join confirmation field must be 0 or 1',
    '_modzzz_jobs_action_title_join' => 'Become Fan',
    '_modzzz_jobs_action_title_leave' => 'Remove Fan',
    '_modzzz_jobs_privacy_join' => 'Become Fan',
 
    '_modzzz_jobs_page_title_applications_by_author' => 'Jobs {0} applied for',

 	'_modzzz_jobs_action_title_apply' => 'Apply',
 	'_modzzz_jobs_page_title_apply' => 'Apply for this Job',
 	'_modzzz_jobs_msg_application_sent' => 'Your Job Application has been sent',

 	'_modzzz_jobs_upwards' => 'Upwards',
 	'_modzzz_jobs_block_skills' => 'Skills Required',

	'_modzzz_jobs_role' => 'Role',
	'_modzzz_jobs_experience' => 'Experience Level',
	'_modzzz_jobs_qualification' => 'Educational Qualification',
	'_modzzz_jobs_salary' => 'Salary',
	'_modzzz_jobs_company' => 'Company',
	'_modzzz_jobs_vacancies' => 'Vacancies',
 	'_modzzz_jobs_category' => 'Category',

	'_modzzz_jobs_permanent' => 'Permanent',
	'_modzzz_jobs_intern' => 'Intern / Work Experience',
	'_modzzz_jobs_temporary' => 'Temporary/Contract/Project',
	'_modzzz_jobs_part_time' => 'Part Time',
	'_modzzz_jobs_full_time' => 'Full Time',
 
	'_modzzz_jobs_form_caption_role' => 'Role',
	'_modzzz_jobs_form_caption_vacancies' => 'Vacancies',
	'_modzzz_jobs_form_caption_experience' => 'Experience',
	'_modzzz_jobs_form_caption_qualification' => 'Educational Qualification',
	'_modzzz_jobs_form_caption_skills' => 'Skills Required',
	'_modzzz_jobs_form_caption_min_salary' => 'Min. Salary',
	'_modzzz_jobs_form_caption_max_salary' => 'Max. Salary',
	'_modzzz_jobs_form_caption_currency' => 'Salary Currency',
	'_modzzz_jobs_form_caption_salary_type' => 'Salary Type',
	'_modzzz_jobs_form_caption_career_level' => 'Career Level',
	'_modzzz_jobs_form_caption_job_type' => 'Job Type',
	'_modzzz_jobs_form_caption_job_status' => 'Job Status',
 
    '_modzzz_jobs_no_preference' => 'no preference',
	'_modzzz_jobs_fresher' => 'Fresher',
	'_modzzz_jobs_less_than_1_year' => 'Less_than 1 Year',
	'_modzzz_jobs_1_to_2_years' => '1 to 2 Years',
	'_modzzz_jobs_2_to_5_years' => '2 to 5 Years',
	'_modzzz_jobs_5_to_7_years' => '5 to 7 Years',
	'_modzzz_jobs_7_to_10_years' => '7 to 10 Years',
	'_modzzz_jobs_10_to_15_years' => '10 to 15 Years',
	'_modzzz_jobs_more_than_15_years' => 'More than 15 Years', 
	 
	'_modzzz_jobs_high_school' => 'High School',
	'_modzzz_jobs_certification' => 'Certification (Diploma)',
	'_modzzz_jobs_vocational' => 'Vocational (Diploma)',
	'_modzzz_jobs_tertiary_education' => 'Tertiary Education',
	'_modzzz_jobs_associates_degree' => 'Associates Degree',
	'_modzzz_jobs_bachelors' => 'Bachelors',
	'_modzzz_jobs_masters' => 'Masters',
	'_modzzz_jobs_doctorate' => 'Doctorate',
	'_modzzz_jobs_professional_engineering' => 'Professional-Engineering',
	 
	'_modzzz_jobs_student_college' => 'Student (College)',
	'_modzzz_jobs_student_high_school' => 'Student (High School)',
	'_modzzz_jobs_entry_level' => 'Entry Level (less than 2 years experience)',
	'_modzzz_jobs_mid_career' => 'Mid Career (2+ years of experience)',
	'_modzzz_jobs_management' => 'Management (Manager/Director of Staff)',
	'_modzzz_jobs_executive' => 'Executive (SVP, EVP, VP)',
	'_modzzz_jobs_senior_executive' => 'Senior Executive (President, CEO)',

	'_modzzz_jobs_per_year' => 'Per Year',
	'_modzzz_jobs_per_month' => 'Per Month',
	'_modzzz_jobs_per_week' => 'Per Week',
	'_modzzz_jobs_fortnightly' => 'Fortnightly',
	'_modzzz_jobs_per_hour' => 'Per Hour',
	  
   	'_modzzz_jobs_form_caption_business_type' => 'Business Type',  
 	'_modzzz_jobs_form_caption_employee_count' => 'Employee Count',  
 	'_modzzz_jobs_form_caption_office_count' => 'Office Count',  
 
	'_modzzz_jobs_caption_state' => 'State',  
	'_modzzz_jobs_block_jobs_states' => 'States',  
    '_modzzz_jobs_regions_for_country' => 'States/Regions for',  
	'_modzzz_jobs_block_browse_state' => 'Browse States', 
	'_modzzz_jobs_block_browse_state_jobs' => 'Browse Jobs by State', 
	'_modzzz_jobs_block_account' => 'Jobs in my Area',  
	'_modzzz_jobs_block_browse_country' => 'Browse by Country', 
	'_modzzz_jobs_page_title_local' => 'Browse Local Jobs',  
	'_modzzz_jobs_caption_browse_local' => 'Browse Local Jobs in {0}', 
	'_modzzz_jobs_menu_local' => 'Local Jobs', 
 	'_modzzz_jobs_block_local' => 'More Local Jobs',
	'_modzzz_jobs_block_other' => 'Other Jobs by this Company',
 	'_modzzz_jobs_caption_browse_other' => 'Other Jobs by {0}',	
 	'_modzzz_jobs_block_local_jobs' => 'Local Jobs',
	'_modzzz_jobs_block_jobs' => 'Jobs',
 	'_modzzz_jobs_block_stats' => 'Statistics',

	'_modzzz_jobs_block_jobs_categories' => 'Categories', 
    '_modzzz_jobs_block_category_jobs' => 'Jobs in this Category',
    '_modzzz_jobs_block_subcategories' => 'Sub-Categories',  
    '_modzzz_jobs_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button', 
	'_modzzz_jobs_categ_name' => 'Category',
	'_modzzz_jobs_categ_btn_edit' => 'Edit',
	'_modzzz_jobs_categ_btn_delete' => 'Delete',
	'_modzzz_jobs_categ_btn_add' => 'Add',
	'_modzzz_jobs_categ_btn_save' => 'Save',
	'_modzzz_jobs_categ_btn_subcategories' => 'Sub-Categories', 
 	'_modzzz_jobs_categories' => 'Categories',
 	'_modzzz_jobs_menu_admin_manage_categories' => 'Categories',
  	'_modzzz_jobs_menu_admin_manage_subcategories' => 'Sub-Cats',
  	'_modzzz_jobs_subcategories' => 'Sub-Categories',
  	'_modzzz_jobs_categories' => 'Categories',
    '_modzzz_jobs_form_caption_parent_category' => 'Category',
    '_modzzz_jobs_all_categories' => 'All Categories',
    '_modzzz_jobs_block_categories' => 'Categories',
    '_modzzz_jobs_block_jobs_subcategories' => 'Sub-Categories',
    '_modzzz_jobs_block_answer_categories' => 'Jobs Categories',
    '_modzzz_jobs_menu_categories' => 'Categories',
    '_modzzz_jobs_page_title_browse_by_category' => 'Browse Jobs By Category: ',
    '_modzzz_jobs_form_caption_category' => 'Category',
    '_modzzz_jobs_form_err_category' => 'Category is invalid', 
	'_modzzz_jobs_page_title_category' => 'Category', 
    '_modzzz_jobs_page_title_categories' => 'Jobs Categories',
    '_modzzz_jobs_page_title_subcategories' => 'Jobs Sub-Categories', 
    '_modzzz_jobs_jobs_in_category' => '<b>Jobs</b> in <b>%s</b>',  
 
    '_modzzz_jobs_posted_on' => 'Posted on', 
    '_modzzz_jobs_listed_by' => 'Listed by', 
    '_modzzz_jobs_company' => 'Company', 
  
    '_modzzz_jobs_company_page_title_browse_featured' => 'Featured Companies', 
    '_modzzz_jobs_posted' => 'Posted', 
    '_modzzz_jobs_jobs_posted' => 'Jobs posted', 

    '_modzzz_jobs_block_today_job' => 'Job for the Day', 
    '_modzzz_jobs_block_featured_jobs' => 'Featured Available Jobs', 
    '_modzzz_jobs_block_featured_wanted_jobs' => 'Featured Wanted Jobs', 
    '_modzzz_jobs_block_featured_companies' => 'Featured Companies', 
 
    '_modzzz_jobs_menu_companies' => 'Companies', 
    '_modzzz_jobs_present_icon' => 'Present Icon', 
    '_modzzz_jobs_form_header_company_edit' => 'Edit Company Details', 


    '_modzzz_jobs_form_header_select_company' => 'Select Company (Select from existing or choose to add a new one)', 
    '_modzzz_jobs_form_header_company' => 'New Company Details',
    '_modzzz_jobs_form_icon' => 'Icon', 
    '_modzzz_jobs_select_company' => '-- select company ---',
    '_modzzz_jobs_select_no_company' => '-- no company added yet ---',
    '_modzzz_jobs_form_caption_address' => 'Address',
    '_modzzz_jobs_form_caption_company' => 'Company', 
    '_modzzz_jobs_form_caption_website' => 'Website Link',
    '_modzzz_jobs_form_info_company' => 'Company advertising the Job',
    '_modzzz_jobs_caption_country' => 'Country',
    '_modzzz_jobs_caption_state' => 'State',
    '_modzzz_jobs_caption_name'=> 'Name',
    '_modzzz_jobs_form_caption_email'=> 'Email',
    '_modzzz_jobs_form_caption_telephone'=> 'Telephone', 
    '_modzzz_jobs_form_caption_fax'=> 'Fax', 
    '_modzzz_jobs_form_caption_name'=> 'Name',

    '_sbs_txt_title_modzzz_jobs' => 'Jobs',
    '_modzzz_jobs' => 'Jobs',
    '_modzzz_jobs_fans' => 'fans',
    '_modzzz_jobs_add' => 'add',
    '_modzzz_jobs_wall_added_new' => 'added new',
    '_modzzz_jobs_wall_object' => 'job',
    '_modzzz_jobs_for_job' => 'for %s',
    '_modzzz_jobs_job_single' => 'job',
    '_modzzz_jobs_job_plural' => 'jobs',
    '_modzzz_jobs_user_unknown' => 'Someone',

    '_modzzz_jobs_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new job <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_jobs_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed job <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_jobs_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated job <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_jobs_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented job <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_jobs_sbs_change' => 'information was updated',
    '_modzzz_jobs_sbs_comment' => 'new comment arrived',
    '_modzzz_jobs_sbs_rate' => 'rating was updated',
    '_modzzz_jobs_sbs_join' => 'new fan',

    '_modzzz_jobs_tab_featured' => 'Featured',
    '_modzzz_jobs_tab_recent' => 'Recent',
    '_modzzz_jobs_tab_top' => 'Top',
    '_modzzz_jobs_tab_popular' => 'Popular',

    '_modzzz_jobs_block_submenu_main' => 'Main',
    '_modzzz_jobs_block_submenu_add_job' => 'Add',
    '_modzzz_jobs_block_submenu_manage_jobs' => 'Manage',
    '_modzzz_jobs_block_submenu_pending_jobs' => 'Pending Approval',

    '_modzzz_jobs_block_actions' => 'Actions',
    '_modzzz_jobs_block_rate' => 'Rate',    
    '_modzzz_jobs_block_info' => 'Info',
    '_modzzz_jobs_block_desc' => 'Description',
    '_modzzz_jobs_block_photo' => 'Photos',
    '_modzzz_jobs_block_video' => 'Videos',
    '_modzzz_jobs_block_sound' => 'Sounds',
    '_modzzz_jobs_block_files' => 'Files',
    '_modzzz_jobs_block_file' => 'Files',
    '_modzzz_jobs_block_comments' => 'Comments',
    '_modzzz_jobs_block_latest_featured_job' => 'Latest Featured Job',
    '_modzzz_jobs_block_recent' => 'Recent Public Jobs (Offers)',
    '_modzzz_jobs_block_administration_owner' => 'Administration',
    '_modzzz_jobs_block_users_jobs' => 'User\'s Jobs',
    '_modzzz_jobs_block_my_jobs' => 'Jobs I posted',
    '_modzzz_jobs_block_search_jobs' => 'Search Jobs', 
    '_modzzz_jobs_block_homepage' => 'Jobs',
    '_modzzz_jobs_block_location' => 'Location',

    '_modzzz_jobs_caption_add' => 'Add Job',
    '_modzzz_jobs_caption_share_job' => 'Share Job',
    '_modzzz_jobs_caption_share_company' => 'Share Company', 
    '_modzzz_jobs_caption_admin_actions' => 'Links',
    '_modzzz_jobs_caption_pending_approval' => 'Pending Approval Jobs', 

    '_modzzz_jobs_menu_root' => 'Jobs',
    '_modzzz_jobs_menu_main' => 'Jobs Home',
    '_modzzz_jobs_menu_recent' => 'Recent',
    '_modzzz_jobs_menu_top_rated' => 'Top Rated',
    '_modzzz_jobs_menu_popular' => 'Popular',
    '_modzzz_jobs_menu_featured' => 'Featured',
    '_modzzz_jobs_menu_wanted' => 'Wanted', 
    '_modzzz_jobs_menu_tags' => 'Tags',
    '_modzzz_jobs_menu_categories' => 'Categories',
    '_modzzz_jobs_menu_calendar' => 'Calendar',
    '_modzzz_jobs_menu_search' => 'Search',
    '_modzzz_jobs_menu_view_job' => 'Main',
    '_modzzz_jobs_menu_view_forum' => 'Forum',
    '_modzzz_jobs_menu_view_applications' => 'View Applications', 
    '_modzzz_jobs_menu_view_comments' => 'Comments',
    '_modzzz_jobs_menu_view_photos' => 'Photos',
    '_modzzz_jobs_menu_view_videos' => 'Videos',
    '_modzzz_jobs_menu_view_sounds' => 'Sounds',
    '_modzzz_jobs_menu_view_files' => 'Files',
    '_modzzz_jobs_menu_my_jobs_profile' => 'Jobs',

    '_modzzz_jobs_menu_admin_pending_approval' => 'Pending Approval',
    '_modzzz_jobs_menu_admin_entries' => 'Admin Jobs',
    '_modzzz_jobs_menu_admin_add_entry' => 'Add Job',
    '_modzzz_jobs_menu_admin_settings' => 'Settings',
    
    '_modzzz_jobs_page_title_home' => 'Jobs Home',
    '_modzzz_jobs_page_title_calendar' => 'Jobs Calendar ',
    '_modzzz_jobs_page_title_comments' => 'Comments',
    '_modzzz_jobs_page_title_photos' => 'Photos',
    '_modzzz_jobs_page_title_videos' => 'Videos',
    '_modzzz_jobs_page_title_sounds' => 'Sounds',
    '_modzzz_jobs_page_title_files' => 'Files',
    '_modzzz_jobs_page_title_fans' => 'Job\'s Fans',
    '_modzzz_jobs_page_title_applications' => 'Job\'s Applications', 
    '_modzzz_jobs_page_title_my_jobs' => 'My Jobs',
    '_modzzz_jobs_page_title_search' => 'Jobs Search',
    '_modzzz_jobs_page_title_add' => 'Add Job', 
    '_modzzz_jobs_page_title_edit' => 'Edit Job',
    '_modzzz_jobs_page_company_title_edit' => 'Edit Company',

    '_modzzz_jobs_page_title_administration' => 'Jobs Administration',
    '_modzzz_jobs_page_title_browse' => 'Browse Jobs',
    '_modzzz_jobs_company_page_title_browse' => 'Browse Companies',
  
    '_modzzz_jobs_applicants_page_title_broadcast' => 'Send broadcast message to all applicants for this job',
	'_modzzz_jobs_applicants_msg_broadcast_message_sent' => 'Broadcast message have been sent',
    '_modzzz_jobs_applicants_msg_broadcast_no_recipients' => 'There are no applicants for this job yet',

    '_modzzz_jobs_page_title_pending_approval' => 'Pending Approval Jobs',
    '_modzzz_jobs_page_title_search_results' => 'Jobs Search Results',
    '_modzzz_jobs_page_title_browse_by_author' => '\'s jobs',
    '_modzzz_jobs_page_title_admin_jobs' => 'Admin Jobs',
    '_modzzz_jobs_page_title_browse_by_category' => 'Browse Jobs By Category: ',
    '_modzzz_jobs_page_title_browse_by_tag' => 'Browse Jobs By Tag: ',
    '_modzzz_jobs_page_title_browse_recent' => 'Recent Jobs',
    '_modzzz_jobs_page_title_browse_seeking' => 'Wanted Jobs', 
    '_modzzz_jobs_page_title_browse_top_rated' => 'Top Rated Jobs',
    '_modzzz_jobs_page_title_browse_popular' => 'Popular Jobs',
    '_modzzz_jobs_page_title_browse_featured' => 'Featured Jobs',
    '_modzzz_jobs_page_title_browse_featured_wanted' => 'Featured Wanted Jobs',
    '_modzzz_jobs_page_title_browse_by_day' => 'Browse Jobs By Day: ',
    '_modzzz_jobs_page_title_tags' => 'Jobs Tags',
    '_modzzz_jobs_page_title_categories' => 'Jobs Categories',
    '_modzzz_jobs_page_title_broadcast' => 'Send broadcast message to all fans for this job',
    '_modzzz_jobs_page_company_title_broadcast' => 'Send broadcast message to all fans of jobs listed by this company',
    '_modzzz_jobs_page_title_upload_photos' => 'Add Photos',
    '_modzzz_jobs_page_title_upload_videos' => 'Add Videos',
    '_modzzz_jobs_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_jobs_page_title_upload_files' => 'Add Files',
    '_modzzz_jobs_page_title_invite' => 'Send Invitation about ',
    '_modzzz_jobs_page_company_title_invite' => 'Send Invitation to friends - ', 

    '_modzzz_jobs_msg_pending_approval' => 'this job is pending approval, please wait until it will be activated',
    '_modzzz_jobs_msg_job_was_deleted' => 'Job was deleted',
    '_modzzz_jobs_company_msg_job_was_deleted' => 'Company was deleted',

    '_modzzz_jobs_msg_removed_from_featured' => 'Job was removed from featured',
    '_modzzz_jobs_msg_added_to_featured' => 'Job was added to featured',

    '_modzzz_jobs_msg_removed_from_today' => 'Item was removed as Job for the day',
    '_modzzz_jobs_msg_added_to_today' => 'Item was made Job for the day',

    '_modzzz_jobs_company_msg_removed_from_featured' => 'Company was removed from featured',
    '_modzzz_jobs_company_msg_added_to_featured' => 'Company was added to featured',
 
    '_modzzz_jobs_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_jobs_msg_you_have_pending_approval_jobs' => 'You have <a href="%s">%d pending approval jobs</a>',
    '_modzzz_jobs_msg_you_have_no_jobs' => 'You don\'t have any jobs. <a href="%s">Click here</a> to add one.',
    '_modzzz_jobs_msg_you_have_some_jobs' => 'You have <a href="%s">%d job listing(s)</a>. <a href="%s">Click here</a> to add more.',
    
	'_modzzz_jobs_msg_broadcast_message_sent' => 'Broadcast message have been sent',
    '_modzzz_jobs_msg_broadcast_no_recipients' => 'There are no fans of this job yet',
    '_modzzz_jobs_msg_invitation_sent' => '%d invitations have been sent',
    '_modzzz_jobs_msg_no_users_to_invite' => 'There are no users in your contacts', 
    '_modzzz_jobs_msg_joined_already' => 'You are already a fan of this job',
    '_modzzz_jobs_msg_join_success' => 'You have successfully become a fan of this job',
	'_modzzz_jobs_msg_leave_success' => 'You are no longer a fan of this job',

    '_modzzz_jobs_company_msg_broadcast_no_recipients' => 'There are no fans of any jobs listed by this company',
 
    '_modzzz_jobs_admin_delete' => 'Delete',
    '_modzzz_jobs_admin_activate' => 'Activate',
    '_modzzz_jobs_admin_add_new_job' => 'Add New Job',
    '_modzzz_jobs_admin_jobs' => 'Admin Jobs',
    '_modzzz_jobs_admin_settings' => 'Admin Settings',

    '_modzzz_jobs_form_header_info' => 'Job\'s Info',
    '_modzzz_jobs_form_header_images' => 'Photos',
    '_modzzz_jobs_form_header_videos' => 'Videos',
    '_modzzz_jobs_form_header_sounds' => 'Sounds',
    '_modzzz_jobs_form_header_files' => 'Files',
    '_modzzz_jobs_form_header_privacy' => 'Privacy Settings',
    '_modzzz_jobs_form_caption_title' => 'Title',
    '_modzzz_jobs_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_jobs_form_caption_desc' => 'Description',
    '_modzzz_jobs_form_err_desc' => 'Please enter at least 20 characters',
    '_modzzz_jobs_form_err_tags' => 'Please enter tags',
    '_modzzz_jobs_form_caption_author_id' => 'Author',
    '_modzzz_jobs_form_info_author' => 'Author profile ID number',
    '_modzzz_jobs_form_caption_keyword' => 'Keyword',
    '_modzzz_jobs_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_modzzz_jobs_form_caption_category' => 'Category',
    '_modzzz_jobs_form_err_category' => 'Category is invalid',    
    '_modzzz_jobs_form_caption_images_choice' => 'Choose',
    '_modzzz_jobs_form_info_images_choice' => 'You can choose several images from your "Jobs" category',
    '_modzzz_jobs_form_caption_images_upload' => 'Upload',    
    '_modzzz_jobs_form_info_images_upload' => 'Image will be placed in the "Jobs" category automatically',
    '_modzzz_jobs_form_caption_videos_choice' => 'Choose',
    '_modzzz_jobs_form_info_videos_choice' => 'You can choose several videos from your "Jobs" category',
    '_modzzz_jobs_form_caption_videos_upload' => 'Upload',
    '_modzzz_jobs_form_info_videos_upload' => 'Video will be placed in the "Jobs" category automatically',
    '_modzzz_jobs_form_caption_sounds_choice' => 'Choose',
    '_modzzz_jobs_form_info_sounds_choice' => 'You can choose several sounds from your "Jobs" category',
    '_modzzz_jobs_form_caption_sounds_upload' => 'Upload',
    '_modzzz_jobs_form_info_sounds_upload' => 'Sound will be placed in the "Jobs" category automatically',
    '_modzzz_jobs_form_caption_files_choice' => 'Choose',
    '_modzzz_jobs_form_info_files_choice' => 'Unclick checkbox to remove file from this job',
    '_modzzz_jobs_form_caption_files_upload' => 'Upload',
    '_modzzz_jobs_form_info_files_upload' => 'File will be placed in the "Jobs" category and set as private automatically',
    '_modzzz_jobs_form_caption_file_title' => 'Title:',
    '_modzzz_jobs_form_caption_file_price' => 'Price:',
    '_modzzz_jobs_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_jobs_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_jobs_form_info_thumb_choice' => 'You can choose any image from your "Jobs" category as job thumbnail',
    '_modzzz_jobs_form_caption_broadcast_title' => 'Broadcast message title',
    '_modzzz_jobs_form_err_broadcast_title' => 'Please enter from 3 to 100 characters', 
    '_modzzz_jobs_form_caption_broadcast_message' => 'Broadcast message',
    '_modzzz_jobs_form_err_broadcast_message' => 'Please enter at least 10 characters',
    '_modzzz_jobs_form_caption_country' => 'Country',
    '_modzzz_jobs_form_err_country' => 'Country is a required field',
    '_modzzz_jobs_form_caption_city' => 'City',
    '_modzzz_jobs_form_err_city' => 'Please enter from 2 to 50 characters',
    '_modzzz_jobs_form_caption_zip' => 'Zip/Postal Code',
    '_modzzz_jobs_form_err_zip' => 'Zip/Postal code is required',

    '_modzzz_jobs_action_title_edit' => 'Edit',
    '_modzzz_jobs_action_title_delete' => 'Delete',
    '_modzzz_jobs_action_title_share' => 'Share',
    '_modzzz_jobs_action_title_broadcast' => 'Mail Fans',
    '_modzzz_jobs_action_title_broadcast_applicants' => 'Mail Applicants', 
    '_modzzz_jobs_action_title_leave' => 'Leave',
    '_modzzz_jobs_action_title_invite' => 'Invite',
    '_modzzz_jobs_action_add_to_featured' => 'Feature',    
    '_modzzz_jobs_action_remove_from_featured' => 'Unfeature', 
    '_modzzz_jobs_action_add_to_today' => 'Feature Today',    
    '_modzzz_jobs_action_remove_from_today' => 'Unfeature Today', 
    '_modzzz_jobs_action_add_job' => 'Add Job',
    '_modzzz_jobs_action_my_jobs' => 'My Jobs',
    '_modzzz_jobs_action_upload_photos' => 'Add Photos',
    '_modzzz_jobs_action_upload_videos' => 'Add Videos',
    '_modzzz_jobs_action_upload_sounds' => 'Add Sounds',
    '_modzzz_jobs_action_upload_files' => 'Add Files',
    '_modzzz_jobs_action_jobs_home' => 'Jobs Home',
    '_modzzz_jobs_privacy_view_fans' => 'View Fans', 
    '_modzzz_jobs_privacy_view_job' => 'View Job',
    '_modzzz_jobs_privacy_comment' => 'Comment',
    '_modzzz_jobs_privacy_rate' => 'Rate',
    '_modzzz_jobs_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_jobs_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_jobs_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_jobs_privacy_upload_files' => 'Upload Files',
    '_modzzz_jobs_privacy_edit_job' => 'Edit Job',
    '_modzzz_jobs_privacy_post_in_forum' => 'Post In Forum',
    '_modzzz_jobs_privacy_admins_only' => 'Admins Only',
 
    '_mma_jobs_files_add' => 'jobs files add',  
    '_mma_jobs_photos_add' => 'jobs photos add',  
    '_mma_jobs_videos_add' => 'jobs videos add',  
    '_mma_jobs_sounds_add' => 'jobs sounds add',  
    '_mma_jobs_apply' => 'jobs apply',  
	'_mma_jobs_view_job' => 'jobs view job', 
    '_mma_jobs_browse' => 'jobs browse', 
    '_mma_jobs_search' => 'jobs search', 
    '_mma_jobs_add_job' => 'jobs add job', 
    '_mma_jobs_comments_delete_and_edit' => 'jobs comments delete and edit', 
    '_mma_jobs_edit_any_job' => 'jobs edit any job', 
    '_mma_jobs_delete_any_job' => 'jobs delete any job', 
    '_mma_jobs_mark_as_featured' => 'jobs mark as featured', 
    '_mma_jobs_approve_jobs' => 'jobs approve jobs', 
    '_mma_jobs_broadcast_message' => 'jobs broadcast message',

    '_modzzz_jobs_packages_empty' => 'There are no Job Packages', 
    '_modzzz_jobs_package_description' => 'Description', 
    '_modzzz_jobs_package_featured' => 'Featured', 

    '_modzzz_jobs_featured_status' => 'Featured Status', 
    '_modzzz_jobs_featured_until' => 'Featured until', 
    '_modzzz_jobs_not_featured' => 'Not Featured', 
 	'_modzzz_jobs_extend_featured' => 'Extend Featured Status',  
	'_modzzz_jobs_purchase_featured' => 'Purchase Featured Status', 
	'_modzzz_jobs_form_caption_currency' => 'Currency',  

    '_modzzz_jobs_menu_packages' => 'Packages', 
    '_modzzz_jobs_page_title_packages' => 'Job Packages', 
    '_modzzz_jobs_block_packages' => 'Job Packages', 

	'_modzzz_jobs_caption_membership_view_filter' => 'Allow viewing by membership',
	'_modzzz_jobs_err_membership_view_filter' => 'incorrect value', 
    '_modzzz_jobs_info_membership_view_filter' => 'only these members will be able to view this Job listing',
    '_modzzz_jobs_membership_filter_none' => 'Allow All',	
  
    '_modzzz_jobs_on' => 'on',  
    '_modzzz_jobs_yes' => 'yes',  
    '_modzzz_jobs_no' => 'no', 

	'_modzzz_jobs_categ_btn_edit' => 'Edit',
	'_modzzz_jobs_categ_btn_delete' => 'Delete',
	'_modzzz_jobs_categ_btn_add' => 'Add',
	'_modzzz_jobs_categ_btn_save' => 'Save',
 
	'_modzzz_jobs_package_videos' => 'Videos',  	
	'_modzzz_jobs_package_photos' => 'Photos',  	
	'_modzzz_jobs_package_sounds' => 'Sounds',  	
	'_modzzz_jobs_package_files' => 'Files', 
   
    '_mma_jobs_purchase_featured' => 'jobs purchase featured',  
	'_modzzz_jobs_action_title_purchase_featured' => 'Get Featured',
	'_modzzz_jobs_action_title_extend_featured' => 'Extend Featured',  
	'_modzzz_jobs_purchase_featured_status' => 'Purchase Featured Status',  
	'_modzzz_jobs_quantity' => 'Quantity',   
	'_modzzz_jobs_purchase_success' => 'You successfully Purchased {0} Days of Featured Status', 
	'_modzzz_jobs_purchase_fail' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_jobs_transaction_completed_already' => 'This transaction was already completed',  
	'_modzzz_jobs_featured_cost_per_day' => 'Cost per Day',  
	'_modzzz_jobs_caption_num_featured_days' => 'Number of Featured Days',    
	'_modzzz_jobs_caption_err_featured_days' => 'You must enter Number of Featured Days',    
	'_modzzz_jobs_get_featured' => 'Get Featured',  

	'_modzzz_jobs_packages' => 'Packages',
	'_modzzz_jobs_package_name' => 'Package Name',
	'_modzzz_jobs_package_price' => 'Package Price',
	'_modzzz_jobs_package_days' => 'Package Days',
	'_modzzz_jobs_form_caption_package' => 'Payment Package',
	'_modzzz_jobs_form_err_package' => 'Please select a Package',  
	'_modzzz_jobs_purchaser' => 'Purchaser', 
	'_modzzz_jobs_invoice_no' => 'Invoice #', 
	'_modzzz_jobs_package' => 'Package', 
	'_modzzz_jobs_invoice_date' => 'Invoice Date', 
	'_modzzz_jobs_invoice_due_date' => 'Due Date', 
	'_modzzz_jobs_status' => 'Status',
	'_modzzz_jobs_pending' => 'Pending',
	'_modzzz_jobs_paid' => 'Paid',
	'_modzzz_jobs_active' => 'Active',
	'_modzzz_jobs_inactive' => 'Inactive',
	'_modzzz_jobs_approved' => 'Approved',
	'_modzzz_jobs_expired' => 'Expired', 
	'_modzzz_jobs_block_submenu_pending_invoices' => 'Pending Invoices',
	'_modzzz_jobs_block_submenu_orders' => 'Orders',
	'_modzzz_jobs_page_title_orders' => 'Orders', 
	'_modzzz_jobs_page_title_invoices' => 'Invoices', 
	'_modzzz_jobs_menu_manage_invoices' => 'Invoices', 
	'_modzzz_jobs_menu_manage_packages' => 'Packages',
	'_modzzz_jobs_menu_manage_orders' => 'Orders',
	'_modzzz_jobs_payment_method' => 'Payment Method',
	'_modzzz_jobs_total' => 'Total',
	'_modzzz_jobs_invoice_id' => 'Invoice ID',
	'_modzzz_jobs_next_due_date' => 'Next Due Date',
	'_modzzz_jobs_order_no' => 'Order #',
	'_modzzz_jobs_product_status' => 'Product Status',
	'_modzzz_jobs_order_date' => 'Order Date',
	'_modzzz_jobs_purchase_failed' => 'Sorry, there was a problem with the Payment.  View your Pending Orders <a href="{0}">here</a>.',
	'_modzzz_jobs_transaction_completed_already' => 'The Transaction exists already. Click <a href="{0}">here</a> to view the Job listing.',
	'_modzzz_jobs_purchase_success' => 'Thank you. The Payment was successful. Click <a href="{0}">here</a> to view the Job listing.',  
	'_modzzz_jobs_trans_save_failed' => 'The Payment was successful but there was a problem saving the transaction. Please contact the administrator with your Paypal transaction details so they can manually process your Order.',
	'_modzzz_jobs_post_purchase_header' => 'Job Listing Purchase',  
 
    '_modzzz_jobs_block_map' => 'Map',
 
    '_modzzz_jobs_week_sun' => 'Sun',
    '_modzzz_jobs_week_mon' => 'Mon',
    '_modzzz_jobs_week_tue' => 'Tue',
    '_modzzz_jobs_week_wed' => 'Wed',
    '_modzzz_jobs_week_thu' => 'Thur', 
    '_modzzz_jobs_week_fri' => 'Fri',
    '_modzzz_jobs_week_sat' => 'Sat',
     
	'_modzzz_jobs_continue' => 'Continue',

	'_modzzz_jobs_action_title_premium' => 'Get Premium',  
    '_modzzz_jobs_page_title_premium' => 'Get Premium Listing',   
	'_mma_jobs_purchase' => 'jobs purchase package', 
 
    '_modzzz_jobs_action_title_extend' => 'Extend',  
    '_modzzz_jobs_page_title_extend' => 'Extend Job listing',   
	'_mma_jobs_extend' => 'jobs extend', 

    '_modzzz_jobs_action_title_relist' => 'Re-list',  
    '_modzzz_jobs_page_title_relist' => 'Re-list Job listing',  
	'_mma_jobs_relist' => 'jobs relist', 

    '_modzzz_jobs_form_caption_current_no_package' => 'No Package currently',   
    '_modzzz_jobs_form_caption_current_package' => 'Current Package',  
    '_modzzz_jobs_form_caption_package_price' => 'Package Price',  
    '_modzzz_jobs_form_caption_package_days' => 'Length of Listing',   
 	'_modzzz_jobs_expires_never' => 'unlimited (never expires)', 
 	'_modzzz_jobs_days' => 'days', 
 	'_modzzz_jobs_form_caption_current_item' => 'Job Listing', 
    '_modzzz_jobs_extend' => 'Extend',  
    '_modzzz_jobs_block_statistics' => 'Statistics',  
    '_modzzz_jobs_block_price' => 'Price',  
    '_modzzz_jobs_block_share' => 'Share', 
    '_modzzz_jobs_block_facebook_comments' => 'Facebook Comments', 
    
	'_modzzz_jobs_miles' => 'miles', 
    '_modzzz_jobs_kilometers' => 'Km', 
	'_modzzz_jobs_map_search_explanation' => 'Enter the City and Country (eg. miramer or miramer,US)', 

    '_modzzz_jobs_enter_your_jobs' => 'Enter your Listing',
    '_modzzz_jobs_block_jobs_create' => 'Post your Job', 
    '_modzzz_jobs_block_latest_comments' => 'Latest Comments',
    '_modzzz_jobs_block_forum' => 'Latest Forum Posts',
    '_modzzz_jobs_posted_by' => 'Posted by',
    '_modzzz_jobs_continue' => 'Continue',  
    '_modzzz_jobs_block_search' => 'Job Search',  

    '_modzzz_jobs_form_caption_select_resume' => 'Select Resume', 
    '_modzzz_jobs_form_info_select_resume' => 'you can select from your list of existing resume', 
    '_modzzz_jobs_resume_view_online' => 'View Online Resume',
 
	'_modzzz_jobs_allow_num_listings' => 'Number of Listings allowed', 	
	'_modzzz_jobs_allow_videos' => 'Allow Videos', 	
	'_modzzz_jobs_allow_photos' => 'Allow Photos', 	
	'_modzzz_jobs_allow_sounds' => 'Allow Sounds', 	
	'_modzzz_jobs_allow_files' => 'Allow Files', 
 	'_modzzz_jobs_featured' => 'Featured', 	
 	'_modzzz_jobs_package_desc' => 'Package Description',  
    '_modzzz_jobs_block_submenu_expired_jobs' => 'Expired',
    '_modzzz_jobs_page_title_expired' => 'Expired Listings', 
 	'_modzzz_jobs_expires' => 'Expires', 	 
 	'_modzzz_jobs_never' => 'Never',  
 	'_modzzz_jobs_featured_listing' => 'Featured Listing (never expires)',  

	'_modzzz_jobs_block_browse_categories_drilldown' => 'Categories Drilldown', 
	'_modzzz_jobs_category_drilldown_for_item' => 'Categories Drilldown for <b>{0}</b>', 
 
 	'_modzzz_jobs_paypal_item_desc' => 'Payment for Job Listing - {0}',  
 	'_modzzz_jobs_paypal_featured_item_desc' => 'Purchase Featured Status - {0}',  
    
	'_modzzz_jobs_page_title_embed_video' => 'Embed Video for Job',
    '_modzzz_jobs_action_embed_video' => 'Embed Video',

    '_modzzz_jobs_caption_search' => 'Search for Jobs',

    '_modzzz_jobs_location' => 'Location', 
    '_modzzz_jobs_read_cover_letter' => 'Read Cover Letter', 
    '_modzzz_jobs_cover_letter' => 'Cover Letter', 

	/*added 7.1 */
    '_modzzz_jobs_wall_added_new_comment' => 'commented on a',
    '_modzzz_jobs_wall_added_new_items' => 'added {0} new job listing(s)',
	'_modzzz_jobs_single' => 'Job Listing',
    '_modzzz_jobs_posted_in_topic' => 'Posted in Forum',
    '_modzzz_jobs_posted_in_jobs' => 'Posted in Job Listing', 
    '_modzzz_jobs_adm_stats' => 'Pending Jobs', 
	'_sys_module_jobs' => 'Jobs', 
    '_modzzz_jobs_block_calendar' => 'Calendar', 
    '_modzzz_jobs_apply_attach_message' => 'Attached is a copy of their resume.', 

    '_modzzz_jobs_download_resume_online_at' => 'Download a copy of their Resume <a href="{0}">here</a>', 
    '_modzzz_jobs_view_resume_online_at' => 'View their Resume online at ', 
	'_modzzz_jobs_browse_jobs_in_country' => 'Postings in {0}', 

	'_mma_jobs_mark_as_today' => 'jobs mark as today', 

	'_modzzz_jobs_caption_browse_company_jobs' => 'Browse job openings for Company - {0}', 
    '_modzzz_jobs_block_company_jobs' => 'Job Openings', 
    '_modzzz_jobs_block_location' => 'Location', 
    '_modzzz_jobs_block_contact' => 'Contact Information', 

    '_modzzz_jobs_form_caption_application_link' => 'Application Link', 
    '_modzzz_jobs_form_info_application_link' => 'This is a URL where members can submit their application', 

    '_modzzz_jobs_form_caption_sub_category' => 'Sub-Category', 

    '_modzzz_jobs_page_title_feature_item' => 'Feature this Listing',
    '_modzzz_jobs_feature_listing_desc' => 'Cost for featuring a Listing',

    '_modzzz_jobs_buy_link' => '<a href="{0}">Buy more here</a>',
	'_modzzz_jobs_form_caption_cost_to_view' => 'Cost to View',
	'_modzzz_jobs_form_caption_cost_to_post' => 'Cost to Post',
	'_modzzz_jobs_form_caption_cost_to_feature' => 'Cost to Feature',
	'_modzzz_jobs_form_caption_credits_balance' => 'Credits Balance',
	'_modzzz_jobs_form_caption_points_balance' => 'Points Balance',
	'_modzzz_jobs_credits' => 'Credits',
	'_modzzz_jobs_points' => 'Points',
	'_modzzz_jobs_msg_feature_success' => 'Listing was successfully featured',
	'_modzzz_jobs_msg_feature_failure' => 'Failed to feature listing',
	'_modzzz_jobs_form_caption_feature' => 'Make this Featured',
	'_modzzz_jobs_form_caption_submit' => 'Go Ahead',
    '_mma_jobs_allow_embed' => 'jobs allow video embed', 
	'_modzzz_jobs_form_per_day' => 'per day',
	'_modzzz_jobs_caption_num_post_days' => 'Number of days for post',
	'_modzzz_jobs_form_caption_post' => 'Post a Job listing for a period specified below',
	'_modzzz_jobs_form_caption_view' => 'Pay to view this Job listing',

    '_modzzz_jobs_msg_insufficient_credits_view' => 'Your Credits balance is {0}. You need {1} Credits to view listings.',
    '_modzzz_jobs_msg_insufficient_points_view' => 'Your Points balance is {0}. You need {1} Points to view listings.',

    '_modzzz_jobs_msg_insufficient_credits_post' => 'Your Credits balance is {0}. You need {1} Credits to post listings.',
    '_modzzz_jobs_msg_insufficient_points_post' => 'Your Points balance is {0}. You need {1} Points to post listings.',

    '_modzzz_jobs_msg_insufficient_credits_feature' => 'Your Credits balance is {0}. You need {1} Credits to feature listings.',
    '_modzzz_jobs_msg_insufficient_points_feature' => 'Your Points balance is {0}. You need {1} Points to feature listings.',
	'_modzzz_jobs_featured_jobs' => 'This listing is featured',

	'_modzzz_jobs_block_map_view' => 'Map View',
    '_mma_jobs_allow_embed' => 'jobs allow video embed', 
   	'_modzzz_jobs_block_video_embed' => 'Youtube Videos',
	'_modzzz_jobs_form_caption_youtube_link' => 'Video URL', 
	'_modzzz_jobs_form_caption_youtube_caption' => 'Video Title',  
	'_modzzz_jobs_form_header_youtube' => 'Youtube Videos',
	'_modzzz_jobs_form_caption_youtube_attach' => 'Video',
	'_modzzz_jobs_form_info_youtube_attach' => 'you can add multiple Youtube Videos',
	'_modzzz_jobs_form_caption_youtube_choice' => 'Existing Videos',  
	'_modzzz_jobs_form_info_youtube_choice' => 'Uncheck Videos that you want to remove', 
    '_modzzz_jobs_page_title_embed_video' => 'Embed Video',
    '_modzzz_jobs_action_embed_video' => 'Embed Video',

    '_modzzz_jobs_block_logo' => 'Logo', 
    '_modzzz_jobs_form_header_logo' => 'Logo', 
    '_modzzz_jobs_present_icon' => 'Present Icon', 
    '_modzzz_jobs_form_caption_icon' => 'Icon', 
    '_modzzz_jobs_remove' => 'Remove', 

	'_wall_reposted_modzzz_jobs_add' => 'reposted a job listing', 

 );
