<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Listing
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Business Directory';

$aLangContent = array(
 

    '_modzzz_listing_employees' => 'employees',
    '_modzzz_listing_sbs_work' => 'new employee',
    '_modzzz_listing_block_employees' => 'Employees',
    '_modzzz_listing_block_employees_unconfirmed' => 'Unconfirmed Employees',
	'_modzzz_listing_block_my_listings_worked' => 'I am Employed here',
    '_modzzz_listing_caption_manage_employees' => 'Manage Employees',
    '_modzzz_listing_menu_view_employees' => 'Employees',
    '_modzzz_listing_page_title_employees' => 'Business\'s Employees',
    '_modzzz_listing_action_manage_employees' => 'Employees',
    '_modzzz_listing_privacy_view_employees' => 'View Employees',
    '_modzzz_listing_privacy_employees_only' => 'Employees Only',
    '_modzzz_listing_privacy_employees' => 'Employees',

    '_modzzz_listing_spy_work' => '<a href="{profile_link}">{profile_nick}</a> is an employee of listing <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_listing_page_title_browse_by_author_worked_listings' => '\'s worked listings',
    '_modzzz_listing_msg_worked_already' => 'You are already an employee of this listing',
    '_modzzz_listing_msg_worked_request_pending' => 'You have already indicate that you are an employee of this listing. Please wait while your request is processed by listing admin(s).',
    '_modzzz_listing_msg_work_success' => 'You are now confirmed as an employee of this listing',
    '_modzzz_listing_msg_work_success_pending' => 'You have successfully submitted your request to be flagged as an employee of this listing. Please wait while your request is processed by listing admin(s).',
	'_modzzz_listing_msg_resign_success' => 'You are no lomger an employee of this listing',
    '_modzzz_listing_form_caption_work_confirmation' => 'Employee Confirmation',
    '_modzzz_listing_form_info_work_confirmation' => 'If enabled, listing admin(s) will have to confirm each user before he/she becomes a employee.',
    '_modzzz_listing_form_work_confirmation_disabled' => 'Disabled',
    '_modzzz_listing_form_work_confirmation_enabled' => 'Enabled',
    '_modzzz_listing_form_err_work_confirmation' => 'Employee confirmation field must be 0 or 1',
    '_modzzz_listing_action_title_work' => 'I am Employee',
    '_modzzz_listing_action_title_work_admin' => 'Add Employee',
    '_modzzz_listing_action_title_resign' => 'Remove Employee',
    '_modzzz_listing_privacy_work' => 'Become Employee',





    '_modzzz_listing_fans' => 'fans',
    '_modzzz_listing_sbs_join' => 'new fan',
    '_modzzz_listing_block_fans' => 'Fans',
    '_modzzz_listing_block_fans_unconfirmed' => 'Unconfirmed Fans',
	'_modzzz_listing_block_my_listings_joined' => 'Joined Businesses',
    '_modzzz_listing_caption_manage_fans' => 'Manage Fans',
    '_modzzz_listing_menu_view_fans' => 'Fans',
    '_modzzz_listing_page_title_fans' => 'Business\'s Fans',
    '_modzzz_listing_action_manage_fans' => 'Manage Fans',
    '_modzzz_listing_privacy_view_fans' => 'View Fans',
    '_modzzz_listing_privacy_fans_only' => 'Fans Only',
    '_modzzz_listing_privacy_fans' => 'Fans',

    '_modzzz_listing_spy_join' => '<a href="{profile_link}">{profile_nick}</a> joined listing <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_listing_page_title_browse_by_author_joined_listings' => '\'s joined listings',
    '_modzzz_listing_msg_joined_already' => 'You have already joined this listing',
    '_modzzz_listing_msg_joined_request_pending' => 'You have already joined this listing. Please wait while your request is processed by listing admin(s).',
    '_modzzz_listing_msg_join_success' => 'You have successfully joined this listing',
    '_modzzz_listing_msg_join_success_pending' => 'You have successfully joined this listing. Please wait while your request is processed by listing admin(s).',
	'_modzzz_listing_msg_leave_success' => 'You have successfully left this listing',
    '_modzzz_listing_form_caption_join_confirmation' => 'Join Confirmation',
    '_modzzz_listing_form_info_join_confirmation' => 'If enabled, listing admin(s) will have to confirm each user before he/she becomes a fan.',
    '_modzzz_listing_form_join_confirmation_disabled' => 'Disabled',
    '_modzzz_listing_form_join_confirmation_enabled' => 'Enabled',
    '_modzzz_listing_form_err_join_confirmation' => 'Join confirmation field must be 0 or 1',
    '_modzzz_listing_action_title_join' => 'Become Fan',
    '_modzzz_listing_action_title_leave' => 'Remove Fan',
    '_modzzz_listing_privacy_join' => 'Become Fan',
 
    '_modzzz_listing_packages_empty' => 'There are no Business Packages', 
    '_modzzz_listing_package_description' => 'Description', 
    '_modzzz_listing_package_featured' => 'Featured', 

    '_modzzz_listing_featured_status' => 'Featured Status', 
    '_modzzz_listing_featured_until' => 'Featured until', 
    '_modzzz_listing_not_featured' => 'Not Featured', 
 	'_modzzz_listing_extend_featured' => 'Extend Featured Status',  
	'_modzzz_listing_purchase_featured' => 'Purchase Featured Status', 
	'_modzzz_listing_form_caption_currency' => 'Currency',  

    '_modzzz_listing_menu_packages' => 'Packages', 
    '_modzzz_listing_page_title_packages' => 'Business Packages', 
    '_modzzz_listing_block_packages' => 'Business Packages', 

    '_modzzz_listing_menu_view_forum' => 'Forum', 
    '_modzzz_listing_privacy_post_in_forum' => 'Post In Forum',
  
	'_modzzz_listing_caption_membership_view_filter' => 'Allow viewing by membership',
	'_modzzz_listing_err_membership_view_filter' => 'incorrect value', 
    '_modzzz_listing_info_membership_view_filter' => 'only these members will be able to view this business listing',
    '_modzzz_listing_membership_filter_none' => 'Allow All',	

    '_mma_listing_files_add' => 'listing files add',  
    '_mma_listing_photos_add' => 'listing photos add',  
    '_mma_listing_videos_add' => 'listing videos add',  
    '_mma_listing_sounds_add' => 'listing sounds add',  
	
    '_modzzz_listing_continue' => 'Continue',  
    '_modzzz_listing_admin_assign' => 'Assign to Claimant',  
    '_modzzz_listing_menu_manage_claims' => 'Claims',  
    '_modzzz_listing_claimed_by' => 'Claimed by',  
    '_modzzz_listing_on' => 'on',  
    '_modzzz_listing_yes' => 'Yes',  
    '_modzzz_listing_no' => 'No',  
 
	'_modzzz_listing_package_videos' => 'Videos',  	
	'_modzzz_listing_package_photos' => 'Photos',  	
	'_modzzz_listing_package_sounds' => 'Sounds',  	
	'_modzzz_listing_package_files' => 'Files', 

	'_modzzz_listing_block_listing_states' => 'States', 
 
    '_mma_listing_purchase_featured' => 'listing purchase featured', 
    '_mma_listing_make_claim' => 'listing make claim', 
 
	'_modzzz_listing_block_browse_categories_drilldown' => 'Categories Drilldown', 
	'_modzzz_listing_category_drilldown_for_item' => 'Categories Drilldown for <b>{0}</b>', 

    '_modzzz_listing_regions_for_country' => 'States/Regions for',  
	'_modzzz_listing_block_browse_state' => 'Browse States', 
	'_modzzz_listing_block_browse_state_listings' => 'Browse Businesses by State', 
	'_modzzz_listing_block_account' => 'Businesses in my Area',  
	'_modzzz_listing_block_browse_country' => 'Browse by Country', 
	'_modzzz_listing_page_title_local' => 'Browse Local Businesses',  
	'_modzzz_listing_caption_browse_local' => 'Browse Local Businesses in {0}', 
	'_modzzz_listing_menu_local' => 'Local', 
 	'_modzzz_listing_block_local' => 'More Local Businesses',
	'_modzzz_listing_block_other' => 'Other Businesses by this member',
 	'_modzzz_listing_caption_browse_other' => 'Other Businesses by {0}',


	'_modzzz_listing_action_title_purchase_featured' => 'Get Featured',
	'_modzzz_listing_action_title_extend_featured' => 'Extend Featured',  
	'_modzzz_listing_purchase_featured_status' => 'Purchase Featured Status',  
	'_modzzz_listing_quantity' => 'Quantity',   
	'_modzzz_listing_purchase_success' => 'You successfully Purchased {0} Days of Featured Status', 
	'_modzzz_listing_purchase_fail' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_listing_purchase_failed' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_listing_transaction_completed_already' => 'This transaction was already completed',  
	'_modzzz_listing_featured_cost_per_day' => 'Cost per Day',  
	'_modzzz_listing_caption_num_featured_days' => 'Number of Featured Days',    
	'_modzzz_listing_caption_err_featured_days' => 'You must enter Number of Featured Days',    
	'_modzzz_listing_get_featured' => 'Get Featured',  
 

    '_modzzz_listing_parent_categories' => 'Parent', 
    '_modzzz_listing_block_category_listing' => 'Businesses in this Category',
    '_modzzz_listing_block_subcategories' => 'Sub-Categories',  
    '_modzzz_listing_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button', 
	'_modzzz_listing_categ_name' => 'Category',
	'_modzzz_listing_categ_btn_edit' => 'Edit',
	'_modzzz_listing_categ_btn_delete' => 'Delete',
	'_modzzz_listing_categ_btn_add' => 'Add',
	'_modzzz_listing_categ_btn_save' => 'Save',
	'_modzzz_listing_categ_btn_subcategories' => 'Sub-Categories', 
 	'_modzzz_listing_categories' => 'Categories',
 	'_modzzz_listing_menu_admin_manage_categories' => 'Categories',
  	'_modzzz_listing_menu_admin_manage_subcategories' => 'Sub-Cats',
  	'_modzzz_listing_subcategories' => 'Sub-Categories',
    '_modzzz_listing_all_categories' => 'All Categories',
    '_modzzz_listing_block_categories' => 'Categories',
    '_modzzz_listing_block_listing_subcategories' => 'Sub-Categories',
    '_modzzz_listing_block_answer_categories' => 'Business Categories',
    '_modzzz_listing_menu_categories' => 'Categories',
    '_modzzz_listing_page_title_browse_by_category' => 'Browse Businesses By Category: ',
    '_modzzz_listing_form_caption_category' => 'Category',
    '_modzzz_listing_form_err_category' => 'Category is invalid', 
	'_modzzz_listing_page_title_category' => 'Category', 
    '_modzzz_listing_page_title_categories' => 'Business Listing Categories',
    '_modzzz_listing_page_title_subcategories' => 'Business Listing Sub-Categories', 
    '_modzzz_listing_listings_in_category' => '<b>Businesses</b> in <b>%s</b>',  
    '_modzzz_listing_block_listing' => 'Businesses', 
    
	'_modzzz_listing_packages' => 'Packages',
	'_modzzz_listing_package_name' => 'Package Name',
	'_modzzz_listing_package_price' => 'Package Price',
	'_modzzz_listing_package_days' => 'Package Days',
	'_modzzz_listing_form_caption_package' => 'Business Package',
	'_modzzz_listing_form_err_package' => 'Please select a Business Package',  
	'_modzzz_listing_purchaser' => 'Purchaser', 
	'_modzzz_listing_invoice_no' => 'Invoice #', 
	'_modzzz_listing_package' => 'Package', 
	'_modzzz_listing_invoice_date' => 'Invoice Date', 
	'_modzzz_listing_invoice_due_date' => 'Due Date', 
	'_modzzz_listing_status' => 'Status',
	'_modzzz_listing_pending' => 'Pending',
	'_modzzz_listing_paid' => 'Paid',
	'_modzzz_listing_active' => 'Active',
	'_modzzz_listing_inactive' => 'Inactive',
	'_modzzz_listing_approved' => 'Approved',
	'_modzzz_listing_expired' => 'Expired', 
	'_modzzz_listing_block_submenu_pending_invoices' => 'Pending Invoices',
	'_modzzz_listing_block_submenu_orders' => 'Orders',
	'_modzzz_listing_page_title_orders' => 'Orders', 
	'_modzzz_listing_page_title_invoices' => 'Invoices', 
	'_modzzz_listing_menu_manage_invoices' => 'Invoices', 
	'_modzzz_listing_menu_manage_packages' => 'Packages',
	'_modzzz_listing_menu_manage_orders' => 'Orders',
	'_modzzz_listing_payment_method' => 'Payment Method',
	'_modzzz_listing_total' => 'Total',
	'_modzzz_listing_invoice_id' => 'Invoice ID',
	'_modzzz_listing_next_due_date' => 'Next Due Date',
	'_modzzz_listing_order_no' => 'Order #',
	 '_modzzz_listing_product_status' => 'Product Status',
	'_modzzz_listing_order_date' => 'Order Date',
	'_modzzz_listing_purchase_failed' => 'Sorry, there was a problem with the Payment.  View your Pending Orders <a href="{0}">here</a>.',
	'_modzzz_listing_transaction_completed_already' => 'The Transaction exists already. Click <a href="{0}">here</a> to view the Business.',
	'_modzzz_listing_purchase_success' => 'Thank you. The Payment was successful. Click <a href="{0}">here</a> to view the Business.',  
	'_modzzz_listing_trans_save_failed' => 'The Payment was successful but there was a Problem saving the transaction. Please contact the administrator with your Paypal transaction details so they can manually process your Order.',
	'_modzzz_listing_post_purchase_header' => 'Business Listing Purchase',  
 

	'_modzzz_listing_caption_state' => 'State',  
	'_modzzz_listing_regions_for_country' => 'States/Regions for',  
	'_modzzz_listing_block_browse_state' => 'Browse States', 
	'_modzzz_listing_block_browse_state_events' => 'Browse Businesses by State',
	'_modzzz_listing_block_browse_country' => 'Browse by Country', 
	'_modzzz_listing_page_title_local' => 'Browse Local Businesses',  
	'_modzzz_listing_caption_browse_local' => 'Browse Local Businesses in {0}', 
	'_modzzz_listing_menu_local' => 'Local',
 	'_modzzz_listing_caption_search' => 'Search Business listings',
 

    '_modzzz_listing_no_listings' => 'There are no Businesses',
    '_sbs_txt_title_modzzz_listing' => 'Businesses',
    '_modzzz_listing' => 'Business',
    '_modzzz_listing_plural' => 'Businesses',
    '_modzzz_listing_add' => 'add',
    '_modzzz_listing_wall_added_new' => 'added new',
    '_modzzz_listing_wall_object' => 'business listing',
    '_modzzz_listing_for_listing' => 'for %s',
    '_modzzz_listing_listing_single' => 'business listing',
    '_modzzz_listing_listing_plural' => 'business listings',
    '_modzzz_listing_user_unknown' => 'Someone',
    '_modzzz_listing_disabled' => 'disabled',
    '_modzzz_listing_enabled' => 'enabled',
    '_modzzz_listing_cannot_delete_default_parent' => 'Cannot Delete Default Parent Category',
	    
	 '_modzzz_listing_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new business listing <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_listing_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed business listing <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_listing_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated business listing <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_listing_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented business listing <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_listing_sbs_change' => 'information was updated',
    '_modzzz_listing_sbs_comment' => 'new comment arrived',
    '_modzzz_listing_sbs_rate' => 'rating was updated',
 
    '_modzzz_listing_tab_featured' => 'Featured',
    '_modzzz_listing_tab_recent' => 'Recent',
    '_modzzz_listing_tab_top' => 'Top',
    '_modzzz_listing_tab_popular' => 'Popular',

    '_modzzz_listing_block_submenu_main' => 'Main',
    '_modzzz_listing_block_submenu_add_listing' => 'Add',
    '_modzzz_listing_block_submenu_manage_listing' => 'Manage',
    '_modzzz_listing_block_submenu_pending_listing' => 'Pending Approval',

    '_modzzz_listing_block_actions' => 'Actions',
    '_modzzz_listing_block_rate' => 'Rate',    
    '_modzzz_listing_block_info' => 'Info',
    '_modzzz_listing_block_desc' => 'Description',
    '_modzzz_listing_block_photo' => 'Photos',
    '_modzzz_listing_block_video' => 'Videos',
    '_modzzz_listing_block_sound' => 'Sounds',
    '_modzzz_listing_block_files' => 'Files',
    '_modzzz_listing_block_file' => 'Files',
    '_modzzz_listing_block_comments' => 'Comments',
    '_modzzz_listing_block_latest_featured_listing' => 'Latest Featured Businesses',
    '_modzzz_listing_block_recent' => 'Recent Businesses',
    '_modzzz_listing_block_popular' => 'Popular Businesses',
    '_modzzz_listing_block_top' => 'Top Rated Businesses',
    '_modzzz_listing_block_search' => 'Search Businesses',
    '_modzzz_listing_block_listing_categories' => 'Business Categories',

    '_modzzz_listing_block_administration_owner' => 'Administration',
    '_modzzz_listing_block_users_listing' => "User Businesses",
    '_modzzz_listing_block_my_listing' => 'My Businesses',
    '_modzzz_listing_block_my_listings' => 'My Businesses',
    '_modzzz_listing_block_area_listings' => 'Businesses in my Area',

    '_modzzz_listing_block_homepage' => 'Business listings',

    '_modzzz_listing_caption_add' => 'Add Business',
    '_modzzz_listing_caption_share_listing' => 'Share Business',
    '_modzzz_listing_caption_admin_actions' => 'Links',
    '_modzzz_listing_caption_pending_approval' => 'Pending Approval Businesses', 
    
	'_modzzz_listing_menu_manage_parents' => 'Parent Cats',
    '_modzzz_listing_menu_manage_categories' => 'Cats',
    '_modzzz_listing_categ_btn_save' => 'Save',
    '_modzzz_listing_categ_btn_edit' => 'Edit',
    '_modzzz_listing_categ_btn_delete' => 'Delete',
    '_modzzz_listing_categ_name' => 'Name',
    '_modzzz_listing_categ_icon' => 'Icon',
    '_modzzz_listing_categ_present_icon' => 'Present Icon',
    '_modzzz_listing_categ_btn_add' => 'Add',

    '_modzzz_listing_menu_root' => 'Businesses',
    '_modzzz_listing_menu_main' => 'Businesses Home',
    '_modzzz_listing_menu_recent' => 'Recent',
    '_modzzz_listing_menu_top_rated' => 'Top Rated',
    '_modzzz_listing_menu_popular' => 'Popular',
    '_modzzz_listing_menu_featured' => 'Featured',
    '_modzzz_listing_menu_tags' => 'Tags',
    '_modzzz_listing_menu_categories' => 'Categories',
    '_modzzz_listing_menu_calendar' => 'Calendar',
    '_modzzz_listing_menu_search' => 'Search',
    '_modzzz_listing_menu_view_listing' => 'Main',
    '_modzzz_listing_menu_view_comments' => 'Comments',
    '_modzzz_listing_menu_view_photos' => 'Photos',
    '_modzzz_listing_menu_view_videos' => 'Videos',
    '_modzzz_listing_menu_view_sounds' => 'Sounds',
    '_modzzz_listing_menu_view_files' => 'Files',
    '_modzzz_listing_menu_my_listing_profile' => 'Businesses',

    '_modzzz_listing_menu_admin_pending_approval' => 'Pending',
    '_modzzz_listing_menu_admin_entries' => 'Admin Businesses',
    '_modzzz_listing_menu_admin_add_entry' => 'Add',
    '_modzzz_listing_menu_admin_settings' => 'Settings',
    
    '_modzzz_listing_page_title_home' => 'Business Home',
    '_modzzz_listing_page_title_calendar' => 'Business Calendar',
    '_modzzz_listing_page_title_comments' => 'Comments',
    '_modzzz_listing_page_title_photos' => 'Photos',
    '_modzzz_listing_page_title_videos' => 'Videos',
    '_modzzz_listing_page_title_sounds' => 'Sounds',
    '_modzzz_listing_page_title_files' => 'Files',
    '_modzzz_listing_page_title_my_listing' => 'My Businesses',
    '_modzzz_listing_page_title_search' => 'Business Search',
    '_modzzz_listing_page_title_add' => 'Add Business', 
    '_modzzz_listing_page_title_edit' => 'Edit Business',
    '_modzzz_listing_page_title_administration' => 'Businesses Administration',
    '_modzzz_listing_admin_block_administration' => 'Admin.',

    '_modzzz_listing_page_title_browse' => 'Browse Businesses',
    '_modzzz_listing_page_title_pending_approval' => 'Pending Approval Businesses',
    '_modzzz_listing_page_title_search_results' => 'Business Search Results',
    '_modzzz_listing_page_title_browse_by_author' => "\'s listings",
    '_modzzz_listing_page_title_admin_listing' => 'Admin Businesses',
    '_modzzz_listing_page_title_browse_by_category' => 'Browse Businesses By Category: ',
    '_modzzz_listing_page_title_browse_by_tag' => 'Browse Businesses By Tag: ',
    '_modzzz_listing_page_title_browse_recent' => 'Recent Businesses',
    '_modzzz_listing_page_title_browse_top_rated' => 'Top Rated Businesses',
    '_modzzz_listing_page_title_browse_popular' => 'Popular Businesses',
    '_modzzz_listing_page_title_browse_featured' => 'Featured Businesses',
    '_modzzz_listing_page_title_browse_by_day' => 'Browse Businesses By Day: ',
    '_modzzz_listing_page_title_tags' => 'Businesses Tags',
    '_modzzz_listing_page_title_upload_photos' => 'Add Photos',
    '_modzzz_listing_page_title_upload_videos' => 'Add Videos',
    '_modzzz_listing_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_listing_page_title_upload_files' => 'Add Files',

    '_modzzz_listing_msg_pending_approval' => 'this listing is pending approval, please wait until it will be activated',
    '_modzzz_listing_msg_listing_was_deleted' => 'Business was deleted',
    '_modzzz_listing_msg_removed_from_featured' => 'Business was removed from featured',
    '_modzzz_listing_msg_added_to_featured' => 'Business was added to featured',
    '_modzzz_listing_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_listing_msg_you_have_pending_approval_listing' => 'You have <a href="%s">%d pending approval listings</a>',
    '_modzzz_listing_msg_you_have_no_listing' => 'You do not have any business listings. <a href="%s">Click here</a> to add one.',
    '_modzzz_listing_msg_you_have_some_listing' => 'You have <a href="%s">%d listing(s)</a>. <a href="%s">Click here</a> to add more.',

    '_modzzz_listing_admin_delete' => 'Delete',
    '_modzzz_listing_admin_activate' => 'Activate',
    '_modzzz_listing_admin_add_new_listing' => 'Add New Business',
    '_modzzz_listing_admin_listing' => 'Admin Business',
    '_modzzz_listing_admin_settings' => 'Admin Settings',

    '_modzzz_listing_form_header_info' => 'Business Info',
    '_modzzz_listing_form_header_images' => 'Business Photos',
    '_modzzz_listing_form_header_videos' => 'Business Videos',
    '_modzzz_listing_form_header_sounds' => 'Business Sounds',
    '_modzzz_listing_form_header_files' => 'Business Files',
    '_modzzz_listing_form_header_privacy' => 'Privacy Settings',
    '_modzzz_listing_form_caption_title' => 'Title',
    '_modzzz_listing_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_listing_form_caption_desc' => 'Description',
    '_modzzz_listing_form_err_desc' => 'Please enter at least 20 characters',
    '_modzzz_listing_form_err_tags' => 'Please enter tags',
    '_modzzz_listing_form_caption_author_id' => 'Author',
    '_modzzz_listing_form_info_author' => 'Author profile ID number',
    '_modzzz_listing_form_caption_keyword' => 'Keyword',
    '_modzzz_listing_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_modzzz_listing_form_caption_category' => 'Category',
    '_modzzz_listing_form_err_category' => 'Category is invalid',    
    '_modzzz_listing_form_caption_images_choice' => 'Choose',
    '_modzzz_listing_form_info_images_choice' => 'You can choose several images from your "Business" category',
    '_modzzz_listing_form_caption_images_upload' => 'Upload',    
    '_modzzz_listing_form_info_images_upload' => 'Image will be placed in the "Business" category automatically',
    '_modzzz_listing_form_caption_videos_choice' => 'Choose',
    '_modzzz_listing_form_info_videos_choice' => 'You can choose several videos from your "Business" category',
    '_modzzz_listing_form_caption_videos_upload' => 'Upload',
    '_modzzz_listing_form_info_videos_upload' => 'Video will be placed in the "Business" category automatically',
    '_modzzz_listing_form_caption_sounds_choice' => 'Choose',
    '_modzzz_listing_form_info_sounds_choice' => 'You can choose several sounds from your "Business" category',
    '_modzzz_listing_form_caption_sounds_upload' => 'Upload',
    '_modzzz_listing_form_info_sounds_upload' => 'Sound will be placed in the "Business" category automatically',
    '_modzzz_listing_form_caption_files_choice' => 'Choose',
    '_modzzz_listing_form_info_files_choice' => 'Unclick checkbox to remove file from this listing',
    '_modzzz_listing_form_caption_files_upload' => 'Upload',
    '_modzzz_listing_form_info_files_upload' => 'File will be placed in the "Business" category and set as private automatically',
    '_modzzz_listing_form_caption_file_title' => 'Title:',
    '_modzzz_listing_form_caption_file_price' => 'Price:',
    '_modzzz_listing_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_listing_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_listing_form_info_thumb_choice' => 'You can choose any image from your "Business" category as listing thumbnail',
    '_modzzz_listing_form_caption_country' => 'Country',
    '_modzzz_listing_form_err_country' => 'Country is a required field',
    '_modzzz_listing_form_caption_city' => 'City',
    '_modzzz_listing_form_err_city' => 'Please enter from 2 to 50 characters',
    '_modzzz_listing_form_caption_zip' => 'Zip/Postal Code',
    '_modzzz_listing_form_err_zip' => 'Zip/Postal code is required',
    '_modzzz_listing_form_err_email' => 'Invalid Email entered',

    '_modzzz_listing_action_title_edit' => 'Edit',
    '_modzzz_listing_action_title_delete' => 'Delete',
    '_modzzz_listing_action_title_share' => 'Share',
    '_modzzz_listing_action_add_to_featured' => 'Feature',    
    '_modzzz_listing_action_remove_from_featured' => 'Unfeature',
    '_modzzz_listing_action_add_listing' => 'Add Business',
    '_modzzz_listing_action_my_listing' => 'My Business',
    '_modzzz_listing_action_upload_photos' => 'Add Photos',
    '_modzzz_listing_action_upload_videos' => 'Add Videos',
    '_modzzz_listing_action_upload_sounds' => 'Add Sounds',
    '_modzzz_listing_action_upload_files' => 'Add Files',
    '_modzzz_listing_action_listing_home' => 'Home',

    '_modzzz_listing_action_title_inquire' => 'Inquire About', 
    '_modzzz_listing_action_title_spread' => 'Spread This', 
    '_modzzz_listing_action_title_promote' => 'Promote', 
    '_modzzz_listing_invitation_sent' => '%d Invitations have been sent',
	'_modzzz_listing_no_users_msg' => 'There are no users in your contacts',
	'_modzzz_listing_caption_invite' => 'Send Invitation To Friends',

    '_modzzz_listing_inquiry_subject' => 'Subject', 
    '_modzzz_listing_inquiry_subject_info' => 'Enter the Subject of your inquiry', 
    '_modzzz_listing_form_caption_review_inquiry' => 'Message', 
    '_modzzz_listing_form_info_review_inquiry' => 'Enter your inquiry here. It will be forwarded to the Business Owner',  
	'_modzzz_listing_caption_make_inquiry' => 'Make Inquiry',
    '_modzzz_listing_inquiry_sent' => 'your inquiry has been sent',
    '_modzzz_listing_inquiry_not_sent' => 'your inquiry has not been sent',
	'_mma_listing_make_inquiry' => 'listing make inquiry',

	'_modzzz_listing_action_title_claim' => 'Claim Business',
    '_modzzz_listing_claim_subject' => 'Subject', 
    '_modzzz_listing_claim_subject_info' => 'Enter the Subject of your claim', 
    '_modzzz_listing_claim_text' => 'Message', 
    '_modzzz_listing_claim_text_info' => 'Enter your proof of claim here. It will be forwarded to the Administrators',  
	'_modzzz_listing_caption_make_claim' => 'Make Claim',
    '_modzzz_listing_claim_sent' => 'your claim request has been sent',
    '_modzzz_listing_claim_not_sent' => 'your claim request has not been sent',
	 
	'_modzzz_listing_user_unknown' => 'Unknown', 
    '_modzzz_listing_price' => 'Price',

	'_modzzz_listing_business_contact' => 'Business Contact', 
	'_modzzz_listing_location' => 'Location',
	'_modzzz_listing_map' => 'Google Map', 
	'_modzzz_listing_form_caption_businessfax' => 'Fax',
	'_modzzz_listing_form_caption_businesstelephone' => 'Telephone',
	'_modzzz_listing_form_caption_businessemail' => 'Email',
	'_modzzz_listing_form_caption_businesswebsite' => 'Website',
	'_modzzz_listing_form_info_businesswebsite' => 'must be a valid URL (eg. http://www.mybusiness.com)', 
	'_modzzz_listing_form_caption_businessname' => 'Business Name',
	'_modzzz_listing_form_caption_address1' => 'Address 1',
	'_modzzz_listing_form_caption_address2' => 'Address 2', 
	'_modzzz_listing_form_err_listingoption' => 'Please select an Option', 
	'_modzzz_listing_form_err_listingtype' => 'Please select a Type',
    '_modzzz_listing_form_err_city' => 'Please enter from 3 to 150 characters',
  
    '_modzzz_listing_privacy_view_listing' => 'View Business',
    '_modzzz_listing_privacy_comment' => 'Comment',
    '_modzzz_listing_privacy_rate' => 'Rate',
    '_modzzz_listing_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_listing_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_listing_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_listing_privacy_upload_files' => 'Upload Files',
    '_modzzz_listing_privacy_edit_listing' => 'Edit Business',
    '_modzzz_listing_privacy_admins_only' => 'Admins Only',
    '_modzzz_listing_anonymous_note' => 'your name will not appear as the poster', 
    '_mma_listing_view_listing' => 'listing view listing', 
    '_mma_listing_browse' => 'listing browse', 
    '_mma_listing_search' => 'listing search', 
    '_mma_listing_add_listing' => 'listing add listing', 
    '_mma_listing_comments_delete_and_edit' => 'listing comments delete and edit', 
    '_mma_listing_edit_any_listing' => 'listing edit any listing', 
    '_mma_listing_delete_any_listing' => 'listing delete any listing', 
    '_mma_listing_mark_as_featured' => 'listing mark as featured', 
    '_mma_listing_approve_listing' => 'listing approve listing',   


	'_modzzz_listing_action_title_premium' => 'Get Premium',  
    '_modzzz_listing_page_title_premium' => 'Get Premium Listing',   
	'_mma_listing_purchase' => 'listing purchase package', 

    '_modzzz_listing_action_title_extend' => 'Extend',  
    '_modzzz_listing_page_title_extend' => 'Extend Business listing',   
	'_mma_listing_extend' => 'listing extend', 

    '_modzzz_listing_action_title_relist' => 'Re-list',  
    '_modzzz_listing_page_title_relist' => 'Re-list Business listing',  
	'_mma_listing_relist' => 'listing relist', 
  
    '_modzzz_listing_form_caption_current_no_package' => 'No Package currently',   
    '_modzzz_listing_form_caption_current_package' => 'Current Package',  
    '_modzzz_listing_form_caption_package_price' => 'Package Price',  
    '_modzzz_listing_form_caption_package_days' => 'Length of Listing',   
 	'_modzzz_listing_expires_never' => 'unlimited (never expires)', 
 	'_modzzz_listing_days' => 'days', 
 	'_modzzz_listing_form_caption_current_item' => 'Business', 
    '_modzzz_listing_extend' => 'Extend',  
    '_modzzz_listing_block_statistics' => 'Statistics',  
    '_modzzz_listing_block_price' => 'Price',  
	
    '_modzzz_listing_form_header_location' => 'Business Location',  
    '_modzzz_listing_form_header_contact' => 'Business Contact Details',  
     
	'_modzzz_listing_miles' => 'miles', 
    '_modzzz_listing_kilometers' => 'Km', 
	'_modzzz_listing_map_search_explanation' => 'Enter the City and Country (eg. miramer or miramer,US)', 

    '_modzzz_listing_enter_your_listing' => 'Enter your Business',
    '_modzzz_listing_block_listing_create' => 'Post your Business', 
    '_modzzz_listing_block_latest_comments' => 'Latest Comments',
    '_modzzz_listing_block_forum' => 'Latest Forum Posts',
    '_modzzz_listing_posted_by' => 'Posted by',
    '_modzzz_listing_posted_in' => 'Posted In',
 
	'_modzzz_listing_allow_num_listings' => 'Number of Businesses allowed', 	
	'_modzzz_listing_allow_videos' => 'Allow Videos', 	
	'_modzzz_listing_allow_photos' => 'Allow Photos', 	
	'_modzzz_listing_allow_sounds' => 'Allow Sounds', 	
	'_modzzz_listing_allow_files' => 'Allow Files', 	
 	'_modzzz_listing_featured' => 'Featured', 

	'_modzzz_listing_package_desc' => 'Package Description',  

    '_modzzz_listing_block_submenu_expired_listing' => 'Expired',
    '_modzzz_listing_page_title_expired' => 'Expired Businesses', 
	'_modzzz_listing_expires' => 'Expires',  
	'_modzzz_listing_never' => 'Never',  
 	'_modzzz_listing_featured_listing' => 'Featured Business (never expires)',  
 
    '_modzzz_listing_page_title_broadcast' => 'Send broadcast message to all fans of this listing',
    '_modzzz_listing_msg_broadcast_message_sent' => 'Broadcast messages have been sent',
    '_modzzz_listing_msg_broadcast_no_recipients' => 'There are no fans for this listing yet',
    '_modzzz_listing_form_caption_broadcast_title' => 'Broadcast message title',
    '_modzzz_listing_form_err_broadcast_title' => 'Please enter from 3 to 100 characters', 
    '_modzzz_listing_form_caption_broadcast_message' => 'Broadcast message',
    '_modzzz_listing_form_err_broadcast_message' => 'Please enter at least 10 characters',
    '_modzzz_listing_action_title_broadcast' => 'Broadcast',
    '_mma_listing_broadcast_message' => 'listing broadcast message',

    '_modzzz_listing_block_coupons' => 'Coupons', 
    '_modzzz_listing_block_deals' => 'Deals',
    '_modzzz_listing_block_reviews' => 'Reviews',
    '_modzzz_listing_block_jobs' => 'Jobs',
  
    '_modzzz_listing_form_caption_subcategories' => 'Sub-Categories',
    '_modzzz_listing_form_caption_categories' => 'Categories',

    '_mma_listing_mark_as_favorite' => 'listing mark as favorite', 
    '_modzzz_listing_menu_favorite' => 'Favorites',
    '_modzzz_listing_msg_removed_from_favorite' => 'Business was removed from favorite',
    '_modzzz_listing_msg_added_to_favorite' => 'Business was added to favorite',
    '_modzzz_listing_page_title_browse_favorite' => 'Favorite Businesses',
    '_modzzz_listing_action_add_to_favorite' => 'Favorite',    
    '_modzzz_listing_action_remove_from_favorite' => 'Not Favorite',
    '_modzzz_listing_pay_invoice' => 'PAY INVOICE',

	'_modzzz_listing_menu_drilldown' => 'Drilldown',
    '_modzzz_listing_caption_browse_area_listings' => 'Businesses in my Area',
 

    '_mma_listing_post_reviews' => 'listing post reviews',  
    '_modzzz_listing_page_title_reviews' => 'Business listing\'s Testimonials', 
    '_modzzz_listing_block_latest_reviews' => 'Latest Testimonials', 
	'_modzzz_listing_action_title_review' => 'Post Testimonial', 
    '_modzzz_listing_review_text' => 'Testimonial', 
    '_modzzz_listing_review_text_info' => 'If you have used the services of this listing, you can post a testimonial for the benefit of others who may wish to use their services', 
    '_modzzz_listing_form_caption_post_review' => 'Post Testimonial - ', 
    '_modzzz_listing_review_saved' => 'Testimonial has been saved', 
    '_modzzz_listing_review_not_saved' => 'Testimonial has not been saved',  
    '_modzzz_listing_review' => 'Testimonial', 
    '_modzzz_listing_block_listing_reviews' => 'Testimonials',
    '_modzzz_listing_menu_view_reviews' => 'Testimonials', 
	'_modzzz_listing_review_for' => 'Testimonial for', 
	'_modzzz_listing_block_reviews' => 'Testimonials', 
	'_modzzz_listing_block_my_reviews' => 'My Business Testimonials',  
 	'_modzzz_listing_action_title_post_review' => 'Post Review', 
	'_modzzz_listing_block_browse_reviews' => 'Browse Business Testimonials',
	'_modzzz_listing_page_title_review_add' => 'Add a Testimonial for Business Listing',
	'_modzzz_listing_page_title_review_browse' => 'Browse Testimonials for Business Listing', 
    '_modzzz_listing_action_title_add_review' => 'Add Testimonial',
    '_modzzz_listing_page_title_review_edit' => 'Edit Testimonial',
    '_modzzz_listing_msg_listing_review_was_deleted' => 'Testimonial was successfully deleted',
    '_modzzz_listing_msg_pending_review_approval' => 'this testimonial is pending approval, please wait until it will be activated',
    '_modzzz_listing_menu_view_reviews' => 'Testimonials',  
	'_modzzz_listing_posted_for' => 'Posted for Business',  
	'_modzzz_listing_by' => 'by',
	'_modzzz_listing_posted' => 'Posted', 
	'_modzzz_listing_form_review_header_info' => 'Review Info',
	'_modzzz_listing_block_details' => 'Details',

	'_modzzz_listing_friend' => 'Friend',
	
	/*added 7.1 */
    '_modzzz_listing_wall_added_new_comment' => 'commented on a',
    '_modzzz_listing_wall_added_new_items' => 'added {0} new business listing(s)',
	'_modzzz_listing_single' => 'Business Listing',
    '_modzzz_listing_posted_in_topic' => 'Posted in Forum',
    '_modzzz_listing_posted_in_listing' => 'Posted in Business', 
    '_modzzz_listing_block_calendar' => 'Calendar', 
	'_modzzz_listing_block_location' => 'Business Location', 
    '_modzzz_listing_block_map' => 'Map View', 
    '_modzzz_listing_caption_location_for_listing' => 'Located at Place',
 	'_modzzz_listing_tags' => 'Tags',
 	'_sys_module_listing' => 'Business listings', 
    '_modzzz_listing_adm_stats' => 'Pending Business listings',
 
 	'_modzzz_listing_title_add_employee' => 'Add Employee to listing - ',
 	'_modzzz_listing_add_employee_success' => 'Successfully added Employee <b>{0}</b> to listing',
 	'_modzzz_listing_add_employee_failed' => 'Failed to add Employee <b>{0}</b>. Please double check the name',
   
	'_modzzz_listing_form_caption_employee' => 'Employee',
	'_modzzz_listing_form_info_employee' => 'Enter username of member you want to add as employee',
	
	'_modzzz_listing_jobs_available' => 'Jobs Available',
    '_modzzz_listing_browse_listing_in_country' => 'Businesses in {0}', 

	'_modzzz_listing_located' => 'Located at',
	'_modzzz_listing_block_facebook_comments' => 'Facebook Comments',

	'_modzzz_listing_menu_view_website' => 'Website', 
	'_modzzz_listing_form_caption_website' => 'Website', 

 	'_modzzz_listing_title_website' => '{0} - Website', 

    '_modzzz_listing_block_submenu_joined_listing' => 'Joined Businesses',
    '_modzzz_listing_caption_browse_by_author_joined_listings' => 'Browse Joined Businesses: ',
	'_modzzz_listing_regions_in_country' => 'Regions in {0}', 

	'_modzzz_listing_form_caption_language' => 'Language', 
	'_modzzz_listing_form_header_add_category' => 'Add Category', 
	'_modzzz_listing_msg_categ_disable_success' => 'Successfully disabled selected Categories', 
	'_modzzz_listing_msg_categ_delete_success' => 'Successfully deleted selected Categories', 
	'_modzzz_listing_form_err_transfer_category' => 'You cannot transfer items to the same Category', 

	'_modzzz_listing_msg_categ_add_success' => 'Successfully added Category', 
	'_modzzz_listing_msg_categ_transfer_success' => 'Successfully transfered Items from Category', 

	'_modzzz_listing_form_header_transfer' => 'Category Transfer - Transfer Items from one category to another', 
	'_modzzz_listing_form_err_select_subcategory' => 'You must select a Sub-Category',  
	'_modzzz_listing_form_err_select_category' => 'You must select a Category', 
	'_modzzz_listing_form_err_select_language' => 'You must select a Language', 
 
	'_modzzz_listing_form_caption_from_category' => 'From Category', 
	'_modzzz_listing_form_caption_to_category' => 'To Category', 
	'_modzzz_listing_form_caption_to_subcategory' => 'Move Items to this Sub-Category', 
	'_modzzz_listing_form_caption_from_subcategory' => 'Move Items from this Sub-Category', 
 	'_modzzz_listing_form_caption_parent_category' => 'Parent Category', 
 
	'_modzzz_listing_form_caption_public' => 'Public', 
	'_modzzz_listing_form_info_public' => 'Only Admin can add items to categories that are not public', 
 
 	'_modzzz_listing_form_header_delete_subcategory' => 'Select Sub-Categories to delete',  
	'_modzzz_listing_msg_warning_delete' => '!! WARNING !!! Items that are attached to a deleted Category will be deleted also. Use the "Category Transfer" form above to assign a different Category to items if you want to preserve them', 
	'_modzzz_listing_items' => 'items', 

	'_modzzz_listing_form_header_edit_category' => 'Edit Category', 
	'_modzzz_listing_form_caption_exist_category' => 'Existing Category', 
	'_modzzz_listing_form_caption_exist_subcategory' => 'Existing Sub-Category', 
	'_modzzz_listing_form_caption_new_name' => 'New Name', 
	'_modzzz_listing_form_caption_add_new_category' => 'Add New Category', 
	'_modzzz_listing_form_caption_update_category' => 'Update Category', 	'_modzzz_listing_form_caption_add_new_subcategory' => 'Add New Sub-Category', 
	'_modzzz_listing_form_caption_update_subcategory' => 'Update Sub-Category', 
	'_modzzz_listing_msg_categ_update_success' => 'Successfully updated Category', 
	'_modzzz_listing_msg_subcateg_update_success' => 'Successfully updated Sub-Category', 

	'_modzzz_listing_listed_in' => 'Listed in', 

	'_modzzz_listing_block_browse_news' => 'Browse Business News',
	'_modzzz_listing_page_title_news_add' => 'Add News',
	'_modzzz_listing_page_title_news_browse' => 'Browse News',  
    '_modzzz_listing_action_title_add_news' => 'Add News',
    '_modzzz_listing_page_title_news_edit' => 'Edit News',
    '_modzzz_listing_msg_band_news_was_deleted' => 'News was successfully deleted',
    '_modzzz_listing_msg_pending_news_approval' => 'this news is pending approval, please wait until it will be activated',
    '_modzzz_listing_menu_view_news' => 'News', 
    '_modzzz_listing_block_news' => 'News',
    '_modzzz_listing_msg_listing_news_was_deleted' => 'News item was successfully deleted',

	'_modzzz_listing_block_browse_events' => 'Browse Business Events',
	'_modzzz_listing_page_title_event_add' => 'Add an Event',
	'_modzzz_listing_page_title_event_browse' => 'Browse Events',  
    '_modzzz_listing_action_title_add_event' => 'Add Event',
    '_modzzz_listing_page_title_event_edit' => 'Edit Event',
    '_modzzz_listing_msg_band_event_was_deleted' => 'Event was successfully deleted',
    '_modzzz_listing_msg_pending_event_approval' => 'this event is pending approval, please wait until it will be activated',
    '_modzzz_listing_menu_view_events' => 'Events', 
    '_modzzz_listing_block_events' => 'Business Events',
 	'_modzzz_listing_form_header_event_location' => 'Event Location',
	'_modzzz_listing_form_header_event_contact' => 'Contact Details',
 	'_modzzz_listing_event' => 'Event',
	'_modzzz_listing_event_single' => 'Event',
    '_modzzz_listing_msg_listing_event_was_deleted' => 'Event listing was successfully deleted', 
 	'_modzzz_listing_form_caption_place' => 'Place',
 	'_modzzz_listing_form_caption_state' => 'State',
 	'_modzzz_listing_form_caption_street' => 'Street',
 	'_modzzz_listing_form_caption_event_start' => 'Event Start',
 	'_modzzz_listing_form_caption_event_end' => 'Event End',
 	'_modzzz_listing_block_event_location' => 'Event Location', 
	'_modzzz_listing_happening' => 'Happening',
	'_modzzz_listing_block_map_view' => 'Map View',
	'_modzzz_listing_to' => 'to',
 
	'_modzzz_listing_block_my_employers' => 'Employers',
	'_modzzz_listing_caption_browse_by_author_employers_listings' => 'Browse Employers',
	'_modzzz_listing_caption_news_for_listing' => 'News for Business',  

    '_modzzz_listing_page_title_feature_item' => 'Feature this Business',
    '_modzzz_listing_feature_listing_desc' => 'Cost for featuring a Business',

    '_modzzz_listing_insufficient_credits_message' => 'Your Credits balance is {0}. You need {1} Credits to feature this listing.',
    '_modzzz_listing_insufficient_points_message' => 'Your Points balance is {0}. You need {1} Points to feature this listing.',
    '_modzzz_listing_buy_link' => '<a href="{0}">Buy more here</a>',
	'_modzzz_listing_form_caption_cost_to_feature' => 'Cost to Feature',
	'_modzzz_listing_form_caption_credits_balance' => 'Credits Balance',
	'_modzzz_listing_form_caption_points_balance' => 'Points Balance',
	'_modzzz_listing_credits' => 'Credits',
	'_modzzz_listing_points' => 'Points',
	'_modzzz_listing_msg_feature_success' => 'Business was successfully featured',
	'_modzzz_listing_msg_feature_failure' => 'Failed to feature listing',
	'_modzzz_listing_form_caption_feature' => 'Make this Featured',
	'_modzzz_listing_form_caption_submit' => 'Go Ahead',
	'_modzzz_listing_form_per_day' => 'per day',

	'_modzzz_listing_action_title_add_deal' => 'Add Deal',
	'_modzzz_listing_action_title_add_job' => 'Add Job',
	'_modzzz_listing_action_title_add_coupon' => 'Add Coupon',

	'_modzzz_listing_caption_event_for_listing' => 'Event for Business',

    '_mma_listing_allow_embed' => 'listing allow video embed', 
   	'_modzzz_listing_block_video_embed' => 'Youtube Videos',
	'_modzzz_listing_form_caption_youtube_link' => 'Video URL', 
	'_modzzz_listing_form_caption_youtube_caption' => 'Video Title',  
	'_modzzz_listing_form_header_youtube' => 'Youtube Videos',
	'_modzzz_listing_form_caption_youtube_attach' => 'Video',
	'_modzzz_listing_form_info_youtube_attach' => 'you can add multiple Youtube Videos',
	'_modzzz_listing_form_caption_youtube_choice' => 'Existing Videos',  
	'_modzzz_listing_form_info_youtube_choice' => 'Uncheck Videos that you want to remove', 
    '_modzzz_listing_page_title_embed_video' => 'Embed Video',
    '_modzzz_listing_action_embed_video' => 'Embed Video',
    '_modzzz_listing_visit' => 'Visit',

    '_modzzz_listing_block_logo' => 'Logo', 
    '_modzzz_listing_form_header_logo' => 'Logo', 
    '_modzzz_listing_present_icon' => 'Present Icon', 
    '_modzzz_listing_form_caption_icon' => 'Icon', 
    '_modzzz_listing_remove' => 'Remove', 


    '_modzzz_listing_action_title_rss' => 'RSS Info', 
	'_modzzz_listing_msg_credit_insufficient' => '{0} Credits are needed to Post a listing<br>You currently have {1} Credits',
	'_modzzz_listing_msg_credit_sufficient' => '{0} Credits will be deducted for Posting a listing',

    '_modzzz_listing_form_caption_pros' => 'Pros',
    '_modzzz_listing_form_caption_cons' => 'Cons',
    '_modzzz_listing_form_caption_general_comments' => 'General Comments',
    '_modzzz_listing_form_header_grating' => 'General Rating',
    '_modzzz_listing_form_header_orating' => 'Optional Rating',

    '_modzzz_listing_form_caption_review_quality' => 'Quality and productivity',
    '_modzzz_listing_form_info_review_quality' => 'Rating on a scale of 1 to 5',
    '_modzzz_listing_form_caption_review_features' => 'Features and functionality',
    '_modzzz_listing_form_info_review_features' => 'Rating on a scale of 1 to 5',
 
    '_modzzz_listing_form_caption_review_value' => 'Value for money',
    '_modzzz_listing_form_info_review_value' => 'Rating on a scale of 1 to 5',
    '_modzzz_listing_form_caption_review_support' => 'Customer Support',
    '_modzzz_listing_form_info_review_support' => 'Rating on a scale of 1 to 5',
 
    '_modzzz_listing_form_caption_name' => 'Name',
    '_modzzz_listing_form_err_name' => 'You must enter name',
    '_modzzz_listing_form_caption_companyname' => 'Company Name',
    '_modzzz_listing_form_caption_review_industry' => 'Your Industry',
    '_modzzz_listing_form_caption_review_employee_count' => 'Number of Employees',
    '_modzzz_listing_form_caption_review_email' => 'Your Email',
    '_modzzz_listing_form_caption_review_phone' => 'Your Phone Number (with extension)',
    '_modzzz_listing_form_caption_review_cell' => 'Cellphone', 
    '_modzzz_listing_block_media' => 'Media',
    '_modzzz_listing_form_err_review_inquiry' => 'You must state what you are inquiring about',
 
	'_modzzz_listing_employee_option_1' => '1 Employee',
	'_modzzz_listing_employee_option_2' => '2 to 5 Employees',
	'_modzzz_listing_employee_option_3' => '6 to 10 Employees',
	'_modzzz_listing_employee_option_4' => '11 to 20 Employees',
	'_modzzz_listing_employee_option_5' => '21 to 50 Employees',
	'_modzzz_listing_employee_option_6' => '51 to 100 Employees',
	'_modzzz_listing_employee_option_7' => '101 to 500 Employees',
	'_modzzz_listing_employee_option_8' => '501 to 1000 Employees',
	'_modzzz_listing_employee_option_9' => '1000 and More Employees',
 
	'_modzzz_listing_block_operation' => 'Business Hours', 
	'_modzzz_listing_from' => 'from',
	'_modzzz_listing_to' => 'to',
	'_modzzz_listing_time_am' => 'AM',
	'_modzzz_listing_time_pm' => 'PM',

	'_modzzz_listing_short_mon' => 'Monday',
	'_modzzz_listing_short_tue' => 'Tuesday',
	'_modzzz_listing_short_wed' => 'Wedneday',
	'_modzzz_listing_short_thur' => 'Thursday',
	'_modzzz_listing_short_fri' => 'Friday',
	'_modzzz_listing_short_sat' => 'Saturday',
	'_modzzz_listing_short_sun' => 'Sunday',
	
	'_modzzz_listing_form_caption_operation' => 'Open/Closing Hours',     
	'_modzzz_listing_form_header_operating_hours' => 'Hours', 
	'_modzzz_listing_form_caption_operation_choice' => 'Existing Operation Hours',
	'_modzzz_listing_form_caption_operation_attach' => 'Add Operation Hours', 
	'_modzzz_listing_form_info_operation_choice' => 'Uncheck entries that you want to remove',
	'_modzzz_listing_form_info_operation_attach' => 'You can add multiple entries',

);
