<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'BooneEx Groups';

$aLangContent = array(
    '_sys_module_groups' => 'Groups',
    '_sbs_txt_title_bx_groups' => 'Groups',
    '_bx_groups' => 'Groups',
    '_bx_groups_fans' => 'fans',
    '_bx_groups_add' => 'add',
    '_bx_groups_wall_added_new' => 'added new',
    '_bx_groups_wall_object' => 'group',
    '_bx_groups_for_group' => 'for %s',
    '_bx_groups_group_single' => 'group',
    '_bx_groups_group_plural' => 'groups',
    '_bx_groups_user_unknown' => 'Someone',
    '_bx_groups_admin_links' => 'Links',

    '_bx_groups_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new group <a href="{entry_url}">{entry_title}</a>',
    '_bx_groups_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed group <a href="{entry_url}">{entry_title}</a>',
    '_bx_groups_spy_join' => '<a href="{profile_link}">{profile_nick}</a> joined group <a href="{entry_url}">{entry_title}</a>',
    '_bx_groups_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated group <a href="{entry_url}">{entry_title}</a>',
    '_bx_groups_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented group <a href="{entry_url}">{entry_title}</a>',

    '_bx_groups_sbs_change' => 'information was updated',
    '_bx_groups_sbs_comment' => 'new comment arrived',
    '_bx_groups_sbs_rate' => 'rating was updated',
    '_bx_groups_sbs_join' => 'new fan',

    '_bx_groups_tab_featured' => 'Featured',
    '_bx_groups_tab_recent' => 'Recent',
    '_bx_groups_tab_top' => 'Top',
    '_bx_groups_tab_popular' => 'Popular',

    '_bx_groups_block_submenu_main' => 'Main',
    '_bx_groups_block_submenu_add_group' => 'Add',
    '_bx_groups_block_submenu_manage_groups' => 'Manage',
    '_bx_groups_block_submenu_pending_groups' => 'Pending Approval',

    '_bx_groups_block_actions' => 'Actions',
    '_bx_groups_block_rate' => 'Rate',    
    '_bx_groups_block_info' => 'Info',
    '_bx_groups_block_desc' => 'Description',
    '_bx_groups_block_photo' => 'Photos',
    '_bx_groups_block_video' => 'Videos',
    '_bx_groups_block_sound' => 'Sounds',
    '_bx_groups_block_files' => 'Files',
    '_bx_groups_block_file' => 'Files',
    '_bx_groups_block_fans' => 'Fans',
    '_bx_groups_block_fans_unconfirmed' => 'Unconfirmed Fans',
    '_bx_groups_block_comments' => 'Comments',
    '_bx_groups_block_latest_featured_group' => 'Latest Featured Group',
    '_bx_groups_block_recent' => 'Recent Public Groups',
    '_bx_groups_block_administration_owner' => 'Administration',
    '_bx_groups_block_users_groups' => 'User\'s Groups',
    '_bx_groups_block_my_groups' => 'My Groups',
	'_bx_groups_block_my_groups_joined' => 'Joined Groups',
    '_bx_groups_block_homepage' => 'Public Groups',
    '_bx_groups_block_states' => 'States',

    '_bx_groups_caption_add' => 'Add Group',
    '_bx_groups_caption_share_group' => 'Share Group',
    '_bx_groups_caption_admin_actions' => 'Links',
    '_bx_groups_caption_pending_approval' => 'Pending Approval Groups', 
    '_bx_groups_caption_manage_fans' => 'Manage Fans',

    '_bx_groups_menu_root' => 'Groups',
    '_bx_groups_menu_main' => 'Groups Home',
    '_bx_groups_menu_recent' => 'Recent',
    '_bx_groups_menu_top_rated' => 'Top Rated',
    '_bx_groups_menu_popular' => 'Popular',
    '_bx_groups_menu_featured' => 'Featured',
    '_bx_groups_menu_tags' => 'Tags',
    '_bx_groups_menu_categories' => 'Categories',
    '_bx_groups_menu_calendar' => 'Calendar',
    '_bx_groups_menu_search' => 'Search',
    '_bx_groups_menu_view_group' => 'Main',
    '_bx_groups_menu_view_forum' => 'Forum',
    '_bx_groups_menu_view_comments' => 'Comments',
    '_bx_groups_menu_view_fans' => 'Fans',
    '_bx_groups_menu_view_photos' => 'Photos',
    '_bx_groups_menu_view_videos' => 'Videos',
    '_bx_groups_menu_view_sounds' => 'Sounds',
    '_bx_groups_menu_view_files' => 'Files',
    '_bx_groups_menu_my_groups_profile' => 'Groups',

    '_bx_groups_menu_admin_pending_approval' => 'Pending Approval',
    '_bx_groups_menu_admin_entries' => 'Active Groups',
    '_bx_groups_menu_admin_add_entry' => 'Add Group',
    '_bx_groups_menu_admin_settings' => 'Settings',
    
    '_bx_groups_page_title_home' => 'Groups Home',
    '_bx_groups_page_title_calendar' => 'Groups Calendar ',
    '_bx_groups_page_title_comments' => 'Comments',
    '_bx_groups_page_title_photos' => 'Photos',
    '_bx_groups_page_title_videos' => 'Videos',
    '_bx_groups_page_title_sounds' => 'Sounds',
    '_bx_groups_page_title_files' => 'Files',
    '_bx_groups_page_title_fans' => 'Group\'s Fans',
    '_bx_groups_page_title_my_groups' => 'My Groups',
    '_bx_groups_page_title_search' => 'Groups Search',
    '_bx_groups_page_title_add' => 'Add Group', 
    '_bx_groups_page_title_edit' => 'Edit Group',
    '_bx_groups_page_title_administration' => 'Groups Administration',
    '_bx_groups_page_title_browse' => 'Browse Groups',
    '_bx_groups_page_title_pending_approval' => 'Pending Approval Groups',
    '_bx_groups_page_title_search_results' => 'Groups Search Results',
    '_bx_groups_page_title_browse_by_author' => '\'s groups',
    '_bx_groups_page_title_browse_by_author_joined_groups' => '\'s joined groups',
    '_bx_groups_page_title_admin_groups' => 'Active Groups',
    '_bx_groups_page_title_browse_by_category' => 'Browse Groups By Category: ',
    '_bx_groups_page_title_browse_by_tag' => 'Browse Groups By Tag: ',
    '_bx_groups_page_title_browse_recent' => 'Recent Groups',
    '_bx_groups_page_title_browse_top_rated' => 'Top Rated Groups',
    '_bx_groups_page_title_browse_popular' => 'Popular Groups',
    '_bx_groups_page_title_browse_featured' => 'Featured Groups',
    '_bx_groups_page_title_browse_by_day' => 'Browse Groups By Day: ',
    '_bx_groups_page_title_tags' => 'Groups Tags',
    '_bx_groups_page_title_categories' => 'Groups Categories',
    '_bx_groups_page_title_broadcast' => 'Send broadcast message to all fans of this group',
    '_bx_groups_page_title_upload_photos' => 'Add Photos',
    '_bx_groups_page_title_upload_videos' => 'Add Videos',
    '_bx_groups_page_title_upload_sounds' => 'Add Sounds',
    '_bx_groups_page_title_upload_files' => 'Add Files',
    '_bx_groups_page_title_invite' => 'Send Invitation To ',

    '_bx_groups_msg_pending_approval' => 'this group is pending approval, please wait until it will be activated',
    '_bx_groups_msg_group_was_deleted' => 'Group was deleted',
    '_bx_groups_msg_removed_from_featured' => 'Group was removed from featured',
    '_bx_groups_msg_added_to_featured' => 'Group was added to featured',
    '_bx_groups_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_bx_groups_msg_you_have_pending_approval_groups' => 'You have <a href="%s">%d pending approval groups</a>',
    '_bx_groups_msg_you_have_no_groups' => 'You don\'t have any groups. <a href="%s">Click here</a> to add one.',
    '_bx_groups_msg_you_have_some_groups' => 'You have <a href="%s">%d group(s)</a>. <a href="%s">Click here</a> to add more.',
    '_bx_groups_msg_broadcast_message_sent' => 'Broadcast messages have been sent',
    '_bx_groups_msg_broadcast_no_recipients' => 'There are no fans in this group yet',
    '_bx_groups_msg_joined_already' => 'You have already joined this group',
    '_bx_groups_msg_joined_request_pending' => 'You have already joined this group. Please wait while your request is processed by group admin(s).',
    '_bx_groups_msg_join_success' => 'You have successfully joined this group',
    '_bx_groups_msg_join_success_pending' => 'You have successfully joined this group. Please wait while your request is processed by group admin(s).',
	'_bx_groups_msg_leave_success' => 'You have successfully left this group',
    '_bx_groups_msg_invitation_sent' => '%d invitations have been sent',
    '_bx_groups_msg_no_users_to_invite' => 'There are no users in your contacts',

    '_bx_groups_admin_delete' => 'Delete',
    '_bx_groups_admin_activate' => 'Activate',
    '_bx_groups_admin_add_new_group' => 'Add New Group',
    '_bx_groups_admin_groups' => 'Admin Groups',
    '_bx_groups_admin_settings' => 'Admin Settings',

    '_bx_groups_form_header_info' => 'Group\'s Info',
    '_bx_groups_form_header_images' => 'Group\'s Photos',
    '_bx_groups_form_header_videos' => 'Group\'s Videos',
    '_bx_groups_form_header_sounds' => 'Group\'s Sounds',
    '_bx_groups_form_header_files' => 'Group\'s Files',
    '_bx_groups_form_header_privacy' => 'Privacy Settings',
    '_bx_groups_form_caption_title' => 'Title',
    '_bx_groups_form_err_title' => 'Please enter from 3 to 100 characters',
    '_bx_groups_err_title' => 'Please enter from 3 to 100 characters',
    '_bx_groups_form_caption_desc' => 'Description',
    '_bx_groups_err_desc' => 'Please enter at least 20 characters',
    '_bx_groups_form_err_desc' => 'Please enter at least 20 characters',
    '_bx_groups_form_err_tags' => 'Please enter tags',
    '_bx_groups_form_caption_author_id' => 'Author',
    '_bx_groups_form_info_author' => 'Author profile ID number',
    '_bx_groups_form_caption_keyword' => 'Keyword',
    '_bx_groups_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_bx_groups_form_caption_category' => 'Category',
    '_bx_groups_form_err_category' => 'Category is invalid',    
    '_bx_groups_form_caption_images_choice' => 'Choose',
    '_bx_groups_form_info_images_choice' => 'Unchecked images will be deleted',
    '_bx_groups_form_caption_images_upload' => 'Upload',    
    '_bx_groups_form_info_images_upload' => 'Image will be placed in the "Groups" category automatically',
    '_bx_groups_form_caption_videos_choice' => 'Choose',
    '_bx_groups_form_info_videos_choice' => 'Unchecked videos will be deleted',
    '_bx_groups_form_caption_videos_upload' => 'Upload',
    '_bx_groups_form_info_videos_upload' => 'Video will be placed in the "Groups" category automatically',
    '_bx_groups_form_caption_sounds_choice' => 'Choose',
    '_bx_groups_form_info_sounds_choice' => 'Unchecked sounds will be deleted',
    '_bx_groups_form_caption_sounds_upload' => 'Upload',
    '_bx_groups_form_info_sounds_upload' => 'Sound will be placed in the "Groups" category automatically',
    '_bx_groups_form_caption_files_choice' => 'Choose',
    '_bx_groups_form_info_files_choice' => 'Unchecked files will be deleted',
    '_bx_groups_form_caption_files_upload' => 'Upload',
    '_bx_groups_form_info_files_upload' => 'File will be placed in the "Groups" category and set as private automatically',
    '_bx_groups_form_caption_file_title' => 'Title:',
    '_bx_groups_form_caption_file_price' => 'Price:',
    '_bx_groups_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_bx_groups_form_caption_thumb_choice' => 'Choose thumbnail',
    '_bx_groups_form_info_thumb_choice' => 'You can choose any uploaded image as group thumbnail',
    '_bx_groups_form_caption_broadcast_title' => 'Broadcast message title',
    '_bx_groups_form_err_broadcast_title' => 'Please enter from 3 to 100 characters', 
    '_bx_groups_form_caption_broadcast_message' => 'Broadcast message',
    '_bx_groups_form_err_broadcast_message' => 'Please enter at least 10 characters',
    '_bx_groups_form_caption_country' => 'Country',
    '_bx_groups_form_err_country' => 'Country is a required field',
    '_bx_groups_form_caption_city' => 'City',
    '_bx_groups_form_err_city' => 'Please enter from 2 to 50 characters',
    '_bx_groups_form_caption_zip' => 'Zip/Postal Code',
    '_bx_groups_form_err_zip' => 'Zip/Postal code is required',
    '_bx_groups_form_caption_join_confirmation' => 'Join Confirmation',
    '_bx_groups_form_info_join_confirmation' => 'If enabled, group admin(s) will have to confirm each user before he/she becomes a fan.',
    '_bx_groups_form_join_confirmation_disabled' => 'Disabled',
    '_bx_groups_form_join_confirmation_enabled' => 'Enabled',
    '_bx_groups_form_err_join_confirmation' => 'Join confirmation field must be 0 or 1',

    '_bx_groups_action_title_edit' => 'Edit',
    '_bx_groups_action_title_delete' => 'Delete',
    '_bx_groups_action_title_share' => 'Share',
    '_bx_groups_action_title_broadcast' => 'Broadcast',
    '_bx_groups_action_title_join' => 'Join',
    '_bx_groups_action_title_leave' => 'Leave',
    '_bx_groups_action_title_invite' => 'Invite',
    '_bx_groups_action_add_to_featured' => 'Feature',    
    '_bx_groups_action_remove_from_featured' => 'Unfeature',
    '_bx_groups_action_add_group' => 'Add Group',
    '_bx_groups_action_my_groups' => 'My Groups',
    '_bx_groups_action_manage_fans' => 'Manage Fans',
    '_bx_groups_action_upload_photos' => 'Add Photos',
    '_bx_groups_action_upload_videos' => 'Add Videos',
    '_bx_groups_action_upload_sounds' => 'Add Sounds',
    '_bx_groups_action_upload_files' => 'Add Files',
    '_bx_groups_action_groups_home' => 'Groups Home',

    '_bx_groups_privacy_view_group' => 'View Group',
    '_bx_groups_privacy_view_fans' => 'View Fans',
    '_bx_groups_privacy_view_comment' => 'View Comment', 
    '_bx_groups_privacy_comment' => 'Comment',
    '_bx_groups_privacy_rate' => 'Rate',
    '_bx_groups_privacy_join' => 'Join',
    '_bx_groups_privacy_upload_photos' => 'Upload Photos',
    '_bx_groups_privacy_upload_videos' => 'Upload Videos',
    '_bx_groups_privacy_upload_sounds' => 'Upload Sounds',
    '_bx_groups_privacy_upload_files' => 'Upload Files',
    '_bx_groups_privacy_edit_group' => 'Edit Group',
    '_bx_groups_privacy_post_in_forum' => 'Post In Forum',
    '_bx_groups_privacy_fans_only' => 'Fans Only',
    '_bx_groups_privacy_fans' => 'Fans',
    '_bx_groups_privacy_admins_only' => 'Admins Only',

    '_mma_groups_view_group' => 'groups view group', 
    '_mma_groups_browse' => 'groups browse', 
    '_mma_groups_search' => 'groups search', 
    '_mma_groups_add_group' => 'groups add group', 
    '_mma_groups_comments_delete_and_edit' => 'groups comments delete and edit', 
    '_mma_groups_edit_any_group' => 'groups edit any group', 
    '_mma_groups_delete_any_group' => 'groups delete any group', 
    '_mma_groups_mark_as_featured' => 'groups mark as featured', 
    '_mma_groups_approve_groups' => 'groups approve groups', 
    '_mma_groups_broadcast_message' => 'groups broadcast message',
  
 
	'_bx_groups_caption_browse_other' => 'Other Groups by {0}',
	'_bx_groups_comments' => 'Comments',  	
	'_bx_groups_caption_categories' => 'Categories',  
	'_bx_groups_all_categories' => 'All Categories',  
	'_bx_groups_all_countries' => 'All Countries',  
	'_bx_groups_created' => 'Created',  
	'_bx_groups_block_search' => 'Quick Search',  
	
	'_bx_groups_regions_for_country' => 'Groups in',  
	'_bx_groups_block_browse_state' => 'Browse States', 
	'_bx_groups_block_browse_state_groups' => 'Browse Groups by State', 
	'_bx_groups_block_common_categories' => 'Common Categories', 
	'_bx_groups_block_latest_activities' => 'Latest Activities', 
	'_bx_groups_block_account' => 'Groups in my Area', 
	'_bx_groups_block_latest_comments' => 'Latest Public Comments', 

	'_bx_groups_block_browse_country' => 'Browse by Country', 
	'_bx_groups_page_title_local' => 'Browse Local Groups',  
	'_bx_groups_caption_browse_local' => 'Browse Local Groups in {0}', 
	'_bx_groups_menu_local' => 'Local', 

	'_bx_groups_block_sponsor' => 'Sponsor', 
	'_bx_groups_block_local' => 'More Local Groups',
  	'_bx_groups_block_other' => 'Other Groups by this member',
  	'_bx_groups_caption_sponsor_name' => 'Sponsor Name',
  	'_bx_groups_caption_sponsor_email' => 'Sponsor Email',
  	'_bx_groups_caption_sponsor_phone' => 'Sponsor Telephone',
  	'_bx_groups_caption_sponsor_website' => 'Sponsor Website',
  	'_bx_groups_caption_sponsor_fax' => 'Sponsor Fax',
   	'_bx_groups_form_header_sponsor' => 'Sponsor Info',
 
   	'_bx_groups_block_top_list' => 'Top Rated Public Groups',  
   	'_bx_groups_block_popular_list' => 'Popular Public Groups',  
	'_bx_groups_block_featured' => 'Recently Featured Groups',  
   	'_bx_groups_block_calendar' => 'Groups Calendar',  
	'_bx_groups_block_forum' => 'Latest Public Forum Posts',  
  
	'_bx_groups_continue' => 'Continue',  
	'_bx_groups_enter_your_group_name' => 'Enter your group name',  
	'_bx_groups_caption_state' => 'State',  
	'_bx_groups_form_caption_state' => 'State',  


	'_bx_groups_feed_make_admin' => '<a href="{profile_link}">{profile_nick}</a> is now an admin for group <a href="{entry_url}">{entry_title}</a>',  

	'_bx_groups_feed_remove_admin' => '<a href="{profile_link}">{profile_nick}</a> is no longer an admin for group <a href="{entry_url}">{entry_title}</a>',  

	'_bx_groups_feed_featured' => '<a href="{profile_link}">{profile_nick}</a> has featured group <a href="{entry_url}">{entry_title}</a>',  

	'_bx_groups_feed_unfeatured' => '<a href="{profile_link}">{profile_nick}</a> has un-featured group <a href="{entry_url}">{entry_title}</a>',  
 
	'_bx_groups_feed_delete' => '<a href="{profile_link}">{profile_nick}</a> removed group <a href="{entry_url}">{entry_title}</a>',  

	'_bx_groups_feed_post' => '<a href="{profile_link}">{profile_nick}</a> added new group <a href="{entry_url}">{entry_title}</a>',  

	'_bx_groups_feed_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed group <a href="{entry_url}">{entry_title}</a>',  

	'_bx_groups_feed_join' => '<a href="{profile_link}">{profile_nick}</a> is attending group <a href="{entry_url}">{entry_title}</a>',  

	'_bx_groups_feed_unjoin' => '<a href="{profile_link}">{profile_nick}</a> is no longer attending group <a href="{entry_url}">{entry_title}</a>',  

	'_bx_groups_feed_rate' => '<a href="{profile_link}">{profile_nick}</a> rated group <a href="{entry_url}">{entry_title}</a>',  

	'_bx_groups_feed_comment' => '<a href="{profile_link}">{profile_nick}</a> commented on group <a href="{entry_url}">{entry_title}</a>', 
  
	'_bx_groups_block_browse_sponsors' => 'Browse Group Sponsors',
	'_bx_groups_page_title_sponsor_add' => 'Add a Sponsor for Group - {0}',
	'_bx_groups_page_title_sponsor_browse' => 'Browse Sponsors for Group - {0}',  
    '_bx_groups_action_title_add_sponsor' => 'Add Sponsor',
    '_bx_groups_page_title_sponsor_edit' => 'Edit Sponsor',
    '_bx_groups_msg_group_was_sponsor_deleted' => 'Sponsor was successfully deleted',
    '_bx_groups_msg_pending_sponsor_approval' => 'this sponsor is pending approval, please wait until it will be activated',
    '_bx_groups_menu_view_sponsors' => 'Sponsors', 
    '_bx_groups_block_sponsors' => 'Sponsors',

	'_bx_groups_block_browse_blogs' => 'Browse Group Blogs',
	'_bx_groups_page_title_blog_add' => 'Add a Blog for Group - {0}',
	'_bx_groups_page_title_blog_browse' => 'Browse Blogs for Group - {0}',  
    '_bx_groups_action_title_add_blog' => 'Add Blog',
    '_bx_groups_page_title_blog_edit' => 'Edit Blog',
    '_bx_groups_msg_group_was_blog_deleted' => 'Blog was successfully deleted',
    '_bx_groups_msg_pending_blog_approval' => 'this blog is pending approval, please wait until it will be activated',
    '_bx_groups_menu_view_blogs' => 'Blogs', 
    '_bx_groups_block_blogs' => 'Blogs',

	
	'_bx_groups_block_browse_venues' => 'Browse Group Venues',
	'_bx_groups_page_title_venue_add' => 'Add a Venue for Group - {0}',
	'_bx_groups_page_title_venue_browse' => 'Browse Venues for Group - {0}',  
    '_bx_groups_action_title_add_venue' => 'Add Venue',
    '_bx_groups_page_title_venue_edit' => 'Edit Venue',
    '_bx_groups_msg_group_was_venue_deleted' => 'Venue was successfully deleted',
    '_bx_groups_msg_pending_venue_approval' => 'this venue is pending approval, please wait until it will be activated',
    '_bx_groups_menu_view_venues' => 'Venues', 
    '_bx_groups_block_venues' => 'Venues',

	'_bx_groups_block_browse_news' => 'Browse Group News',
	'_bx_groups_page_title_news_add' => 'Add a News for Group - {0}',
	'_bx_groups_page_title_news_browse' => 'Browse News for Group - {0}',  
    '_bx_groups_action_title_add_news' => 'Add News',
    '_bx_groups_page_title_news_edit' => 'Edit News',
    '_bx_groups_msg_group_was_news_deleted' => 'News was successfully deleted',
    '_bx_groups_msg_pending_news_approval' => 'this news is pending approval, please wait until it will be activated',
    '_bx_groups_menu_view_news' => 'News', 
    '_bx_groups_block_news' => 'News',
 
	'__bx_groups_event_birthday' => 'Birthday',
	'__bx_groups_event_sporting' => 'Sports/Fitness',
	'__bx_groups_event_party' => 'Party',
	'__bx_groups_event_convention' => 'Convention',
	'__bx_groups_event_social' => 'Social',
	'__bx_groups_event_work' => 'Work',
	'__bx_groups_event_exhibitions' => 'Exhibitions',
	'__bx_groups_event_festivals' => 'Fetes and Festivals', 
	'__bx_groups_event_politics' => 'Politics', 
	'__bx_groups_event_benefits' => 'Benefits/nonprofit', 
	'__bx_groups_event_comedy' => 'Comedy',  
	'__bx_groups_event_meeting' => 'Meeting',   
	'__bx_groups_event_other' => 'Other', 
    
 	'_bx_groups_posted_by' => 'Posted by',
    '_bx_groups_posted' => 'Posted',
  
    '_bx_groups_subprofile_form_header_info' => 'Info',
    '_bx_groups_subprofile_form_header_images' => 'Photos',
    '_bx_groups_subprofile_form_header_videos' => 'Videos',
    '_bx_groups_subprofile_form_header_sounds' => 'Sounds',
    '_bx_groups_subprofile_form_header_files' => 'Files',
    '_bx_groups_block_photos' => 'Photos',
 
    '_bx_groups_featured_status' => 'Featured Status', 
    '_bx_groups_featured_until' => 'Featured until', 
    '_bx_groups_not_featured' => 'Not Featured', 
 	'_bx_groups_extend_featured' => 'Extend Featured Status',  
	'_bx_groups_purchase_featured' => 'Purchase Featured Status', 
	'_bx_groups_form_caption_currency' => 'Currency',
    '_mma_groups_purchase_featured' => 'groups purchase featured',  
	'_bx_groups_action_title_purchase_featured' => 'Get Featured',
	'_bx_groups_action_title_extend_featured' => 'Extend Featured',  
	'_bx_groups_purchase_featured_status' => 'Purchase Featured Status',  
	'_bx_groups_quantity' => 'Quantity',   
	'_bx_groups_purchase_success' => 'You successfully Purchased {0} Days of Featured Status', 
	'_bx_groups_purchase_fail' => 'Your attempt to Purchase Featured Status has failed',  
	'_bx_groups_purchase_failed' => 'Your attempt to Purchase Featured Status has failed',  
	'_bx_groups_transaction_completed_already' => 'This transaction was already completed',  
	'_bx_groups_featured_cost_per_day' => 'Cost per Day',  
	'_bx_groups_caption_num_featured_days' => 'Number of Featured Days',    
	'_bx_groups_caption_err_featured_days' => 'You must enter Number of Featured Days',    
	'_bx_groups_get_featured' => 'Get Featured',  

	'_bx_groups_block_browse_categories_drilldown' => 'Categories Drilldown', 
	'_bx_groups_category_drilldown_for_item' => 'Categories Drilldown for <b>{0}</b>',  
 	'_bx_groups_featured_purchase_desc' => 'Purchase Featured Status - {0}',   
 
   	'_bx_groups_form_caption_video_embed_code' => 'Embed Code',
   	'_bx_groups_block_video_embed' => 'External Video',
 	'_bx_groups_form_info_video_embed_code' => 'Enter either the URL or Embed Code for Youtube Video. Enter the Embed Code for other video sharing site (eg &lt;embed&gt;....&lt;/embed&gt;)', 
	'_bx_groups_block_youtubes' => 'Youtube Videos', 
	'_bx_groups_form_caption_youtube_link' => 'Video URL', 
	'_bx_groups_form_caption_youtube_caption' => 'Video Title',  
	'_bx_groups_form_header_youtube' => 'Youtube Videos',
	'_bx_groups_form_caption_youtube_attach' => 'Video',
	'_bx_groups_form_info_youtube_attach' => 'you can add multiple Youtube Videos',
	'_bx_groups_form_caption_youtube_choice' => 'Existing Videos',  
	'_bx_groups_form_info_youtube_choice' => 'Uncheck Videos that you want to remove',  
    '_bx_groups_page_title_embed_video' => 'Embed Video for - ',
    '_bx_groups_action_embed_video' => 'Embed Video',
   	'_bx_groups_form_header_video_embed' => 'Video Embed',
   	'_bx_groups_caption_video_embed_code' => 'Embed Code', 


    '_bx_groups_calendar' => 'Groups Calendar ',
    '_bx_groups_caption_event_for_group' => 'Event for Group', 

	'_bx_groups_menu_drilldown' => 'Drilldown', 
	'_bx_groups_caption_browse_my_local' => 'Groups in my area', 
	'_bx_groups_block_created' => 'Groups I Created', 
	'_bx_groups_block_joined' => 'Groups I Joined', 
	'_bx_groups_action_groups_joined' => 'Joined', 
  

  	/*added 7.1 */
    '_bx_groups_wall_added_new_comment' => 'commented on a',
    '_bx_groups_wall_added_new_items' => 'added {0} new band(s)',
    '_bx_groups_posted_in_topic' => 'Posted in Forum',
    '_bx_groups_posted_in_group' => 'Posted for Group', 
	'_bx_groups_event_single' => 'Group Event',
	'_bx_groups_event' => 'Group Event',
	'_bx_groups_venue_single' => 'Group Venue',
	'_bx_groups_venue' => 'Group Venue',
	'_bx_groups_sponsor_single' => 'Group Sponsor',
	'_bx_groups_sponsor' => 'Group Sponsor',
	'_bx_groups_views' => 'views',
    '_bx_groups_adm_stats' => 'Pending Groups',
	'_bx_groups_tags' => 'Tags', 
	'_bx_groups_go' => 'Go', 
 
    '_mma_groups_broadcast_message' => 'groups broadcast message',    
    '_mma_groups_files_add' => 'groups files add',  
    '_mma_groups_photos_add' => 'groups photos add',  
    '_mma_groups_videos_add' => 'groups videos add',  
    '_mma_groups_sounds_add' => 'groups sounds add',  
    '_mma_groups_rss_add' => 'groups rss add',
	
	'_bx_groups_accept_invitation' => 'Accept Group Invitation - ',  
    '_bx_groups_block_forum_feed' => 'Forum Feed',
 
	'_bx_groups_caption_membership_view_filter' => 'Allow viewing by membership',
	'_bx_groups_err_membership_view_filter' => 'incorrect value', 
    '_bx_groups_info_membership_view_filter' => 'only these members will be able to view this group',
	'_bx_groups_caption_membership_join_filter' => 'Allow joining by membership',
	'_bx_groups_err_membership_join_filter' => 'incorrect value', 
    '_bx_groups_info_membership_join_filter' => 'only these members will be able to join this group',
    '_bx_groups_membership_filter_none' => 'Allow All',	

 
    '_bx_groups_action_title_excel' => 'Export Participants', 
    '_bx_groups_action_title_print' => 'Print Participants',  
 
	'_bx_groups_block_browse_events' => 'Browse Group Events',
	'_bx_groups_page_title_event_add' => 'Add a Event for Group - {0}',
	'_bx_groups_page_title_event_browse' => 'Browse Events for Group - {0}',  
    '_bx_groups_action_title_add_event' => 'Add Event',
    '_bx_groups_page_title_event_edit' => 'Edit Event',
    '_bx_groups_msg_group_was_event_deleted' => 'Event was successfully deleted',
    '_bx_groups_msg_pending_event_approval' => 'this event is pending approval, please wait until it will be activated',
    '_bx_groups_menu_view_events' => 'Events', 
    '_bx_groups_block_events' => 'Events',
    '_bx_groups_block_events' => 'Events',  
	'_bx_groups_caption_city' => 'City',
	'_bx_groups_caption_country' => 'Country',
	'_bx_groups_caption_desc' => 'Description',
	'_bx_groups_caption_edit' => 'Edit Event',
	'_bx_groups_caption_event_end' => 'Date end',
	'_bx_groups_caption_event_start' => 'Date start',
	'_bx_groups_caption_invite' => 'Send Invitation To ',
	'_bx_groups_caption_join_filter' => 'Allow to join',
	'_bx_groups_caption_keyword' => 'Keyword',
	'_bx_groups_caption_membership_filter' => 'Allow joining by membership',
	'_bx_groups_caption_photo' => 'Photo',
	'_bx_groups_caption_place' => 'Place name',
    '_bx_groups_caption_search' => 'Search',
    '_bx_groups_caption_search_results' => 'Search Results:',
	'_bx_groups_caption_title' => 'Title',	
 
 
	'_bx_groups_block_rss_feed' => 'RSS Feed',
	'_bx_groups_form_caption_rss' => 'RSS Link', 
	'_bx_groups_form_caption_rss_caption' => 'Feed Caption',  
	'_bx_groups_form_caption_rss_link' => 'Feed Link', 
	'_bx_groups_form_header_rss' => 'RSS Feeds',
	'_bx_groups_form_caption_rss_attach' => 'New Feed',
	'_bx_groups_form_info_rss_attach' => 'you can add multiple RSS Feeds',
	'_bx_groups_form_caption_rss_choice' => 'Existing Feeds', 
  	'_bx_groups_form_info_rss_choice' => 'Uncheck the Feeds you want to remove', 

	'_bx_groups_block_categories' => 'Categories',
	'_bx_groups_form_header_location' => 'Location',

	'_bx_groups_form_header_contact' => 'Contact Details',  
	'_bx_groups_form_caption_website' => 'Website',  
	'_bx_groups_form_caption_email' => 'Email',  
	'_bx_groups_form_caption_telephone' => 'Telephone',  
	'_bx_groups_form_caption_fax' => 'Fax',  
	'_bx_groups_block_contact' => 'Contact Information',  
	'_bx_groups_block_location' => 'Location',
	'_bx_groups_block_map' => 'Map View',
	'_bx_groups_form_caption_address1' => 'Address 1',
 
	'_bx_groups_browse_groups_in_country' => 'Groups in {0}',
 
	'_bx_groups_title_add_fan' => 'Add Fan to Group',  
	'_bx_groups_title_add_admin' => 'Add Administrator to Group',  

	'_bx_groups_form_caption_enter_member' => 'Member Name',  
	'_bx_groups_form_info_enter_member' => 'You can enter multiple Member Names separated by comma',  
 
  	'_bx_groups_action_title_add_fan' => 'Add Fan',  
	'_bx_groups_action_title_add_admin' => 'Add Admin',  

	'_bx_groups_msg_add_fan_success' => 'Successfully added Member(s) as Fan',  
	'_bx_groups_msg_add_admin_success' => 'Successfully added Member(s) as Administrator',  
	'_bx_groups_msg_add_fan_fail' => 'Failed to add Member(s) as Fan',  
	'_bx_groups_msg_add_admin_fail' => 'Failed to add Member(s) as Administrator',  
 	'_bx_groups_block_admins' => 'Administrators',  
 	'_bx_groups_action_manage_admins' => 'Manage Admins',  
 	'_bx_groups_caption_manage_admins' => 'Manage Admins',  

  	'_bx_groups_msg_private_join' => 'This Group is Private. You have to become a fan to access it',  
  	'_bx_groups_msg_private_join_pending' => 'This Group is Private. You have already sent a fan request to access it. The Group Administrator will review your request and make a decision shortly',  
 	'_bx_groups_login' => '<a href="{0}">Login</a>',  
 	'_bx_groups_block_joined_groups' => 'Groups I have Joined',  

	/*begin - added patch 2.1.7*/
	'_bx_groups_privacy_view_forum' => 'View Forum', 
	/*end - added patch 2.1.7*/

    '_bx_groups_caption_browse_by_country' => 'Browse Groups By Country: ',
 	
	'_bx_groups_caption_news_for_group' => 'News for Group',  
 	
	/*begin - added patch 2.1.9*/ 
	'_bx_groups_threshold' => 'Threshold', 
	'_bx_groups_menu_admin_membership' => 'Membership',
    '_bx_groups_membership_changes_saved' => 'Membership changes have been saved',
	'_bx_groups_membership_settings_desc' => 'You can set thresholds for the amount of members that can join a Group based on the Membership level of the Group Creator',
	'_bx_groups_threshold_msg_notification_members' => 'This Group  has reached its threshold of {0} members', 
	/*end - added patch 2.1.9*/

	'_bx_groups_caption_browse_local' => 'Browse local Groups in {0}', 
  '_wall_reposted_bx_groups_add' => 'reposted a group',
  '_wall_reposted_title_bx_groups_add' => '{0} reposted a group',
  '_wall_reposted_bx_groups_comment_add' => 'reposted a group comment',
  '_wall_reposted_title_bx_groups_comment_add' => '{0} reposted a group comment',
 
  '_bx_groups_popup_title_ban_member' => 'Ban Member', 
  '_bx_groups_msg_ban_success' => 'Successfully banned member',  
  '_bx_groups_msg_ban_fail' => 'Failed to ban member', 
  '_bx_groups_action_title_ban' => 'Ban Member', 
  '_bx_groups_btn_members_unban' => 'UnBan Members', 
  '_bx_groups_block_banned_members' => 'Banned Members', 

	'_bx_groups_block_logo' => 'Logo', 
	'_bx_groups_form_header_logo' => 'Logo', 
	'_bx_groups_present_icon' => 'Present Icon', 
	'_bx_groups_form_caption_icon' => 'Icon', 
	'_bx_groups_remove' => 'Remove', 
	'_bx_groups_caption_browse_group_survey' => 'Group Survey - {0}', 
	'_bx_groups_action_title_add_survey' => 'Post Survey', 
	'_bx_groups_block_survey' => 'Survey', 



);