<?php
/***************************************************************************
*                            Dolphin Smart Charity Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Charity
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Charity Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Charity';

$aLangContent = array(
  
    '_modzzz_charity_yes' => 'Yes',
    '_modzzz_charity_no' => 'No',
 
    '_modzzz_charity_form_caption_capacity' => 'Charity Capacity',
    '_modzzz_charity_form_caption_about_us' => 'About us',
    '_modzzz_charity_form_caption_dress_code' => 'Dress Code',
    '_modzzz_charity_caption_desc' => 'Description',
    '_modzzz_charity_block_details' => 'Details',
    '_modzzz_charity_form_caption_position' => 'Position',
    '_modzzz_charity_form_info_position' => 'In what capacity does this volunteer serve?',
    '_modzzz_charity_form_caption_member_name' => 'Member Name',
    '_modzzz_charity_form_caption_staff_name' => 'Staff Name',
    '_modzzz_charity_form_caption_program_name' => 'Program',
    '_modzzz_charity_form_caption_branch_name' => 'Branch',
    '_modzzz_charity_block_location' => 'Location',

    '_modzzz_charity_fans' => 'fans',
    '_modzzz_charity_sbs_join' => 'new fan',
    '_modzzz_charity_block_fans' => 'Fans',
    '_modzzz_charity_block_fans_unconfirmed' => 'Unconfirmed Fans',
	'_modzzz_charity_block_my_charities_joined' => 'Joined Charities',
    '_modzzz_charity_caption_manage_fans' => 'Manage Fans',
    '_modzzz_charity_menu_view_fans' => 'Fans',
    '_modzzz_charity_page_title_fans' => 'Charity\'s Fans',
    '_modzzz_charity_action_manage_fans' => 'Manage Fans',
    '_modzzz_charity_privacy_view_fans' => 'View Fans',
    '_modzzz_charity_privacy_fans_only' => 'Fans Only',
    '_modzzz_charity_privacy_fans' => 'Fans',

    '_modzzz_charity_spy_join' => '<a href="{profile_link}">{profile_nick}</a> joined charity <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_charity_sbs_join' => 'new fan',
    '_modzzz_charity_page_title_browse_by_author_joined_charities' => '\'s joined charities',
    '_modzzz_charity_msg_joined_already' => 'You have already joined this charity',
    '_modzzz_charity_msg_joined_request_pending' => 'You have already joined this charity. Please wait while your request is processed by charity admin(s).',
    '_modzzz_charity_msg_join_success' => 'You have successfully joined this charity',
    '_modzzz_charity_msg_join_success_pending' => 'You have successfully joined this charity. Please wait while your request is processed by charity admin(s).',
	'_modzzz_charity_msg_leave_success' => 'You have successfully left this charity',
    '_modzzz_charity_form_caption_join_confirmation' => 'Join Confirmation',
    '_modzzz_charity_form_info_join_confirmation' => 'If enabled, charity admin(s) will have to confirm each user before he/she becomes a fan.',
    '_modzzz_charity_form_join_confirmation_disabled' => 'Disabled',
    '_modzzz_charity_form_join_confirmation_enabled' => 'Enabled',
    '_modzzz_charity_form_err_join_confirmation' => 'Join confirmation field must be 0 or 1',
    '_modzzz_charity_action_title_join' => 'Become Fan',
    '_modzzz_charity_action_title_leave' => 'Remove Fan',
    '_modzzz_charity_privacy_join' => 'Become Fan',
 
    '_modzzz_charity_packages_empty' => 'There are no Paid Packages', 
    '_modzzz_charity_package_description' => 'Description', 
    '_modzzz_charity_package_featured' => 'Featured', 

    '_modzzz_charity_featured_status' => 'Featured Status', 
    '_modzzz_charity_featured_until' => 'Featured until', 
    '_modzzz_charity_not_featured' => 'Not Featured', 
 	'_modzzz_charity_extend_featured' => 'Extend Featured Status',  
	'_modzzz_charity_purchase_featured' => 'Purchase Featured Status', 
	'_modzzz_charity_form_caption_currency' => 'Currency',  
  
    '_modzzz_charity_menu_packages' => 'Packages', 
    '_modzzz_charity_page_title_packages' => 'Paid Packages', 
    '_modzzz_charity_block_packages' => 'Paid Packages', 

    '_modzzz_charity_menu_view_forum' => 'Forum', 
    '_modzzz_charity_privacy_post_in_forum' => 'Post In Forum',
 
   	'_modzzz_charity_form_header_video_embed' => 'Video Embed',
   	'_modzzz_charity_caption_video_embed_code' => 'Embed Code',
	'_modzzz_charity_form_info_video_embed_code' => 'Enter either the URL or Embed Code for Youtube Video. Enter the Embed Code for other video sharing site (eg &lt;embed&gt;....&lt;/embed&gt;)',
   	'_modzzz_charity_block_video_embed' => 'External Video',
  
	'_modzzz_charity_caption_membership_view_filter' => 'Allow viewing by membership',
	'_modzzz_charity_err_membership_view_filter' => 'incorrect value', 
    '_modzzz_charity_info_membership_view_filter' => 'only these members will be able to view this charity',
    '_modzzz_charity_membership_filter_none' => 'Allow All',	

    '_mma_charity_create_faqs' => 'charity create FAQ',  
    '_mma_charity_post_reviews' => 'charity post reviews',  
    '_mma_charity_view_donors' => 'charity view donors',  

    '_mma_charity_files_add' => 'charity files add',  
    '_mma_charity_photos_add' => 'charity photos add',  
    '_mma_charity_videos_add' => 'charity videos add',  
    '_mma_charity_sounds_add' => 'charity sounds add',  
	
    '_modzzz_charity_continue' => 'Continue',  
    '_modzzz_charity_admin_assign' => 'Assign to Claimant',  
    '_modzzz_charity_menu_manage_claims' => 'Claims',  
    '_modzzz_charity_claimed_by' => 'Claimed by',  
    '_modzzz_charity_on' => 'on',  
  
	'_modzzz_charity_package_videos' => 'Videos',  	
	'_modzzz_charity_package_photos' => 'Photos',  	
	'_modzzz_charity_package_sounds' => 'Sounds',  	
	'_modzzz_charity_package_files' => 'Files', 

	'_modzzz_charity_block_charity_states' => 'Browse Local Charities', 
 
    '_mma_charity_purchase_featured' => 'charity purchase featured', 
    '_mma_charity_make_claim' => 'charity make claim', 
    '_mma_charity_make_inquiry' => 'charity make inquiry', 

    '_modzzz_charity_regions_for_country' => 'Find Charities in',  
	'_modzzz_charity_block_browse_state' => 'Browse States', 
	'_modzzz_charity_block_browse_state_charities' => 'Browse Charities by State', 
	'_modzzz_charity_block_account' => 'Charities in my Area',  
	'_modzzz_charity_block_browse_country' => 'Browse by Country', 
	'_modzzz_charity_page_title_local' => 'Browse Local Charities',  
	'_modzzz_charity_caption_browse_local' => 'Browse Local Charities in {0}', 
	'_modzzz_charity_menu_local' => 'Local', 
 	'_modzzz_charity_block_local' => 'More Local Charities',
	'_modzzz_charity_block_other' => 'Other Charities by this member',
 	'_modzzz_charity_caption_browse_other' => 'Other Charities by {0}',


	'_modzzz_charity_action_title_purchase_featured' => 'Get Featured',
	'_modzzz_charity_action_title_extend_featured' => 'Extend Featured',  
	'_modzzz_charity_purchase_featured_status' => 'Purchase Featured Status',  
	'_modzzz_charity_quantity' => 'Quantity',   
	'_modzzz_charity_purchase_success' => 'You successfully Purchased {0} Days of Featured Status', 
	'_modzzz_charity_purchase_failed' => 'Your attempt to Purchase Premium Listing has failed',  
	'_modzzz_charity_purchase_featured_failed' => 'Your attempt to Purchase Featured Status has failed',  
	'_modzzz_charity_transaction_completed_already' => 'This transaction was already completed',  
	'_modzzz_charity_featured_cost_per_day' => 'Cost per Day',  
	'_modzzz_charity_caption_num_featured_days' => 'Number of Featured Days',    
	'_modzzz_charity_caption_err_featured_days' => 'You must enter Number of Featured Days',    
	'_modzzz_charity_get_featured' => 'Get Featured',  
 

    '_modzzz_charity_parent_categories' => 'Categories', 
    '_modzzz_charity_sub_categories' => 'Sub-Categories', 

    '_modzzz_charity_block_category_charity' => 'Charities in this Category',
    '_modzzz_charity_block_subcategories' => 'Sub-Categories',  
    '_modzzz_charity_manage_subcategories_msg' => 'To manage Sub-Categories, go to Parent Categories and select the Category of interest. Then click the Sub-Categories button', 
	'_modzzz_charity_categ_name' => 'Category',
	'_modzzz_charity_categ_btn_edit' => 'Edit',
	'_modzzz_charity_categ_btn_delete' => 'Delete',
	'_modzzz_charity_categ_btn_add' => 'Add',
	'_modzzz_charity_categ_btn_save' => 'Save',
	'_modzzz_charity_categ_btn_subcategories' => 'Sub-Categories', 
 	'_modzzz_charity_categories' => 'Categories',
 	'_modzzz_charity_menu_admin_manage_categories' => 'Categories',
  	'_modzzz_charity_menu_admin_manage_subcategories' => 'Sub-Cats',
  	'_modzzz_charity_subcategories' => 'Sub-Categories',
  	'_modzzz_charity_categories' => 'Categories',
    '_modzzz_charity_all_categories' => 'All Categories',
    '_modzzz_charity_block_categories' => 'Categories',
    '_modzzz_charity_block_categories' => 'Categories',
    '_modzzz_charity_block_charity_subcategories' => 'Sub-Categories',
    '_modzzz_charity_block_answer_categories' => 'Charity Categories',
    '_modzzz_charity_menu_categories' => 'Categories',
    '_modzzz_charity_page_title_browse_by_category' => 'Browse Charities By Category: ',
    '_modzzz_charity_form_caption_category' => 'Category',
    '_modzzz_charity_form_err_category' => 'Category is invalid', 
	'_modzzz_charity_page_title_category' => 'Category', 
    '_modzzz_charity_page_title_categories' => 'Charity Categories',
    '_modzzz_charity_page_title_subcategories' => 'Charity Sub-Categories', 
    '_modzzz_charity_charities_in_category' => '<b>Charities</b> in <b>%s</b>',  
    '_modzzz_charity_block_charity' => 'Charities', 
    
	'_modzzz_charity_packages' => 'Packages',
	'_modzzz_charity_package_name' => 'Package Name',
	'_modzzz_charity_package_price' => 'Package Price',
	'_modzzz_charity_package_days' => 'Package Days',
	'_modzzz_charity_form_caption_package' => 'Package',
	'_modzzz_charity_form_err_package' => 'Please select a Package',  
	'_modzzz_charity_purchaser' => 'Purchaser', 
	'_modzzz_charity_invoice_no' => 'Invoice #', 
	'_modzzz_charity_package' => 'Package', 
	'_modzzz_charity_invoice_date' => 'Invoice Date', 
	'_modzzz_charity_invoice_due_date' => 'Due Date', 
	'_modzzz_charity_status' => 'Status',
	'_modzzz_charity_pending' => 'Pending',
	'_modzzz_charity_paid' => 'Paid',
	'_modzzz_charity_active' => 'Active',
	'_modzzz_charity_inactive' => 'Inactive',
	'_modzzz_charity_approved' => 'Approved',
	'_modzzz_charity_expired' => 'Expired', 
	'_modzzz_charity_block_submenu_pending_invoices' => 'Pending Invoices',
	'_modzzz_charity_block_submenu_orders' => 'Orders',
	'_modzzz_charity_page_title_orders' => 'Orders', 
	'_modzzz_charity_page_title_invoices' => 'Invoices', 
	'_modzzz_charity_menu_manage_invoices' => 'Invoices', 
	'_modzzz_charity_menu_manage_packages' => 'Packages',
	'_modzzz_charity_menu_manage_orders' => 'Orders',
	'_modzzz_charity_payment_method' => 'Payment Method',
	'_modzzz_charity_total' => 'Total',
	'_modzzz_charity_invoice_id' => 'Invoice ID',
	'_modzzz_charity_next_due_date' => 'Next Due Date',
	'_modzzz_charity_order_no' => 'Order #',
	 '_modzzz_charity_product_status' => 'Product Status',
	'_modzzz_charity_order_date' => 'Order Date',
	'_modzzz_charity_purchase_failed' => 'Sorry, there was a problem with the Payment.  View your Pending Orders <a href="{0}">here</a>.',
	'_modzzz_charity_transaction_completed_already' => 'The Transaction exists already. Click <a href="{0}">here</a> to view the Charity.',
	'_modzzz_charity_purchase_success' => 'Thank you. The Payment was successful. Click <a href="{0}">here</a> to view the Charity.',  
	'_modzzz_charity_trans_save_failed' => 'The Payment was successful but there was a Problem saving the transaction. Please contact the administrator with your Paypal transaction details so they can manually process your Order.',
	'_modzzz_charity_post_purchase_header' => 'Charity Purchase',  
 
	'_modzzz_charity_caption_state' => 'State',  
 	'_modzzz_charity_caption_search' => 'Search Charities', 
    '_modzzz_charity_no_charities' => 'There are no Charities',
    '_sbs_txt_title_modzzz_charity' => 'Charities',
    '_modzzz_charity' => 'Charity',
    '_modzzz_charity_add' => 'add',
    '_modzzz_charity_wall_added_new' => 'added new',
    '_modzzz_charity_wall_object' => 'charity',
    '_modzzz_charity_for_charity' => 'for %s',
    '_modzzz_charity_charity_single' => 'charity',
    '_modzzz_charity_charity_plural' => 'charities',
    '_modzzz_charity_user_unknown' => 'Unknown',
    '_modzzz_charity_disabled' => 'disabled',
    '_modzzz_charity_enabled' => 'enabled',
    '_modzzz_charity_cannot_delete_default_parent' => 'Cannot Delete Default Parent Category',
	  
    '_modzzz_charity_block_map' => 'Map View',

     '_modzzz_charity_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new charity <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_charity_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed charity <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_charity_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated charity <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_charity_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented charity <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_charity_sbs_change' => 'information was updated',
    '_modzzz_charity_sbs_comment' => 'new comment arrived',
    '_modzzz_charity_sbs_rate' => 'rating was updated',
 
    '_modzzz_charity_tab_featured' => 'Featured',
    '_modzzz_charity_tab_recent' => 'Recent',
    '_modzzz_charity_tab_top' => 'Top',
    '_modzzz_charity_tab_popular' => 'Popular',

    '_modzzz_charity_block_submenu_main' => 'Main',
    '_modzzz_charity_block_submenu_add_charity' => 'Add',
    '_modzzz_charity_block_submenu_manage_charity' => 'Manage',
    '_modzzz_charity_block_submenu_pending_charity' => 'Pending Approval',

    '_modzzz_charity_block_actions' => 'Actions',
    '_modzzz_charity_block_rate' => 'Rate',    
    '_modzzz_charity_block_info' => 'Charity Info',
    '_modzzz_charity_block_listed_by' => 'Listed By', 
    '_modzzz_charity_block_desc' => 'Description',
    '_modzzz_charity_block_photo' => 'Photos',
    '_modzzz_charity_block_video' => 'Videos',
    '_modzzz_charity_block_sound' => 'Sounds',
    '_modzzz_charity_block_files' => 'Files',
    '_modzzz_charity_block_file' => 'Files',
    '_modzzz_charity_block_comments' => 'Comments',
    '_modzzz_charity_block_latest_featured_charity' => 'Latest Featured Charities',
    '_modzzz_charity_block_recent' => 'Recent Charities',
    '_modzzz_charity_block_popular' => 'Popular Charities',
    '_modzzz_charity_block_top' => 'Top Rated Charities',
    '_modzzz_charity_block_search' => 'Search Charities',
    '_modzzz_charity_block_charity_categories' => 'Charity Categories',

    '_modzzz_charity_block_administration_owner' => 'Administration',
    '_modzzz_charity_block_users_charity' => "User Charities",
    '_modzzz_charity_block_my_charity' => 'My Charity',
    '_modzzz_charity_block_my_charities' => 'My Charities',
    '_modzzz_charity_block_area_charities' => 'Charities in my Area',

    '_modzzz_charity_block_homepage' => 'Charities',

    '_modzzz_charity_caption_add' => 'Add Charity',
    '_modzzz_charity_caption_share_charity' => 'Share Charity',
    '_modzzz_charity_caption_admin_actions' => 'Links',
    '_modzzz_charity_caption_pending_approval' => 'Pending Approval Charities', 
    
	'_modzzz_charity_menu_manage_parents' => 'Parent Cats',
    '_modzzz_charity_menu_manage_categories' => 'Cats',
    '_modzzz_charity_categ_btn_save' => 'Save',
    '_modzzz_charity_categ_btn_edit' => 'Edit',
    '_modzzz_charity_categ_btn_delete' => 'Delete',
    '_modzzz_charity_categ_name' => 'Name',
    '_modzzz_charity_categ_icon' => 'Icon',
    '_modzzz_charity_categ_present_icon' => 'Present Icon',
    '_modzzz_charity_categ_btn_add' => 'Add',

    '_modzzz_charity_menu_root' => 'Charities',
    '_modzzz_charity_menu_main' => 'Charity Home',
    '_modzzz_charity_menu_recent' => 'Recent',
    '_modzzz_charity_menu_top_rated' => 'Top Rated',
    '_modzzz_charity_menu_popular' => 'Popular',
    '_modzzz_charity_menu_featured' => 'Featured',
    '_modzzz_charity_menu_tags' => 'Tags',
    '_modzzz_charity_menu_categories' => 'Categories',
    '_modzzz_charity_menu_calendar' => 'Calendar',
    '_modzzz_charity_menu_search' => 'Search',
    '_modzzz_charity_menu_view_charity' => 'Main',
    '_modzzz_charity_menu_view_comments' => 'Comments',
    '_modzzz_charity_menu_view_photos' => 'Photos',
    '_modzzz_charity_menu_view_videos' => 'Videos',
    '_modzzz_charity_menu_view_sounds' => 'Sounds',
    '_modzzz_charity_menu_view_files' => 'Files',
    '_modzzz_charity_menu_my_charity_profile' => 'Charities',

    '_modzzz_charity_menu_admin_pending_approval' => 'Pending',
    '_modzzz_charity_menu_admin_entries' => 'Charities',
    '_modzzz_charity_menu_admin_add_entry' => 'Add',
    '_modzzz_charity_menu_admin_settings' => 'Settings',
    
    '_modzzz_charity_page_title_home' => 'Charity Home',
    '_modzzz_charity_page_title_calendar' => 'Charity Calendar',
    '_modzzz_charity_page_title_comments' => 'Comments',
    '_modzzz_charity_page_title_photos' => 'Photos',
    '_modzzz_charity_page_title_videos' => 'Videos',
    '_modzzz_charity_page_title_sounds' => 'Sounds',
    '_modzzz_charity_page_title_files' => 'Files',
    '_modzzz_charity_page_title_my_charity' => 'My Charities',
    '_modzzz_charity_page_title_search' => 'Search',
    '_modzzz_charity_page_title_add' => 'Add Charity', 
    '_modzzz_charity_page_title_edit' => 'Edit Charity',
    '_modzzz_charity_page_title_administration' => 'Charities Administration',
    '_modzzz_charity_page_title_browse' => 'Browse Charities',
    '_modzzz_charity_page_title_pending_approval' => 'Pending Approval Charities',
    '_modzzz_charity_page_title_search_results' => 'Charity Search Results',
    '_modzzz_charity_page_title_browse_by_author' => "\'s charities",
    '_modzzz_charity_page_title_admin_charity' => 'Admin Charities',
    '_modzzz_charity_page_title_browse_by_category' => 'Browse Charities By Category: ',
    '_modzzz_charity_page_title_browse_by_tag' => 'Browse Charities By Tag: ',
    '_modzzz_charity_page_title_browse_recent' => 'Recent Charities',
    '_modzzz_charity_page_title_browse_top_rated' => 'Top Rated Charities',
    '_modzzz_charity_page_title_browse_popular' => 'Popular Charities',
    '_modzzz_charity_page_title_browse_featured' => 'Featured Charities',
    '_modzzz_charity_page_title_browse_by_day' => 'Browse Charities By Day: ',
    '_modzzz_charity_page_title_tags' => 'Charities Tags',
    '_modzzz_charity_page_title_categories' => 'Charities Categories',
    '_modzzz_charity_page_title_upload_photos' => 'Add Photos',
    '_modzzz_charity_page_title_upload_videos' => 'Add Videos',
    '_modzzz_charity_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_charity_page_title_upload_files' => 'Add Files',

    '_modzzz_charity_msg_pending_approval' => 'this charity is pending approval, please wait until it will be activated',
    '_modzzz_charity_msg_charity_was_deleted' => 'Charity was deleted',
    '_modzzz_charity_msg_removed_from_featured' => 'Charity was removed from featured',
    '_modzzz_charity_msg_added_to_featured' => 'Charity was added to featured',
    '_modzzz_charity_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_charity_msg_you_have_pending_approval_charity' => 'You have <a href="%s">%d pending approval charities</a>',
    '_modzzz_charity_msg_you_have_no_charity' => 'You do not have any charities. <a href="%s">Click here</a> to add one.',
    '_modzzz_charity_msg_you_have_some_charity' => 'You have <a href="%s">%d charity(s)</a>. <a href="%s">Click here</a> to add more.',

    '_modzzz_charity_admin_delete' => 'Delete',
    '_modzzz_charity_admin_activate' => 'Activate',
    '_modzzz_charity_admin_add_new_charity' => 'Add New Charity',
    '_modzzz_charity_admin_charity' => 'Admin Charity',
    '_modzzz_charity_admin_settings' => 'Admin Settings',

    '_modzzz_charity_form_header_info' => 'Charity Info',
    '_modzzz_charity_form_header_images' => 'Charity Photos',
    '_modzzz_charity_form_header_videos' => 'Charity Videos',
    '_modzzz_charity_form_header_sounds' => 'Charity Sounds',
    '_modzzz_charity_form_header_files' => 'Charity Files',
    '_modzzz_charity_form_header_privacy' => 'Privacy Settings',
    '_modzzz_charity_form_caption_title' => 'Title',
    '_modzzz_charity_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_charity_form_caption_desc' => 'Description',
    '_modzzz_charity_form_err_desc' => 'Please enter at least 5 characters',
    '_modzzz_charity_form_err_tags' => 'Please enter tags',
    '_modzzz_charity_form_caption_author_id' => 'Author',
    '_modzzz_charity_form_info_author' => 'Author profile ID number',
    '_modzzz_charity_form_caption_keyword' => 'Keyword',
    '_modzzz_charity_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_modzzz_charity_form_caption_category' => 'Category',
    '_modzzz_charity_form_err_category' => 'Category is invalid',    
    '_modzzz_charity_form_caption_images_choice' => 'Choose',
    '_modzzz_charity_form_info_images_choice' => 'You can choose several images from your "Charity" category',
    '_modzzz_charity_form_caption_images_upload' => 'Upload',    
    '_modzzz_charity_form_info_images_upload' => 'Image will be placed in the "Charity" category automatically',
    '_modzzz_charity_form_caption_videos_choice' => 'Choose',
    '_modzzz_charity_form_info_videos_choice' => 'You can choose several videos from your "Charity" category',
    '_modzzz_charity_form_caption_videos_upload' => 'Upload',
    '_modzzz_charity_form_info_videos_upload' => 'Video will be placed in the "Charity" category automatically',
    '_modzzz_charity_form_caption_sounds_choice' => 'Choose',
    '_modzzz_charity_form_info_sounds_choice' => 'You can choose several sounds from your "Charity" category',
    '_modzzz_charity_form_caption_sounds_upload' => 'Upload',
    '_modzzz_charity_form_info_sounds_upload' => 'Sound will be placed in the "Charity" category automatically',
    '_modzzz_charity_form_caption_files_choice' => 'Choose',
    '_modzzz_charity_form_info_files_choice' => 'Unclick checkbox to remove file from this charity',
    '_modzzz_charity_form_caption_files_upload' => 'Upload',
    '_modzzz_charity_form_info_files_upload' => 'File will be placed in the "Charity" category and set as private automatically',
    '_modzzz_charity_form_caption_file_title' => 'Title:',
    '_modzzz_charity_form_caption_file_price' => 'Price:',
    '_modzzz_charity_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_charity_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_charity_form_info_thumb_choice' => 'You can choose any image from your "Charity" category as charity thumbnail',
    '_modzzz_charity_form_caption_country' => 'Country',
    '_modzzz_charity_form_err_country' => 'Country is a required field',
    '_modzzz_charity_form_caption_city' => 'City',
    '_modzzz_charity_form_err_city' => 'Please enter from 2 to 50 characters',
    '_modzzz_charity_form_caption_zip' => 'Zip/Postal Code',
    '_modzzz_charity_form_err_zip' => 'Zip/Postal code is required',
    '_modzzz_charity_form_err_email' => 'Invalid Email entered',

    '_modzzz_charity_action_title_edit' => 'Edit',
    '_modzzz_charity_action_title_delete' => 'Delete',
    '_modzzz_charity_action_title_share' => 'Share',
    '_modzzz_charity_action_add_to_featured' => 'Make Featured',    
    '_modzzz_charity_action_remove_from_featured' => 'Unfeature',
    '_modzzz_charity_action_add_charity' => 'Add Charity',
    '_modzzz_charity_action_my_charity' => 'My Charity',
    '_modzzz_charity_action_upload_photos' => 'Add Photos',
    '_modzzz_charity_action_upload_videos' => 'Add Videos',
    '_modzzz_charity_action_upload_sounds' => 'Add Sounds',
    '_modzzz_charity_action_upload_files' => 'Add Files',
    '_modzzz_charity_action_charity_home' => 'Home',

    '_modzzz_charity_action_title_claim' => 'Claim Charity',
    '_modzzz_charity_action_title_inquire' => 'Inquire About', 
    '_modzzz_charity_action_title_spread' => 'Spread This', 
    '_modzzz_charity_action_title_promote' => 'Promote', 
    '_modzzz_charity_invitation_sent' => '%d Invitations have been sent',
	'_modzzz_charity_no_users_msg' => 'There are no users in your contacts',
 
    '_modzzz_charity_inquiry_subject' => 'Subject', 
    '_modzzz_charity_inquiry_subject_info' => 'Enter the Subject of your inquiry', 
    '_modzzz_charity_inquiry_text' => 'Message', 
    '_modzzz_charity_inquiry_text_info' => 'Enter your inquiry here. It will be forwarded to the Charity Owner',  
	'_modzzz_charity_caption_make_inquiry' => 'Make Inquiry',
    '_modzzz_charity_inquiry_sent' => 'your inquiry has been sent',
    '_modzzz_charity_inquiry_not_sent' => 'your inquiry has not been sent',
   
    '_modzzz_charity_claim_subject' => 'Subject', 
    '_modzzz_charity_claim_subject_info' => 'Enter the Subject of your claim', 
    '_modzzz_charity_claim_text' => 'Message', 
    '_modzzz_charity_claim_text_info' => 'Enter your proof of claim here. It will be forwarded to the Administrators',  
	'_modzzz_charity_caption_make_claim' => 'Make Claim',
    '_modzzz_charity_claim_sent' => 'your claim request has been sent',
    '_modzzz_charity_claim_not_sent' => 'your claim request has not been sent',
	 
	'_modzzz_charity_user_unknown' => 'Unknown', 
    '_modzzz_charity_price' => 'Price',

	'_modzzz_charity_business_contact' => 'Charity Contact Details', 
	'_modzzz_charity_location' => 'Location',
	'_modzzz_charity_map' => 'Google Map', 
	'_modzzz_charity_form_caption_businessfax' => 'Fax',
	'_modzzz_charity_form_caption_businesstelephone' => 'Telephone',
	'_modzzz_charity_form_caption_businessemail' => 'Email',
	'_modzzz_charity_form_caption_businesswebsite' => 'Website',
	'_modzzz_charity_form_caption_businessname' => 'Business Name',
	'_modzzz_charity_form_caption_address1' => 'Address 1',
	'_modzzz_charity_form_caption_address2' => 'Address 2', 
	'_modzzz_charity_form_err_charityoption' => 'Please select an Option', 
	'_modzzz_charity_form_err_charitytype' => 'Please select a Type',
    '_modzzz_charity_form_err_city' => 'Please enter from 3 to 150 characters',
  
    '_modzzz_charity_privacy_view_charity' => 'View Charity',
    '_modzzz_charity_privacy_comment' => 'Comment',
    '_modzzz_charity_privacy_rate' => 'Rate',
    '_modzzz_charity_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_charity_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_charity_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_charity_privacy_upload_files' => 'Upload Files',
    '_modzzz_charity_privacy_edit_charity' => 'Edit Charity',
    '_modzzz_charity_privacy_admins_only' => 'Admins Only',
    '_modzzz_charity_anonymous_note' => 'your name will not appear as the poster', 
    '_mma_charity_view_charity' => 'charity view charity', 
    '_mma_charity_browse' => 'charity browse', 
    '_mma_charity_search' => 'charity search', 
    '_mma_charity_add_charity' => 'charity add charity', 
    '_mma_charity_comments_delete_and_edit' => 'charity comments delete and edit', 
    '_mma_charity_edit_any_charity' => 'charity edit any charity', 
    '_mma_charity_delete_any_charity' => 'charity delete any charity', 
    '_mma_charity_mark_as_featured' => 'charity mark as featured', 
    '_mma_charity_approve_charity' => 'charity approve charity',   


	'_modzzz_charity_action_title_premium' => 'Get Premium',  
    '_modzzz_charity_page_title_premium' => 'Get Premium Charity',   
	'_mma_charity_purchase' => 'charity purchase package', 

    '_modzzz_charity_action_title_extend' => 'Extend',  
    '_modzzz_charity_page_title_extend' => 'Extend charity listing',   
	'_mma_charity_extend' => 'charity extend', 

    '_modzzz_charity_action_title_relist' => 'Re-list',  
    '_modzzz_charity_page_title_relist' => 'Re-list charity listing',  
	'_mma_charity_relist' => 'charity relist', 
  
    '_modzzz_charity_form_caption_current_no_package' => 'No Package currently',   
    '_modzzz_charity_form_caption_current_package' => 'Current Package',  
    '_modzzz_charity_form_caption_package_price' => 'Package Price',  
    '_modzzz_charity_form_caption_package_days' => 'Length of Charity',   
 	'_modzzz_charity_expires_never' => 'unlimited (never expires)', 
 	'_modzzz_charity_days' => 'days', 
 	'_modzzz_charity_form_caption_current_item' => 'Charity', 
    '_modzzz_charity_extend' => 'Extend',  
    '_modzzz_charity_block_statistics' => 'Statistics',  
    '_modzzz_charity_block_price' => 'Price',  
	
    '_modzzz_charity_form_header_headquarters' => 'HeadQuarters Location',  
    '_modzzz_charity_form_header_location' => 'Location',  
    '_modzzz_charity_form_header_contact' => 'Charity Contact Details',  
    '_modzzz_charity_block_share' => 'Share', 
    '_modzzz_charity_block_facebook_comments' => 'Facebook Comments', 
    
	'_modzzz_charity_miles' => 'miles', 
    '_modzzz_charity_kilometers' => 'Km', 
	'_modzzz_charity_map_search_explanation' => 'Enter the City and Country (eg. miramer or miramer,US)', 

    '_modzzz_charity_enter_your_charity' => 'Enter your charity name',
    '_modzzz_charity_block_charity_create' => 'List your Charity with us', 
    '_modzzz_charity_block_latest_comments' => 'Latest Comments',
    '_modzzz_charity_block_forum' => 'Latest Forum Posts',
    '_modzzz_charity_posted_by' => 'Posted by',
    '_modzzz_charity_posted_in' => 'In', 
 	'_modzzz_charity_posted_on' => 'on', 
 	'_modzzz_charity_remove' => 'Remove',   
     '_modzzz_charity_posted' => 'Posted',

    '_modzzz_charity_subprofile_form_header_info' => 'Info',
    '_modzzz_charity_subprofile_form_header_images' => 'Photos',
    '_modzzz_charity_subprofile_form_header_videos' => 'Videos',
    '_modzzz_charity_subprofile_form_header_sounds' => 'Sounds',
    '_modzzz_charity_subprofile_form_header_files' => 'Files',
   
	'_modzzz_charity_caption_invite' => 'Send Invitation to Friends',
	'_modzzz_charity_caption_join_filter' => 'Allow to join',
	'_modzzz_charity_caption_keyword' => 'Keyword',
	'_modzzz_charity_caption_membership_filter' => 'Allow joining by membership',  
    '_modzzz_charity_caption_search_results' => 'Search Results:',
	'_modzzz_charity_caption_title' => 'Title',	

	'_modzzz_charity_allow_num_listings' => 'Number of Listings allowed', 	
	'_modzzz_charity_allow_videos' => 'Allow Videos', 	
	'_modzzz_charity_allow_photos' => 'Allow Photos', 	
	'_modzzz_charity_allow_sounds' => 'Allow Sounds', 	
	'_modzzz_charity_allow_files' => 'Allow Files', 	
 	'_modzzz_charity_featured' => 'Featured', 	
 	'_modzzz_charity_package_desc' => 'Package Description',  

    '_modzzz_charity_block_submenu_expired_charity' => 'Expired',
    '_modzzz_charity_page_title_expired' => 'Expired Listings', 
 	'_modzzz_charity_expires' => 'Expires', 	 
 	'_modzzz_charity_never' => 'Never',  
 	'_modzzz_charity_featured_listing' => 'Featured Listing (never expires)',  
 	'_modzzz_charity_not_featured_listing' => 'Listing is not Featured',  

    '_modzzz_charity_page_title_broadcast' => 'Send broadcast message to all fans of this charity',
    '_modzzz_charity_msg_broadcast_message_sent' => 'Broadcast messages have been sent',
    '_modzzz_charity_msg_broadcast_no_recipients' => 'There are no fans for this charity yet',
    '_modzzz_charity_form_caption_broadcast_title' => 'Broadcast message title',
    '_modzzz_charity_form_err_broadcast_title' => 'Please enter from 3 to 100 characters', 
    '_modzzz_charity_form_caption_broadcast_message' => 'Broadcast message',
    '_modzzz_charity_form_err_broadcast_message' => 'Please enter at least 10 characters',
    '_modzzz_charity_action_title_broadcast' => 'Broadcast',
    '_mma_charity_broadcast_message' => 'charity broadcast message',
 
    '_modzzz_charity_form_caption_charity_name' => 'Charity Name',
    '_modzzz_charity_form_caption_believe' => 'What We Believe',
    '_modzzz_charity_form_caption_history' => 'History', 
    '_modzzz_charity_form_caption_service_hours' => 'Service Hours',

    '_modzzz_charity_block_believe' => 'What We Believe',
    '_modzzz_charity_block_history' => 'History', 
    '_modzzz_charity_block_service_hours' => 'Service Hours',
 
    '_modzzz_charity_page_title_reviews' => 'Charity\'s Testimonials', 
    '_modzzz_charity_block_latest_reviews' => 'Latest Testimonials', 
	'_modzzz_charity_action_title_review' => 'Testimonial', 
    '_modzzz_charity_review_text' => 'Testimonial', 
    '_modzzz_charity_review_text_info' => 'If you have been to services at this charity, you can post a testimonial for the benefit of others who may wish to visit', 
    '_modzzz_charity_form_caption_post_review' => 'Post Testimonial - ', 
    '_modzzz_charity_review_saved' => 'Testimonial has been saved', 
    '_modzzz_charity_review_not_saved' => 'Testimonial has not been saved',  
    '_modzzz_charity_review' => 'Testimonial', 
    '_modzzz_charity_block_charity_reviews' => 'Testimonials',
    '_modzzz_charity_menu_view_reviews' => 'Testimonials', 
	'_modzzz_charity_review_for' => 'Testimonial for', 
	'_modzzz_charity_block_reviews' => 'Testimonials', 
	'_modzzz_charity_block_my_reviews' => 'My Charity Testimonials',  
 	'_modzzz_charity_action_title_post_review' => 'Post Testimonial', 
	'_modzzz_charity_block_browse_reviews' => 'Browse Charity Testimonials',
	'_modzzz_charity_page_title_review_add' => 'Add a Testimonial for Charity',
	'_modzzz_charity_page_title_review_browse' => 'Browse Testimonials for Charity',  
    '_modzzz_charity_action_title_add_review' => 'Add Testimonial',
    '_modzzz_charity_page_title_review_edit' => 'Edit Testimonial',
    '_modzzz_charity_msg_charity_review_was_deleted' => 'Charity Testimonial was successfully deleted',
    '_modzzz_charity_msg_pending_review_approval' => 'this charity testimonial is pending approval, please wait until it will be activated',
    '_modzzz_charity_menu_view_reviews' => 'Testimonials',  
	'_mma_charity_add_review' => 'charity add testimonial', 
	'_modzzz_charity_posted_for' => 'Posted for Charity',  
	'_modzzz_charity_by' => 'by',

 	'_modzzz_charity_action_title_add_to_faq' => 'Manage FAQ',
	'_modzzz_charity_faqs_no_items' => 'No items in this Faq',
	'_modzzz_charity_faq' => 'FAQ',   
	'_modzzz_charity_form_header_faq_info' => 'FAQ Info',  
	'_modzzz_charity_privacy_view_faq' => 'View FAQ',  
    '_modzzz_charity_block_faq' => 'FAQ', 
    '_modzzz_charity_block_faqs_items' => 'Faq Questions',  
	'_modzzz_charity_block_browse_faqs' => 'Browse FAQ',
	'_modzzz_charity_page_title_faq_add' => 'Manage Faq for Charity',
	'_modzzz_charity_page_title_faq_browse' => 'Browse FAQ for Charity',  
    '_modzzz_charity_action_title_add_faq' => 'Add FAQ',
    '_modzzz_charity_page_title_faq_edit' => 'Edit FAQ',
 
    '_modzzz_charity_msg_charity_faq_was_deleted' => 'FAQ was successfully deleted',
    '_modzzz_charity_msg_pending_faq_approval' => 'this FAQ is pending approval, please wait until it will be activated',
    '_modzzz_charity_menu_view_faqs' => 'FAQ',
    '_modzzz_charity_faq_items' => '{0} questions', 
    '_modzzz_charity_form_caption_question' => 'Question',
    '_modzzz_charity_form_caption_answer' => 'Answer (for Question above)',
    '_modzzz_charity_add_another_question' => 'Add another Question', 
    '_modzzz_charity_form_header_charity_faq' => 'Select Questions you want to remove from FAQ ',
    '_modzzz_charity_form_caption_charity_faq_choice' => 'Existing Questions',
    '_modzzz_charity_form_info_charity_faq_choice' => 'These are FAQ Questions that you have created already',


	'_modzzz_charity_block_browse_events' => 'Browse Charity Events',
	'_modzzz_charity_page_title_event_add' => 'Add an Event for Charity',
	'_modzzz_charity_page_title_event_browse' => 'Browse Events for Charity',  
    '_modzzz_charity_action_title_add_event' => 'Add Event',
    '_modzzz_charity_page_title_event_edit' => 'Edit Event',
    '_modzzz_charity_msg_charity_event_was_deleted' => 'Event was successfully deleted',
    '_modzzz_charity_msg_pending_event_approval' => 'this event is pending approval, please wait until it will be activated',
    '_modzzz_charity_menu_view_events' => 'Events', 
    '_modzzz_charity_block_events' => 'Events', 
	'_modzzz_charity_caption_event_end' => 'Date end',
	'_modzzz_charity_caption_event_start' => 'Date start',
	'_modzzz_charity_caption_place' => 'Place name',
 
	'_modzzz_charity_block_browse_sermons' => 'Browse Charity Sermons',
	'_modzzz_charity_page_title_sermon_add' => 'Add a Sermon for Charity',
	'_modzzz_charity_page_title_sermon_browse' => 'Browse Sermons for Charity',  
    '_modzzz_charity_action_title_add_sermon' => 'Add Sermon',
    '_modzzz_charity_page_title_sermon_edit' => 'Edit Sermon',
    '_modzzz_charity_msg_charity_sermon_was_deleted' => 'Sermon was successfully deleted',
    '_modzzz_charity_msg_pending_sermon_approval' => 'this sermon is pending approval, please wait until it will be activated',
    '_modzzz_charity_menu_view_sermons' => 'Sermons', 
    '_modzzz_charity_block_sermons' => 'Sermons',

	'_modzzz_charity_block_browse_staffs' => 'Browse Charity Staff',
	'_modzzz_charity_page_title_staff_add' => 'Add a Staff for Charity',
	'_modzzz_charity_page_title_staff_browse' => 'Browse Staff for Charity',  
    '_modzzz_charity_action_title_add_staff' => 'Add Staff',
    '_modzzz_charity_page_title_staff_edit' => 'Edit Staff',
    '_modzzz_charity_msg_charity_staff_was_deleted' => 'Staff was successfully deleted',
    '_modzzz_charity_msg_pending_staff_approval' => 'this staff is pending approval, please wait until it will be activated',
    '_modzzz_charity_menu_view_staffs' => 'Staff', 
    '_modzzz_charity_block_staffs' => 'Staff', 

	'_modzzz_charity_block_browse_supporters' => 'Browse Charity Supporters',
	'_modzzz_charity_page_title_supporter_add' => 'Add a Supporter for Charity',
	'_modzzz_charity_page_title_supporter_browse' => 'Browse Supporters for Charity',  
    '_modzzz_charity_action_title_add_supporter' => 'Add Supporter',
    '_modzzz_charity_page_title_supporter_edit' => 'Edit Supporter',
    '_modzzz_charity_msg_charity_supporter_was_deleted' => 'Supporter was successfully deleted',
    '_modzzz_charity_msg_pending_supporter_approval' => 'this supporter is pending approval, please wait until it will be activated',
    '_modzzz_charity_menu_view_supporters' => 'Supporters', 
    '_modzzz_charity_block_supporters' => 'Supporters', 

 	'_modzzz_charity_block_browse_news' => 'Browse Charity News',
	'_modzzz_charity_page_title_news_add' => 'Add News for Charity',
	'_modzzz_charity_page_title_news_browse' => 'Browse News for Charity',  
    '_modzzz_charity_action_title_add_news' => 'Add News',
    '_modzzz_charity_page_title_news_edit' => 'Edit News',
    '_modzzz_charity_msg_charity_news_was_deleted' => 'News was successfully deleted',
    '_modzzz_charity_msg_pending_news_approval' => 'this news is pending approval, please wait until it will be activated',
    '_modzzz_charity_menu_view_news' => 'News', 
    '_modzzz_charity_block_news' => 'News',

	'_modzzz_charity_block_browse_branches' => 'Browse Charity Branches',
	'_modzzz_charity_page_title_branches_add' => 'Add a Branch for Charity',
	'_modzzz_charity_page_title_branches_browse' => 'Browse Branches for Charity',  
    '_modzzz_charity_action_title_add_branches' => 'Add Branch',
    '_modzzz_charity_page_title_branches_edit' => 'Edit Branch',
    '_modzzz_charity_msg_charity_branches_was_deleted' => 'Branches was successfully deleted',
    '_modzzz_charity_msg_pending_branches_approval' => 'this branches is pending approval, please wait until it will be activated',
    '_modzzz_charity_menu_view_branches' => 'Branches', 
    '_modzzz_charity_block_branches' => 'Branches',

	'_modzzz_charity_block_browse_programs' => 'Browse Charity Programs',
	'_modzzz_charity_page_title_programs_add' => 'Add a Program for Charity',
	'_modzzz_charity_page_title_programs_browse' => 'Browse Programs for Charity',  
    '_modzzz_charity_action_title_add_programs' => 'Add Program',
    '_modzzz_charity_page_title_programs_edit' => 'Edit Program',
    '_modzzz_charity_msg_charity_programs_was_deleted' => 'Programs was successfully deleted',
    '_modzzz_charity_msg_pending_programs_approval' => 'this programs is pending approval, please wait until it will be activated',
    '_modzzz_charity_menu_view_programs' => 'Our Work', 
    '_modzzz_charity_block_programs' => 'Our Work',

	'_modzzz_charity_block_browse_members' => 'Browse Charity Volunteers',
	'_modzzz_charity_page_title_members_add' => 'Add a Volunteer for Charity',
	'_modzzz_charity_page_title_members_browse' => 'Browse Volunteers for Charity',  
    '_modzzz_charity_action_title_add_members' => 'Add Volunteer',
    '_modzzz_charity_page_title_members_edit' => 'Edit Volunteer',
    '_modzzz_charity_msg_charity_members_was_deleted' => 'Volunteer was successfully deleted',
    '_modzzz_charity_msg_pending_members_approval' => 'this volunteer is pending approval, please wait until it will be activated',
    '_modzzz_charity_menu_view_members' => 'Volunteers', 
    '_modzzz_charity_block_members' => 'Volunteers',
  
    '_modzzz_charity_subprofile_form_header_info' => 'Info',
    '_modzzz_charity_subprofile_form_header_images' => 'Photos',
    '_modzzz_charity_subprofile_form_header_videos' => 'Videos',
    '_modzzz_charity_subprofile_form_header_sounds' => 'Sounds',
    '_modzzz_charity_subprofile_form_header_files' => 'Files',

    '_modzzz_charity_form_caption_paypal' => 'Paypal',
    '_modzzz_charity_form_info_paypal' => 'Paypal account for accepting donations. Leave blank if you do not wish to receive donations',
    '_modzzz_charity_action_title_make_donation' => 'Make Donation', 
    '_modzzz_charity_page_title_donation_add' => 'Make Donation',
    '_modzzz_charity_page_title_donation_browse' => 'Browse Donations', 
    '_modzzz_charity_form_caption_error_message' => 'Error Message',
    '_modzzz_charity_form_caption_amount' => 'Amount', 
    '_modzzz_charity_form_error_amount' => 'you must enter amount',
    '_modzzz_charity_paypal_donation_desc' => 'Donation to Charity - {0}',
    '_modzzz_charity_donation_failed' => 'Donation failed. Please try again',   
    '_mma_charity_make_donation' => 'charity make donation',  
    '_modzzz_charity_donation_err_wrong_transaction' => 'There was a problem with donation transaction',  
    '_modzzz_charity_donation_err_wrong_verification_status' => 'There was a problem verifying your Paypal information',  
    '_modzzz_charity_caption_browse_charity_donors' => 'Browse donors to Charity - {0}',  
    '_modzzz_charity_donation' => 'Donation', 
    '_modzzz_charity_block_donors' => 'Donors',  
    '_modzzz_charity_donated_to' => 'Donated to', 
    '_modzzz_charity_donated_by' => 'Donated by', 
    '_modzzz_charity_donated' => 'Donated',   
    '_modzzz_charity_someone' => 'Someone',  
    '_modzzz_charity_form_caption_first_name' => 'First Name',   
    '_modzzz_charity_form_caption_last_name' => 'Last Name',   
    '_modzzz_charity_form_caption_anonymous' => 'Anonymous',   
    '_modzzz_charity_form_info_anonymous' => 'You will not be listed in the Donors list',
    '_modzzz_charity_privacy_view_donors' => 'View Donors',
    '_modzzz_charity_menu_manage_donors' => 'Donors',
    '_modzzz_charity_charities' => 'Charities',
    '_modzzz_charity_action_forum' => 'Forum',
    '_modzzz_charity_action_title_forum' => 'Forum',
    '_modzzz_charity_calendar' => 'Calendar - ',

	'_modzzz_charity_event_auction' => 'Auction',  
	'_modzzz_charity_event_concert' => 'Concert',   
	'_modzzz_charity_event_charity_event' => 'Charity Event',  
	'_modzzz_charity_event_corporate_function' => 'Corporate function', 
	'_modzzz_charity_event_fund_raiser' => 'Fund Raiser',
	'_modzzz_charity_event_luncheon' => 'Luncheon',  
	'_modzzz_charity_event_shopping_fair' => 'Shopping Fair', 
	'_modzzz_charity_event_sport_event' => 'Sport Event', 
	'_modzzz_charity_event_tour' => 'Tour',   
	'_modzzz_charity_event_other' => 'Other',
 
  	/*added 7.1 */
    '_modzzz_charity_wall_added_new_comment' => 'commented on a',
    '_modzzz_charity_wall_added_new_items' => 'added {0} new charities',
	'_modzzz_charity_single' => 'Charity',
    '_modzzz_charity_posted_in_topic' => 'Posted in Forum',
    '_modzzz_charity_posted_in_charity' => 'Posted for Charity',
	'_modzzz_charity_message' => 'Message',
    '_modzzz_charity_block_calendar' => 'Calendar', 
    '_modzzz_charity_adm_stats' => 'Pending Charities',
 	'_sys_module_charity' => 'Charity',  

	'_modzzz_charity_event_single' => 'Charity Event',
	'_modzzz_charity_event' => 'Charity Event',
  
	'_modzzz_charity_branch_single' => 'Charity Branch',
	'_modzzz_charity_branch' => 'Charity Branch',
 
	'_modzzz_charity_views' => 'views',
	'_modzzz_charity_more_details' => 'more details ..',
 	
	'_modzzz_charity_branches' => 'Charity Branches',
	'_modzzz_charity_event' => 'Charity Event',
	'_modzzz_charity_members' => 'Charity Members',
	'_modzzz_charity_news' => 'Charity News',
	'_modzzz_charity_programs' => 'Charity Programs',
	'_modzzz_charity_staff' => 'Charity Staff',
	'_modzzz_charity_supporter' => 'Charity Supporter',
	'_modzzz_charity_browse_charity_in_country' => 'Browse Charity in {0}',

 );